Don't try things that are destined to fail but whose failure doesn't matter or isn't handled properly.

diff --git a/10.4-transitional/unstable/main/finkinfo/net/ipv6calc.patch b/10.4-transitional/unstable/main/finkinfo/net/ipv6calc.patch
--- a/10.4-transitional/unstable/main/finkinfo/net/ipv6calc.patch
+++ b/10.4-transitional/unstable/main/finkinfo/net/ipv6calc.patch
@@ -92,6 +92,20 @@ diff -Nurd -x'*~' ipv6calc-0.50.orig/ipv6logconv/Makefile.in ipv6calc-0.50/ipv6l
  		install -m 755 ipv6logconv $(root)@bindir@
 -	
 +
+diff -Nurd -x'*~' ipv6calc-0.50.orig/ipv6logconv/test_ipv6logconv.sh ipv6calc-0.50/ipv6logconv/test_ipv6logconv.sh
+--- ipv6calc-0.50.orig/ipv6logconv/test_ipv6logconv.sh	2005-09-15 13:49:02.000000000 -0400
++++ ipv6calc-0.50/ipv6logconv/test_ipv6logconv.sh	2006-03-29 01:46:25.000000000 -0500
+@@ -70,6 +70,10 @@
+ #set -x
+ ## main ##
+ echo "Run 'ipv6logconv' function tests..." >&2
++if [ $UID = 0 ]; then
++  echo "WARNING: skipping ipv6logconv test! (cannot run it as root)"
++  exit 0
++fi
+ 
+ if [ "$1" != "bulk" ]; then
+ 	testscenarios | grep -v "^#" | while read line; do
 diff -Nurd -x'*~' ipv6calc-0.50.orig/ipv6logstats/Makefile.in ipv6calc-0.50/ipv6logstats/Makefile.in
 --- ipv6calc-0.50.orig/ipv6logstats/Makefile.in	2005-09-15 13:35:02.000000000 -0400
 +++ ipv6calc-0.50/ipv6logstats/Makefile.in	2005-11-09 02:58:11.000000000 -0500
@@ -107,6 +121,20 @@ diff -Nurd -x'*~' ipv6calc-0.50.orig/ipv6logstats/Makefile.in ipv6calc-0.50/ipv6
  
  CC	= gcc
  
+diff -Nurd -x'*~' ipv6calc-0.50.orig/ipv6logstats/test_ipv6logstats.sh ipv6calc-0.50/ipv6logstats/test_ipv6logstats.sh
+--- ipv6calc-0.50.orig/ipv6logstats/test_ipv6logstats.sh	2003-06-15 09:33:41.000000000 -0400
++++ ipv6calc-0.50/ipv6logstats/test_ipv6logstats.sh	2006-03-29 01:46:33.000000000 -0500
+@@ -20,6 +20,10 @@
+ #set -x
+ ## main ##
+ echo "Run 'ipv6logstats' function tests..."
++if [ $UID = 0 ]; then
++  echo "WARNING: skipping ipv6logstats test! (cannot run it as root)"
++  exit 0
++fi
+ 
+ #testscenarios
+ testscenarios | ./ipv6logstats
 diff -Nurd -x'*~' ipv6calc-0.50.orig/lib/Makefile ipv6calc-0.50/lib/Makefile
 --- ipv6calc-0.50.orig/lib/Makefile	2005-09-15 13:29:19.000000000 -0400
 +++ ipv6calc-0.50/lib/Makefile	2005-11-09 02:58:11.000000000 -0500
