pangocairo-branch files to stable

diff --git a/10.4/stable/crypto/finkinfo/mozilla.patch b/10.4/stable/crypto/finkinfo/mozilla.patch
--- a/10.4/stable/crypto/finkinfo/mozilla.patch
+++ b/10.4/stable/crypto/finkinfo/mozilla.patch
@@ -1,7 +1,7 @@
 diff -Naur mozilla-1.7.2.old/.mozconfig mozilla-1.7.2.new/.mozconfig
 --- mozilla-1.7.2.old/.mozconfig	Thu Jan  1 09:00:00 1970
 +++ mozilla-1.7.2.new/.mozconfig	Sat Aug 21 02:12:35 2004
-@@ -0,0 +1,23 @@
+@@ -0,0 +1,24 @@
 +ac_add_options --enable-macos-target=10.3
 +ac_add_options --enable-prebinding
 +ac_add_options --enable-default-toolkit=gtk2
@@ -22,6 +22,7 @@ diff -Naur mozilla-1.7.2.old/.mozconfig mozilla-1.7.2.new/.mozconfig
 +ac_add_options --enable-mathml
 +ac_add_options --enable-extensions=all
 +ac_add_options --enable-xinerama
++ac_add_options --enable-postscript
 +ac_add_options --with-default-mozilla-five-home=@PREFIX@/lib/mozilla
 +mk_add_options MOZ_MAKE_FLAGS=-j4
 +
@@ -62,7 +63,7 @@ diff -Naur mozilla-1.7.2.old/config/autoconf.mk.in mozilla-1.7.2.new/config/auto
 diff -Naur mozilla-1.7.2.old/config/config.mk mozilla-1.7.2.new/config/config.mk
 --- mozilla-1.7.2.old/config/config.mk	Sun Apr 11 07:51:37 2004
 +++ mozilla-1.7.2.new/config/config.mk	Fri Aug 20 20:36:42 2004
-@@ -702,7 +702,7 @@
+@@ -712,7 +712,7 @@
  ifeq ($(OS_ARCH),Darwin)
  ifdef USE_PREBINDING
  export LD_PREBIND=1
@@ -71,7 +72,7 @@ diff -Naur mozilla-1.7.2.old/config/config.mk mozilla-1.7.2.new/config/config.mk
  endif
  ifdef MACOS_SDK_DIR
  export NEXT_ROOT=$(MACOS_SDK_DIR)
-@@ -747,7 +747,7 @@
+@@ -765,7 +765,7 @@
  # Tell the linker where NSS is, if we're building crypto
  ifeq ($(OS_ARCH),Darwin)
  ifeq (,$(findstring crypto,$(MOZ_META_COMPONENTS)))
@@ -95,7 +96,7 @@ diff -Naur mozilla-1.7.2.old/config/rules.mk mozilla-1.7.2.new/config/rules.mk
 diff -Naur mozilla-1.7.2.old/configure mozilla-1.7.2.new/configure
 --- mozilla-1.7.2.old/configure	Sun Jun  6 03:44:52 2004
 +++ mozilla-1.7.2.new/configure	Sat Aug 21 03:41:21 2004
-@@ -4976,7 +4976,7 @@
+@@ -4980,7 +4980,7 @@
      ;;
  
  *-darwin*)
@@ -104,7 +105,7 @@ diff -Naur mozilla-1.7.2.old/configure mozilla-1.7.2.new/configure
      HOST_NSPR_MDCPUCFG='\"md/_darwin.cfg\"'
      HOST_OPTIMIZE_FLAGS="${HOST_OPTIMIZE_FLAGS=-O3}"
      ;;
-@@ -5207,8 +5207,8 @@
+@@ -5211,8 +5117,8 @@
  
  *-darwin*) 
      _PEDANTIC=
@@ -386,9 +387,15 @@ diff -Naur mozilla-1.7.2.old/fink/prefs.js mozilla-1.7.2.new/fink/prefs.js
 +
 diff -Naur mozilla-1.7.2.old/fink/update-mozilla-chrome mozilla-1.7.2.new/fink/update-mozilla-chrome
 --- mozilla-1.7.2.old/fink/update-mozilla-chrome	Thu Jan  1 09:00:00 1970
-+++ mozilla-1.7.2.new/fink/update-mozilla-chrome	Fri Aug 20 20:07:48 2004
-@@ -0,0 +1,24 @@
++++ mozilla-1.7.2.new/fink/update-mozilla-chrome	Tue Jan 17 04:34:03 2006
+@@ -0,0 +1,33 @@
 +#!/bin/sh -e
++
++if [ "$UID" -ne "0" ]; then
++    exec /usr/bin/sudo -H "$0" "$@"
++    echo "Could not switch to root...aborting $0"
++    exit 0
++fi
 +
 +ulimit -s unlimited || true
 +
@@ -397,6 +404,7 @@ diff -Naur mozilla-1.7.2.old/fink/update-mozilla-chrome mozilla-1.7.2.new/fink/u
 +
 +export DYLD_LIBRARY_PATH=$MOZILLA_FIVE_HOME
 +
++cd ${MOZILLA_FIVE_HOME}
 +TMPFILE=`tempfile`
 +cat ${CHROME_DIR}/* >>${TMPFILE}
 +mv ${TMPFILE} ${MOZILLA_FIVE_HOME}/chrome/installed-chrome.txt
@@ -407,9 +415,11 @@ diff -Naur mozilla-1.7.2.old/fink/update-mozilla-chrome mozilla-1.7.2.new/fink/u
 +rm -f  ${MOZILLA_FIVE_HOME}/component.reg
 +rm -f  ${MOZILLA_FIVE_HOME}/components/*.dat
 +
-+sudo -H ${MOZILLA_FIVE_HOME}/regxpcom || true
-+sudo -H ${MOZILLA_FIVE_HOME}/regchrome || true
++export HOME=~root
++sudo -H ./run-mozilla.sh ${MOZILLA_FIVE_HOME}/regxpcom || true
++sudo -H ./run-mozilla.sh ${MOZILLA_FIVE_HOME}/regchrome || true
 +
++echo "Done registering components"
 +exit 0
 +
 diff -Naur mozilla-1.7.2.old/modules/libpref/src/nsPrefService.cpp mozilla-1.7.2.new/modules/libpref/src/nsPrefService.cpp
@@ -453,7 +463,7 @@ diff -Naur mozilla-1.7.2.old/nsprpub/configure mozilla-1.7.2.new/nsprpub/configu
 -    ;;
  *)
      echo $ac_n "checking for dlopen in -ldl""... $ac_c" 1>&6
- echo "configure:4845: checking for dlopen in -ldl" >&5
+ echo "configure:4853: checking for dlopen in -ldl" >&5
 diff -Naur mozilla-1.7.2.old/nsprpub/pr/include/md/_darwin.h mozilla-1.7.2.new/nsprpub/pr/include/md/_darwin.h
 --- mozilla-1.7.2.old/nsprpub/pr/include/md/_darwin.h	Thu Nov 27 10:30:44 2003
 +++ mozilla-1.7.2.new/nsprpub/pr/include/md/_darwin.h	Fri Aug 20 20:07:49 2004
@@ -499,7 +509,7 @@ diff -Naur mozilla-1.7.2.old/nsprpub/pr/src/linking/prlink.c mozilla-1.7.2.new/n
 diff -Naur mozilla-1.7.2.old/security/coreconf/Darwin.mk mozilla-1.7.2.new/security/coreconf/Darwin.mk
 --- mozilla-1.7.2.old/security/coreconf/Darwin.mk	Thu Nov 13 10:59:22 2003
 +++ mozilla-1.7.2.new/security/coreconf/Darwin.mk	Fri Aug 20 20:18:08 2004
-@@ -68,7 +68,7 @@
+@@ -80,7 +80,7 @@
  ARCH		= darwin
  
  # May override this with -bundle to create a loadable module.
@@ -511,7 +521,7 @@ diff -Naur mozilla-1.7.2.old/security/coreconf/Darwin.mk mozilla-1.7.2.new/secur
 diff -Naur mozilla-1.7.2.old/security/nss/cmd/platlibs.mk mozilla-1.7.2.new/security/nss/cmd/platlibs.mk
 --- mozilla-1.7.2.old/security/nss/cmd/platlibs.mk	Sun Apr 20 13:23:14 2003
 +++ mozilla-1.7.2.new/security/nss/cmd/platlibs.mk	Fri Aug 20 20:07:54 2004
-@@ -195,7 +195,7 @@
+@@ -207,7 +207,7 @@
  endif
  
  ifeq ($(OS_ARCH), Darwin)
@@ -543,7 +553,7 @@ diff -Naur mozilla-1.7.2.old/security/nss/lib/ssl/config.mk mozilla-1.7.2.new/se
 +EXTRA_SHARED_LIBS += -dylib_file @PREFIX@/lib/mozilla/libsoftokn3.dylib:$(DIST)/lib/libsoftokn3.dylib
  endif
  
- endif
+ ifeq ($(OS_TARGET),SunOS)
 diff -Naur mozilla-1.7.2.old/themes/Makefile.in mozilla-1.7.2.new/themes/Makefile.in
 --- mozilla-1.7.2.old/themes/Makefile.in	Thu Sep 25 21:48:58 2003
 +++ mozilla-1.7.2.new/themes/Makefile.in	Fri Aug 20 20:07:54 2004
@@ -552,21 +562,37 @@ diff -Naur mozilla-1.7.2.old/themes/Makefile.in mozilla-1.7.2.new/themes/Makefil
  # select classic as the default skin
  libs::
 -	echo skin,install,select,classic/1.0 >> $(DIST)/bin/chrome/installed-chrome.txt
-+# fix lator
++# fix later
 +#	echo skin,install,select,classic/1.0 >> $(DIST)/bin/chrome/installed-chrome.txt
  
  install::
 -	echo skin,install,select,classic/1.0 >> $(DESTDIR)$(mozappdir)/chrome/installed-chrome.txt
-+# fix lator
++# fix later
 +#	echo skin,install,select,classic/1.0 >> $(DESTDIR)$(mozappdir)/chrome/installed-chrome.txt
 diff -ur mozilla.bak/dist/private/nss/oiddata.h mozilla/dist/private/nss/oiddata.h
 --- mozilla.bak/security/nss/lib/pki1/oiddata.h	2002-01-03 21:22:07.000000000 -0800
 +++ mozilla/security/nss/lib/pki1/oiddata.h	2005-06-13 15:47:27.000000000 -0700
-@@ -39,6 +39,7 @@
- static const char OIDDATA_CVS_ID[] = "@(#) $RCSfile: oiddata.h,v $ $Revision: 1.1 $ $Date: 2002/01/04 05:22:07 $ $Name: MOZILLA_1_7_5_RELEASE $ ; @(#) $RCSfile: oiddata.h,v $ $Revision: 1.1 $ $Date: 2002/01/04 05:22:07 $ $Name: MOZILLA_1_7_5_RELEASE $";
+@@ -39,6 +39,9 @@
+ static const char OIDDATA_CVS_ID[] = "@(#) $RCSfile: mozilla.patch,v $ $Revision: 1.5 $ $Date: 2006/09/13 18:24:46 $ $Name:  $ ; @(#) $RCSfile: mozilla.patch,v $ $Revision: 1.5 $ $Date: 2006/09/13 18:24:46 $ $Name:  $";
  #endif /* DEBUG */
  
++/* added to fix building on Tiger/gcc4 (bug 284386) */
++/* fixed for mozilla1.8, so remove this block from the patch for 1.8 */
 +#include "pki1t.h"
  #ifndef NSSPKI1T_H
  #include "nsspki1t.h"
  #endif /* NSSPKI1T_H */
+
+diff -Naur mozilla/gfx/src/gtk/nsScreenGtk.cpp mozilla/gfx/src/gtk/nsScreenGtk-new.cpp
+--- mozilla/gfx/src/gtk/nsScreenGtk.cpp	2004-04-20 19:35:51.000000000 +0200
++++ mozilla/gfx/src/gtk/nsScreenGtk-new.cpp	2006-01-10 18:40:24.000000000 +0100
+@@ -143,7 +143,7 @@
+   if (!gdk_property_get(root_window,
+                         gdk_atom_intern ("_NET_WORKAREA", FALSE),
+                         cardinal_atom,
+-                        0, G_MAXLONG, FALSE,
++                        0, G_MAXLONG - 3, FALSE,
+                         &type_returned,
+                         &format_returned,
+                         &length_returned,
+
diff --git a/10.4/stable/main/finkinfo/editors/tea.patch b/10.4/stable/main/finkinfo/editors/tea.patch
--- a/10.4/stable/main/finkinfo/editors/tea.patch
+++ b/10.4/stable/main/finkinfo/editors/tea.patch
@@ -1,7 +1,46 @@
-diff -ruN tea-14.3.0/src/rox_strings.c tea-14.3.0-patched/src/rox_strings.c
---- tea-14.3.0/src/rox_strings.c	2006-10-04 04:52:08.000000000 -0700
-+++ tea-14.3.0-patched/src/rox_strings.c	2007-08-05 20:10:19.000000000 -0700
-@@ -32,6 +32,7 @@
+diff -Nurd -x'*~' tea-17.6.1.orig/configure tea-17.6.1/configure
+--- tea-17.6.1.orig/configure	2008-06-03 06:01:16.000000000 -0400
++++ tea-17.6.1/configure	2008-06-03 23:09:55.000000000 -0400
+@@ -5781,7 +5781,7 @@
+ 
+ 
+ echo -n "checking for zziplib... "
+-if pkg-config --exists zziplib  ; then
++if false ; then
+ 	LIBS="$LIBS `pkg-config --libs zziplib `"
+ 	CFLAGS="$CFLAGS `pkg-config --cflags zziplib `"
+ 
+@@ -5813,6 +5813,7 @@
+ 		echo "yes"
+ 	else
+ 		echo "no"
++		exit 1
+ 	fi
+ 
+ else
+@@ -6257,7 +6258,7 @@
+ 	echo -n "checking for gtk+-unix-print-2.0... "
+ 	if pkg-config --exists gtk+-unix-print-2.0  ; then
+ 		LIBS="$LIBS `pkg-config --libs gtk+-unix-print-2.0 `"
+-		CFLAGS="$CFLAGS `pkg-config --cflags gtk+-unix-print-2.0 `"
++		CPPFLAGS="$CPPFLAGS `pkg-config --cflags gtk+-unix-print-2.0 `"
+ 		echo "yes"
+ 
+ cat >>confdefs.h <<\_ACEOF
+@@ -6298,7 +6299,8 @@
+ 	echo "yes"
+ 
+ else
+-	echo -n "GtkSourceView2 not found, now we search GtkSourceView1"
++	echo -n "Fink package enforces GtkSourceView2 usage, not falling back to  GtkSourceView1"
++	exit 1
+ 
+ 	if pkg-config --exists gtksourceview-1.0 ; then
+ 		LIBS="$LIBS `pkg-config --libs gtksourceview-1.0`"
+diff -Nurd -x'*~' tea-17.6.1.orig/src/rox_strings.c tea-17.6.1/src/rox_strings.c
+--- tea-17.6.1.orig/src/rox_strings.c	2008-05-07 05:14:23.000000000 -0400
++++ tea-17.6.1/src/rox_strings.c	2008-06-03 20:36:43.000000000 -0400
+@@ -34,6 +34,7 @@
  
  #include <ctype.h>
  #include <sys/stat.h>
diff --git a/10.4/stable/main/finkinfo/gnome/libgnomeprint2.2.patch b/10.4/stable/main/finkinfo/gnome/libgnomeprint2.2.patch
--- a/10.4/stable/main/finkinfo/gnome/libgnomeprint2.2.patch
+++ b/10.4/stable/main/finkinfo/gnome/libgnomeprint2.2.patch
@@ -1,36 +1,26 @@
-diff -Naur libgnomeprint-2.6.0-old/configure libgnomeprint-2.6.0/configure
---- libgnomeprint-2.6.0-old/configure	Mon Mar 22 09:04:21 2004
-+++ libgnomeprint-2.6.0/configure	Wed Apr  7 10:22:13 2004
-@@ -22437,7 +22437,7 @@
- GNOME_PRINT_DATA_DIR=$GNOME_PRINT_DATA_DIR
+diff -Nurd -x'*~' libgnomeprint-2.18.3.orig/configure libgnomeprint-2.18.3/configure
+--- libgnomeprint-2.18.3.orig/configure	2008-01-28 11:07:08.000000000 -0500
++++ libgnomeprint-2.18.3/configure	2008-01-30 23:37:20.000000000 -0500
+@@ -23957,11 +23957,6 @@
+   ;;
+ esac
  
+-if test "x$LIBM" = "x"; then
+-	{ { echo "$as_me:$LINENO: error: You need -lm(mathematic library) for this version of libgnomeprint." >&5
+-echo "$as_me: error: You need -lm(mathematic library) for this version of libgnomeprint." >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
+ LDFLAGS="$LDFLAGS $LIBM"
+ 
+ FREETYPE_LIBS=
+@@ -24915,8 +24910,8 @@
+    { (exit 1); exit 1; }; }
+ fi
  
 -LIBGNOMEPRINT_CFLAGS="$GP_CFLAGS $FREETYPE_CFLAGS"
+-LIBGNOMEPRINT_LIBS="$GP_LIBS $FREETYPE_LIBS $Z_LIBS"
 +LIBGNOMEPRINT_CFLAGS="$FREETYPE_CFLAGS $GP_CFLAGS"
--LIBGNOMEPRINT_LIBS="$GP_LIBS $FREETYPE_LIBS"
-+LIBGNOMEPRINT_LIBS="$GP_LIBS $FREETYPE_LIBS $Z_LIBS"
++LIBGNOMEPRINT_LIBS="$FREETYPE_LIBS $GP_LIBS $Z_LIBS"
  
  
-diff -Naur libgnomeprint-2.6.0-old/libgnomeprint/gnome-fontmap.c libgnomeprint-2.6.0/libgnomeprint/gnome-fontmap.c
---- libgnomeprint-2.6.0-old/libgnomeprint/gnome-fontmap.c	Fri Jan 30 15:22:08 2004
-+++ libgnomeprint-2.6.0/libgnomeprint/gnome-fontmap.c	Wed Apr  7 10:22:13 2004
-@@ -197,6 +197,8 @@
- 		font_type = GP_FONT_ENTRY_TYPE1;
- 	else if (strcasecmp (c, ".ttf") == 0)
- 		font_type = GP_FONT_ENTRY_TRUETYPE;
-+        else if (strcasecmp (c, ".otf") == 0)
-+                font_type = GP_FONT_ENTRY_TRUETYPE;
- 	else if (strcasecmp (c, ".font") == 0) /* See #102400 */
- 		font_type = GP_FONT_ENTRY_TRUETYPE;
- 	else {
-diff -Naur libgnomeprint-2.6.0-old/libgnomeprint/gnome-print.c libgnomeprint-2.6.0/libgnomeprint/gnome-print.c
---- libgnomeprint-2.6.0-old/libgnomeprint/gnome-print.c	Tue Feb 24 15:33:07 2004
-+++ libgnomeprint-2.6.0/libgnomeprint/gnome-print.c	Wed Apr  7 10:22:13 2004
-@@ -28,6 +28,7 @@
- #include <config.h>
- #include <string.h>
- #include <gmodule.h>
-+#include <sys/types.h>
  
- #include <libgnomeprint/gnome-print-i18n.h>
- #include <libgnomeprint/gnome-print-private.h>
