Remove nad2bin check from configure

diff --git a/10.9-libcxx/stable/main/finkinfo/sci/grass64.patch b/10.9-libcxx/stable/main/finkinfo/sci/grass64.patch
--- a/10.9-libcxx/stable/main/finkinfo/sci/grass64.patch
+++ b/10.9-libcxx/stable/main/finkinfo/sci/grass64.patch
@@ -1,6 +1,66 @@
-diff -uNr grass-6.4.3/include/iostream/empq_impl.h grass-6.4.3.fink/include/iostream/empq_impl.h
---- grass-6.4.3/include/iostream/empq_impl.h	2012-12-22 05:52:06.000000000 -0500
-+++ grass-6.4.3.fink/include/iostream/empq_impl.h	2013-11-22 18:38:57.000000000 -0500
+diff -ruN grass-6.4.3-orig/configure grass-6.4.3/configure
+--- grass-6.4.3-orig/configure	2021-02-04 17:05:23.000000000 +0900
++++ grass-6.4.3/configure	2021-02-04 17:08:58.000000000 +0900
+@@ -7273,44 +7273,6 @@
+ 
+ 
+ 
+-# nad2bin needs to be in path for installing datum gridshift files
+-
+-# Extract the first word of "nad2bin", so it can be a program name with args.
+-set dummy nad2bin; ac_word=$2
+-echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+-echo "configure:7282: checking for $ac_word" >&5
+-
+-case "$NAD2BIN" in
+-  /*)
+-  ac_cv_path_NAD2BIN="$NAD2BIN" # Let the user override the test with a path.
+-  ;;
+-  ?:/*)			 
+-  ac_cv_path_NAD2BIN="$NAD2BIN" # Let the user override the test with a dos path.
+-  ;;
+-  *)
+-  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+-  ac_dummy="$PATH"
+-  for ac_dir in $ac_dummy; do 
+-    test -z "$ac_dir" && ac_dir=.
+-    if test -f $ac_dir/$ac_word; then
+-      ac_cv_path_NAD2BIN="$ac_dir/$ac_word"
+-      break
+-    fi
+-  done
+-  IFS="$ac_save_ifs"
+-  test -z "$ac_cv_path_NAD2BIN" && ac_cv_path_NAD2BIN="no"
+-  ;;
+-esac
+-NAD2BIN="$ac_cv_path_NAD2BIN"
+-if test -n "$NAD2BIN"; then
+-  echo "$ac_t""$NAD2BIN" 1>&6
+-else
+-  echo "$ac_t""no" 1>&6
+-fi
+-
+-if test "$NAD2BIN" = "no"; then
+-    { echo "configure: error: *** Unable to locate nad2bin (needs to be in PATH)." 1>&2; exit 1; }
+-fi
+ 
+ # Done checking PROJ
+ 
+diff -ruN grass-6.4.3-orig/imagery/i.landsat.toar/landsat_met.c grass-6.4.3/imagery/i.landsat.toar/landsat_met.c
+--- grass-6.4.3-orig/imagery/i.landsat.toar/landsat_met.c	2021-02-04 17:05:23.000000000 +0900
++++ grass-6.4.3/imagery/i.landsat.toar/landsat_met.c	2021-02-04 17:08:33.000000000 +0900
+@@ -17,7 +17,7 @@
+ #define TM5_MET_SIZE    28700	/* .met file size 28686 bytes */
+ 
+ 
+-inline void chrncpy(char *dest, char src[], int n)
++static inline void chrncpy(char *dest, char src[], int n)
+ {
+     int i;
+ 
+diff -ruN grass-6.4.3-orig/include/iostream/empq_impl.h grass-6.4.3/include/iostream/empq_impl.h
+--- grass-6.4.3-orig/include/iostream/empq_impl.h	2021-02-04 17:05:23.000000000 +0900
++++ grass-6.4.3/include/iostream/empq_impl.h	2021-02-04 17:08:33.000000000 +0900
 @@ -36,6 +36,8 @@
  #define __EMPQ_IMPL_H
  
@@ -10,9 +70,9 @@ diff -uNr grass-6.4.3/include/iostream/empq_impl.h grass-6.4.3.fink/include/iost
  using namespace std;
  
  #include "empq.h"
-diff -uNr grass-6.4.3/include/iostream/imbuffer.h grass-6.4.3.fink/include/iostream/imbuffer.h
---- grass-6.4.3/include/iostream/imbuffer.h	2012-12-22 05:52:06.000000000 -0500
-+++ grass-6.4.3.fink/include/iostream/imbuffer.h	2013-11-22 18:38:57.000000000 -0500
+diff -ruN grass-6.4.3-orig/include/iostream/imbuffer.h grass-6.4.3/include/iostream/imbuffer.h
+--- grass-6.4.3-orig/include/iostream/imbuffer.h	2021-02-04 17:05:23.000000000 +0900
++++ grass-6.4.3/include/iostream/imbuffer.h	2021-02-04 17:08:33.000000000 +0900
 @@ -22,6 +22,9 @@
  
  
@@ -23,9 +83,9 @@ diff -uNr grass-6.4.3/include/iostream/imbuffer.h grass-6.4.3.fink/include/iostr
  #include <assert.h>
  #include <stdlib.h>
  
-diff -uNr grass-6.4.3/lib/init/init.sh grass-6.4.3.fink/lib/init/init.sh
---- grass-6.4.3/lib/init/init.sh	2013-04-27 05:52:12.000000000 -0400
-+++ grass-6.4.3.fink/lib/init/init.sh	2013-11-22 18:47:08.000000000 -0500
+diff -ruN grass-6.4.3-orig/lib/init/init.sh grass-6.4.3/lib/init/init.sh
+--- grass-6.4.3-orig/lib/init/init.sh	2021-02-04 17:05:24.000000000 +0900
++++ grass-6.4.3/lib/init/init.sh	2021-02-04 17:08:33.000000000 +0900
 @@ -25,7 +25,8 @@
  trap "echo 'User break!' ; exit" 2 3 15
  
@@ -100,9 +160,9 @@ diff -uNr grass-6.4.3/lib/init/init.sh grass-6.4.3.fink/lib/init/init.sh
  echo "Cleaning up temporary files ..."
  
  "$ETC/clean_temp" > /dev/null
-diff -uNr grass-6.4.3/lib/python/ctypes/ctypesgencore/printer/defaultheader.py grass-6.4.3.fink/lib/python/ctypes/ctypesgencore/printer/defaultheader.py
---- grass-6.4.3/lib/python/ctypes/ctypesgencore/printer/defaultheader.py	2011-04-16 05:52:08.000000000 -0400
-+++ grass-6.4.3.fink/lib/python/ctypes/ctypesgencore/printer/defaultheader.py	2013-11-22 18:38:57.000000000 -0500
+diff -ruN grass-6.4.3-orig/lib/python/ctypes/ctypesgencore/printer/defaultheader.py grass-6.4.3/lib/python/ctypes/ctypesgencore/printer/defaultheader.py
+--- grass-6.4.3-orig/lib/python/ctypes/ctypesgencore/printer/defaultheader.py	2021-02-04 17:05:24.000000000 +0900
++++ grass-6.4.3/lib/python/ctypes/ctypesgencore/printer/defaultheader.py	2021-02-04 17:08:33.000000000 +0900
 @@ -1,7 +1,5 @@
  '''Wrapper for %(name)s
  
@@ -111,9 +171,9 @@ diff -uNr grass-6.4.3/lib/python/ctypes/ctypesgencore/printer/defaultheader.py g
  
  Do not modify this file.
  '''
-diff -uNr grass-6.4.3/macosx/Makefile grass-6.4.3.fink/macosx/Makefile
---- grass-6.4.3/macosx/Makefile	2013-06-01 05:52:06.000000000 -0400
-+++ grass-6.4.3.fink/macosx/Makefile	2013-11-22 18:38:57.000000000 -0500
+diff -ruN grass-6.4.3-orig/macosx/Makefile grass-6.4.3/macosx/Makefile
+--- grass-6.4.3-orig/macosx/Makefile	2021-02-04 17:05:24.000000000 +0900
++++ grass-6.4.3/macosx/Makefile	2021-02-04 17:08:33.000000000 +0900
 @@ -4,8 +4,8 @@
  
  MACOSX_APP_NAME = GRASS-${GRASS_VERSION_MAJOR}.${GRASS_VERSION_MINOR}.app
@@ -163,9 +223,9 @@ diff -uNr grass-6.4.3/macosx/Makefile grass-6.4.3.fink/macosx/Makefile
  
  macosx-support-dir:
  	${MAKE_DIR_CMD} ${MACOSX_SUPPDIR}
-diff -uNr grass-6.4.3/macosx/Makefile.orig grass-6.4.3.fink/macosx/Makefile.orig
---- grass-6.4.3/macosx/Makefile.orig	1969-12-31 19:00:00.000000000 -0500
-+++ grass-6.4.3.fink/macosx/Makefile.orig	2013-06-01 05:52:06.000000000 -0400
+diff -ruN grass-6.4.3-orig/macosx/Makefile.orig grass-6.4.3/macosx/Makefile.orig
+--- grass-6.4.3-orig/macosx/Makefile.orig	1970-01-01 09:00:00.000000000 +0900
++++ grass-6.4.3/macosx/Makefile.orig	2021-02-04 17:08:33.000000000 +0900
 @@ -0,0 +1,123 @@
 +MODULE_TOPDIR = ..
 +
@@ -290,9 +350,9 @@ diff -uNr grass-6.4.3/macosx/Makefile.orig grass-6.4.3.fink/macosx/Makefile.orig
 +clean: cleansubdirs
 +	-rm -rf ${ARCH_DISTDIR}/${MACOSX_APP_NAME}/ 2>/dev/null
 +	-rm -rf ${ARCH_DISTDIR}/modbuild/ 2>/dev/null
-diff -uNr grass-6.4.3/macosx/app/build_gui_user_menu.sh grass-6.4.3.fink/macosx/app/build_gui_user_menu.sh
---- grass-6.4.3/macosx/app/build_gui_user_menu.sh	2013-06-01 05:52:06.000000000 -0400
-+++ grass-6.4.3.fink/macosx/app/build_gui_user_menu.sh	2013-11-22 18:48:37.000000000 -0500
+diff -ruN grass-6.4.3-orig/macosx/app/build_gui_user_menu.sh grass-6.4.3/macosx/app/build_gui_user_menu.sh
+--- grass-6.4.3-orig/macosx/app/build_gui_user_menu.sh	2021-02-04 17:05:24.000000000 +0900
++++ grass-6.4.3/macosx/app/build_gui_user_menu.sh	2021-02-04 17:08:33.000000000 +0900
 @@ -14,7 +14,7 @@
  GRASS_MMVER=`cut -d . -f 1-2 "$GISBASE/etc/VERSIONNUMBER"`
  BINDIR="$HOME/Library/GRASS/$GRASS_MMVER/Modules/bin"
@@ -302,9 +362,9 @@ diff -uNr grass-6.4.3/macosx/app/build_gui_user_menu.sh grass-6.4.3.fink/macosx/
  SCRIPTDIRG="/Library/GRASS/$GRASS_MMVER/Modules/scripts"
  MENUDIR="$HOME/Library/GRASS/$GRASS_MMVER/Modules/etc"
  
-diff -uNr grass-6.4.3/macosx/app/build_html_user_index.sh grass-6.4.3.fink/macosx/app/build_html_user_index.sh
---- grass-6.4.3/macosx/app/build_html_user_index.sh	2011-05-21 05:52:10.000000000 -0400
-+++ grass-6.4.3.fink/macosx/app/build_html_user_index.sh	2013-11-22 18:38:57.000000000 -0500
+diff -ruN grass-6.4.3-orig/macosx/app/build_html_user_index.sh grass-6.4.3/macosx/app/build_html_user_index.sh
+--- grass-6.4.3-orig/macosx/app/build_html_user_index.sh	2021-02-04 17:05:24.000000000 +0900
++++ grass-6.4.3/macosx/app/build_html_user_index.sh	2021-02-04 17:08:33.000000000 +0900
 @@ -19,13 +19,13 @@
  GRASS_MMVER=`cut -d . -f 1-2 "$GISBASE/etc/VERSIONNUMBER"`
  GRASSVERSION=`cat "$GISBASE/etc/VERSIONNUMBER"`
@@ -321,9 +381,9 @@ diff -uNr grass-6.4.3/macosx/app/build_html_user_index.sh grass-6.4.3.fink/macos
  fi
  
  write_html_header()
-diff -uNr grass-6.4.3/macosx/app/grass.sh.in grass-6.4.3.fink/macosx/app/grass.sh.in
---- grass-6.4.3/macosx/app/grass.sh.in	2013-06-01 05:52:06.000000000 -0400
-+++ grass-6.4.3.fink/macosx/app/grass.sh.in	2013-11-22 18:38:57.000000000 -0500
+diff -ruN grass-6.4.3-orig/macosx/app/grass.sh.in grass-6.4.3/macosx/app/grass.sh.in
+--- grass-6.4.3-orig/macosx/app/grass.sh.in	2021-02-04 17:05:24.000000000 +0900
++++ grass-6.4.3/macosx/app/grass.sh.in	2021-02-04 17:08:33.000000000 +0900
 @@ -32,7 +32,7 @@
  grass_ver=`cut -d . -f 1-2 "$GISBASE/etc/VERSIONNUMBER"`
  
@@ -466,9 +526,9 @@ diff -uNr grass-6.4.3/macosx/app/grass.sh.in grass-6.4.3.fink/macosx/app/grass.s
  	fi
  fi
  if [ "$GRASS_GUI" = "text" ] && [ "$x11" = "tig" ] ; then
-diff -uNr grass-6.4.3/macosx/app/grass.sh.in.orig grass-6.4.3.fink/macosx/app/grass.sh.in.orig
---- grass-6.4.3/macosx/app/grass.sh.in.orig	1969-12-31 19:00:00.000000000 -0500
-+++ grass-6.4.3.fink/macosx/app/grass.sh.in.orig	2013-06-01 05:52:06.000000000 -0400
+diff -ruN grass-6.4.3-orig/macosx/app/grass.sh.in.orig grass-6.4.3/macosx/app/grass.sh.in.orig
+--- grass-6.4.3-orig/macosx/app/grass.sh.in.orig	1970-01-01 09:00:00.000000000 +0900
++++ grass-6.4.3/macosx/app/grass.sh.in.orig	2021-02-04 17:08:33.000000000 +0900
 @@ -0,0 +1,267 @@
 +#! /bin/sh
 +#############################################################################
@@ -737,9 +797,9 @@ diff -uNr grass-6.4.3/macosx/app/grass.sh.in.orig grass-6.4.3.fink/macosx/app/gr
 +fi
 +
 +exec "$GISBASE/etc/Init.sh" "$@"
-diff -uNr grass-6.4.3/macosx/app/python_wrapper grass-6.4.3.fink/macosx/app/python_wrapper
---- grass-6.4.3/macosx/app/python_wrapper	2010-02-20 05:53:27.000000000 -0500
-+++ grass-6.4.3.fink/macosx/app/python_wrapper	2013-11-22 18:38:57.000000000 -0500
+diff -ruN grass-6.4.3-orig/macosx/app/python_wrapper grass-6.4.3/macosx/app/python_wrapper
+--- grass-6.4.3-orig/macosx/app/python_wrapper	2021-02-04 17:05:24.000000000 +0900
++++ grass-6.4.3/macosx/app/python_wrapper	2021-02-04 17:08:33.000000000 +0900
 @@ -29,9 +29,7 @@
  SYSARCH=`uname -p`
  SYSVER=`uname -r | cut -d . -f 1`
@@ -751,9 +811,9 @@ diff -uNr grass-6.4.3/macosx/app/python_wrapper grass-6.4.3.fink/macosx/app/pyth
  # can't run python 64bit if wx not 64bit, assume OSX 10.5+  possible 64bit
  if [ $(($SYSVER)) -gt 5 ] && [ "$GRASS_WX64BIT" = "0" ] ; then
  	case $SYSARCH in
-diff -uNr grass-6.4.3/macosx/modbuild/Makefile grass-6.4.3.fink/macosx/modbuild/Makefile
---- grass-6.4.3/macosx/modbuild/Makefile	2009-04-25 05:52:32.000000000 -0400
-+++ grass-6.4.3.fink/macosx/modbuild/Makefile	2013-11-22 18:38:57.000000000 -0500
+diff -ruN grass-6.4.3-orig/macosx/modbuild/Makefile grass-6.4.3/macosx/modbuild/Makefile
+--- grass-6.4.3-orig/macosx/modbuild/Makefile	2021-02-04 17:05:24.000000000 +0900
++++ grass-6.4.3/macosx/modbuild/Makefile	2021-02-04 17:08:33.000000000 +0900
 @@ -9,7 +9,7 @@
  	MACOSX_APP_NAME = GRASS-${GRASS_VERSION_MAJOR}.${GRASS_VERSION_MINOR}.app
  endif
@@ -792,30 +852,9 @@ diff -uNr grass-6.4.3/macosx/modbuild/Makefile grass-6.4.3.fink/macosx/modbuild/
  	-cp $(MODULE_TOPDIR)/include/Make/Lib.make $(ARCH_DISTDIR)/modbuild/include/Make/
  	-cp $(MODULE_TOPDIR)/include/Make/Man.make $(ARCH_DISTDIR)/modbuild/include/Make/
  	sed -e 's,$$(DEPENDENCIES),,g' $(MODULE_TOPDIR)/include/Make/Module.make > $(ARCH_DISTDIR)/modbuild/include/Make/Module.make
---- grass-6.4.3/raster/r.terraflow/nodata.cc.orig	2013-11-22 19:32:02.000000000 -0500
-+++ grass-6.4.3/raster/r.terraflow/nodata.cc	2013-11-22 19:32:21.000000000 -0500
-@@ -73,7 +73,7 @@
- 
- 
- int
--is_void(elevation_type el) {
-+grass_is_void(elevation_type el) {
-   return (el == nodataType::ELEVATION_NODATA);
- }
- 
---- grass-6.4.3/raster/r.terraflow/nodata.h.orig	2013-11-22 19:31:57.000000000 -0500
-+++ grass-6.4.3/raster/r.terraflow/nodata.h	2013-11-22 19:32:13.000000000 -0500
-@@ -37,7 +37,7 @@
- int is_nodata(elevation_type el);
- int is_nodata(int x);
- int is_nodata(float x);
--int is_void(elevation_type el);
-+int grass_is_void(elevation_type el);
- 
- 
- class nodataType : public ijBaseType {
---- grass-6.4.3/raster/r.terraflow/direction.cc.orig	2013-11-22 19:09:10.000000000 -0500
-+++ grass-6.4.3/raster/r.terraflow/direction.cc	2013-11-22 19:31:07.000000000 -0500
+diff -ruN grass-6.4.3-orig/raster/r.terraflow/direction.cc grass-6.4.3/raster/r.terraflow/direction.cc
+--- grass-6.4.3-orig/raster/r.terraflow/direction.cc	2021-02-04 17:05:25.000000000 +0900
++++ grass-6.4.3/raster/r.terraflow/direction.cc	2021-02-04 17:08:33.000000000 +0900
 @@ -53,11 +53,11 @@
    
    if(!is_nodata(elevwin.get())) {
@@ -832,14 +871,27 @@ diff -uNr grass-6.4.3/macosx/modbuild/Makefile grass-6.4.3.fink/macosx/modbuild/
      }
    }
    
---- grass-6.4.3/imagery/i.landsat.toar/landsat_met.c.orig	2013-11-22 19:41:33.000000000 -0500
-+++ grass-6.4.3/imagery/i.landsat.toar/landsat_met.c	2013-11-22 19:41:49.000000000 -0500
-@@ -17,7 +17,7 @@
- #define TM5_MET_SIZE    28700	/* .met file size 28686 bytes */
+diff -ruN grass-6.4.3-orig/raster/r.terraflow/nodata.cc grass-6.4.3/raster/r.terraflow/nodata.cc
+--- grass-6.4.3-orig/raster/r.terraflow/nodata.cc	2021-02-04 17:05:25.000000000 +0900
++++ grass-6.4.3/raster/r.terraflow/nodata.cc	2021-02-04 17:08:33.000000000 +0900
+@@ -73,7 +73,7 @@
  
  
--inline void chrncpy(char *dest, char src[], int n)
-+static inline void chrncpy(char *dest, char src[], int n)
- {
-     int i;
+ int
+-is_void(elevation_type el) {
++grass_is_void(elevation_type el) {
+   return (el == nodataType::ELEVATION_NODATA);
+ }
  
+diff -ruN grass-6.4.3-orig/raster/r.terraflow/nodata.h grass-6.4.3/raster/r.terraflow/nodata.h
+--- grass-6.4.3-orig/raster/r.terraflow/nodata.h	2021-02-04 17:05:25.000000000 +0900
++++ grass-6.4.3/raster/r.terraflow/nodata.h	2021-02-04 17:08:33.000000000 +0900
+@@ -37,7 +37,7 @@
+ int is_nodata(elevation_type el);
+ int is_nodata(int x);
+ int is_nodata(float x);
+-int is_void(elevation_type el);
++int grass_is_void(elevation_type el);
+ 
+ 
+ class nodataType : public ijBaseType {
diff --git a/10.9-libcxx/stable/main/finkinfo/sci/grass72.patch b/10.9-libcxx/stable/main/finkinfo/sci/grass72.patch
--- a/10.9-libcxx/stable/main/finkinfo/sci/grass72.patch
+++ b/10.9-libcxx/stable/main/finkinfo/sci/grass72.patch
@@ -1,6 +1,6 @@
 diff -ruN grass-7.2.0-orig/aclocal.m4 grass-7.2.0/aclocal.m4
---- grass-7.2.0-orig/aclocal.m4	2017-04-22 08:00:46.000000000 +0900
-+++ grass-7.2.0/aclocal.m4	2017-04-22 08:01:03.000000000 +0900
+--- grass-7.2.0-orig/aclocal.m4	2021-02-04 17:11:27.000000000 +0900
++++ grass-7.2.0/aclocal.m4	2021-02-04 17:12:13.000000000 +0900
 @@ -510,7 +510,7 @@
  	*-apple-darwin*)
  	    SHLIB_CFLAGS="-fno-common"
@@ -10,10 +10,58 @@ diff -ruN grass-7.2.0-orig/aclocal.m4 grass-7.2.0/aclocal.m4
  	    LD_LIBRARY_PATH_VAR="DYLD_LIBRARY_PATH"
  	    ;;
  	*-sun-solaris*)
-Binary files grass-7.2.0-orig/gui/wxpython/core/.DS_Store and grass-7.2.0/gui/wxpython/core/.DS_Store differ
+diff -ruN grass-7.2.0-orig/configure grass-7.2.0/configure
+--- grass-7.2.0-orig/configure	2021-02-04 17:11:28.000000000 +0900
++++ grass-7.2.0/configure	2021-02-04 17:12:37.000000000 +0900
+@@ -5709,45 +5709,6 @@
+ 
+ 
+ 
+-# nad2bin needs to be in path for installing datum gridshift files
+-
+-# Extract the first word of "nad2bin", so it can be a program name with args.
+-set dummy nad2bin; ac_word=$2
+-echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+-echo "configure:5718: checking for $ac_word" >&5
+-
+-case "$NAD2BIN" in
+-  /*)
+-  ac_cv_path_NAD2BIN="$NAD2BIN" # Let the user override the test with a path.
+-  ;;
+-  ?:/*)			 
+-  ac_cv_path_NAD2BIN="$NAD2BIN" # Let the user override the test with a dos path.
+-  ;;
+-  *)
+-  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+-  ac_dummy="$PATH"
+-  for ac_dir in $ac_dummy; do 
+-    test -z "$ac_dir" && ac_dir=.
+-    if test -f $ac_dir/$ac_word; then
+-      ac_cv_path_NAD2BIN="$ac_dir/$ac_word"
+-      break
+-    fi
+-  done
+-  IFS="$ac_save_ifs"
+-  test -z "$ac_cv_path_NAD2BIN" && ac_cv_path_NAD2BIN="no"
+-  ;;
+-esac
+-NAD2BIN="$ac_cv_path_NAD2BIN"
+-if test -n "$NAD2BIN"; then
+-  echo "$ac_t""$NAD2BIN" 1>&6
+-else
+-  echo "$ac_t""no" 1>&6
+-fi
+-
+-if test "$NAD2BIN" = "no"; then
+-    { echo "configure: error: *** Unable to locate nad2bin (needs to be in PATH)." 1>&2; exit 1; }
+-fi
+-
+ # Done checking PROJ
+ 
+ # Enable regex option
 diff -ruN grass-7.2.0-orig/gui/wxpython/core/gcmd.py grass-7.2.0/gui/wxpython/core/gcmd.py
---- grass-7.2.0-orig/gui/wxpython/core/gcmd.py	2017-04-22 08:00:46.000000000 +0900
-+++ grass-7.2.0/gui/wxpython/core/gcmd.py	2017-04-22 08:04:03.000000000 +0900
+--- grass-7.2.0-orig/gui/wxpython/core/gcmd.py	2021-02-04 17:11:30.000000000 +0900
++++ grass-7.2.0/gui/wxpython/core/gcmd.py	2021-02-04 17:12:13.000000000 +0900
 @@ -777,9 +777,7 @@
  
      :return: system encoding (can be None)
@@ -26,8 +74,8 @@ diff -ruN grass-7.2.0-orig/gui/wxpython/core/gcmd.py grass-7.2.0/gui/wxpython/co
      Debug.msg(1, "GetSystemEncoding(): %s" % enc)
      return enc
 diff -ruN grass-7.2.0-orig/include/Make/Install.make grass-7.2.0/include/Make/Install.make
---- grass-7.2.0-orig/include/Make/Install.make	2017-04-22 08:00:47.000000000 +0900
-+++ grass-7.2.0/include/Make/Install.make	2017-04-22 08:01:03.000000000 +0900
+--- grass-7.2.0-orig/include/Make/Install.make	2021-02-04 17:11:34.000000000 +0900
++++ grass-7.2.0/include/Make/Install.make	2021-02-04 17:12:13.000000000 +0900
 @@ -116,11 +116,6 @@
  	-$(INSTALL) config.status $(INST_DIR)/config.status
  	-$(CHMOD) -R a+rX $(INST_DIR) 2>/dev/null
@@ -41,8 +89,8 @@ diff -ruN grass-7.2.0-orig/include/Make/Install.make grass-7.2.0/include/Make/In
  	$(MAKE_DIR_CMD) $@
  
 diff -ruN grass-7.2.0-orig/include/Make/Platform.make.in grass-7.2.0/include/Make/Platform.make.in
---- grass-7.2.0-orig/include/Make/Platform.make.in	2017-04-22 08:00:47.000000000 +0900
-+++ grass-7.2.0/include/Make/Platform.make.in	2017-04-22 08:01:03.000000000 +0900
+--- grass-7.2.0-orig/include/Make/Platform.make.in	2021-02-04 17:11:34.000000000 +0900
++++ grass-7.2.0/include/Make/Platform.make.in	2021-02-04 17:12:13.000000000 +0900
 @@ -51,6 +51,7 @@
  STRIPFLAG           = @STRIPFLAG@
  LD_SEARCH_FLAGS     = @LD_SEARCH_FLAGS@
@@ -52,8 +100,8 @@ diff -ruN grass-7.2.0-orig/include/Make/Platform.make.in grass-7.2.0/include/Mak
  #generate static (ST) or shared (SH)
  GRASS_LIBRARY_TYPE  = @GRASS_LIBRARY_TYPE@
 diff -ruN grass-7.2.0-orig/include/Make/Rules.make grass-7.2.0/include/Make/Rules.make
---- grass-7.2.0-orig/include/Make/Rules.make	2017-04-22 08:00:47.000000000 +0900
-+++ grass-7.2.0/include/Make/Rules.make	2017-04-22 08:01:03.000000000 +0900
+--- grass-7.2.0-orig/include/Make/Rules.make	2021-02-04 17:11:34.000000000 +0900
++++ grass-7.2.0/include/Make/Rules.make	2021-02-04 17:12:13.000000000 +0900
 @@ -38,6 +38,7 @@
  	PATH="$(ARCH_DISTDIR)/bin:$(GISBASE)/bin:$(GISBASE)/scripts:$$PATH" \
  	PYTHONPATH="$(GRASS_PYTHONPATH)" \
@@ -62,10 +110,9 @@ diff -ruN grass-7.2.0-orig/include/Make/Rules.make grass-7.2.0/include/Make/Rule
  	LC_ALL=C \
  	$(1)
  
-Binary files grass-7.2.0-orig/lib/init/.DS_Store and grass-7.2.0/lib/init/.DS_Store differ
 diff -ruN grass-7.2.0-orig/lib/init/grass.py grass-7.2.0/lib/init/grass.py
---- grass-7.2.0-orig/lib/init/grass.py	2017-04-22 08:00:47.000000000 +0900
-+++ grass-7.2.0/lib/init/grass.py	2017-04-22 08:01:03.000000000 +0900
+--- grass-7.2.0-orig/lib/init/grass.py	2021-02-04 17:11:35.000000000 +0900
++++ grass-7.2.0/lib/init/grass.py	2021-02-04 17:12:13.000000000 +0900
 @@ -1114,8 +1114,7 @@
              ## TOO DRASTIC: sys.exit("Fix system locale settings and then try again.")
              locale.setlocale(locale.LC_ALL, 'C')
@@ -84,11 +131,9 @@ diff -ruN grass-7.2.0-orig/lib/init/grass.py grass-7.2.0/lib/init/grass.py
                  normalized = locale.normalize('%s.%s' % (language, encoding))
                  locale.setlocale(locale.LC_ALL, normalized)
              except locale.Error as e:
-Binary files grass-7.2.0-orig/lib/python/.DS_Store and grass-7.2.0/lib/python/.DS_Store differ
-Binary files grass-7.2.0-orig/lib/python/ctypes/.DS_Store and grass-7.2.0/lib/python/ctypes/.DS_Store differ
 diff -ruN grass-7.2.0-orig/lib/python/ctypes/loader.py grass-7.2.0/lib/python/ctypes/loader.py
---- grass-7.2.0-orig/lib/python/ctypes/loader.py	2017-04-22 08:00:47.000000000 +0900
-+++ grass-7.2.0/lib/python/ctypes/loader.py	2017-04-22 08:05:52.000000000 +0900
+--- grass-7.2.0-orig/lib/python/ctypes/loader.py	2021-02-04 17:11:36.000000000 +0900
++++ grass-7.2.0/lib/python/ctypes/loader.py	2021-02-04 17:12:13.000000000 +0900
 @@ -143,7 +143,7 @@
                  '..',
                  'Frameworks'))
@@ -99,8 +144,8 @@ diff -ruN grass-7.2.0-orig/lib/python/ctypes/loader.py grass-7.2.0/lib/python/ct
          return dirs
  
 diff -ruN grass-7.2.0-orig/lib/python/script/utils.py grass-7.2.0/lib/python/script/utils.py
---- grass-7.2.0-orig/lib/python/script/utils.py	2017-04-22 08:00:47.000000000 +0900
-+++ grass-7.2.0/lib/python/script/utils.py	2017-04-27 18:48:04.000000000 +0900
+--- grass-7.2.0-orig/lib/python/script/utils.py	2021-02-04 17:11:36.000000000 +0900
++++ grass-7.2.0/lib/python/script/utils.py	2021-02-04 17:12:13.000000000 +0900
 @@ -158,7 +158,10 @@
      :param bytes bytes_: the bytes to decode
      """
@@ -125,10 +170,9 @@ diff -ruN grass-7.2.0-orig/lib/python/script/utils.py grass-7.2.0/lib/python/scr
      return string.encode(enc) if enc else string.encode()
  
  
-Binary files grass-7.2.0-orig/macosx/.DS_Store and grass-7.2.0/macosx/.DS_Store differ
 diff -ruN grass-7.2.0-orig/macosx/app/grass.sh.in grass-7.2.0/macosx/app/grass.sh.in
---- grass-7.2.0-orig/macosx/app/grass.sh.in	2017-04-22 08:00:47.000000000 +0900
-+++ grass-7.2.0/macosx/app/grass.sh.in	2017-04-27 18:47:34.000000000 +0900
+--- grass-7.2.0-orig/macosx/app/grass.sh.in	2021-02-04 17:11:41.000000000 +0900
++++ grass-7.2.0/macosx/app/grass.sh.in	2021-02-04 17:12:13.000000000 +0900
 @@ -20,6 +20,9 @@
  
  trap "echo 'User break!' ; exit" 2 3 9 15
