Upstream fix for a failing test

diff --git a/finkinfo/gnome/glib2-shlibs.patch b/finkinfo/gnome/glib2-shlibs.patch
--- a/finkinfo/gnome/glib2-shlibs.patch
+++ b/finkinfo/gnome/glib2-shlibs.patch
@@ -381,16 +381,36 @@ diff -Nurd -x'*~' glib-2.34.2.orig/glib/libcharset/charset.alias glib-2.34.2/gli
 +zh_CN.EUC		GB2312
 +zh_TW			UTF-8
 +zh_TW.Big5		BIG5
-diff -Nurd -x'*~' glib-2.34.2.orig/tests/Makefile.in glib-2.34.2/tests/Makefile.in
---- glib-2.34.2.orig/tests/Makefile.in	2012-11-09 22:32:58.000000000 -0500
-+++ glib-2.34.2/tests/Makefile.in	2012-11-17 13:13:41.000000000 -0500
-@@ -702,7 +702,8 @@
- TESTS_ENVIRONMENT = srcdir=$(srcdir) \
- 	LIBCHARSET_ALIAS_DIR=$(top_builddir)/glib/libcharset \
- 	MALLOC_CHECK_=2	\
--        MALLOC_PERTURB_=$$(($${RANDOM:-256} % 256))
-+        MALLOC_PERTURB_=$$(($${RANDOM:-256} % 256)) \
-+	PATH=$(top_builddir):$${PATH}}
+diff -Nurd -x'*~' glib-2.34.2.orig/tests/run-assert-msg-test.sh glib-2.34.2/tests/run-assert-msg-test.sh
+--- glib-2.34.2.orig/tests/run-assert-msg-test.sh	2012-03-11 20:42:43.000000000 -0400
++++ glib-2.34.2/tests/run-assert-msg-test.sh	2012-11-20 11:16:08.000000000 -0500
+@@ -19,6 +19,14 @@
+   error_out=/dev/stderr
+ fi  
  
- progs_ldadd = $(EFENCE) $(libglib) $(EFENCE)
- thread_ldadd = $(libgthread) $(G_THREAD_LIBS) $(progs_ldadd)
++if [ -z "$LIBTOOL" ]; then
++  if [ -f ../libtool ]; then
++    LIBTOOL=../libtool
++  else
++    LIBTOOL=libtool
++  fi
++fi
++
+ echo_v "Running assert-msg-test"
+ OUT=$(./assert-msg-test 2>&1) && fail "assert-msg-test should abort"
+ echo "$OUT" | grep -q '^ERROR:.*assert-msg-test.c:.*:.*main.*: assertion failed: (42 < 0)' || \
+@@ -29,13 +37,8 @@
+   exit 0
+ fi
+ 
+-msg_test="assert-msg-test"
+-if [ -e ".libs/lt-$msg_test" ]; then
+-       msg_test="lt-$msg_test"
+-fi
+ echo_v "Running gdb on assert-msg-test"
+-OUT=$(libtool --mode=execute gdb --batch --ex run --ex "set print elements 0" --ex "print (char*) __glib_assert_msg" .libs/$msg_test 2> $error_out) || \
+-  fail "failed to run gdb"
++OUT=$((echo run; echo "set print elements 0"; echo "print (char*) __glib_assert_msg") | $LIBTOOL --mode=execute gdb --batch -x /dev/stdin assert-msg-test 2> $error_out) || fail "failed to run gdb"
+ 
+ echo_v "Checking if assert message is in __glib_assert_msg"
+ if ! echo "$OUT" | grep -q '^$1.*"ERROR:.*assert-msg-test.c:.*:.*main.*: assertion failed: (42 < 0)"'; then
