fix a failing test

diff --git a/finkinfo/gnome/glib2-shlibs.patch b/finkinfo/gnome/glib2-shlibs.patch
--- a/finkinfo/gnome/glib2-shlibs.patch
+++ b/finkinfo/gnome/glib2-shlibs.patch
@@ -447,3 +447,15 @@ diff -Nurd -x'*~' glib-2.38.2.orig/glib/tests/Makefile.in glib-2.38.2/glib/tests
  
  # These tests corrupt the gcov bookkeeping, so we
  # skip them. See bug 682133
+diff -Nurd -x'*~' glib-2.38.2.orig/tests/run-assert-msg-test.sh glib-2.38.2/tests/run-assert-msg-test.sh
+--- glib-2.38.2.orig/tests/run-assert-msg-test.sh	2013-11-07 10:29:13.000000000 -0500
++++ glib-2.38.2/tests/run-assert-msg-test.sh	2014-06-07 06:32:27.000000000 -0400
+@@ -38,7 +38,7 @@
+ fi
+ 
+ echo_v "Running gdb on assert-msg-test"
+-OUT=$($LIBTOOL --mode=execute gdb --batch -x ${srcdir:-.}/assert-msg-test.gdb ./assert-msg-test 2> $error_out) || fail "failed to run gdb"
++OUT=$($LIBTOOL --mode=execute /usr/bin/gdb --batch -x ${srcdir:-.}/assert-msg-test.gdb ./assert-msg-test 2> $error_out) || fail "failed to run gdb"
+ 
+ echo_v "Checking if assert message is in __glib_assert_msg"
+ if ! echo "$OUT" | grep -q '^$1.*"GLib:ERROR:.*assert-msg-test.c:.*:.*main.*: assertion failed: (42 < 0)"'; then
