Updated to 2.0.1

diff --git a/10.2/unstable/main/finkinfo/text/lilypond.patch b/10.2/unstable/main/finkinfo/text/lilypond.patch
--- a/10.2/unstable/main/finkinfo/text/lilypond.patch
+++ b/10.2/unstable/main/finkinfo/text/lilypond.patch
@@ -1,6 +1,6 @@
-diff -u --rec lilypond-1.8.1-orig/buildscripts/clean-fonts.sh lilypond-1.8.1/buildscripts/clean-fonts.sh
---- lilypond-1.8.1-orig/buildscripts/clean-fonts.sh	Fri Mar 22 01:45:58 2002
-+++ lilypond-1.8.1/buildscripts/clean-fonts.sh	Mon Aug 25 22:20:39 2003
+diff -ru lilypond-2.0.1-orig/buildscripts/clean-fonts.sh lilypond-2.0.1/buildscripts/clean-fonts.sh
+--- lilypond-2.0.1-orig/buildscripts/clean-fonts.sh	Tue Sep 30 00:39:56 2003
++++ lilypond-2.0.1/buildscripts/clean-fonts.sh	Tue Sep 30 00:40:19 2003
 @@ -20,6 +20,7 @@
  /var/texfonts
  /var/cache/fonts
@@ -9,17 +9,26 @@ diff -u --rec lilypond-1.8.1-orig/buildscripts/clean-fonts.sh lilypond-1.8.1/bui
  "
  
  for i in $dirs; do
-diff -u --rec lilypond-1.8.1-orig/buildscripts/lilypond-profile.sh lilypond-1.8.1/buildscripts/lilypond-profile.sh
---- lilypond-1.8.1-orig/buildscripts/lilypond-profile.sh	Wed Aug  6 09:20:17 2003
-+++ lilypond-1.8.1/buildscripts/lilypond-profile.sh	Mon Aug 25 22:21:40 2003
-@@ -7,58 +7,6 @@
+diff -ru lilypond-2.0.1-orig/buildscripts/lilypond-profile.sh lilypond-2.0.1/buildscripts/lilypond-profile.sh
+--- lilypond-2.0.1-orig/buildscripts/lilypond-profile.sh	Tue Sep 30 00:39:56 2003
++++ lilypond-2.0.1/buildscripts/lilypond-profile.sh	Tue Sep 30 00:41:41 2003
+@@ -7,59 +7,6 @@
  # If run by hand or from you .profile, run as follows
  #   . /PATH/TO/lilypond-profile
  
--# workaround for ZSH posix $0-problem
--[ -n "$ZSH_NAME" ] && setopt nofunctionargzero
 -
--if [ `basename "$0"` = "lilypond-profile" ] ; then
+-
+-# workaround for ZSH posix $0-problem
+-
+-# for zsh: start removing here
+-if [ -n "$ZSH_NAME" ] ; then
+-    echo "You are running this script under zsh. Edit this script by hand. "
+-    echo 
+-    echo "(failed to source lilypond-profile)"
+-    return 2
+-fi
+-
+-if [ `basename "$0"` = "lilypond-profile" ] ; then 
 -    cat >/dev/stderr <<EOF
 -    
 -Error: This script cannot be run in a subshell; it MUST be sourced.
@@ -27,7 +36,7 @@ diff -u --rec lilypond-1.8.1-orig/buildscripts/lilypond-profile.sh lilypond-1.8.
 -
 -EXAMPLE 1: One time use 
 -
--	Do
+-	* Do
 -
 -	    . $0
 -
@@ -56,33 +65,117 @@ diff -u --rec lilypond-1.8.1-orig/buildscripts/lilypond-profile.sh lilypond-1.8.
 -
 -	* Logout
 -
--
--
 -EOF
 -
--
--## If the message above is printed erroneously,
--## the following commands  kills the current terminal/shell.
--## hence the ZSH  test above.
--
--    exit 2 
+-    return 2
 -else
--
+ #  for zsh: till here
+ 
  	if [ -z "$LILYPONDPREFIX" ]; then
- 	    datadir=`echo "@local_lilypond_datadir@" | sed 's!//!/!g'`
- 	else
-@@ -80,8 +28,3 @@
+@@ -83,8 +30,3 @@
  	# For direct ps output fonts. Add all available TeX Type1 fonts
  	## GS_FONTPATH=`kpsewhich -expand-path=\\$T1FONTS`:${GS_FONTPATH:=""}
  	## export GS_FONTPATH
 -
--fi
+-fi # remove for zsh
 - 	
 -
 -
-diff -u --rec lilypond-1.8.1-orig/lexer-gcc-3.1.sh lilypond-1.8.1/lexer-gcc-3.1.sh
---- lilypond-1.8.1-orig/lexer-gcc-3.1.sh	Wed Jul 30 13:50:27 2003
-+++ lilypond-1.8.1/lexer-gcc-3.1.sh	Mon Aug 25 22:20:39 2003
+diff -ru lilypond-2.0.1-orig/buildscripts/rpm2cpio.pl lilypond-2.0.1/buildscripts/rpm2cpio.pl
+--- lilypond-2.0.1-orig/buildscripts/rpm2cpio.pl	Tue Sep 30 01:04:57 2003
++++ lilypond-2.0.1/buildscripts/rpm2cpio.pl	Tue Sep 30 01:06:05 2003
+@@ -0,0 +1,88 @@
++#!/usr/bin/perl
++
++# Why does the world need another rpm2cpio?  Because the existing one
++# won't build unless you have half a ton of things that aren't really
++# required for it, since it uses the same library used to extract RPMs.
++# In particular, it won't build on the HPsUX box I'm on.
++
++#
++# Expanded quick-reference help by Rick Moen (not the original author 
++# of this script).
++#
++
++# add a path if desired
++$gzip = "gzip";
++
++sub printhelp {
++  print "\n";
++  print "rpm2cpio, perl version by orabidoo <odar\@pobox.com>\n";
++  print "\n";
++  print "use: rpm2cpio [file.rpm]\n";
++  print "dumps the contents to stdout as a GNU cpio archive\n";
++  print "\n";
++  print "In case it's non-obvious, you'll need to redirect output\n";
++  print "from this script, e.g., './rpm2cpio package.rpm > package.cpio'.\n";
++  print "Then, unpack in, say, /tmp with a cpio incantation like this one:\n";
++  print "'cpio -ivd < package.cpio'\n";
++  print "\n";
++  print "You can optionally combine both steps:\n";
++  print "'rpm2cpio package.rpm | cpio -iduv'\n";
++  print "\n";
++  print "In either event, you will also need the 'cpio' utility available\n";
++  print "on your system.  If you can't find it elsewhere, source code for\n";
++  print "GNU cpio is always available at ftp://ftp.gnu.org/gnu/cpio/.)\n";
++  print "You'll also, of course, need Perl, and will want this Perl script\n";
++  print "set as executable, i.e., by doing 'chmod 775 rpm2cpio'\n";
++  print "\n";
++  print "Be aware that this script works ONLY on version 3-format RPM\n";
++  print "archives.  You can check an archive's RPM-format version using\n";
++  print "the Unix 'file' utility.  Also, be aware that the 'cpio'\n";
++  print "incantations above will unpack files at the current directory\n";
++  print "level.\n";
++  print "\n";
++  
++  exit 0;
++}
++
++if ($#ARGV == -1) {
++  printhelp if -t STDIN;
++  $f = "STDIN";
++} elsif ($#ARGV == 0) {
++  open(F, "< $ARGV[0]") or die "Can't read file $ARGV[0]\n";
++  $f = 'F';
++} else {
++  printhelp;
++}
++
++printhelp if -t STDOUT;
++
++# gobble the file up
++undef $/;
++$|=1;
++$rpm = <$f>;
++close ($f);
++
++($magic, $major, $minor, $crap) = unpack("NCC C90", $rpm);
++
++die "Not an RPM\n" if $magic != 0xedabeedb;
++die "Not a version 3 RPM\n" if $major != 3;
++
++$rpm = substr($rpm, 96);
++
++while ($rpm ne '') {
++  $rpm =~ s/^\c@*//s;
++  ($magic, $crap, $sections, $bytes) = unpack("N4", $rpm);
++  $smagic = unpack("n", $rpm);
++  last if $smagic eq 0x1f8b;
++  die "Error: header not recognized\n" if $magic != 0x8eade801;
++  $rpm = substr($rpm, 16*(1+$sections) + $bytes);
++}
++
++die "bogus RPM\n" if $rpm eq '';
++
++open(ZCAT, "|gzip -cd") || die "can't pipe to gzip\n";
++print STDERR "CPIO archive found!\n";
++
++print ZCAT $rpm;
++close ZCAT;
++
+diff -ru lilypond-2.0.1-orig/lexer-gcc-3.1.sh lilypond-2.0.1/lexer-gcc-3.1.sh
+--- lilypond-2.0.1-orig/lexer-gcc-3.1.sh	Tue Sep 30 00:40:02 2003
++++ lilypond-2.0.1/lexer-gcc-3.1.sh	Tue Sep 30 00:40:28 2003
 @@ -8,7 +8,7 @@
  
  if [ -z "$FLEXLEXER" ]; then
@@ -118,9 +211,9 @@ diff -u --rec lilypond-1.8.1-orig/lexer-gcc-3.1.sh lilypond-1.8.1/lexer-gcc-3.1.
  	$file.orig > $file
      echo "done"
  fi
-diff -u --rec lilypond-1.8.1-orig/lily/kpath.cc lilypond-1.8.1/lily/kpath.cc
---- lilypond-1.8.1-orig/lily/kpath.cc	Sat Aug  2 12:29:55 2003
-+++ lilypond-1.8.1/lily/kpath.cc	Mon Aug 25 22:20:39 2003
+diff -ru lilypond-2.0.1-orig/lily/kpath.cc lilypond-2.0.1/lily/kpath.cc
+--- lilypond-2.0.1-orig/lily/kpath.cc	Tue Sep 30 00:40:01 2003
++++ lilypond-2.0.1/lily/kpath.cc	Tue Sep 30 00:40:28 2003
 @@ -26,6 +26,7 @@
  #define popen REALLYUGLYKLUDGE
  #define pclose ANOTHERREALLYUGLYKLUDGE
@@ -129,9 +222,9 @@ diff -u --rec lilypond-1.8.1-orig/lily/kpath.cc lilypond-1.8.1/lily/kpath.cc
  
  #if HAVE_KPATHSEA_KPATHSEA_H
  extern "C" {
-diff -u --rec lilypond-1.8.1-orig/lily/lily-guile.cc lilypond-1.8.1/lily/lily-guile.cc
---- lilypond-1.8.1-orig/lily/lily-guile.cc	Sat Apr 26 16:59:15 2003
-+++ lilypond-1.8.1/lily/lily-guile.cc	Mon Aug 25 22:20:39 2003
+diff -ru lilypond-2.0.1-orig/lily/lily-guile.cc lilypond-2.0.1/lily/lily-guile.cc
+--- lilypond-2.0.1-orig/lily/lily-guile.cc	Tue Sep 30 00:40:01 2003
++++ lilypond-2.0.1/lily/lily-guile.cc	Tue Sep 30 00:40:28 2003
 @@ -37,6 +37,11 @@
  #include "interval.hh"
  #include "pitch.hh"
@@ -144,9 +237,9 @@ diff -u --rec lilypond-1.8.1-orig/lily/lily-guile.cc lilypond-1.8.1/lily/lily-gu
  #include "source-file.hh"
  
  // #define TEST_GC
-diff -u --rec lilypond-1.8.1-orig/lily/my-lily-parser.cc lilypond-1.8.1/lily/my-lily-parser.cc
---- lilypond-1.8.1-orig/lily/my-lily-parser.cc	Fri Feb 28 16:24:06 2003
-+++ lilypond-1.8.1/lily/my-lily-parser.cc	Mon Aug 25 22:20:39 2003
+diff -ru lilypond-2.0.1-orig/lily/my-lily-parser.cc lilypond-2.0.1/lily/my-lily-parser.cc
+--- lilypond-2.0.1-orig/lily/my-lily-parser.cc	Tue Sep 30 00:40:02 2003
++++ lilypond-2.0.1/lily/my-lily-parser.cc	Tue Sep 30 00:40:28 2003
 @@ -7,6 +7,10 @@
         Jan Nieuwenhuizen <janneke@gnu.org>
  */
@@ -158,28 +251,64 @@ diff -u --rec lilypond-1.8.1-orig/lily/my-lily-parser.cc lilypond-1.8.1/lily/my-
  #include "my-lily-parser.hh"
  #include "my-lily-lexer.hh"
  #include "warn.hh"
-diff -u --rec lilypond-1.8.1-orig/stepmake/stepmake/c++-rules.make lilypond-1.8.1/stepmake/stepmake/c++-rules.make
---- lilypond-1.8.1-orig/stepmake/stepmake/c++-rules.make	Fri Dec  6 09:18:14 2002
-+++ lilypond-1.8.1/stepmake/stepmake/c++-rules.make	Mon Aug 25 22:20:39 2003
-@@ -25,4 +25,5 @@
- 	rm -f $(outdir)/$(*F).cc # avoid recompiling the .cc file 
+diff -ru lilypond-2.0.1-orig/mf/GNUmakefile lilypond-2.0.1/mf/GNUmakefile
+--- lilypond-2.0.1-orig/mf/GNUmakefile	Tue Sep 30 00:39:56 2003
++++ lilypond-2.0.1/mf/GNUmakefile	Tue Sep 30 22:09:32 2003
+@@ -60,7 +60,6 @@
+ PFA_FILES = $(ALL_FONTS:%=$(outdir)/%.pfa)
+ PFB_FILES = $(PFA_FILES:%.pfa=%.pfb)
+ 
+-ALL_GEN_FILES += $(PFA_FILES) $(outdir)/lilypond.map $(outdir)/fonts.scale
+ INSTALLATION_OUT_DIR4=$(local_lilypond_datadir)/fonts/type1
+ INSTALLATION_OUT_FILES4=$(PFA_FILES) $(outdir)/fonts.scale
+ 
+@@ -69,7 +68,7 @@
+ 
+ export MFINPUTS:=.:$(MFINPUTS)
+ 
+-default: pfa_warning $(ALL_GEN_FILES)
++default: $(ALL_GEN_FILES)
+ 
+ 
+ pfa_warning:
+@@ -105,11 +104,11 @@
+ 
+ redhat-package=lilypond-$(TOPLEVEL_VERSION)-1.i386.rpm
+ $(outdir)/$(redhat-package):
+-	wget  --passive-ftp -P $(outdir) ftp://ftp.lilypond.org/pub/LilyPond/binaries/RedHat-9/$(redhat-package)
++	mv ../../$(redhat-package) $(outdir)
+ 
+ get-rpm-pfa: $(outdir)/$(redhat-package)
+ 	cd $(outdir) ; rm -rf usr/ # (root alert!) 
+-	cd $(outdir) ; rpm2cpio $(redhat-package) | cpio -uid '*.pfa'
++	cd $(outdir) ; perl ../../buildscripts/rpm2cpio.pl $(redhat-package) | cpio -uid '*.pfa'
+ 	touch $(addprefix $(outdir)/, $(addsuffix .bla,$(SAUTER_FONTS)))
+ 	cp `find $(outdir)/usr/ -name '*.pfa'` $(outdir)/
+ 
+Only in lilypond-2.0.1/mf: GNUmakefile~
+Only in lilypond-2.0.1/stepmake/stepmake: #c++-rules.make.rej#
+Only in lilypond-2.0.1/stepmake/stepmake: .#c++-rules.make.rej
+diff -ru lilypond-2.0.1-orig/stepmake/stepmake/c++-rules.make lilypond-2.0.1/stepmake/stepmake/c++-rules.make
+--- lilypond-2.0.1-orig/stepmake/stepmake/c++-rules.make	Tue Sep 30 00:39:58 2003
++++ lilypond-2.0.1/stepmake/stepmake/c++-rules.make	Tue Sep 30 00:43:11 2003
+@@ -26,3 +26,4 @@
  
  $(outdir)/%.cc: %.ll
--	$(FLEX) -Cfe -p -p -t $< > $@
-+	$(FLEX) -Cfe -p -p -t $< >> $@
+ 	$(FLEX) -Cfe -p -p -o$@ $< 
 +	perl -i -pe 's/^class istream;/#include <iostream>;\nusing namespace std;/' $@
-diff -u --rec lilypond-1.8.1-orig/stepmake/stepmake/c-vars.make lilypond-1.8.1/stepmake/stepmake/c-vars.make
---- lilypond-1.8.1-orig/stepmake/stepmake/c-vars.make	Wed Jul 17 17:08:20 2002
-+++ lilypond-1.8.1/stepmake/stepmake/c-vars.make	Mon Aug 25 22:20:39 2003
+\ No newline at end of file
+diff -ru lilypond-2.0.1-orig/stepmake/stepmake/c-vars.make lilypond-2.0.1/stepmake/stepmake/c-vars.make
+--- lilypond-2.0.1-orig/stepmake/stepmake/c-vars.make	Tue Sep 30 00:39:58 2003
++++ lilypond-2.0.1/stepmake/stepmake/c-vars.make	Tue Sep 30 00:40:28 2003
 @@ -13,4 +13,4 @@
  
  ALL_C_SOURCES += $(H_FILES) $(C_FILES) $(Y_FILES) $(L_FILES)
  
 -ALL_CFLAGS = $(CFLAGS) $(ICFLAGS) $(DEFINES) $(addprefix -I,$(INCLUDES)) $(USER_CFLAGS) $(EXTRA_CFLAGS) $(MODULE_CFLAGS)
 +ALL_CFLAGS = $(CFLAGS) $(CPPFLAGS) $(ICFLAGS) $(DEFINES) $(addprefix -I,$(INCLUDES)) $(USER_CFLAGS) $(EXTRA_CFLAGS) $(MODULE_CFLAGS)
-diff -u --rec lilypond-1.8.1-orig/stepmake/stepmake/compile-vars.make lilypond-1.8.1/stepmake/stepmake/compile-vars.make
---- lilypond-1.8.1-orig/stepmake/stepmake/compile-vars.make	Wed Jul 17 17:36:15 2002
-+++ lilypond-1.8.1/stepmake/stepmake/compile-vars.make	Mon Aug 25 22:20:39 2003
+diff -ru lilypond-2.0.1-orig/stepmake/stepmake/compile-vars.make lilypond-2.0.1/stepmake/stepmake/compile-vars.make
+--- lilypond-2.0.1-orig/stepmake/stepmake/compile-vars.make	Tue Sep 30 00:39:59 2003
++++ lilypond-2.0.1/stepmake/stepmake/compile-vars.make	Tue Sep 30 00:40:28 2003
 @@ -3,7 +3,7 @@
  ALL_LDFLAGS = $(LDFLAGS) $(ILDFLAGS) $(EXTRA_LDFLAGS) $($(PACKAGE)_LDFLAGS) $(MODULE_LDFLAGS) $(USER_LDFLAGS)
  
@@ -189,9 +318,9 @@ diff -u --rec lilypond-1.8.1-orig/stepmake/stepmake/compile-vars.make lilypond-1
  
  o-dep-out = $(outdir)/$(subst .o,.dep,$(notdir $@))#
  DO_O_DEP = rm -f $(o-dep-out); DEPENDENCIES_OUTPUT="$(o-dep-out) $(outdir)/$(notdir $@)"
-diff -u --rec lilypond-1.8.1-orig/stepmake/stepmake/install-out-targets.make lilypond-1.8.1/stepmake/stepmake/install-out-targets.make
---- lilypond-1.8.1-orig/stepmake/stepmake/install-out-targets.make	Mon Sep 17 03:08:15 2001
-+++ lilypond-1.8.1/stepmake/stepmake/install-out-targets.make	Mon Aug 25 22:20:39 2003
+diff -ru lilypond-2.0.1-orig/stepmake/stepmake/install-out-targets.make lilypond-2.0.1/stepmake/stepmake/install-out-targets.make
+--- lilypond-2.0.1-orig/stepmake/stepmake/install-out-targets.make	Tue Sep 30 00:39:59 2003
++++ lilypond-2.0.1/stepmake/stepmake/install-out-targets.make	Tue Sep 30 00:40:28 2003
 @@ -6,13 +6,13 @@
  # urg, parameterise
  local-install-outfiles: $(INSTALLATION_OUT_FILES) $(foreach suff, $(INSTALLATION_OUT_SUFFIXES), $(INSTALLATION_OUT_FILES$(suff)))
@@ -211,9 +340,9 @@ diff -u --rec lilypond-1.8.1-orig/stepmake/stepmake/install-out-targets.make lil
  
  local-uninstall: local-uninstall-outfiles local-uninstall-files 
  
-diff -u --rec lilypond-1.8.1-orig/stepmake/stepmake/install-targets.make lilypond-1.8.1/stepmake/stepmake/install-targets.make
---- lilypond-1.8.1-orig/stepmake/stepmake/install-targets.make	Mon Sep 17 03:08:15 2001
-+++ lilypond-1.8.1/stepmake/stepmake/install-targets.make	Mon Aug 25 22:20:39 2003
+diff -ru lilypond-2.0.1-orig/stepmake/stepmake/install-targets.make lilypond-2.0.1/stepmake/stepmake/install-targets.make
+--- lilypond-2.0.1-orig/stepmake/stepmake/install-targets.make	Tue Sep 30 00:39:59 2003
++++ lilypond-2.0.1/stepmake/stepmake/install-targets.make	Tue Sep 30 00:40:28 2003
 @@ -7,12 +7,13 @@
  local-install-files: $(INSTALLATION_FILES)
  	$(PRE_INSTALL)
