new upstreams

diff --git a/10.4/unstable/main/finkinfo/database/postgresql81.patch b/10.4/unstable/main/finkinfo/database/postgresql81.patch
--- a/10.4/unstable/main/finkinfo/database/postgresql81.patch
+++ b/10.4/unstable/main/finkinfo/database/postgresql81.patch
@@ -1,6 +1,6 @@
-
---- postgresql-8.1.11/contrib/Makefile	2005-09-01 18:02:44.000000000 -0400
-+++ postgresql-8.1.11-new/contrib/Makefile	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/contrib/Makefile postgresql-8.1.20-new/contrib/Makefile
+--- postgresql-8.1.20/contrib/Makefile	2005-09-01 17:02:44.000000000 -0500
++++ postgresql-8.1.20-new/contrib/Makefile	2010-03-18 22:48:27.000000000 -0500
 @@ -20,6 +20,7 @@
  		lo		\
  		ltree		\
@@ -25,8 +25,9 @@
  #		start-scripts	\ (does not have a makefile)
  #		xml2		\ (requires libxml installed)
  
---- postgresql-8.1.11/contrib/oracle/Makefile	1969-12-31 19:00:00.000000000 -0500
-+++ postgresql-8.1.11-new/contrib/oracle/Makefile	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/contrib/oracle/Makefile postgresql-8.1.20-new/contrib/oracle/Makefile
+--- postgresql-8.1.20/contrib/oracle/Makefile	1969-12-31 18:00:00.000000000 -0600
++++ postgresql-8.1.20-new/contrib/oracle/Makefile	2010-03-18 22:48:27.000000000 -0500
 @@ -0,0 +1,11 @@
 +# oracle conversion Perl scripts
 +
@@ -39,8 +40,9 @@
 +DOCS = README.ora2pg
 +
 +include $(top_srcdir)/contrib/contrib-global.mk
---- postgresql-8.1.11/contrib/oracle/ora2pg.pl	2003-01-07 17:17:14.000000000 -0500
-+++ postgresql-8.1.11-new/contrib/oracle/ora2pg.pl	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/contrib/oracle/ora2pg.pl postgresql-8.1.20-new/contrib/oracle/ora2pg.pl
+--- postgresql-8.1.20/contrib/oracle/ora2pg.pl	2003-01-07 16:17:14.000000000 -0600
++++ postgresql-8.1.20-new/contrib/oracle/ora2pg.pl	2010-03-18 22:48:27.000000000 -0500
 @@ -17,6 +17,10 @@
  
  use strict;
@@ -52,9 +54,10 @@
  use Ora2Pg;
  
  # Initialyze the database connection
---- postgresql-8.1.11/pgsql.sh	1969-12-31 19:00:00.000000000 -0500
-+++ postgresql-8.1.11-new/pgsql.sh	2008-01-15 11:06:46.000000000 -0500
-@@ -0,0 +1,73 @@
+diff -Nurd postgresql-8.1.20/pgsql.sh postgresql-8.1.20-new/pgsql.sh
+--- postgresql-8.1.20/pgsql.sh	1969-12-31 18:00:00.000000000 -0600
++++ postgresql-8.1.20-new/pgsql.sh	2010-03-18 22:48:27.000000000 -0500
+@@ -0,0 +1,81 @@
 +#!/bin/sh
 +
 +die () {
@@ -113,23 +116,32 @@
 +	echo "ok"
 +
 +	printf -- "- initializing database in $DATADIR: "
-+	sudo -u postgres ${PREFIX}/bin/initdb-8.1 -D "$DATADIR" >/tmp/pgsql-init-8.1.log 2>&1 || die "couldn't initialize database"
++	sudo -u postgres ${PREFIX}/bin/initdb-8.1 -E UNICODE -D "$DATADIR" >/tmp/pgsql-init-8.1.log 2>&1 || die "couldn't initialize database"
 +	echo "ok"
 +fi
 +
++PG_COMMAND="sudo -u postgres env"
++if [ -n "$PGPORT" ]; then
++	PG_COMMAND="$PG_COMMAND PGPORT=$PGPORT"
++fi
++PG_COMMAND="$PG_COMMAND ${PREFIX}/bin/pg_ctl-8.1"
++
 +case "$1" in
++	init)
++		;;
 +	start)
-+		unset LC_ALL; LANG=C sudo -u postgres "${PREFIX}/bin/pg_ctl-8.1" start -D "$DATADIR" -l "$LOGFILE"
++		$PG_COMMAND start -D "$DATADIR" -l "$LOGFILE"
 +		;;
 +	restart)
-+		unset LC_ALL; LANG=C sudo -u postgres "${PREFIX}/bin/pg_ctl-8.1" restart -D "$DATADIR" -m fast
++		$PG_COMMAND restart -D "$DATADIR" -m fast
 +		;;
 +	stop)
-+		unset LC_ALL; LANG=C sudo -u postgres "${PREFIX}/bin/pg_ctl-8.1" stop -D "$DATADIR" -m fast
++		$PG_COMMAND stop -D "$DATADIR" -m fast
 +		;;
 +esac
---- postgresql-8.1.11/src/Makefile.global.in	2005-09-27 13:39:32.000000000 -0400
-+++ postgresql-8.1.11-new/src/Makefile.global.in	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/Makefile.global.in postgresql-8.1.20-new/src/Makefile.global.in
+--- postgresql-8.1.20/src/Makefile.global.in	2005-09-27 12:39:32.000000000 -0500
++++ postgresql-8.1.20-new/src/Makefile.global.in	2010-03-18 22:48:27.000000000 -0500
 @@ -73,14 +73,14 @@
  datadir := @datadir@
  ifeq "$(findstring pgsql, $(datadir))" ""
@@ -165,8 +177,9 @@
  endif
  endif
  endif
---- postgresql-8.1.11/src/Makefile.shlib	2005-12-03 15:16:39.000000000 -0500
-+++ postgresql-8.1.11-new/src/Makefile.shlib	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/Makefile.shlib postgresql-8.1.20-new/src/Makefile.shlib
+--- postgresql-8.1.20/src/Makefile.shlib	2005-12-03 14:16:39.000000000 -0600
++++ postgresql-8.1.20-new/src/Makefile.shlib	2010-03-18 22:48:27.000000000 -0500
 @@ -107,11 +107,11 @@
    ifeq ($(DLTYPE), library)
      # linkable library
@@ -181,8 +194,9 @@
    endif
    shlib			= lib$(NAME).$(SO_MAJOR_VERSION).$(SO_MINOR_VERSION)$(DLSUFFIX)
    shlib_major		= lib$(NAME).$(SO_MAJOR_VERSION)$(DLSUFFIX)
---- postgresql-8.1.11/src/backend/main/main.c	2006-01-31 19:32:05.000000000 -0500
-+++ postgresql-8.1.11-new/src/backend/main/main.c	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/backend/main/main.c postgresql-8.1.20-new/src/backend/main/main.c
+--- postgresql-8.1.20/src/backend/main/main.c	2006-01-31 18:32:05.000000000 -0600
++++ postgresql-8.1.20-new/src/backend/main/main.c	2010-03-18 22:48:27.000000000 -0500
 @@ -259,7 +259,8 @@
  	 * possibly first argument) we were called with. The lack of consistency
  	 * here is historical.
@@ -193,17 +207,18 @@
  	{
  		/* Called as "postmaster" */
  		exit(PostmasterMain(argc, argv));
---- postgresql-8.1.11/src/backend/storage/file/fd.c	2006-01-17 18:52:50.000000000 -0500
-+++ postgresql-8.1.11-new/src/backend/storage/file/fd.c	2008-01-15 11:06:35.000000000 -0500
-@@ -51,6 +51,7 @@
- #include "storage/fd.h"
+diff -Nurd postgresql-8.1.20/src/backend/storage/file/fd.c postgresql-8.1.20-new/src/backend/storage/file/fd.c
+--- postgresql-8.1.20/src/backend/storage/file/fd.c	2009-12-03 05:04:02.000000000 -0600
++++ postgresql-8.1.20-new/src/backend/storage/file/fd.c	2010-03-18 22:48:27.000000000 -0500
+@@ -52,6 +52,7 @@
  #include "storage/ipc.h"
+ #include "utils/resowner.h"
  
 +#include <sys/resource.h>
  
  /*
   * We must leave some file descriptors free for system(), the dynamic loader,
-@@ -345,15 +346,21 @@
+@@ -346,15 +347,21 @@
  	int			used = 0;
  	int			highestfd = 0;
  	int			j;
@@ -225,19 +240,21 @@
  		thisfd = dup(0);
  		if (thisfd < 0)
  		{
---- postgresql-8.1.11/src/backend/utils/misc/postgresql.conf.sample	2006-05-21 16:11:02.000000000 -0400
-+++ postgresql-8.1.11-new/src/backend/utils/misc/postgresql.conf.sample	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/backend/utils/misc/postgresql.conf.sample postgresql-8.1.20-new/src/backend/utils/misc/postgresql.conf.sample
+--- postgresql-8.1.20/src/backend/utils/misc/postgresql.conf.sample	2010-02-25 17:44:27.000000000 -0600
++++ postgresql-8.1.20-new/src/backend/utils/misc/postgresql.conf.sample	2010-03-18 22:48:27.000000000 -0500
 @@ -63,7 +63,7 @@
  # - Security & Authentication -
  
  #authentication_timeout = 60		# 1-600, in seconds
 -#ssl = off
 +ssl = off
+ #ssl_renegotiation_limit = 524288	# amount of data between renegotiations
+ 					# in kilobytes
  #password_encryption = on
- #db_user_namespace = off
- 
---- postgresql-8.1.11/src/bin/initdb/initdb.c	2006-05-27 14:07:22.000000000 -0400
-+++ postgresql-8.1.11-new/src/bin/initdb/initdb.c	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/bin/initdb/initdb.c postgresql-8.1.20-new/src/bin/initdb/initdb.c
+--- postgresql-8.1.20/src/bin/initdb/initdb.c	2009-03-31 13:58:26.000000000 -0500
++++ postgresql-8.1.20-new/src/bin/initdb/initdb.c	2010-03-18 22:48:27.000000000 -0500
 @@ -116,7 +116,7 @@
  
  /* defaults */
@@ -247,7 +264,7 @@
  
  /*
   * Warning messages for authentication methods
-@@ -2411,7 +2411,7 @@
+@@ -2423,7 +2423,7 @@
  	sprintf(pgdenv, "PGDATA=%s", pg_data);
  	putenv(pgdenv);
  
@@ -256,7 +273,7 @@
  							   backend_exec)) < 0)
  	{
  		char		full_path[MAXPGPATH];
-@@ -2421,14 +2421,14 @@
+@@ -2433,14 +2433,14 @@
  
  		if (ret == -1)
  			fprintf(stderr,
@@ -273,7 +290,7 @@
  					  "but was not the same version as %s.\n"
  					  "Check your installation.\n"),
  					full_path, progname);
-@@ -2715,9 +2715,9 @@
+@@ -2727,9 +2727,9 @@
  	get_parent_directory(bin_dir);
  
  	printf(_("\nSuccess. You can now start the database server using:\n\n"
@@ -285,9 +302,10 @@
  	   QUOTE_PATH, bin_dir, (strlen(bin_dir) > 0) ? DIR_SEP : "", QUOTE_PATH,
  		   QUOTE_PATH, pg_data_native, QUOTE_PATH,
  	   QUOTE_PATH, bin_dir, (strlen(bin_dir) > 0) ? DIR_SEP : "", QUOTE_PATH,
---- postgresql-8.1.11/src/bin/pg_ctl/pg_ctl.c	2006-06-25 00:38:00.000000000 -0400
-+++ postgresql-8.1.11-new/src/bin/pg_ctl/pg_ctl.c	2008-01-15 11:06:35.000000000 -0500
-@@ -540,7 +540,7 @@
+diff -Nurd postgresql-8.1.20/src/bin/pg_ctl/pg_ctl.c postgresql-8.1.20-new/src/bin/pg_ctl/pg_ctl.c
+--- postgresql-8.1.20/src/bin/pg_ctl/pg_ctl.c	2009-09-01 21:41:20.000000000 -0500
++++ postgresql-8.1.20-new/src/bin/pg_ctl/pg_ctl.c	2010-03-18 22:48:27.000000000 -0500
+@@ -572,7 +572,7 @@
  
  		postmaster_path = pg_malloc(MAXPGPATH);
  
@@ -296,7 +314,7 @@
  								   postmaster_path)) < 0)
  		{
  			char		full_path[MAXPGPATH];
-@@ -549,13 +549,13 @@
+@@ -581,13 +581,13 @@
  				StrNCpy(full_path, progname, MAXPGPATH);
  
  			if (ret == -1)
@@ -312,7 +330,7 @@
  							   "but was not the same version as %s.\n"
  							   "Check your installation.\n"),
  							 full_path, progname);
-@@ -896,7 +896,7 @@
+@@ -928,7 +928,7 @@
  	}
  	else
  	{
@@ -321,8 +339,9 @@
  		if (ret != 0)
  		{
  			write_stderr(_("%s: could not find postmaster program executable\n"), progname);
---- postgresql-8.1.11/src/interfaces/ecpg/compatlib/Makefile	2005-03-14 12:27:49.000000000 -0500
-+++ postgresql-8.1.11-new/src/interfaces/ecpg/compatlib/Makefile	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/interfaces/ecpg/compatlib/Makefile postgresql-8.1.20-new/src/interfaces/ecpg/compatlib/Makefile
+--- postgresql-8.1.20/src/interfaces/ecpg/compatlib/Makefile	2005-03-14 11:27:49.000000000 -0600
++++ postgresql-8.1.20-new/src/interfaces/ecpg/compatlib/Makefile	2010-03-18 22:48:27.000000000 -0500
 @@ -20,6 +20,7 @@
  override CPPFLAGS := -I$(top_srcdir)/src/interfaces/ecpg/include -I$(libpq_srcdir) \
  	-I$(top_srcdir)/src/include/utils $(CPPFLAGS)
@@ -331,8 +350,9 @@
  SHLIB_LINK = -L../ecpglib -lecpg -L../pgtypeslib -lpgtypes $(libpq) \
  	$(filter -lintl -lssl -lcrypto -lkrb5 -lcrypt -lm, $(LIBS)) $(PTHREAD_LIBS)
  
---- postgresql-8.1.11/src/interfaces/ecpg/ecpglib/Makefile	2005-12-05 21:29:26.000000000 -0500
-+++ postgresql-8.1.11-new/src/interfaces/ecpg/ecpglib/Makefile	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/interfaces/ecpg/ecpglib/Makefile postgresql-8.1.20-new/src/interfaces/ecpg/ecpglib/Makefile
+--- postgresql-8.1.20/src/interfaces/ecpg/ecpglib/Makefile	2005-12-05 20:29:26.000000000 -0600
++++ postgresql-8.1.20-new/src/interfaces/ecpg/ecpglib/Makefile	2010-03-18 22:48:27.000000000 -0500
 @@ -19,6 +19,7 @@
  
  override CPPFLAGS := -DFRONTEND -I$(top_srcdir)/src/interfaces/ecpg/include \
@@ -341,8 +361,9 @@
  override CFLAGS += $(PTHREAD_CFLAGS)
  
  # Need to recompile any libpgport object files
---- postgresql-8.1.11/src/makefiles/Makefile.darwin	2006-11-28 00:47:16.000000000 -0500
-+++ postgresql-8.1.11-new/src/makefiles/Makefile.darwin	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/makefiles/Makefile.darwin postgresql-8.1.20-new/src/makefiles/Makefile.darwin
+--- postgresql-8.1.20/src/makefiles/Makefile.darwin	2006-11-27 23:47:16.000000000 -0600
++++ postgresql-8.1.20-new/src/makefiles/Makefile.darwin	2010-03-18 22:48:27.000000000 -0500
 @@ -13,6 +13,6 @@
  # Rule for building shared libs (currently used only for regression test
  # shlib ... should go away, since this is not really enough knowledge)
@@ -351,8 +372,9 @@
 +	$(CC) $(CFLAGS) -bundle -undefined dynamic_lookup -o $@ $< $(BE_DLLLIBS)
  
  sqlmansect = 7
---- postgresql-8.1.11/src/template/darwin	2004-04-26 00:04:42.000000000 -0400
-+++ postgresql-8.1.11-new/src/template/darwin	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/template/darwin postgresql-8.1.20-new/src/template/darwin
+--- postgresql-8.1.20/src/template/darwin	2004-04-25 23:04:42.000000000 -0500
++++ postgresql-8.1.20-new/src/template/darwin	2010-03-18 22:48:27.000000000 -0500
 @@ -1,6 +1,2 @@
 -# Apple's cpp-precomp seems a tad broken, so don't use it
 -# (Note: on OS X before 10.2, you might need -traditional-cpp instead)
@@ -360,8 +382,9 @@
 -
  # Select appropriate semaphore support
  USE_NAMED_POSIX_SEMAPHORES=1
---- postgresql-8.1.11/src/test/regress/pg_regress.sh	2006-10-08 21:45:41.000000000 -0400
-+++ postgresql-8.1.11-new/src/test/regress/pg_regress.sh	2008-01-15 11:06:35.000000000 -0500
+diff -Nurd postgresql-8.1.20/src/test/regress/pg_regress.sh postgresql-8.1.20-new/src/test/regress/pg_regress.sh
+--- postgresql-8.1.20/src/test/regress/pg_regress.sh	2006-10-08 20:45:41.000000000 -0500
++++ postgresql-8.1.20-new/src/test/regress/pg_regress.sh	2010-03-18 22:48:27.000000000 -0500
 @@ -397,6 +397,9 @@
          mkdir -p "$LOGDIR" || { (exit 2); exit; }
      fi
