mege from head

diff --git a/10.4/unstable/main/finkinfo/database/postgis.patch b/10.4/unstable/main/finkinfo/database/postgis.patch
--- a/10.4/unstable/main/finkinfo/database/postgis.patch
+++ b/10.4/unstable/main/finkinfo/database/postgis.patch
@@ -1,6 +1,6 @@
 
---- postgis-1.2.1/extras/template_gis/Makefile	2007-01-04 19:52:57.000000000 -0500
-+++ postgis-1.2.1-new/extras/template_gis/Makefile	2007-02-05 16:51:50.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/Makefile	2007-03-01 03:31:44.000000000 -0500
++++ postgis-1.3.1-new/extras/template_gis/Makefile	2007-09-18 10:46:24.000000000 -0400
 @@ -19,8 +19,7 @@
  SCRIPT_INSTALL=$(INSTALL_BIN) $(SCRIPT) $(SCRIPT_TARGET)
  SCRIPT_LINKDIR=$(DESTDIR)$(prefix)/bin
@@ -11,16 +11,7 @@
  SCRIPT_UNINSTALL=rm -f $(SCRIPT_TARGET)
  SCRIPT_UNLINK=rm -f $(SCRIPT_LINK)
  
-@@ -31,7 +30,7 @@
- MAN1_INSTALL=$(INSTALL_DATA) $(MAN1) $(MAN1_TARGET)
- MAN1_UNINSTALL=rm -f $(MAN1_TARGET)
- 
--DEFAULTS_DIR=$(DESTDIR)/etc/default
-+DEFAULTS_DIR=$(DESTDIR)@FINKPREFIX@/etc
- SCRIPT_DEFAULTS=$(DEFAULTS_DIR)/postgis
- 
- all: $(SCRIPTS_IN)
-@@ -41,7 +40,6 @@
+@@ -42,7 +41,6 @@
  	@mkdir -p $(SCRIPT_TARGETDIR)
  	@mkdir -p $(SCRIPT_LINKDIR)
  	$(foreach SCRIPT, $(SCRIPTS), $(SCRIPT_INSTALL);)
@@ -28,8 +19,8 @@
  	@mkdir -p $(DEFAULTS_DIR)
  	cp profile $(SCRIPT_DEFAULTS)
  	rm -f $(SCRIPT_TARGETDIR)/profile
---- postgis-1.2.1/extras/template_gis/createdb.postgis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/createdb.postgis.1	2007-02-05 15:57:32.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/createdb.postgis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/createdb.postgis.1	2007-09-18 10:46:24.000000000 -0400
 @@ -43,7 +43,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
@@ -39,8 +30,8 @@
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
---- postgis-1.2.1/extras/template_gis/createdb.postgis.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/createdb.postgis.in	2007-02-05 16:23:01.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/createdb.postgis.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/createdb.postgis.in	2007-09-18 10:46:24.000000000 -0400
 @@ -5,7 +5,7 @@
  # but the specified owner will not have 
  # extra privileges on objects in the template. see createdb.postgis(1)
@@ -50,8 +41,8 @@
  
  for ARGVN in $1 $2 ; do
      if [ `expr substr $ARGVN 1 11` = "--template=" ]; then
---- postgis-1.2.1/extras/template_gis/mktemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/mktemplate_gis.1	2007-02-05 15:57:36.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/mktemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/mktemplate_gis.1	2007-09-18 10:46:24.000000000 -0400
 @@ -89,7 +89,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
@@ -61,8 +52,8 @@
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
---- postgis-1.2.1/extras/template_gis/mktemplate_gis.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/mktemplate_gis.in	2007-02-05 16:23:17.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/mktemplate_gis.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/mktemplate_gis.in	2007-09-18 10:46:24.000000000 -0400
 @@ -3,7 +3,7 @@
  #create a template database, named template_gis by default,
  #and grant ownership or full privileges to the postgis tables to a user, postgres by default
@@ -84,8 +75,8 @@
  export SCRIPTS GRTABLES GRSCHEMAS GRUSER DBAUSER TDB
 -$SUDO -c "@bindir@/mktemplate_gis.sh"
 +$SUDO -c "@bindir@/mktemplate_gis.sh-@FINKPGRAWVERSION@"
---- postgis-1.2.1/extras/template_gis/mktemplate_gis.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/mktemplate_gis.sh.in	2007-02-05 16:23:22.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/mktemplate_gis.sh.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/mktemplate_gis.sh.in	2007-09-18 10:46:24.000000000 -0400
 @@ -6,7 +6,7 @@
  
  cd /tmp
@@ -95,8 +86,8 @@
  
  check_dba $DBAUSER
  template_rm $TDB
---- postgis-1.2.1/extras/template_gis/postgis_env.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/postgis_env.sh.in	2007-02-05 16:23:30.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/postgis_env.sh.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/postgis_env.sh.in	2007-09-18 10:46:24.000000000 -0400
 @@ -3,7 +3,7 @@
  # environment variables for postgis
  
@@ -121,8 +112,8 @@
  	fi
  fi
  
---- postgis-1.2.1/extras/template_gis/postgres_lib.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/postgres_lib.sh.in	2007-02-05 16:25:51.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/postgres_lib.sh.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/postgres_lib.sh.in	2007-09-18 10:46:24.000000000 -0400
 @@ -39,9 +39,9 @@
  		echo "you may be not allowed to do so (maybe wrong password)."
  		exit 1
@@ -217,8 +208,8 @@
  	else
  		echo "$db_create"
  	fi
---- postgis-1.2.1/extras/template_gis/profile	2006-06-09 02:03:59.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/profile	2007-02-05 15:57:22.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/profile	2006-06-09 02:03:59.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/profile	2007-09-18 10:46:24.000000000 -0400
 @@ -1,6 +1,6 @@
  
  #those are the default variables for postgresql-postgis.
@@ -227,8 +218,8 @@
  #and then from $HOME/postgis/profile
  
  #values should NOT be in quotes
---- postgis-1.2.1/extras/template_gis/rmtemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/rmtemplate_gis.1	2007-02-05 15:58:13.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/rmtemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/rmtemplate_gis.1	2007-09-18 10:46:24.000000000 -0400
 @@ -45,7 +45,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
@@ -238,8 +229,8 @@
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
---- postgis-1.2.1/extras/template_gis/rmtemplate_gis.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/rmtemplate_gis.in	2007-02-05 16:26:10.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/rmtemplate_gis.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/rmtemplate_gis.in	2007-09-18 10:46:24.000000000 -0400
 @@ -3,7 +3,7 @@
  #drop template_gis
  #it may be used to drop any postgresql template, by supplying argument
@@ -261,8 +252,8 @@
  export DBAUSER TDB
 -$SUDO -c "@bindir@/rmtemplate_gis.sh"
 +$SUDO -c "@bindir@/rmtemplate_gis.sh-@FINKPGRAWVERSION@"
---- postgis-1.2.1/extras/template_gis/rmtemplate_gis.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.2.1-new/extras/template_gis/rmtemplate_gis.sh.in	2007-02-05 16:26:15.000000000 -0500
+--- postgis-1.3.1/extras/template_gis/rmtemplate_gis.sh.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.1-new/extras/template_gis/rmtemplate_gis.sh.in	2007-09-18 10:46:24.000000000 -0400
 @@ -6,7 +6,7 @@
  
  cd /tmp
@@ -272,8 +263,8 @@
  
  check_dba $DBAUSER
  template_rm $TDB
---- postgis-1.2.1/java/jdbc/Makefile	2007-01-08 05:12:01.000000000 -0500
-+++ postgis-1.2.1-new/java/jdbc/Makefile	2007-02-05 14:22:41.000000000 -0500
+--- postgis-1.3.1/java/jdbc/Makefile	2007-01-18 13:51:15.000000000 -0500
++++ postgis-1.3.1-new/java/jdbc/Makefile	2007-09-18 10:46:24.000000000 -0400
 @@ -27,7 +27,7 @@
  
  # Configure the helper executables used during build.
@@ -283,8 +274,8 @@
  JAVA?=java
  JAR?=jar
  MKDIR?=mkdir -p
---- postgis-1.2.1/lwgeom/lwgeom_gml.c	2006-01-09 10:55:55.000000000 -0500
-+++ postgis-1.2.1-new/lwgeom/lwgeom_gml.c	2007-02-05 14:25:59.000000000 -0500
+--- postgis-1.3.1/lwgeom/lwgeom_gml.c	2007-06-08 06:28:52.000000000 -0400
++++ postgis-1.3.1-new/lwgeom/lwgeom_gml.c	2007-09-18 10:46:24.000000000 -0400
 @@ -38,10 +38,10 @@
  
  #define DEF_PRECISION 15
@@ -343,8 +334,8 @@
  		}
  	}
  
---- postgis-1.2.1/lwgeom/lwgeom_kml.c	2006-12-15 05:48:56.000000000 -0500
-+++ postgis-1.2.1-new/lwgeom/lwgeom_kml.c	2007-02-05 14:25:32.000000000 -0500
+--- postgis-1.3.1/lwgeom/lwgeom_kml.c	2007-06-08 06:28:52.000000000 -0400
++++ postgis-1.3.1-new/lwgeom/lwgeom_kml.c	2007-09-18 10:46:24.000000000 -0400
 @@ -38,10 +38,10 @@
  
  #define DEF_PRECISION 15
@@ -403,3 +394,20 @@
  		}
  	}
  
+--- postgis-1.3.1/utils/postgis_restore.pl	2006-11-20 07:59:55.000000000 -0500
++++ postgis-1.3.1-new/utils/postgis_restore.pl	2007-09-18 10:49:49.000000000 -0400
+@@ -690,7 +690,7 @@
+ #
+ # Open a pipe to the SQL monitor
+ #
+-open( PSQL, "| psql -a $dbname") || die "Can't run psql\n";
++open( PSQL, "| psql-@FINKPGRAWVERSION@ -a $dbname") || die "Can't run psql\n";
+ 
+ #
+ # Source new postgis.sql
+@@ -717,4 +717,4 @@
+ open(INPUT, "<$dumpascii") || die "Can't read $postgissql\n";
+ while(<INPUT>) { print PSQL; }
+ close(INPUT);
+-close(PSQL) || die "psql run failed\n"
++close(PSQL) || die "psql-@FINKPGRAWVERSION@ run failed\n"
