sync with HEAD (pangocairo-root-40)

diff --git a/10.4/unstable/main/finkinfo/database/postgis.patch b/10.4/unstable/main/finkinfo/database/postgis.patch
--- a/10.4/unstable/main/finkinfo/database/postgis.patch
+++ b/10.4/unstable/main/finkinfo/database/postgis.patch
@@ -1,99 +1,87 @@
 
---- postgis-1.3.1/extras/template_gis/Makefile	2007-03-01 03:31:44.000000000 -0500
-+++ postgis-1.3.1-new/extras/template_gis/Makefile	2007-09-18 10:46:24.000000000 -0400
-@@ -19,8 +19,7 @@
- SCRIPT_INSTALL=$(INSTALL_BIN) $(SCRIPT) $(SCRIPT_TARGET)
- SCRIPT_LINKDIR=$(DESTDIR)$(prefix)/bin
- SCRIPT_LINK=$(SCRIPT_LINKDIR)/$(SCRIPT)
--SCRIPT_DOLINK=rm -f $(SCRIPT_LINK); \
--              $(LN_S) $(SCRIPT_TARGET) $(SCRIPT_LINKDIR)
-+SCRIPT_DOLINK= install -c -m 755 $(SCRIPT_LINK) $(SCRIPT_TARGETDIR)
- SCRIPT_UNINSTALL=rm -f $(SCRIPT_TARGET)
- SCRIPT_UNLINK=rm -f $(SCRIPT_LINK)
+--- postgis-1.3.2/README.postgis	2007-12-02 15:37:13.000000000 -0500
++++ postgis-1.3.2-new/README.postgis	2007-12-12 08:50:57.000000000 -0500
+@@ -143,8 +143,8 @@
  
-@@ -42,7 +41,6 @@
- 	@mkdir -p $(SCRIPT_TARGETDIR)
- 	@mkdir -p $(SCRIPT_LINKDIR)
- 	$(foreach SCRIPT, $(SCRIPTS), $(SCRIPT_INSTALL);)
--	$(foreach SCRIPT, $(PUBLIC_SCRIPTS), $(SCRIPT_DOLINK);)
- 	@mkdir -p $(DEFAULTS_DIR)
- 	cp profile $(SCRIPT_DEFAULTS)
- 	rm -f $(SCRIPT_TARGETDIR)/profile
---- postgis-1.3.1/extras/template_gis/createdb.postgis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/createdb.postgis.1	2007-09-18 10:46:24.000000000 -0400
+ So, as postgres run:
+ 
+-  createlang plpgsql yourdatabase
+-  psql -f lwpostgis.sql -d your_database
++  createlang-@FINKPGRAWVERSION@ plpgsql yourdatabase
++  psql-@FINKPGRAWVERSION@ -f lwpostgis.sql -d your_database
+ 
+ Your database should now be spatially enabled.
+ 
+@@ -166,7 +166,7 @@
+ Soft upgrade consists of sourcing the lwpostgis_upgrade.sql
+ script in your spatial database:
+ 
+-  psql -f lwpostgis_upgrade.sql -d your_spatial_database
++  psql-@FINKPGRAWVERSION@ -f lwpostgis_upgrade.sql -d your_spatial_database
+ 
+ If a soft upgrade is not possible the script will abort and 
+ you will be warned about HARD UPGRADE being required,
+@@ -187,7 +187,7 @@
+ 
+ 	# Create a "custom-format" dump of the database you want
+ 	# to upgrade (let's call it "olddb")
+-	$ pg_dump -Fc olddb olddb.dump
++	$ pg_dump-@FINKPGRAWVERSION@ -Fc olddb olddb.dump
+ 
+ 	# Restore the dump while upgrading postgis into
+ 	# a new database. 
+@@ -204,9 +204,9 @@
+ 	# drop the attrelid, varattnum and stats columns in the geometry_columns
+ 	# table, which are no-more needed. Keeping them won't hurt.
+ 	# !!! DROPPING THEM WHEN REALLY NEEDED WILL DO HARM !!!!
+-	$ psql newdb -c "ALTER TABLE geometry_columns DROP attrelid"
+-	$ psql newdb -c "ALTER TABLE geometry_columns DROP varattnum"
+-	$ psql newdb -c "ALTER TABLE geometry_columns DROP stats"
++	$ psql-@FINKPGRAWVERSION@ newdb -c "ALTER TABLE geometry_columns DROP attrelid"
++	$ psql-@FINKPGRAWVERSION@ newdb -c "ALTER TABLE geometry_columns DROP varattnum"
++	$ psql-@FINKPGRAWVERSION@ newdb -c "ALTER TABLE geometry_columns DROP stats"
+ 
+ 	# The spatial_ref_sys table is restored from the dump, to 
+         # ensure your custom additions are kept, but the distributed 
+@@ -214,7 +214,7 @@
+         # entries, drop the table and source the new one.
+ 	# If you did make additions we assume you know how to backup them before
+ 	# upgrading the table. Replace it with the new like this:
+-	$ psql newdb
++	$ psql-@FINKPGRAWVERSION@ newdb
+ 	newdb=> DELETE FROM spatial_ref_sys;
+ 	DROP
+ 	newdb=> \i spatial_ref_sys.sql
+--- postgis-1.3.2/extras/template_gis/createdb.postgis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.2-new/extras/template_gis/createdb.postgis.1	2007-12-12 08:46:50.000000000 -0500
 @@ -43,7 +43,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
  .TP
 -.B /etc/default/postgis
-+.B @FINKPREFIX@/etc/postgis
++.B @FINKPREFIX@/etc/default/postgis
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
---- postgis-1.3.1/extras/template_gis/createdb.postgis.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/createdb.postgis.in	2007-09-18 10:46:24.000000000 -0400
-@@ -5,7 +5,7 @@
- # but the specified owner will not have 
- # extra privileges on objects in the template. see createdb.postgis(1)
- 
--source @bindir@/postgis_env.sh
-+source @bindir@/postgis_env.sh-@FINKPGRAWVERSION@
- 
- for ARGVN in $1 $2 ; do
-     if [ `expr substr $ARGVN 1 11` = "--template=" ]; then
---- postgis-1.3.1/extras/template_gis/mktemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/mktemplate_gis.1	2007-09-18 10:46:24.000000000 -0400
+--- postgis-1.3.2/extras/template_gis/mktemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.2-new/extras/template_gis/mktemplate_gis.1	2007-12-12 08:46:43.000000000 -0500
 @@ -89,7 +89,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
  .TP
 -.B /etc/default/postgis
-+.B @FINKPREFIX@/etc/postgis
++.B @FINKPREFIX@/etc/default/postgis
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
---- postgis-1.3.1/extras/template_gis/mktemplate_gis.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/mktemplate_gis.in	2007-09-18 10:46:24.000000000 -0400
-@@ -3,7 +3,7 @@
- #create a template database, named template_gis by default,
- #and grant ownership or full privileges to the postgis tables to a user, postgres by default
- 
--source @bindir@/postgis_env.sh
-+source @bindir@/postgis_env.sh-@FINKPGRAWVERSION@
- 
- for ARGVN in $1 $2 $3 $4 $5 $6 ; do
-     if [ `expr substr $ARGVN 1 7` = "--user=" ]; then
-@@ -59,9 +59,9 @@
-     SCRIPTS="${SCRIPTS} ${TMPTOPO}"
- fi
- 
--source @bindir@/postgres_lib.sh
-+source @bindir@/postgres_lib.sh-@FINKPGRAWVERSION@
- 
- sudo_dba DBAUSER
- 
- export SCRIPTS GRTABLES GRSCHEMAS GRUSER DBAUSER TDB
--$SUDO -c "@bindir@/mktemplate_gis.sh"
-+$SUDO -c "@bindir@/mktemplate_gis.sh-@FINKPGRAWVERSION@"
---- postgis-1.3.1/extras/template_gis/mktemplate_gis.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/mktemplate_gis.sh.in	2007-09-18 10:46:24.000000000 -0400
-@@ -6,7 +6,7 @@
- 
- cd /tmp
- 
--source @bindir@/postgres_lib.sh
-+source @bindir@/postgres_lib.sh-@FINKPGRAWVERSION@
- 
- check_dba $DBAUSER
- template_rm $TDB
---- postgis-1.3.1/extras/template_gis/postgis_env.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/postgis_env.sh.in	2007-09-18 10:46:24.000000000 -0400
+--- postgis-1.3.2/extras/template_gis/postgis_env.sh.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.2-new/extras/template_gis/postgis_env.sh.in	2007-12-12 08:46:32.000000000 -0500
 @@ -3,7 +3,7 @@
  # environment variables for postgis
  
  #read optional configuration files. last prevails
 -for file in "/etc/default/postgis" "$HOME/.postgis/profile" ; do
-+for file in "@FINKPREFIX@/etc/postgis@FINKPGVERSION@" "@FINKPREFIX@/etc/postgis" "$HOME/.postgis/profile" ; do
++for file in "@FINKPREFIX@/etc/default/postgis" "$HOME/.postgis/profile" ; do
  	if [ -f "$file" ]; then
  		tmpval=`grep "^TEMPLATEDB=" $file | cut -d= -f2`
  		if [ -n "$tmpval" ]; then
@@ -112,8 +100,8 @@
  	fi
  fi
  
---- postgis-1.3.1/extras/template_gis/postgres_lib.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/postgres_lib.sh.in	2007-09-18 10:46:24.000000000 -0400
+--- postgis-1.3.2/extras/template_gis/postgres_lib.sh.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.2-new/extras/template_gis/postgres_lib.sh.in	2007-12-12 08:51:30.000000000 -0500
 @@ -39,9 +39,9 @@
  		echo "you may be not allowed to do so (maybe wrong password)."
  		exit 1
@@ -208,77 +196,32 @@
  	else
  		echo "$db_create"
  	fi
---- postgis-1.3.1/extras/template_gis/profile	2006-06-09 02:03:59.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/profile	2007-09-18 10:46:24.000000000 -0400
+--- postgis-1.3.2/extras/template_gis/profile	2006-06-09 02:03:59.000000000 -0400
++++ postgis-1.3.2-new/extras/template_gis/profile	2007-12-12 08:43:29.000000000 -0500
 @@ -1,6 +1,6 @@
  
  #those are the default variables for postgresql-postgis.
 -#this file will be scanned from /etc/default/postgis,
-+#this file will be scanned from @FINKPREFIX@/etc/postgis,
++#this file will be scanned from @FINKPREFIX@/etc/default/postgis,
  #and then from $HOME/postgis/profile
  
  #values should NOT be in quotes
---- postgis-1.3.1/extras/template_gis/rmtemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/rmtemplate_gis.1	2007-09-18 10:46:24.000000000 -0400
+--- postgis-1.3.2/extras/template_gis/rmtemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.2-new/extras/template_gis/rmtemplate_gis.1	2007-12-12 08:43:15.000000000 -0500
 @@ -45,7 +45,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
  .TP
 -.B /etc/default/postgis
-+.B @FINKPREFIX@/etc/postgis
++.B @FINKPREFIX@/etc/default/postgis
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
---- postgis-1.3.1/extras/template_gis/rmtemplate_gis.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/rmtemplate_gis.in	2007-09-18 10:46:24.000000000 -0400
-@@ -3,7 +3,7 @@
- #drop template_gis
- #it may be used to drop any postgresql template, by supplying argument
+--- postgis-1.3.2/lwgeom/lwgeom_gml.c	2007-10-10 17:27:51.000000000 -0400
++++ postgis-1.3.2-new/lwgeom/lwgeom_gml.c	2007-12-12 09:15:30.000000000 -0500
+@@ -51,10 +51,10 @@
+ static char *getSRSbySRID(int SRID);
  
--source @bindir@/postgis_env.sh
-+source @bindir@/postgis_env.sh-@FINKPGRAWVERSION@
- 
- for ARGVN in $1 $2 $3 $4 ; do
-     if [ `expr substr $ARGVN 1 11` = "--template=" ]; then
-@@ -21,9 +21,9 @@
-     fi
- done
- 
--source @bindir@/postgres_lib.sh
-+source @bindir@/postgres_lib.sh-@FINKPGRAWVERSION@
- 
- sudo_dba $DBAUSER
- 
- export DBAUSER TDB
--$SUDO -c "@bindir@/rmtemplate_gis.sh"
-+$SUDO -c "@bindir@/rmtemplate_gis.sh-@FINKPGRAWVERSION@"
---- postgis-1.3.1/extras/template_gis/rmtemplate_gis.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.1-new/extras/template_gis/rmtemplate_gis.sh.in	2007-09-18 10:46:24.000000000 -0400
-@@ -6,7 +6,7 @@
- 
- cd /tmp
- 
--source @bindir@/postgres_lib.sh
-+source @bindir@/postgres_lib.sh-@FINKPGRAWVERSION@
- 
- check_dba $DBAUSER
- template_rm $TDB
---- postgis-1.3.1/java/jdbc/Makefile	2007-01-18 13:51:15.000000000 -0500
-+++ postgis-1.3.1-new/java/jdbc/Makefile	2007-09-18 10:46:24.000000000 -0400
-@@ -27,7 +27,7 @@
- 
- # Configure the helper executables used during build.
- 
--JAVAC?=javac -target 1.2 -source 1.2
-+JAVAC?=javac -target 1.4 -source 1.2
- JAVA?=java
- JAR?=jar
- MKDIR?=mkdir -p
---- postgis-1.3.1/lwgeom/lwgeom_gml.c	2007-06-08 06:28:52.000000000 -0400
-+++ postgis-1.3.1-new/lwgeom/lwgeom_gml.c	2007-09-18 10:46:24.000000000 -0400
-@@ -38,10 +38,10 @@
- 
- #define DEF_PRECISION 15
  /* Add dot, sign, exponent sign, 'e', exponent digits */
 -#define SHOW_DIGS (precision + 8)
 +#define SHOW_DIGS (gml_precision + 8)
@@ -289,28 +232,18 @@
  
  
  /**
-@@ -58,7 +58,7 @@
- 	char *srs;
- 	int SRID;
+@@ -85,8 +85,8 @@
+ 	geom = (PG_LWGEOM *)PG_DETOAST_DATUM(PG_GETARG_DATUM(1));
  
--	precision = DEF_PRECISION;
-+	gml_precision = DEF_PRECISION;
- 
- 	if ( PG_ARGISNULL(0) ) PG_RETURN_NULL();
- 
-@@ -66,9 +66,9 @@
- 
- 	/* Get precision (if provided)  */
- 	if ( PG_NARGS() > 1 && ! PG_ARGISNULL(1) )
--			precision = PG_GETARG_INT32(1);
-+			gml_precision = PG_GETARG_INT32(1);
- 	
+ 	/* Get precision  */
+-	precision = PG_GETARG_INT32(2);
 -	if ( precision < 1 || precision > 15 )
++	gml_precision = PG_GETARG_INT32(2);
 +	if ( gml_precision < 1 || gml_precision > 15 )
  	{
  		elog(ERROR, "Precision out of range 1..15");
  		PG_RETURN_NULL();
-@@ -424,8 +424,8 @@
+@@ -440,8 +440,8 @@
  			getPoint2d_p(pa, i, &pt);
  			if ( i ) ptr += sprintf(ptr, " ");
  			ptr += sprintf(ptr, "%.*g,%.*g",
@@ -321,7 +254,7 @@
  		}
  	}
  	else 
-@@ -436,9 +436,9 @@
+@@ -452,9 +452,9 @@
  			getPoint4d_p(pa, i, &pt);
  			if ( i ) ptr += sprintf(ptr, " ");
  			ptr += sprintf(ptr, "%.*g,%.*g,%.*g",
@@ -334,9 +267,33 @@
  		}
  	}
  
---- postgis-1.3.1/lwgeom/lwgeom_kml.c	2007-06-08 06:28:52.000000000 -0400
-+++ postgis-1.3.1-new/lwgeom/lwgeom_kml.c	2007-09-18 10:46:24.000000000 -0400
-@@ -38,10 +38,10 @@
+@@ -798,8 +798,8 @@
+ 			getPoint2d_p(pa, i, &pt);
+ 			if ( i ) ptr += sprintf(ptr, " ");
+ 			ptr += sprintf(ptr, "%.*g %.*g",
+-				precision, pt.x,
+-				precision, pt.y);
++				gml_precision, pt.x,
++				gml_precision, pt.y);
+ 		}
+ 	}
+ 	else 
+@@ -810,9 +810,9 @@
+ 			getPoint4d_p(pa, i, &pt);
+ 			if ( i ) ptr += sprintf(ptr, " ");
+ 			ptr += sprintf(ptr, "%.*g %.*g,%.*g",
+-				precision, pt.x,
+-				precision, pt.y,
+-				precision, pt.z);
++				gml_precision, pt.x,
++				gml_precision, pt.y,
++				gml_precision, pt.z);
+ 		}
+ 	}
+ 
+--- postgis-1.3.2/lwgeom/lwgeom_kml.c	2007-10-22 20:19:54.000000000 -0400
++++ postgis-1.3.2-new/lwgeom/lwgeom_kml.c	2007-12-12 09:14:49.000000000 -0500
+@@ -40,10 +40,10 @@
  
  #define DEF_PRECISION 15
  /* Add dot, sign, exponent sign, 'e', exponent digits */
@@ -349,7 +306,7 @@
  
  
  /**
-@@ -58,7 +58,7 @@
+@@ -60,7 +60,7 @@
  	char *srs;
  	int SRID;
  
@@ -358,7 +315,7 @@
  
  	if ( PG_ARGISNULL(0) ) PG_RETURN_NULL();
  
-@@ -66,9 +66,9 @@
+@@ -68,9 +68,9 @@
  
  	/* Get precision (if provided)  */
  	if ( PG_NARGS() > 1 && ! PG_ARGISNULL(1) )
@@ -370,7 +327,7 @@
  	{
  		elog(ERROR, "Precision out of range 1..15");
  		PG_RETURN_NULL();
-@@ -409,8 +409,8 @@
+@@ -411,8 +411,8 @@
  			getPoint2d_p(pa, i, &pt);
  			if ( i ) ptr += sprintf(ptr, " ");
  			ptr += sprintf(ptr, "%.*g,%.*g,0",
@@ -381,7 +338,7 @@
  		}
  	}
  	else 
-@@ -421,9 +421,9 @@
+@@ -423,9 +423,9 @@
  			getPoint4d_p(pa, i, &pt);
  			if ( i ) ptr += sprintf(ptr, " ");
  			ptr += sprintf(ptr, "%.*g,%.*g,%.*g",
@@ -394,9 +351,46 @@
  		}
  	}
  
---- postgis-1.3.1/utils/postgis_restore.pl	2006-11-20 07:59:55.000000000 -0500
-+++ postgis-1.3.1-new/utils/postgis_restore.pl	2007-09-18 10:49:49.000000000 -0400
-@@ -690,7 +690,7 @@
+--- postgis-1.3.2/utils/postgis_restore.pl	2006-11-20 07:59:55.000000000 -0500
++++ postgis-1.3.2-new/utils/postgis_restore.pl	2007-12-12 08:48:53.000000000 -0500
+@@ -375,7 +375,7 @@
+ #
+ print "Scanning $dump list\n"; 
+ open( OUTPUT, ">$dumplist") || die "Can't write to ".$dump.".list\n";
+-open( INPUT, "pg_restore -l $dump |") || die "Couldn't run pg_restore -l $dump\n";
++open( INPUT, "pg_restore-@FINKPGRAWVERSION@ -l $dump |") || die "Couldn't run pg_restore-@FINKPGRAWVERSION@ -l $dump\n";
+ while( my $line = <INPUT> )
+ {
+ 	next if $line =~ /^;/;
+@@ -613,7 +613,7 @@
+ close(OUTPUT);
+ 
+ print "Producing ascii dump $dumpascii\n"; 
+-open( INPUT, "pg_restore -L $dumplist $dump |") || die "Can't run pg_restore\n";
++open( INPUT, "pg_restore-@FINKPGRAWVERSION@ -L $dumplist $dump |") || die "Can't run pg_restore\n";
+ open( OUTPUT, ">$dumpascii") || die "Can't write to $dumpascii\n";
+ while( my $line = <INPUT> )
+ {
+@@ -673,7 +673,7 @@
+ 	#  when implemented operators skip must be disabled
+ 	#  in the first scan of ToC
+ }
+-close(INPUT) || die "pg_restore call failed\n";
++close(INPUT) || die "pg_restore-@FINKPGRAWVERSION@ call failed\n";
+ close(OUTPUT);
+ 
+ #exit(1);
+@@ -682,15 +682,15 @@
+ # Create the new db and install plpgsql language
+ #
+ print "Creating db ($dbname)\n";
+-`createdb $createdb_opt $dbname`;
++`createdb-@FINKPGRAWVERSION@ $createdb_opt $dbname`;
+ die "Database creation failed\n" if ($?);
+ print "Adding plpgsql\n";
+-`createlang plpgsql $dbname`;
++`createlang-@FINKPGRAWVERSION@ plpgsql $dbname`;
+ 
  #
  # Open a pipe to the SQL monitor
  #
