patchfile-ified

diff --git a/10.4/unstable/main/finkinfo/database/postgis.patch b/10.4/unstable/main/finkinfo/database/postgis.patch
--- a/10.4/unstable/main/finkinfo/database/postgis.patch
+++ b/10.4/unstable/main/finkinfo/database/postgis.patch
@@ -1,18 +1,20 @@
-diff -Nurd postgis-1.3.3/README.postgis postgis-1.3.3-new/README.postgis
---- postgis-1.3.3/README.postgis	2008-04-12 14:32:14.000000000 -0400
-+++ postgis-1.3.3-new/README.postgis	2008-06-11 16:46:54.000000000 -0400
-@@ -143,8 +143,8 @@
+diff -Nurd postgis-1.3.5/README.postgis postgis-1.3.5-new/README.postgis
+--- postgis-1.3.5/README.postgis	2008-12-15 16:55:34.000000000 -0500
++++ postgis-1.3.5-new/README.postgis	2009-01-15 17:29:57.000000000 -0500
+@@ -145,9 +145,9 @@
  
  So, as postgres run:
  
 -  createlang plpgsql yourdatabase
 -  psql -f lwpostgis.sql -d your_database
+-  psql -f postgis_comments.sql -d your_database
 +  createlang-@FINKPGRAWVERSION@ plpgsql yourdatabase
 +  psql-@FINKPGRAWVERSION@ -f lwpostgis.sql -d your_database
++  psql-@FINKPGRAWVERSION@ -f postgis_comments.sql -d your_database
  
  Your database should now be spatially enabled.
  
-@@ -166,7 +166,7 @@
+@@ -169,7 +169,7 @@
  Soft upgrade consists of sourcing the lwpostgis_upgrade.sql
  script in your spatial database:
  
@@ -21,7 +23,7 @@ diff -Nurd postgis-1.3.3/README.postgis postgis-1.3.3-new/README.postgis
  
  If a soft upgrade is not possible the script will abort and 
  you will be warned about HARD UPGRADE being required,
-@@ -187,7 +187,7 @@
+@@ -190,7 +190,7 @@
  
  	# Create a "custom-format" dump of the database you want
  	# to upgrade (let's call it "olddb")
@@ -30,7 +32,7 @@ diff -Nurd postgis-1.3.3/README.postgis postgis-1.3.3-new/README.postgis
  
  	# Restore the dump while upgrading postgis into
  	# a new database. 
-@@ -204,9 +204,9 @@
+@@ -207,9 +207,9 @@
  	# drop the attrelid, varattnum and stats columns in the geometry_columns
  	# table, which are no-more needed. Keeping them won't hurt.
  	# !!! DROPPING THEM WHEN REALLY NEEDED WILL DO HARM !!!!
@@ -43,7 +45,7 @@ diff -Nurd postgis-1.3.3/README.postgis postgis-1.3.3-new/README.postgis
  
  	# The spatial_ref_sys table is restored from the dump, to 
          # ensure your custom additions are kept, but the distributed 
-@@ -214,7 +214,7 @@
+@@ -217,7 +217,7 @@
          # entries, drop the table and source the new one.
  	# If you did make additions we assume you know how to backup them before
  	# upgrading the table. Replace it with the new like this:
@@ -52,9 +54,9 @@ diff -Nurd postgis-1.3.3/README.postgis postgis-1.3.3-new/README.postgis
  	newdb=> DELETE FROM spatial_ref_sys;
  	DROP
  	newdb=> \i spatial_ref_sys.sql
-diff -Nurd postgis-1.3.3/extras/template_gis/createdb.postgis.1 postgis-1.3.3-new/extras/template_gis/createdb.postgis.1
---- postgis-1.3.3/extras/template_gis/createdb.postgis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.3-new/extras/template_gis/createdb.postgis.1	2008-06-11 16:46:54.000000000 -0400
+diff -Nurd postgis-1.3.5/extras/template_gis/createdb.postgis.1 postgis-1.3.5-new/extras/template_gis/createdb.postgis.1
+--- postgis-1.3.5/extras/template_gis/createdb.postgis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.5-new/extras/template_gis/createdb.postgis.1	2009-01-15 17:23:39.000000000 -0500
 @@ -43,7 +43,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
@@ -64,9 +66,9 @@ diff -Nurd postgis-1.3.3/extras/template_gis/createdb.postgis.1 postgis-1.3.3-ne
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
-diff -Nurd postgis-1.3.3/extras/template_gis/mktemplate_gis.1 postgis-1.3.3-new/extras/template_gis/mktemplate_gis.1
---- postgis-1.3.3/extras/template_gis/mktemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.3-new/extras/template_gis/mktemplate_gis.1	2008-06-11 16:46:54.000000000 -0400
+diff -Nurd postgis-1.3.5/extras/template_gis/mktemplate_gis.1 postgis-1.3.5-new/extras/template_gis/mktemplate_gis.1
+--- postgis-1.3.5/extras/template_gis/mktemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.5-new/extras/template_gis/mktemplate_gis.1	2009-01-15 17:23:39.000000000 -0500
 @@ -89,7 +89,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
@@ -76,9 +78,9 @@ diff -Nurd postgis-1.3.3/extras/template_gis/mktemplate_gis.1 postgis-1.3.3-new/
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
-diff -Nurd postgis-1.3.3/extras/template_gis/postgis_env.sh.in postgis-1.3.3-new/extras/template_gis/postgis_env.sh.in
---- postgis-1.3.3/extras/template_gis/postgis_env.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.3-new/extras/template_gis/postgis_env.sh.in	2008-06-11 16:46:54.000000000 -0400
+diff -Nurd postgis-1.3.5/extras/template_gis/postgis_env.sh.in postgis-1.3.5-new/extras/template_gis/postgis_env.sh.in
+--- postgis-1.3.5/extras/template_gis/postgis_env.sh.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.5-new/extras/template_gis/postgis_env.sh.in	2009-01-15 17:23:39.000000000 -0500
 @@ -3,7 +3,7 @@
  # environment variables for postgis
  
@@ -103,9 +105,9 @@ diff -Nurd postgis-1.3.3/extras/template_gis/postgis_env.sh.in postgis-1.3.3-new
  	fi
  fi
  
-diff -Nurd postgis-1.3.3/extras/template_gis/postgres_lib.sh.in postgis-1.3.3-new/extras/template_gis/postgres_lib.sh.in
---- postgis-1.3.3/extras/template_gis/postgres_lib.sh.in	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.3-new/extras/template_gis/postgres_lib.sh.in	2008-06-11 16:46:54.000000000 -0400
+diff -Nurd postgis-1.3.5/extras/template_gis/postgres_lib.sh.in postgis-1.3.5-new/extras/template_gis/postgres_lib.sh.in
+--- postgis-1.3.5/extras/template_gis/postgres_lib.sh.in	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.5-new/extras/template_gis/postgres_lib.sh.in	2009-01-15 17:23:39.000000000 -0500
 @@ -39,9 +39,9 @@
  		echo "you may be not allowed to do so (maybe wrong password)."
  		exit 1
@@ -200,9 +202,9 @@ diff -Nurd postgis-1.3.3/extras/template_gis/postgres_lib.sh.in postgis-1.3.3-ne
  	else
  		echo "$db_create"
  	fi
-diff -Nurd postgis-1.3.3/extras/template_gis/profile postgis-1.3.3-new/extras/template_gis/profile
---- postgis-1.3.3/extras/template_gis/profile	2006-06-09 02:03:59.000000000 -0400
-+++ postgis-1.3.3-new/extras/template_gis/profile	2008-06-11 16:46:54.000000000 -0400
+diff -Nurd postgis-1.3.5/extras/template_gis/profile postgis-1.3.5-new/extras/template_gis/profile
+--- postgis-1.3.5/extras/template_gis/profile	2006-06-09 02:03:59.000000000 -0400
++++ postgis-1.3.5-new/extras/template_gis/profile	2009-01-15 17:23:39.000000000 -0500
 @@ -1,6 +1,6 @@
  
  #those are the default variables for postgresql-postgis.
@@ -211,9 +213,9 @@ diff -Nurd postgis-1.3.3/extras/template_gis/profile postgis-1.3.3-new/extras/te
  #and then from $HOME/postgis/profile
  
  #values should NOT be in quotes
-diff -Nurd postgis-1.3.3/extras/template_gis/rmtemplate_gis.1 postgis-1.3.3-new/extras/template_gis/rmtemplate_gis.1
---- postgis-1.3.3/extras/template_gis/rmtemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
-+++ postgis-1.3.3-new/extras/template_gis/rmtemplate_gis.1	2008-06-11 16:46:54.000000000 -0400
+diff -Nurd postgis-1.3.5/extras/template_gis/rmtemplate_gis.1 postgis-1.3.5-new/extras/template_gis/rmtemplate_gis.1
+--- postgis-1.3.5/extras/template_gis/rmtemplate_gis.1	2006-05-31 02:43:12.000000000 -0400
++++ postgis-1.3.5-new/extras/template_gis/rmtemplate_gis.1	2009-01-15 17:23:39.000000000 -0500
 @@ -45,7 +45,7 @@
  .LP
  The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
@@ -223,9 +225,9 @@ diff -Nurd postgis-1.3.3/extras/template_gis/rmtemplate_gis.1 postgis-1.3.3-new/
  will designate default values for the whole system.
  .TP
  .B $HOME/.postgis/profile
-diff -Nurd postgis-1.3.3/lwgeom/lwgeom_gml.c postgis-1.3.3-new/lwgeom/lwgeom_gml.c
---- postgis-1.3.3/lwgeom/lwgeom_gml.c	2007-10-10 17:27:51.000000000 -0400
-+++ postgis-1.3.3-new/lwgeom/lwgeom_gml.c	2008-06-11 16:46:54.000000000 -0400
+diff -Nurd postgis-1.3.5/lwgeom/lwgeom_gml.c postgis-1.3.5-new/lwgeom/lwgeom_gml.c
+--- postgis-1.3.5/lwgeom/lwgeom_gml.c	2008-11-05 06:27:37.000000000 -0500
++++ postgis-1.3.5-new/lwgeom/lwgeom_gml.c	2009-01-15 17:23:39.000000000 -0500
 @@ -51,10 +51,10 @@
  static char *getSRSbySRID(int SRID);
  
@@ -250,7 +252,7 @@ diff -Nurd postgis-1.3.3/lwgeom/lwgeom_gml.c postgis-1.3.3-new/lwgeom/lwgeom_gml
  	{
  		elog(ERROR, "Precision out of range 1..15");
  		PG_RETURN_NULL();
-@@ -440,8 +440,8 @@
+@@ -447,8 +447,8 @@
  			getPoint2d_p(pa, i, &pt);
  			if ( i ) ptr += sprintf(ptr, " ");
  			ptr += sprintf(ptr, "%.*g,%.*g",
@@ -261,7 +263,7 @@ diff -Nurd postgis-1.3.3/lwgeom/lwgeom_gml.c postgis-1.3.3-new/lwgeom/lwgeom_gml
  		}
  	}
  	else 
-@@ -452,9 +452,9 @@
+@@ -459,9 +459,9 @@
  			getPoint4d_p(pa, i, &pt);
  			if ( i ) ptr += sprintf(ptr, " ");
  			ptr += sprintf(ptr, "%.*g,%.*g,%.*g",
@@ -274,7 +276,7 @@ diff -Nurd postgis-1.3.3/lwgeom/lwgeom_gml.c postgis-1.3.3-new/lwgeom/lwgeom_gml
  		}
  	}
  
-@@ -798,8 +798,8 @@
+@@ -805,8 +805,8 @@
  			getPoint2d_p(pa, i, &pt);
  			if ( i ) ptr += sprintf(ptr, " ");
  			ptr += sprintf(ptr, "%.*g %.*g",
@@ -285,7 +287,7 @@ diff -Nurd postgis-1.3.3/lwgeom/lwgeom_gml.c postgis-1.3.3-new/lwgeom/lwgeom_gml
  		}
  	}
  	else 
-@@ -810,9 +810,9 @@
+@@ -817,9 +817,9 @@
  			getPoint4d_p(pa, i, &pt);
  			if ( i ) ptr += sprintf(ptr, " ");
  			ptr += sprintf(ptr, "%.*g %.*g,%.*g",
@@ -298,9 +300,9 @@ diff -Nurd postgis-1.3.3/lwgeom/lwgeom_gml.c postgis-1.3.3-new/lwgeom/lwgeom_gml
  		}
  	}
  
-diff -Nurd postgis-1.3.3/lwgeom/lwgeom_kml.c postgis-1.3.3-new/lwgeom/lwgeom_kml.c
---- postgis-1.3.3/lwgeom/lwgeom_kml.c	2008-03-28 17:31:57.000000000 -0400
-+++ postgis-1.3.3-new/lwgeom/lwgeom_kml.c	2008-06-11 16:47:38.000000000 -0400
+diff -Nurd postgis-1.3.5/lwgeom/lwgeom_kml.c postgis-1.3.5-new/lwgeom/lwgeom_kml.c
+--- postgis-1.3.5/lwgeom/lwgeom_kml.c	2008-03-28 17:31:57.000000000 -0400
++++ postgis-1.3.5-new/lwgeom/lwgeom_kml.c	2009-01-15 17:23:39.000000000 -0500
 @@ -40,10 +40,10 @@
  static size_t pointArray_KMLsize(POINTARRAY *pa);
  
@@ -349,9 +351,9 @@ diff -Nurd postgis-1.3.3/lwgeom/lwgeom_kml.c postgis-1.3.3-new/lwgeom/lwgeom_kml
  		}
  	}
  
-diff -Nurd postgis-1.3.3/utils/postgis_restore.pl postgis-1.3.3-new/utils/postgis_restore.pl
---- postgis-1.3.3/utils/postgis_restore.pl	2006-11-20 07:59:55.000000000 -0500
-+++ postgis-1.3.3-new/utils/postgis_restore.pl	2008-06-11 16:46:54.000000000 -0400
+diff -Nurd postgis-1.3.5/utils/postgis_restore.pl postgis-1.3.5-new/utils/postgis_restore.pl
+--- postgis-1.3.5/utils/postgis_restore.pl	2008-10-02 11:59:41.000000000 -0400
++++ postgis-1.3.5-new/utils/postgis_restore.pl	2009-01-15 17:25:21.000000000 -0500
 @@ -375,7 +375,7 @@
  #
  print "Scanning $dump list\n"; 
@@ -387,14 +389,14 @@ diff -Nurd postgis-1.3.3/utils/postgis_restore.pl postgis-1.3.3-new/utils/postgi
 +`createdb-@FINKPGRAWVERSION@ $createdb_opt $dbname`;
  die "Database creation failed\n" if ($?);
  print "Adding plpgsql\n";
--`createlang plpgsql $dbname`;
-+`createlang-@FINKPGRAWVERSION@ plpgsql $dbname`;
+-`createlang $createdb_opt plpgsql $dbname`;
++`createlang-@FINKPGRAWVERSION@ $createdb_opt plpgsql $dbname`;
  
  #
  # Open a pipe to the SQL monitor
  #
--open( PSQL, "| psql -a $dbname") || die "Can't run psql\n";
-+open( PSQL, "| psql-@FINKPGRAWVERSION@ -a $dbname") || die "Can't run psql\n";
+-open( PSQL, "| psql $createdb_opt -a $dbname") || die "Can't run psql\n";
++open( PSQL, "| psql-@FINKPGRAWVERSION@ $createdb_opt -a $dbname") || die "Can't run psql\n";
  
  #
  # Source new postgis.sql
