Updated to latest upstream version

diff --git a/10.3/unstable/main/finkinfo/sound/abcde.patch b/10.3/unstable/main/finkinfo/sound/abcde.patch
--- a/10.3/unstable/main/finkinfo/sound/abcde.patch
+++ b/10.3/unstable/main/finkinfo/sound/abcde.patch
@@ -1,92 +1,97 @@
-diff -urN abcde-2.0.3.orig/Makefile abcde-2.0.3/Makefile
---- abcde-2.0.3.orig/Makefile	Mon Jan 28 00:34:34 2002
-+++ abcde-2.0.3/Makefile	Tue Apr  8 21:21:42 2003
-@@ -9,6 +9,7 @@
- etcdir = ${DESTDIR}/etc
- 
- all:
-+	perl -pi -e 's{/etc/abcde\.conf}{$(etcdir)/abcde\.conf}' abcde
- 
- clean:
- 
-@@ -18,7 +19,9 @@
+diff -ur abcde-2.1.9.orig/Makefile abcde-2.1.9/Makefile
+--- abcde-2.1.9.orig/Makefile	Thu Dec  4 09:03:26 2003
++++ abcde-2.1.9/Makefile	Thu Dec  4 10:11:54 2003
+@@ -18,7 +18,8 @@
  	$(INSTALL) -m 755 -o 0 cddb-tool $(bindir)
  	$(INSTALL) -d -m 755 $(mandir)
  	$(INSTALL) -m 644 -o 0 abcde.1 $(mandir)
+-	$(INSTALL) -m 644 -o 0 cddb-tool.1 $(mandir)
++	$(INSTALL) -m 644 -o 0 cddb-tool.1 $(mandir)
 +	$(INSTALL) -d -m 755 $(etcdir)
  	$(INSTALL) -m 644 -o 0 abcde.conf $(etcdir)
-+	$(INSTALL) -m 755 -o 0 seq $(bindir)
  
  tarball:
- 	@cd .. && tar czvf abcde_$(VERSION).orig.tar.gz \
-diff -urN abcde-2.0.3.orig/abcde abcde-2.0.3/abcde
---- abcde-2.0.3.orig/abcde	Mon Jan 28 00:44:02 2002
-+++ abcde-2.0.3/abcde	Tue Apr  8 21:22:46 2003
-@@ -9,6 +9,9 @@
- # 
- # Copyright for this work is to expire January 1, 2010, after which it
- # shall be public domain.
-+#
-+# Ported to MacOS X by:
-+# Evan Jones <ejones@uwaterloo.ca> http://www.eng.uwaterloo.ca/~ejones/
- 
- VERSION=2.0.3
- 
-@@ -525,6 +528,8 @@
- 			ERRORCODE=no_query
- 			echo 503 > "$ABCDETEMPDIR/cddbquery"
- 		else
-+			# Make sure that cddb-tool knows about our WGET options
-+			export WGET WGETOPTS
- 			CDDBUSER=$(echo $HELLOINFO | cut -f1 -d'@')
- 			CDDBHOST=$(echo $HELLOINFO | cut -f2- -d'@')
- 			$CDDBTOOL query $CDDBURL $CDDBUSER $CDDBHOST $TRACKINFO > "$ABCDETEMPDIR/cddbquery"
-@@ -866,6 +871,11 @@
- 	case "$CDROMREADERSYNTAX" in
+Only in abcde-2.1.9: Makefile.orig
+Only in abcde-2.1.9: Makefile.rej
+diff -ur abcde-2.1.9.orig/abcde abcde-2.1.9/abcde
+--- abcde-2.1.9.orig/abcde	Thu Dec  4 09:03:26 2003
++++ abcde-2.1.9/abcde	Thu Dec  4 11:02:47 2003
+@@ -1141,6 +1141,17 @@
  		cdparanoia) nice $READNICE $CDROMREADER -d $CDROM $UTRACKNUM "$WAVDATA" >&2 ;;
  		cdda2wav) nice $READNICE $CDROMREADER -H -D $CDROM -t $UTRACKNUM "$WAVDATA" >&2 ;;
+ 		dagrab) nice $READNICE $CDROMREADER -d $CDROM -f $WAVDATA -v $UTRACKNUM >&2 ;;
 +		cddafs)
 +			# Find the track's mounted path
-+			FILEPATH=$(mount | grep $CDROM | sed 's/^[^ ]* on \([^(]*\) (.*/\1/')
-+			FILEPATH=$(find "$FILEPATH" | grep "/$UTRACKNUM ");
-+			nice $READNICE $CDROMREADER "$FILEPATH" "$WAVDATA" >&2 ;;
++			REALTRACKNUM=$(expr $UTRACKNUM - 1 + 1)
++			FILEPATH=$(mount | grep "$CDROM on" | sed 's/^[^ ]* on \([^(]*\) (.*/\1/')
++			FILEPATH=$(find "$FILEPATH" | grep "/$REALTRACKNUM ");
++			# If the file exists, copy it
++			if [ -e "$FILEPATH" ] ; then
++				nice $READNICE $CDROMREADER "$FILEPATH" "$WAVDATA" >&2
++			else
++				false
++			fi ;;
  		debug) nice $READNICE $CDROMREADER -d $CDROM -w $UTRACKNUM-[:1] "$WAVDATA" >&2 ;;
  	esac
  	RETURN=$?
-@@ -886,10 +896,10 @@
- CDDBSUBMIT=freedb-submit@freedb.org
+@@ -1162,7 +1173,7 @@
+ CDDBPROTO=5
  HELLOINFO="$(whoami)@$(hostname)"
  INTERACTIVE=y
 -CDROMREADERSYNTAX=cdparanoia
 +CDROMREADERSYNTAX=cddafs
  OUTPUTTYPE=ogg
  ENCODERSYNTAX=default
--OUTPUTFORMAT='${ARTISTFILE}/${TRACKFILE}.$OUTPUTTYPE'
-+OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/$TRACKNUM-${TRACKFILE}.${OUTPUTTYPE}'
- VAOUTPUTFORMAT=${OUTPUTFORMAT}
- PLAYLISTFORMAT='${ARTISTFILE}_-_${ALBUMFILE}.m3u'
+ 
+@@ -1171,10 +1182,8 @@
+ FLACENCODERSYNTAX=default
+ SPEEXENCODERSYNTAX=default
+ 
+-OUTPUTFORMAT='${ARTISTFILE}-${ALBUMFILE}/${TRACKNUM}.${TRACKFILE}'
+-# Use the following VAOUTPUTFORMAT to revert to 2.0.x VA format:
+-#VAOUTPUTFORMAT=${OUTPUTFORMAT}
+-VAOUTPUTFORMAT='Various-${ALBUMFILE}/${TRACKNUM}.${ARTISTFILE}-${TRACKFILE}'
++OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/$TRACKNUM ${TRACKFILE}'
++VAOUTPUTFORMAT=${OUTPUTFORMAT}
+ PLAYLISTFORMAT='${ARTISTFILE}-${ALBUMFILE}.${OUTPUT}.m3u'
  PLAYLISTDATAPREFIX=''
-@@ -913,7 +923,8 @@
- ID3V2=id3v2
+ VAPLAYLISTFORMAT='${ARTISTFILE}-${ALBUMFILE}.${OUTPUT}.m3u'
+@@ -1211,6 +1220,7 @@
  CDPARANOIA=cdparanoia
  CDDA2WAV=cdda2wav
--WGET=wget
+ DAGRAB=dagrab
 +CDDAFS=cp
-+WGET=curl
  CDDISCID=cd-discid
  CDDBTOOL=cddb-tool
  EJECT=eject
-@@ -933,7 +944,8 @@
- ID3V2OPTS=
+@@ -1240,6 +1250,7 @@
  CDPARANOIAOPTS=
  CDDA2WAVOPTS=
--WGETOPTS=
-+CDDAFSOPTS="-f"
-+WGETOPTS="-f -s"
+ DAGRABOPTS=
++CDDAFSOPTS="-f" 	
  CDDBTOOLOPTS=
  EJECTOPTS=
  DISTMP3OPTS=
-@@ -957,7 +969,7 @@
+@@ -1255,13 +1266,16 @@
+ # Custom filename munging:
+ mungefilename ()
+ {
+-	echo "$@" | sed s,:,\ -,g | tr \ / __ | tr -d \'\"\?\[:cntrl:\]
++	echo "$@" | sed s,:,\ -,g | tr / __ | tr -d \'\"\?\[:cntrl:\]
+ }
+ 
+-# Asume fetch if under FreeBSD. wget is used for Linux/OpenBSD/NetBSD.
++# Asume fetch if under FreeBSD. curl is used for Mac OS X. wget is used for Linux/OpenBSD/NetBSD.
+ if [ X$(uname) = "XFreeBSD" ] ; then
+ 	HTTPGET=fetch
+ 	HTTPGETOPTS="-q -o -"
++elif [ X$(uname) = "XDarwin" ] ; then
++	HTTPGET=curl
++	HTTPGETOPTS="-f -s"
+ else
+ 	HTTPGET=wget
+ 	HTTPGETOPTS="-q -O -"
+@@ -1273,7 +1287,7 @@
  USEID3=y
  
  if [ -z "$OUTPUTDIR" ]; then
@@ -95,12 +100,7 @@ diff -urN abcde-2.0.3.orig/abcde abcde-2.0.3/abcde
  fi
  
  if [ -z "$WAVOUTPUTDIR" ]; then
-@@ -969,12 +981,12 @@
- if [ -e /dev/cdroms/cdrom0 ]; then
- 	CDROM=/dev/cdroms/cdrom0
- else
--	CDROM=/dev/cdrom
-+	CDROM=/dev/disk1
+@@ -1281,8 +1295,8 @@
  fi
  
  # Load system defaults
@@ -111,9 +111,18 @@ diff -urN abcde-2.0.3.orig/abcde abcde-2.0.3/abcde
  fi
  # Load user preference defaults
  if [ -r $HOME/.abcde.conf ]; then
-@@ -1027,6 +1039,10 @@
- 		CDROMREADER="$CDDA2WAV"
- 		CDROMREADEROPTS="$CDDA2WAVOPTS"
+@@ -1307,6 +1321,8 @@
+ 		CDROM=/dev/cd0c
+ 	elif [ -e /dev/acd0c ]; then
+ 		CDROM=/dev/acd0c
++	elif [ -e /dev/disk1 ]; then
++		CDROM=/dev/disk1
+ 	else
+ 		echo "abcde error: CDROM device cannot be found." >&2
+ 		exit 1
+@@ -1366,6 +1382,10 @@
+ 		CDROMREADER="$DAGRAB"
+ 		CDROMREADEROPTS="$DAGRABOPTS"
  		;;
 +        cddafs)
 +                CDROMREADER="$CDDAFS"
@@ -121,39 +130,42 @@ diff -urN abcde-2.0.3.orig/abcde abcde-2.0.3/abcde
 +                ;;
  esac
  
- # If nothing has been specified, use oggenc for oggs and lame for mp3s
-diff -urN abcde-2.0.3.orig/abcde.conf abcde-2.0.3/abcde.conf
---- abcde-2.0.3.orig/abcde.conf	Sun Jan 20 21:35:31 2002
-+++ abcde-2.0.3/abcde.conf	Tue Apr  8 21:21:43 2003
-@@ -27,7 +27,7 @@
+ # There's only one normalize...
+diff -ur abcde-2.1.9.orig/abcde.conf abcde-2.1.9/abcde.conf
+--- abcde-2.1.9.orig/abcde.conf	Thu Dec  4 09:03:26 2003
++++ abcde-2.1.9/abcde.conf	Thu Dec  4 09:57:40 2003
+@@ -36,8 +36,8 @@
+ #NORMALIZERSYNTAX=default
  
- # CD reader program to use - currently recognized options are 'cdparanoia'
- # and 'cdda2wav'.
+ # CD reader program to use - currently recognized options are 'cdparanoia',
+-# 'cdda2wav' and 'dagrab'.
 -#CDROMREADERSYNTAX=cdparanoia
++# 'cdda2wav', 'dagrab' and 'cddafs' (Mac OS X only).
 +#CDROMREADERSYNTAX=cddafs
  
- # Specify 'nice'ness of the encoder and of the CD reader.
- # This is a relative 'nice'ness (that is, if the parent process is at a
-@@ -51,7 +51,7 @@
+ # Keep the wav files after encoding. Set it to "y" and remove "clean" from
+ # the list of default actions, since we purge the temp directory as default.
+@@ -73,7 +73,8 @@
  #ID3V2=id3v2
  #CDPARANOIA=cdparanoia
  #CDDA2WAV=cdda2wav
--#WGET=wget
-+#WGET=curl
+-#HTTPGET=wget
++#CDDAFS=cp
++#HTTPGET=curl
  #CDDISCID=cd-discid
  #CDDBTOOL=cddb-tool
  #EJECT=eject
-@@ -71,7 +71,8 @@
+@@ -105,7 +106,8 @@
  #ID3V2OPTS=
  #CDPARANOIAOPTS=
  #CDDA2WAVOPTS=
--#WGETOPTS=
+-#HTTPGETOPTS=
 +#CDDAFSOPTS="-f"
-+#WGETOPTS="-f -s"
++#HTTPGETOPTS="-f -s"
  #CDDBTOOLOPTS=
  #EJECTOPTS=
  #DISTMP3OPTS=
-@@ -96,15 +97,15 @@
+@@ -131,15 +133,15 @@
  #NOCDDBQUERY=n
  
  # CD device you want to read from
@@ -172,76 +184,40 @@ diff -urN abcde-2.0.3.orig/abcde.conf abcde-2.0.3/abcde.conf
 -#WAVOUTPUTDIR=`pwd`
 +#OUTPUTDIR="$HOME/Music"
  
- # OUTPUTTYPE can be either "ogg" or "mp3".
- #OUTPUTTYPE=ogg
-@@ -115,7 +116,7 @@
- # OUTPUTTYPE, ALBUMFILE, ARTISTFILE, TRACKFILE, and TRACKNUM.
- # Make sure to single-quote this variable. abcde will automatically create
- # the directory portion of this filename.
--#OUTPUTFORMAT='${ARTISTFILE}/${TRACKFILE}.${OUTPUTTYPE}'
-+#OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/$TRACKNUM-${TRACKFILE}.${OUTPUTTYPE}'
+ # OUTPUTTYPE can be either "ogg", "mp3", "flac" or "spx", or a combination
+ # of them separated with ",": "ogg,mp3".
+@@ -155,10 +157,10 @@
+ # Since multiple-output was integrated we always append the file type
+ # to the files. Remove it from your user defined string if you are getting
+ # files like ".ogg.ogg".
+-#OUTPUTFORMAT='${ARTISTFILE}-${ALBUMFILE}/${TRACKNUM}.${TRACKFILE}'
++#OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/$TRACKNUM ${TRACKFILE}'
  
  # Like OUTPUTFORMAT but for Various Artists discs.
- #VAOUTPUTFORMAT='${ARTISTFILE}/${TRACKFILE}.${OUTPUTTYPE}'
-diff -urN abcde-2.0.3.orig/cddb-tool abcde-2.0.3/cddb-tool
---- abcde-2.0.3.orig/cddb-tool	Sun Jan 20 21:29:23 2002
-+++ abcde-2.0.3/cddb-tool	Tue Apr  8 21:21:43 2003
-@@ -20,6 +20,9 @@
- #  - Submitted via: line is created by template, when it really should be in send.
- #    Oh well.
+-#VAOUTPUTFORMAT='${ARTISTFILE}/${TRACKFILE}'
++#VAOUTPUTFORMAT=${OUTPUTFORMAT}
  
-+# Ported to MacOS X by:
-+# Evan Jones <ejones@uwaterloo.ca> http://www.eng.uwaterloo.ca/~ejones/
-+
- VERSION=0.4.1
- NAME=cddb-tool
+ # Define how many encoders to run at once. This makes for huge speedups
+ # on SMP systems. Defaults to 1. Equivalent to -j.
+@@ -193,7 +195,7 @@
+ # as $1 and outputs it on stdout.
+ #mungefilename ()
+ #{
+-#	echo "$@" | sed s,:,\ -,g | tr \ / __ | tr -d \'\"\?\[:cntrl:\]
++#	echo "$@" | sed s,:,\ -,g | tr / __ | tr -d \'\"\?\[:cntrl:\]
+ #}
  
-@@ -33,6 +36,7 @@
- # assume a reasonable default if $WGET is undefined
- if [ "$WGET" = "" ]; then
- 	WGET=wget
-+	WGETOPTS="-q -O -"
- fi
- 
- usage() {
-@@ -164,7 +168,7 @@
- 	shift 3
- 	TRACKINFO="$@"
- 	TRACKINFOPLUS=$(echo $TRACKINFO | tr ' ' '+')
--	RESULTS=$($WGET -q -O - "$SERVER?cmd=cddb+query+$TRACKINFOPLUS\&hello=$HELLOINFO\&proto=3") || exit $LOOKUP_ERR
-+	RESULTS=$($WGET $WGETOPTS "$SERVER?cmd=cddb+query+$TRACKINFOPLUS\&hello=$HELLOINFO\&proto=3") || exit $LOOKUP_ERR
- 	echo $RESULTS | tr '\r' '\n' | tr -s '\n' | sed 's/^ //g'
- 	;;
- 
-@@ -175,7 +179,7 @@
- 	CATEGORY="$4"
- 	DISCID="$5"
- 	HELLOINFO="$USER+$HOST+$NAME+$VERSION"
--	$WGET -q -O - $CDDBDATA "$SERVER?cmd=cddb+read+$CATEGORY+$DISCID\&hello=$HELLOINFO\&proto=3" 2>/dev/null
-+	$WGET $WGETOPTS $CDDBDATA "$SERVER?cmd=cddb+read+$CATEGORY+$DISCID\&hello=$HELLOINFO\&proto=3" 2>/dev/null
- 	;;
- 
- 	help) help ;;
-diff -urN abcde-2.0.3.orig/seq abcde-2.0.3/seq
---- abcde-2.0.3.orig/seq	Wed Dec 31 19:00:00 1969
-+++ abcde-2.0.3/seq	Tue Apr  8 21:21:43 2003
-@@ -0,0 +1,19 @@
-+#!/usr/bin/perl -w
-+# A replacement for the GNU seq utility
-+# Written by Evan Jones <ejones@uwaterloo.ca> in December, 2002
-+# http://www.eng.uwaterloo.ca/~ejones/
-+
-+use strict;
-+
-+die "Usage: seq [start] [end]\n" if ( @ARGV != 2 );
-+die "seq: Starting value must be an integer\n" if ( $ARGV[0] !~ /^-?\d+$/ );
-+die "seq: Ending value must be an integer\n" if ( $ARGV[1] !~ /^
-+?\d+$/ );
-+die "seq: Starting value must be less than or equal to the ending value\n" if ( $ARGV[0] > $ARGV[1] );
-+
-+for ( my $i = $ARGV[0]; $i <= $ARGV[1]; ++ $i )
-+{
-+	print( "$i " );
-+}
-+
-+print( "\n" );
+ # If you'd like to have abcde eject the cdrom after all the tracks have been
+diff -ur abcde-2.1.9.orig/cddb-tool abcde-2.1.9/cddb-tool
+--- abcde-2.1.9.orig/cddb-tool	Thu Dec  4 09:03:26 2003
++++ abcde-2.1.9/cddb-tool	Thu Dec  4 10:39:17 2003
+@@ -35,6 +35,9 @@
+ 	if [ X"$(uname)" = X"FreeBSD" ] ; then
+ 		HTTPGET=fetch
+ 		HTTPGETOPTS=${HTTPGETOPTS:="-q -o -"}
++	elif [ X"$(uname)" = X"Darwin" ] ; then
++		HTTPGET=curl
++		HTTPGETOPTS=${HTTPGETOPTS:="-f -s"}
+ 	else
+ 		HTTPGET=wget
+ 		HTTPGETOPTS=${HTTPGETOPTS:="-q -O -"}
