Bring quilt to 0.44. This obsoletes a lot of the old patch. The new patch hasn't been tested very thoroughly.

diff --git a/10.4/unstable/main/finkinfo/devel/quilt.patch b/10.4/unstable/main/finkinfo/devel/quilt.patch
--- a/10.4/unstable/main/finkinfo/devel/quilt.patch
+++ b/10.4/unstable/main/finkinfo/devel/quilt.patch
@@ -1,199 +1,109 @@
-diff -r 96be197f975c Makefile.in
---- a/Makefile.in	Thu Nov 10 07:54:14 2005
-+++ b/Makefile.in	Fri Nov 11 22:36:46 2005
-@@ -41,8 +41,8 @@
- ISODATE :=	$(shell date +%Y-%m-%d)
+diff -r 7b51c215fc54 Makefile.in
+--- a/Makefile.in	Sat Mar  4 17:16:21 2006 -0800
++++ b/Makefile.in	Sat Mar  4 17:59:09 2006 -0800
+@@ -256,7 +256,7 @@ bin/guards.1 : bin/guards
+ 		-e 's:@VERSION''@:$(VERSION):g'				\
+ 		-e 's:@RELEASE''@:$(RELEASE):g'				\
+ 		-e 's:@LOCALEDIR''@:$(localedir):g'			\
+-		-e 's:@DOCSUBDIR''@:$(docdir)/$(PACKAGE)-$(VERSION):g'	\
++		-e 's:@DOCSUBDIR''@:$(docdir)/$(PACKAGE):g'	\
+ 		$< > $@
+ 	@$(if $(filter-out $<,$(NON_EXEC_IN)),chmod +x $@)
  
- #-----------------------------------------------------------------------
--DIRT +=		$(shell find -name '*~')
--DIRT +=		$(shell find -name '.\#*')
-+DIRT +=		$(shell find . -name '*~')
-+DIRT +=		$(shell find . -name '.\#*')
+@@ -320,11 +320,11 @@ endif
+ 	$(INSTALL) -d $(BUILD_ROOT)$(libdir)/$(PACKAGE)
+ 	$(INSTALL) -m 755 $(LIB:%=lib/%) $(BUILD_ROOT)$(libdir)/$(PACKAGE)/
  
- SRC +=		COPYING AUTHORS TODO Makefile.in \
- 		configure.ac config/install-sh \
-@@ -163,7 +163,7 @@
- 		(bash -c ". scripts/patchfns ; cd $$dir ;LC_ALL=C . $$i -h"); \
- 		echo; \
- 	done | \
--	sed -e '/^Usage:/{s/^Usage: \?//;b}' -e '/^$$/!s/^/  /'
-+	sed -f reference.sed
+-	$(INSTALL) -d $(BUILD_ROOT)$(docdir)/$(PACKAGE)-$(VERSION)/
++	$(INSTALL) -d $(BUILD_ROOT)$(docdir)/$(PACKAGE)/
+ 	$(INSTALL) -m 644 doc/README					\
+-		   $(BUILD_ROOT)$(docdir)/$(PACKAGE)-$(VERSION)/
++		   $(BUILD_ROOT)$(docdir)/$(PACKAGE)/
+ 	$(INSTALL) -m 644 doc/quilt.pdf doc/README.MAIL			\
+-		   $(BUILD_ROOT)$(docdir)/$(PACKAGE)-$(VERSION)/
++		   $(BUILD_ROOT)$(docdir)/$(PACKAGE)/
  
- bin/guards.1 : bin/guards
- 	mkdir -p $$(dirname $@)
-@@ -214,9 +214,8 @@
- 	     -e 's:@DIFFSTAT''@:$(DIFFSTAT):g' \
- 	     -e 's:@MTA''@:$(MTA):g' \
- 	     -e 's:@LOCALEDIR''@:$(localedir):g' \
--	     -e 's:@DOCSUBDIR''@:$(docdir)/$(PACKAGE)-$(VERSION):g' \
-+	     -e 's:@DOCSUBDIR''@:$(docdir)/$(PACKAGE):g' \
- 	     $< > $@
--	@chmod --reference=$< $@
- 
- Makefile : Makefile.in
- 	@echo "Please run ./configure by hand"
-@@ -238,11 +237,11 @@
- 	@INSTALL@ -d $(BUILD_ROOT)$(LIB_DIR)
- 	@INSTALL@ -m 755 -s $(LIB:%=lib/%) $(BUILD_ROOT)$(LIB_DIR)/
- 
--	@INSTALL@ -d $(BUILD_ROOT)$(docdir)/$(PACKAGE)-$(VERSION)/
-+	@INSTALL@ -d $(BUILD_ROOT)$(docdir)/$(PACKAGE)/
- 	@INSTALL@ -m 644 doc/README \
--		$(BUILD_ROOT)$(docdir)/$(PACKAGE)-$(VERSION)/
-+		$(BUILD_ROOT)$(docdir)/$(PACKAGE)/
- 	@INSTALL@ -m 644 doc/quilt.pdf doc/README.MAIL \
--		$(BUILD_ROOT)$(docdir)/$(PACKAGE)-$(VERSION)/
-+		$(BUILD_ROOT)$(docdir)/$(PACKAGE)/
- 
- 	@INSTALL@ -d $(BUILD_ROOT)$(mandir)/man1
- 	@INSTALL@ -m 644 $(MAN1) $(BUILD_ROOT)$(mandir)/man1/
-@@ -263,7 +262,7 @@
- 		   $(notdir $(MAN1))) \
- 	       $(BUILD_ROOT)$(etcdir)/bash_completion.d/quilt \
- 	       $(BUILD_ROOT)$(etcdir)/quilt.quiltrc \
+ 	$(INSTALL) -d $(BUILD_ROOT)$(mandir)/man1
+ 	$(INSTALL) -m 644 $(MAN1) $(BUILD_ROOT)$(mandir)/man1/
+@@ -367,7 +367,7 @@ uninstall ::
+ 		   $(notdir $(MAN1)))					\
+ 	       $(BUILD_ROOT)$(etcdir)/bash_completion.d/quilt		\
+ 	       $(BUILD_ROOT)$(etcdir)/quilt.quiltrc			\
 -	       $(BUILD_ROOT)$(docdir)/$(PACKAGE)-$(VERSION)/
 +	       $(BUILD_ROOT)$(docdir)/$(PACKAGE)/
- 	$(MAKE_NLS) -C po uninstall BUILD_ROOT=$(BUILD_ROOT) \
- 		LINGUAS="$(LINGUAS)" localedir=$(localedir)
  
-diff -r 96be197f975c lib/backup-files.c
---- a/lib/backup-files.c	Thu Nov 10 07:54:14 2005
-+++ b/lib/backup-files.c	Fri Nov 11 22:36:46 2005
-@@ -37,7 +37,7 @@
- #include <errno.h>
- #include <string.h>
- #include <alloca.h>
--#include <ftw.h>
-+#include <dirent.h>
+ check: $(TESTS:test/%.test=test/.%.ok)
+ check-all: $(TESTS:test/%.test=check-%)
+diff -r 7b51c215fc54 configure
+--- a/configure	Sat Mar  4 17:16:21 2006 -0800
++++ b/configure	Sat Mar  4 17:59:09 2006 -0800
+@@ -3882,29 +3882,6 @@ echo "$as_me: error: Please specify the 
+   fi
  
- const char *progname;
  
-@@ -312,18 +312,85 @@
- }
+-echo "$as_me:$LINENO: checking whether $CP -l works" >&5
+-echo $ECHO_N "checking whether $CP -l works... $ECHO_C" >&6
+-touch conftest.1
+-if $CP -l conftest.1 conftest.2 2>/dev/null; then
+-	echo "$as_me:$LINENO: result: yes" >&5
+-echo "${ECHO_T}yes" >&6
+-else
+-	{ { echo "$as_me:$LINENO: error: no
+-
+-You appear to have a \`cp' that does not support hard links.
+-You can download GNU fileutils from ftp.gnu.org
+-" >&5
+-echo "$as_me: error: no
+-
+-You appear to have a \`cp' that does not support hard links.
+-You can download GNU fileutils from ftp.gnu.org
+-" >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
+-
+-
+-
+-
  
- int
--walk(const char *path, const struct stat *stat, int flag, struct FTW *ftw)
-+searchdir_p (const char *path, int complain)
-+{
-+	struct stat st;
-+
-+	/* ignore missing files */
-+	if (stat(path, &st) != 0) {
-+		if (complain) perror (path);
-+		return 0;
-+	}
-+	/* and non-directories */
-+	if (!S_ISDIR(st.st_mode)) {
-+		if (complain)
-+			fprintf(stderr, "%s: not a directory\n", path);
-+		return 0;
-+	}
-+	/* no access permission */
-+	if (access(path, R_OK|X_OK) != 0) {
-+		if (complain) perror (path);
-+		return 0;
-+	}
-+
-+	return 1;
-+}
-+
-+int
-+foreachdir (const char *root, int(*walk)(const char *))
-+{
-+	int errors = 0;
-+	DIR *dir;
-+
-+	if (!searchdir_p(root, 1))
-+		return 0;
-+
-+	dir = opendir(root);
-+	if (dir) {
-+		struct dirent *dp = 0;
-+
-+		while ((dp = readdir(dir))) {
-+			if (strcmp(dp->d_name, ".")
-+			   && strcmp(dp->d_name, "..")) {
-+				char *path = alloca (2+ strlen (root) +
-+						    strlen (dp->d_name));
-+				sprintf (path, "%s/%s", root, dp->d_name);
-+				if (searchdir_p (path, 0)) {
-+					/* depth first recurse */
-+					errors += foreachdir(path, walk);
-+				} else {
-+					struct stat st;
-+					if (stat(path, &st) != 0) {
-+						/* ignore missing files */
-+						continue;
-+					}
-+					if (S_ISREG(st.st_mode)) {
-+						/* process regular files */
-+						errors += walk(path);
-+					}
-+				}
-+			}
-+			if (errors > 0) {
-+				break;
-+			}
-+		}
-+	}
-+
-+	if (closedir(dir) !=0) {
-+		++errors;
-+		perror(root);
-+	}
-+
-+	return errors;
-+}
-+
-+int
-+ftwalk(const char *path)
- {
- 	size_t prefix_len=strlen(opt_prefix), suffix_len=strlen(opt_suffix);
- 	size_t len = strlen(path);
- 	char *p;
+ # Check whether --with-date or --without-date was given.
+ if test "${with_date+set}" = set; then
+@@ -3999,32 +3976,6 @@ echo "$as_me: WARNING: Using internal da
+       INTERNAL_DATE=1
  
--	if (flag == FTW_DNR) {
--		perror(path);
--		return 1;
--	}
--	if (!S_ISREG(stat->st_mode))
--		return 0;
- 	if (strncmp(opt_prefix, path, prefix_len))
- 		return 0;  /* prefix does not match */
- 	if (len < suffix_len || strcmp(opt_suffix, path + len - suffix_len))
-@@ -332,6 +399,7 @@
- 	p = alloca(len - prefix_len - suffix_len + 1);
- 	memcpy(p, path + prefix_len, len - prefix_len - suffix_len);
- 	p[len - prefix_len - suffix_len] = '\0';
-+
- 	return process_file(p);
- }
+   fi
+-
+-
+-
+-if test -z "$INTERNAL_DATE"; then
+-  echo "$as_me:$LINENO: checking whether $DATE --rfc-822 works" >&5
+-echo $ECHO_N "checking whether $DATE --rfc-822 works... $ECHO_C" >&6
+-  if $DATE --rfc-822 >/dev/null 2>/dev/null; then
+-	echo "$as_me:$LINENO: result: yes" >&5
+-echo "${ECHO_T}yes" >&6
+-  else
+-	{ { echo "$as_me:$LINENO: error: no
+-
+-If you don't have a version of \`date' that supports --rfc-822, you
+-can specify '--without-date' and $PACKAGE_NAME will use its own
+-internal date.
+-" >&5
+-echo "$as_me: error: no
+-
+-If you don't have a version of \`date' that supports --rfc-822, you
+-can specify '--without-date' and $PACKAGE_NAME will use its own
+-internal date.
+-" >&2;}
+-   { (exit 1); exit 1; }; }
+-  fi
+-fi
+-
  
-@@ -424,13 +492,16 @@
- 	}
- 	for (; optind < argc; optind++) {
- 		if (strcmp(argv[optind], "-") == 0) {
--			char *dir = strdup(opt_prefix), *d = strrchr(dir, '/');
-+			char *dir, *d;
-+
-+			dir = strdup(opt_prefix);
-+			d = strrchr(dir, '/');
- 			if (d)
--				*(d+1) = '\0';
-+				*d = '\0';
- 			else
- 				d = ".";
--			status = nftw(dir, walk, 0, 0);
--			free(dir);
-+
-+			foreachdir (dir, ftwalk);
- 		} else
- 			status = process_file(argv[optind]);
- 		if (status)
-diff -r 96be197f975c quilt/diff.in
---- a/quilt/diff.in	Thu Nov 10 07:54:14 2005
-+++ b/quilt/diff.in	Fri Nov 11 22:36:46 2005
-@@ -338,7 +338,7 @@
+ 
+ 
+diff -r 7b51c215fc54 quilt/diff.in
+--- a/quilt/diff.in	Sat Mar  4 17:16:21 2006 -0800
++++ b/quilt/diff.in	Sat Mar  4 17:59:09 2006 -0800
+@@ -303,7 +303,7 @@ then
  
  	if [ ${#files[@]} -gt 0 ] \
  	   && ! ( cd $QUILT_PC/$last_patch &&
@@ -202,86 +112,53 @@ diff -r 96be197f975c quilt/diff.in
  	then
  		printf $"Failed to copy files to temporary directory\n" >&2
  		die 1
-diff -r 96be197f975c quilt/mail.in
---- a/quilt/mail.in	Thu Nov 10 07:54:14 2005
-+++ b/quilt/mail.in	Fri Nov 11 22:36:46 2005
-@@ -52,8 +52,8 @@
+diff -r 7b51c215fc54 quilt/mail.in
+--- a/quilt/mail.in	Sat Mar  4 17:16:21 2006 -0800
++++ b/quilt/mail.in	Sat Mar  4 17:59:09 2006 -0800
+@@ -64,7 +64,7 @@ with a template for the introduction. Pl
  
  msgid()
  {
 -	local timestamp=$(date --utc "+%Y%m%d%H%M%S.%N")
--	echo "$timestamp@$(hostname -f)"
 +	local timestamp=$(date -u "+%Y%m%d%H%M%S.000000000")
-+	echo "$timestamp@$(hostname)"
+ 	echo "$timestamp@${opt_sender#*@}"
  }
  
- process_mail()
-@@ -73,7 +73,7 @@
- 		| @MTA@ "$@"
- 	else
- 		local from_date=$(date "+%a %b %e %H:%M:%S %Y")
--		echo "From ${LOGNAME:-$(whoami)}@$(hostname -f) $from_date"
-+		echo "From ${LOGNAME:-$(whoami)}@$(hostname) $from_date"
- 		@SED@ -e 's/^From />From /' $tmpfile
- 		echo
- 	fi
-@@ -154,7 +154,7 @@
- (
+@@ -334,7 +334,7 @@ introduction="$(gen_tempfile)"
  	cat <<-EOF
  	Message-Id: <$(msgid)>
+ 	User-Agent: quilt/@VERSION@-@RELEASE@
 -	Date: $(date --rfc-822)
 +	Date: $(date '+%a, %d %b %Y %H:%M:%S %z')
- 	From: $opt_from
+ 	From: ${opt_from:-$opt_sender}
  	To: $(IFS=,; echo "${opt_to[*]}")
  	Cc: $(IFS=,; echo "${opt_cc[*]}")
-@@ -198,7 +198,11 @@
+@@ -401,7 +401,11 @@ fi
  # increment the timestamp by one second and wait with sending until
  # that time has arrived. This allows MUAs to show the messages in the
  # correct order.
--last_ts=$(date '+%s' -d "$(@SED@ -ne $'s/^Date:[ \t]*//p' $introduction)")
-+#last_ts=$(date '+%s' -d "$(@SED@ -ne $'s/^Date:[ \t]*//p' $introduction)")
+-last_ts=$(date '+%s' -d "$(sed -ne $'s/^Date:[ \t]*//p' $introduction)")
++#last_ts=$(date '+%s' -d "$(sed -ne $'s/^Date:[ \t]*//p' $introduction)")
 +# fink has no date available that does -d, so we fudge with the time now.
 +# If the user edits the date field in the message patch 0 could end up
 +# out of order wrt the actual patches. just a minor cosmetic nit.
 +last_ts=$(date '+%s')
  
  num=1
- body=$(gen_tempfile)
-@@ -209,7 +213,7 @@
+ for patch in "${patches[@]}"; do
+@@ -412,7 +416,7 @@ for patch in "${patches[@]}"; do
  	#	sleep 1
  	#done
  	((last_ts++))
 -	new_date="$(date --rfc-822 -d "1970/01/01 UTC $last_ts seconds")"
 +	new_date="$(date -r $last_ts '+%a, %d %b %Y %H:%M:%S %z')"
  
- 	cat_file $(patch_file_name $patch) \
- 	| quilt_mail_patch_filter $patch > $body
-diff -r 96be197f975c quilt/pop.in
---- a/quilt/pop.in	Thu Nov 10 07:54:14 2005
-+++ b/quilt/pop.in	Fri Nov 11 22:36:46 2005
-@@ -52,7 +52,7 @@
- {
- 	local n=0 patch
- 	applied_patches \
--	| tac \
-+	| perl -e 'print reverse <>' \
- 	| if [ -n "$opt_all" ]
- 	then
- 		cat
-@@ -88,10 +88,10 @@
- 		return 0
- 	fi
- 	
--	local apply_ts=$(date -r "$QUILT_PC/$patch/.timestamp" '+%s') ts
-+	local apply_ts=$(dater "$QUILT_PC/$patch/.timestamp" '+%s') ts
- 	for file in $(files_in_patch $patch)
- 	do
--		ts=$(date -r $file '+%s' 2> /dev/null)
-+		ts=$(dater $file '+%s' 2> /dev/null)
- 		[ -z "$ts" ] && return 0
- 		[ "$ts" -gt $apply_ts ] && return 0
- 	done
-@@ -109,7 +109,7 @@
+ 	modify="$(awk '
+ 	sub(/^Recipient-/, "")	{ r = $0
+diff -r 7b51c215fc54 quilt/pop.in
+--- a/quilt/pop.in	Sat Mar  4 17:16:21 2006 -0800
++++ b/quilt/pop.in	Sat Mar  4 17:59:09 2006 -0800
+@@ -93,7 +93,7 @@ check_for_pending_changes()
  	if [ -d $QUILT_PC/$patch ]
  	then
  		if ! rmdir $workdir ||  # note that this is racey...
@@ -290,37 +167,14 @@ diff -r 96be197f975c quilt/pop.in
  		then
  			printf $"Failed to copy files to temporary directory\n" >&2
  			rm -rf $workdir
-diff -r 96be197f975c scripts/dependency-graph.in
---- a/scripts/dependency-graph.in	Thu Nov 10 07:54:14 2005
-+++ b/scripts/dependency-graph.in	Fri Nov 11 22:36:46 2005
-@@ -241,7 +241,7 @@
- 			print STDERR "$ENV{QUILT_PC}/$patch does not exist; skipping\n";
- 			next;
- 		}
--		@files = split(/\n/, `cd $ENV{QUILT_PC}/$patch ; find -type f ! -name .timestamp`);
-+		@files = split(/\n/, `cd $ENV{QUILT_PC}/$patch ; find . -type f ! -name .timestamp`);
- 		@files = map { s:\./::; $_ } @files;
- 	}
- 	push @nodes, {number=>$n++, name=>$patch, file=>$patch,
-diff -r 96be197f975c scripts/inspect.in
---- a/scripts/inspect.in	Thu Nov 10 07:54:14 2005
-+++ b/scripts/inspect.in	Fri Nov 11 22:36:46 2005
-@@ -130,7 +130,7 @@
- 		if ! [ -e $tmpdir/more-md5sums ]
- 		then
- 			( cd $RPM_BUILD_DIR
--			find -type f \
-+			find . -type f \
- 			| sed -e 's:^.\/::' \
- 			| xargs md5sum \
- 			) > $tmpdir/more-md5sums
-diff -r 96be197f975c scripts/patchfns.in
---- a/scripts/patchfns.in	Thu Nov 10 07:54:14 2005
-+++ b/scripts/patchfns.in	Fri Nov 11 22:36:46 2005
-@@ -67,6 +67,27 @@
+diff -r 7b51c215fc54 quilt/scripts/patchfns.in
+--- a/quilt/scripts/patchfns.in	Sat Mar  4 17:16:21 2006 -0800
++++ b/quilt/scripts/patchfns.in	Sat Mar  4 17:59:09 2006 -0800
+@@ -45,6 +45,28 @@ fi
+ fi
  
  # ========================================================
- 
++
 +dater()
 +{
 +  ts=$(perl -e '@st = stat($ARGV[0]); print $st[9];' "$1")
@@ -342,10 +196,10 @@ diff -r 96be197f975c scripts/patchfns.in
 +  done
 +}
 +
- # Quote a string for use in a basic regular expression.
- quote_bre()
- {
-@@ -542,8 +563,7 @@
+ 
+ #declare -a exit_handlers
+ #
+@@ -669,8 +691,7 @@ diff_file()
  		|| old_date=$'\t'"1970-01-01 00:00:00.000000000 +0000"
  	else
  		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
@@ -355,7 +209,7 @@ diff -r 96be197f975c scripts/patchfns.in
  	fi
  	if ! [ -s "$new_file" ]
  	then
-@@ -553,8 +573,7 @@
+@@ -682,8 +703,7 @@ diff_file()
  		|| new_date=$'\t'"1970-01-01 00:00:00.000000000 +0000"
  	else
  		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
@@ -364,11 +218,4 @@ diff -r 96be197f975c scripts/patchfns.in
 +		|| new_date=$'\t'$(dater "$new_file" +'%Y-%m-%d %H:%M:%S.000000000 %z')
  	fi
  
- 	@DIFF@ -N $QUILT_DIFF_OPTS $old_file $new_file \
-diff -r 96be197f975c reference.sed
---- /dev/null	Thu Nov 10 07:54:14 2005
-+++ b/reference.sed	Fri Nov 11 22:36:46 2005
-@@ -0,0 +1,3 @@
-+/^Usage:/{s/^Usage: \?//;b
-+}
-+/^$$/!s/^/  /
+ 	diff $QUILT_DIFF_OPTS $old_file $new_file \
