kde 3.1.3 -- trial by fire!  =)

diff --git a/10.2/unstable/main/finkinfo/kde/kdebase3.patch b/10.2/unstable/main/finkinfo/kde/kdebase3.patch
--- a/10.2/unstable/main/finkinfo/kde/kdebase3.patch
+++ b/10.2/unstable/main/finkinfo/kde/kdebase3.patch
@@ -1,63 +1,6 @@
 
---- startkde	6 May 2003 17:48:14 -0000	1.1.1.8
-+++ startkde	14 May 2003 13:43:52 -0000	1.13
-@@ -34,6 +34,10 @@
- # people's heads. We use colours from the standard KDE palette for those with
- # palettised displays.
- 
-+# we have to unset this for Darwin since it will screw up KDE's dynamic-loading
-+unset DYLD_FORCE_FLAT_NAMESPACE
-+test -d "@PREFIX@" && export PATH="@PREFIX@/bin:${PATH}"
-+
- test "$XDM_MANAGED" || bkg="-solid #C0C0C0"
- xsetroot -cursor_name left_ptr $bkg
- 
-@@ -110,6 +114,11 @@
-     export GS_LIB
- fi
- 
-+# if we're in Apple's X11 and the native window manager is available, use that
-+if test -z "$KDEWM" && test -x /usr/X11R6/bin/quartz-wm; then
-+    KDEWM="/usr/X11R6/bin/quartz-wm"
-+fi
-+
- # Link "tmp" resource to directory in /tmp
- # Creates a directory /tmp/kde-$USER and links $KDEHOME/tmp-$HOSTNAME to it.
- lnusertemp tmp >/dev/null
-@@ -128,7 +137,11 @@
-     # start only dcopserver, don't start whole kdeinit (takes too long)
-     echo 'startkde: Running kpersonalizer...'  1>&2
-     dcopserver
--    kwin &
-+    if test -n "$KDEWM"; then
-+        $KDEWM &
-+    else
-+        kwin &
-+    fi
-     kpersonalizer --before-session
-     # handle kpersonalizer restarts (language change)
-     while test $? -eq 1; do
-@@ -139,7 +152,6 @@
-     sleep 1
- fi
- 
--# the splashscreen and progress indicator
- ksplash
- 
- # We set LD_BIND_NOW to increase the efficiency of kdeinit.
-@@ -150,6 +162,10 @@
-   echo 'startkde: Could not start kdeinit. Check your installation.'  1>&2
-   xmessage -geometry 500x100 "Could not start kdeinit. Check your installation."
- fi
-+
-+# fix up KDE themes
-+echo 'startkde: updating theme cache'
-+kwrapper kinstalltheme
- 
- # finally, give the session control to the session manager
- # if the KDEWM environment variable has been set, then it will be used as KDE's
 --- kate/app/Makefile.am	12 Nov 2002 04:16:41 -0000	1.1.1.4
-+++ kate/app/Makefile.am	26 May 2003 20:09:48 -0000
++++ kate/app/Makefile.am	1 Jun 2003 14:31:53 -0000	1.11
 @@ -1,4 +1,4 @@
 -lib_LTLIBRARIES = libkateinterfaces.la kate.la kwrite.la
 +lib_LTLIBRARIES = libkateinterfaces.la kate.la kwrite.la libkwrite_main.la
@@ -122,8 +65,6 @@
  METASOURCES = AUTO  
    
  INCLUDES= -I../interfaces -I$(srcdir)/../lib $(all_includes)
-RCS file: kate/app/kwrite_main.cpp
-diff -N kate/app/kwrite_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ kate/app/kwrite_main.cpp	26 Nov 2002 21:00:50 -0000	1.1
 @@ -0,0 +1,27 @@
@@ -154,8 +95,8 @@ diff -N kate/app/kwrite_main.cpp
 +{
 +        return kdemain(argc, argv);
 +}
---- kate/app/kwritemain.cpp	3 Mar 2003 01:38:05 -0000	1.1.1.6
-+++ kate/app/kwritemain.cpp	3 Mar 2003 01:55:31 -0000	1.3
+--- kate/app/kwritemain.cpp	19 Jul 2003 03:28:26 -0000	1.1.1.7
++++ kate/app/kwritemain.cpp	19 Jul 2003 03:50:11 -0000	1.4
 @@ -538,7 +538,9 @@
    { 0, 0, 0}
  };
@@ -194,7 +135,7 @@ diff -N kate/app/kwrite_main.cpp
  static const char *PAM_username;
  static const char *PAM_password;
 --- kcontrol/access/Makefile.am	1 Oct 2002 02:33:58 -0000	1.1.1.3
-+++ kcontrol/access/Makefile.am	26 May 2003 20:09:48 -0000
++++ kcontrol/access/Makefile.am	1 Jun 2003 14:31:53 -0000	1.8
 @@ -4,16 +4,23 @@
  
  bin_PROGRAMS = kaccess
@@ -244,36 +185,8 @@ diff -N kate/app/kwrite_main.cpp
  
  INCLUDES= $(all_includes)
 --- kcontrol/info/info.cpp	14 Jan 2003 20:08:39 -0000	1.1.1.4
-+++ kcontrol/info/info.cpp	15 Mar 2003 01:31:16 -0000	1.6
-@@ -50,8 +50,6 @@
- 					    KInfoListWidget::ErrorString */
- static bool	sorting_allowed;	/* is sorting allowed by user ? */
- 
--
--
- #if defined(__linux__)
- # define DEFAULT_ERRORSTRING QString("") /* i18n("Maybe the proc-filesystem is not enabled in Linux-Kernel.") */
- #elif defined(hpux)
-@@ -60,10 +58,6 @@
- #define DEFAULT_ERRORSTRING  i18n("Maybe this system is not completely supported yet :-(")
- #endif
- 
--
--
--
--
- /* easier to read with such a define ! */
- #define I18N_MAX(txt,in,fm,maxw) \
-     { int n = fm.width(txt=in); if (n>maxw) maxw=n; }
-@@ -118,7 +112,6 @@
-     { "OwnerGrabButtonMask",	OwnerGrabButtonMask },
-     { 0L, 0 }};
- 
--
- static QListViewItem* XServer_fill_screen_info( QListViewItem *lBox, QListViewItem *last,
- 	    Display *dpy, int scr, int default_scr)
- {
-@@ -472,6 +465,8 @@
++++ kcontrol/info/info.cpp	9 Jul 2003 14:40:20 -0000	1.7
+@@ -472,6 +472,8 @@
  #include "info_svr4.cpp"
  #elif _AIX
  #include "info_aix.cpp"
@@ -282,8 +195,6 @@ diff -N kate/app/kwrite_main.cpp
  #else
  #include "info_generic.cpp"	/* Default for unsupportet systems.... */
  #endif
-RCS file: kcontrol/info/info_osx.cpp
-diff -N kcontrol/info/info_osx.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ kcontrol/info/info_osx.cpp	25 Jun 2002 02:06:13 -0000	1.1
 @@ -0,0 +1,163 @@
@@ -461,8 +372,6 @@ diff -N kcontrol/info/info_osx.cpp
  #elif sgi
  #include "memory_sgi.cpp"
  #elif defined(__svr4__) && defined(sun)
-RCS file: kcontrol/info/memory_osx.cpp
-diff -N kcontrol/info/memory_osx.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ kcontrol/info/memory_osx.cpp	25 Jun 2002 02:06:13 -0000	1.1
 @@ -0,0 +1,72 @@
@@ -539,7 +448,7 @@ diff -N kcontrol/info/memory_osx.cpp
 +
 +}
 --- kcontrol/kcontrol/Makefile.am	4 Jan 2003 04:47:31 -0000	1.1.1.6
-+++ kcontrol/kcontrol/Makefile.am	26 May 2003 20:09:48 -0000
++++ kcontrol/kcontrol/Makefile.am	1 Jun 2003 14:31:53 -0000	1.11
 @@ -22,43 +22,69 @@
  
  SUBDIRS = . pics
@@ -674,8 +583,6 @@ diff -N kcontrol/info/memory_osx.cpp
  {
    KLocale::setMainCatalogue("kcontrol");
    KAboutData aboutKControl( "kcontrol", I18N_NOOP("KDE Control Center"),
-RCS file: kcontrol/kcontrol/stub_main.cpp
-diff -N kcontrol/kcontrol/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ kcontrol/kcontrol/stub_main.cpp	26 Nov 2002 21:00:51 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -708,7 +615,7 @@ diff -N kcontrol/kcontrol/stub_main.cpp
 +}
 +
 --- kcontrol/kfontinst/configure.in.in	10 Dec 2002 16:41:00 -0000	1.1.1.6
-+++ kcontrol/kfontinst/configure.in.in	26 May 2003 20:09:48 -0000
++++ kcontrol/kfontinst/configure.in.in	1 Jun 2003 14:31:53 -0000	1.6
 @@ -1,6 +1,6 @@
  FOUND_FREETYPE=0
  
@@ -729,7 +636,7 @@ diff -N kcontrol/kcontrol/stub_main.cpp
  #if !defined KFI_THUMBNAIL && !defined KFI_METAINFO
  #include "KfiGlobal.h"
 --- kdeprint/kjobviewer/Makefile.am	25 Jun 2002 02:03:49 -0000	1.1.1.1
-+++ kdeprint/kjobviewer/Makefile.am	26 May 2003 20:09:48 -0000
++++ kdeprint/kjobviewer/Makefile.am	1 Jun 2003 14:31:54 -0000	1.8
 @@ -1,16 +1,23 @@
  INCLUDES = $(all_includes)
  
@@ -773,7 +680,7 @@ diff -N kcontrol/kcontrol/stub_main.cpp
  messages: rc.cpp
  	$(XGETTEXT) *.cpp -o $(podir)/kjobviewer.pot
 --- kdeprint/kprinter/Makefile.am	10 Jul 2002 03:20:23 -0000	1.1.1.2
-+++ kdeprint/kprinter/Makefile.am	26 May 2003 20:09:48 -0000
++++ kdeprint/kprinter/Makefile.am	1 Jun 2003 14:31:54 -0000	1.7
 @@ -1,21 +1,28 @@
  INCLUDES = $(all_includes)
  
@@ -813,7 +720,7 @@ diff -N kcontrol/kcontrol/stub_main.cpp
 +dummy.cpp: main.cpp
 +	cat main.cpp > dummy.cpp
 --- kdesktop/Makefile.am	1 Oct 2002 02:35:37 -0000	1.1.1.3
-+++ kdesktop/Makefile.am	26 May 2003 20:09:48 -0000
++++ kdesktop/Makefile.am	1 Jun 2003 14:31:54 -0000	1.4
 @@ -1,10 +1,6 @@
  ## Makefile.am of kdebase/kdesktop
  
@@ -871,8 +778,6 @@ diff -N kcontrol/kcontrol/stub_main.cpp
  {
      //setup signal handling
      signal(SIGTERM, signalHandler);
-RCS file: kdesktop/stub_main.cpp
-diff -N kdesktop/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ kdesktop/stub_main.cpp	26 Nov 2002 21:00:51 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -904,8 +809,8 @@ diff -N kdesktop/stub_main.cpp
 +        return kdemain(argc, argv);
 +}
 +
---- kdm/backend/client.c	6 May 2003 17:50:39 -0000	1.1.1.5
-+++ kdm/backend/client.c	6 May 2003 18:23:16 -0000	1.4
+--- kdm/backend/client.c	19 Jul 2003 03:28:22 -0000	1.1.1.6
++++ kdm/backend/client.c	19 Jul 2003 03:50:13 -0000	1.5
 @@ -38,6 +38,7 @@
   * user verification and session initiation.
   */
@@ -964,7 +869,7 @@ diff -N kdesktop/stub_main.cpp
  libkfindpart_la_SOURCES = kfindpart.cpp
  libkfindpart_la_LDFLAGS = $(all_libraries) $(KDE_PLUGIN)
 --- khotkeys/khotkeys/Makefile.am	25 Jun 2002 02:03:52 -0000	1.1.1.1
-+++ khotkeys/khotkeys/Makefile.am	26 May 2003 20:09:50 -0000
++++ khotkeys/khotkeys/Makefile.am	1 Jun 2003 14:31:54 -0000	1.6
 @@ -1,15 +1,25 @@
  # $Id: Makefile.am,v 1.12 2002/02/12 14:32:08 ellis Exp $
  
@@ -1010,8 +915,6 @@ diff -N kdesktop/stub_main.cpp
  {                             // no need to i18n these, no GUI
      {
  	// multiheaded hotkeys
-RCS file: khotkeys/khotkeys/stub_main.cpp
-diff -N khotkeys/khotkeys/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ khotkeys/khotkeys/stub_main.cpp	26 Nov 2002 21:00:52 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -1164,7 +1067,7 @@ diff -N khotkeys/khotkeys/stub_main.cpp
  
  kickermenu_recentdocs_la_METASOURCES = AUTO
 --- kicker/proxy/Makefile.am	25 Jun 2002 02:03:52 -0000	1.1.1.1
-+++ kicker/proxy/Makefile.am	26 May 2003 20:09:50 -0000
++++ kicker/proxy/Makefile.am	1 Jun 2003 14:31:55 -0000	1.4
 @@ -3,32 +3,48 @@
  CLEANFILES = dummy.cpp
  
@@ -1257,8 +1160,6 @@ diff -N khotkeys/khotkeys/stub_main.cpp
  {
      KAboutData aboutData( "extensionproxy", I18N_NOOP("Panel extension proxy.")
                            , "v0.1.0"
-RCS file: kicker/proxy/stub_main.cpp
-diff -N kicker/proxy/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ kicker/proxy/stub_main.cpp	26 Nov 2002 21:00:52 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -1312,10 +1213,10 @@ diff -N kicker/proxy/stub_main.cpp
  libtaskmanager_la_LIBADD = $(LIB_KDECORE)
  
  messages:
---- kioslave/Makefile.am	29 Oct 2002 03:05:23 -0000	1.1.1.4
-+++ kioslave/Makefile.am	29 Oct 2002 03:39:31 -0000	1.6
-@@ -8,10 +8,14 @@
- SMB_SUBDIR=smb
+--- kioslave/Makefile.am	19 Jul 2003 03:30:12 -0000	1.1.1.5
++++ kioslave/Makefile.am	19 Jul 2003 03:50:14 -0000	1.7
+@@ -10,10 +10,14 @@
+ SMB_SUBDIR=smbro
  endif
  
 +if include_kioslave_nfs
@@ -1328,12 +1229,12 @@ diff -N kicker/proxy/stub_main.cpp
  
 -
 -SUBDIRS = about cgi floppy filter fish info mac man nfs nntp pop3 imap4 smtp \
--  smbro sftp tar zip finger thumbnail $(LDAP_SUBDIR) $(SMB_SUBDIR) $(DEVICES_SUBDIR)
+-  sftp tar zip finger thumbnail $(LDAP_SUBDIR) $(SMB_SUBDIR) $(DEVICES_SUBDIR)
 +SUBDIRS = about cgi floppy filter fish info mac man nntp pop3 imap4 smtp \
-+	smbro sftp tar zip finger thumbnail $(LDAP_SUBDIR) $(SMB_SUBDIR) \
++	sftp tar zip finger thumbnail $(LDAP_SUBDIR) $(SMB_SUBDIR) \
 +	$(NFS_SUBDIR) $(DEVICES_SUBDIR)
---- kioslave/devices/configure.in.in	29 Oct 2002 03:05:23 -0000	1.1.1.2
-+++ kioslave/devices/configure.in.in	11 Nov 2002 20:56:20 -0000	1.2
+--- kioslave/devices/configure.in.in	19 Jul 2003 03:30:18 -0000	1.1.1.3
++++ kioslave/devices/configure.in.in	19 Jul 2003 03:50:14 -0000	1.3
 @@ -7,6 +7,9 @@
      Linux)
          DEVICESDIR=devices
@@ -1411,8 +1312,6 @@ diff -N kicker/proxy/stub_main.cpp
 +
 +The only solution is to probably reimplement clnt.h locally to fix
 +these (wrapping the "#include <rpc/rpc.h>" in an extern "C" isn't enough).
-RCS file: kioslave/nfs/configure.in.in
-diff -N kioslave/nfs/configure.in.in
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ kioslave/nfs/configure.in.in	18 Dec 2002 17:11:17 -0000	1.3
 @@ -0,0 +1,12 @@
@@ -1429,7 +1328,7 @@ diff -N kioslave/nfs/configure.in.in
 +AC_MSG_RESULT($withval)
 +AM_CONDITIONAL(include_kioslave_nfs, test "$with_nfs" = "yes")
 --- klipper/Makefile.am	14 Jan 2003 20:11:15 -0000	1.1.1.5
-+++ klipper/Makefile.am	26 May 2003 20:09:51 -0000
++++ klipper/Makefile.am	1 Jun 2003 14:31:55 -0000	1.10
 @@ -1,23 +1,30 @@
  INCLUDES= $(all_includes)
  
@@ -1471,7 +1370,7 @@ diff -N kioslave/nfs/configure.in.in
  klipper_panelapplet_la_LDFLAGS = $(all_libraries) -module -avoid-version
  
 --- kmenuedit/Makefile.am	14 Aug 2002 14:27:55 -0000	1.1.1.3
-+++ kmenuedit/Makefile.am	26 May 2003 20:09:51 -0000
++++ kmenuedit/Makefile.am	1 Jun 2003 14:31:55 -0000	1.8
 @@ -1,18 +1,24 @@
  INCLUDES = $(all_includes)
  
@@ -1504,7 +1403,7 @@ diff -N kioslave/nfs/configure.in.in
  noinst_HEADERS = kmenuedit.h menueditview.h treeview.h desktopfileeditor.h basictab.h khotkeys.h
  
 --- konqueror/Makefile.am	17 Jan 2003 15:03:12 -0000	1.1.1.5
-+++ konqueror/Makefile.am	26 May 2003 20:09:51 -0000
++++ konqueror/Makefile.am	1 Jun 2003 14:31:55 -0000	1.5
 @@ -5,7 +5,7 @@
  #SUBDIRS = . kfmexec client iconview dirtree listview keditbookmarks shellcmdplugin about pics sidebar
  SUBDIRS = . kfmexec client iconview listview keditbookmarks shellcmdplugin about pics sidebar
@@ -1558,7 +1457,7 @@ diff -N kioslave/nfs/configure.in.in
  messages: rc.cpp
  	$(EXTRACTRC) *.rc */*.rc >> rc.cpp
 --- konqueror/client/Makefile.am	14 Aug 2002 14:30:59 -0000	1.1.1.2
-+++ konqueror/client/Makefile.am	26 May 2003 20:09:51 -0000
++++ konqueror/client/Makefile.am	1 Jun 2003 14:31:56 -0000	1.8
 @@ -1,12 +1,12 @@
  AM_CPPFLAGS = -DQT_NO_CAST_ASCII
  
@@ -1600,9 +1499,9 @@ diff -N kioslave/nfs/configure.in.in
  
  messages:
  	$(XGETTEXT) -kaliasLocal *.h *.cc -o $(podir)/kfmclient.pot
---- konqueror/client/kfmclient.cc	6 May 2003 18:00:18 -0000	1.1.1.7
-+++ konqueror/client/kfmclient.cc	6 May 2003 18:23:18 -0000	1.6
-@@ -64,7 +64,9 @@
+--- konqueror/client/kfmclient.cc	19 Jul 2003 03:33:24 -0000	1.1.1.8
++++ konqueror/client/kfmclient.cc	19 Jul 2003 03:50:16 -0000	1.7
+@@ -65,7 +65,9 @@
     {0,0,0}
  };
  
@@ -1613,8 +1512,6 @@ diff -N kioslave/nfs/configure.in.in
  {
    KCmdLineArgs::init(argc, argv, appName, description, version, false);
  
-RCS file: konqueror/client/stub_main.cpp
-diff -N konqueror/client/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ konqueror/client/stub_main.cpp	26 Nov 2002 21:00:53 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -1647,7 +1544,7 @@ diff -N konqueror/client/stub_main.cpp
 +}
 +
 --- konqueror/keditbookmarks/Makefile.am	29 Oct 2002 03:05:50 -0000	1.1.1.3
-+++ konqueror/keditbookmarks/Makefile.am	26 May 2003 20:09:51 -0000
++++ konqueror/keditbookmarks/Makefile.am	1 Jun 2003 14:31:56 -0000	1.6
 @@ -2,22 +2,29 @@
  
  METASOURCES = AUTO
@@ -1699,8 +1596,6 @@ diff -N konqueror/client/stub_main.cpp
  {
    KLocale::setMainCatalogue("konqueror");
    KAboutData aboutData("keditbookmarks", I18N_NOOP("KEditBookmarks"), "1.1",
-RCS file: konqueror/keditbookmarks/stub_main.cpp
-diff -N konqueror/keditbookmarks/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ konqueror/keditbookmarks/stub_main.cpp	26 Nov 2002 21:00:53 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -1813,7 +1708,7 @@ diff -N konqueror/keditbookmarks/stub_main.cpp
  
  public slots:
 --- konsole/konsole/Makefile.am	6 May 2003 17:53:37 -0000	1.1.1.6
-+++ konsole/konsole/Makefile.am	26 May 2003 20:09:51 -0000
++++ konsole/konsole/Makefile.am	1 Jun 2003 14:31:56 -0000	1.9
 @@ -12,13 +12,12 @@
  
  # you can add here more. This one gets installed
@@ -1957,8 +1852,8 @@ diff -N konqueror/keditbookmarks/stub_main.cpp
  {
    KLocale::setMainCatalogue("konsole");
    KCmdLineArgs::init(argc, argv, "kwrited",
---- konsole/konsole/main.cpp	6 May 2003 17:53:37 -0000	1.1.1.7
-+++ konsole/konsole/main.cpp	29 Mar 2003 02:34:58 -0000	1.6
+--- konsole/konsole/main.cpp	19 Jul 2003 03:29:50 -0000	1.1.1.8
++++ konsole/konsole/main.cpp	19 Jul 2003 03:50:17 -0000	1.7
 @@ -125,7 +125,8 @@
  
  
@@ -1969,8 +1864,6 @@ diff -N konqueror/keditbookmarks/stub_main.cpp
  {
    setgid(getgid()); setuid(getuid()); // drop privileges
  
-RCS file: konsole/konsole/stub_main.cpp
-diff -N konsole/konsole/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ konsole/konsole/stub_main.cpp	26 Nov 2002 21:00:53 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -2003,7 +1896,7 @@ diff -N konsole/konsole/stub_main.cpp
 +}
 +
 --- ksmserver/Makefile.am	10 Jul 2002 03:24:29 -0000	1.1.1.2
-+++ ksmserver/Makefile.am	26 May 2003 20:09:51 -0000
++++ ksmserver/Makefile.am	1 Jun 2003 14:31:56 -0000	1.7
 @@ -20,18 +20,28 @@
  INCLUDES=  $(all_includes)
  
@@ -2058,8 +1951,6 @@ diff -N konsole/konsole/stub_main.cpp
  {
      sanity_check(argc, argv);
  
-RCS file: ksmserver/stub_main.cpp
-diff -N ksmserver/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ ksmserver/stub_main.cpp	26 Nov 2002 21:00:54 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -2123,7 +2014,7 @@ diff -N ksmserver/stub_main.cpp
  <html>
  <p>
 --- kwin/Makefile.am	10 Jul 2002 03:24:51 -0000	1.1.1.2
-+++ kwin/Makefile.am	26 May 2003 20:09:51 -0000
++++ kwin/Makefile.am	1 Jun 2003 14:31:57 -0000	1.7
 @@ -3,14 +3,21 @@
  SUBDIRS = . kcmkwin pics clients
  
@@ -2314,7 +2205,7 @@ diff -N ksmserver/stub_main.cpp
  METASOURCES               = AUTO
  
 --- kwin/kcmkwin/kwindecoration/Makefile.am	1 Oct 2002 02:37:35 -0000	1.1.1.3
-+++ kwin/kcmkwin/kwindecoration/Makefile.am	26 May 2003 20:09:51 -0000
++++ kwin/kcmkwin/kwindecoration/Makefile.am	1 Jun 2003 14:31:57 -0000	1.2
 @@ -5,8 +5,7 @@
  kcm_kwindecoration_la_SOURCES = kwindecoration.cpp buttons.cpp kwindecorationIface.skel
  noinst_HEADERS = kwindecoration.h kwindecorationIface.h buttons.h
@@ -2337,7 +2228,7 @@ diff -N ksmserver/stub_main.cpp
  messages:
  	$(XGETTEXT) *.cpp -o $(podir)/kcmkwm.pot
 --- kxkb/Makefile.am	29 Oct 2002 03:07:04 -0000	1.1.1.5
-+++ kxkb/Makefile.am	26 May 2003 20:09:51 -0000
++++ kxkb/Makefile.am	1 Jun 2003 14:31:57 -0000	1.12
 @@ -7,20 +7,30 @@
  
  bin_PROGRAMS = kxkb
@@ -2394,8 +2285,6 @@ diff -N ksmserver/stub_main.cpp
  {
      KAboutData about("kxkb", I18N_NOOP("KDE Keyboard Tool"), "0.8",
                       DESCRIPTION, KAboutData::License_LGPL,
-RCS file: kxkb/stub_main.cpp
-diff -N kxkb/stub_main.cpp
 --- /dev/null	1 Jan 1970 00:00:00 -0000
 +++ kxkb/stub_main.cpp	26 Nov 2002 21:00:56 -0000	1.1
 @@ -0,0 +1,28 @@
@@ -2472,3 +2361,60 @@ diff -N kxkb/stub_main.cpp
          paths.append("/usr/lib/mozilla/plugins");
          paths.append("$MOZILLA_HOME/plugins");
          config->writeEntry( "scanPaths", paths );
+--- startkde	19 Jul 2003 03:27:12 -0000	1.1.1.9
++++ startkde	19 Jul 2003 03:50:11 -0000	1.14
+@@ -24,6 +24,10 @@
+ #   2) everything in $KDEDIR/share/autostart (kdesktop, kicker, etc.)
+ #   3) the rest of the session.
+ 
++# we have to unset this for Darwin since it will screw up KDE's dynamic-loading
++unset DYLD_FORCE_FLAT_NAMESPACE
++test -d "@PREFIX@" && export PATH="@PREFIX@/bin:${PATH}"
++
+ # The user's personal KDE directory is usually ~/.kde, but this setting
+ # may be overridden by setting KDEHOME.
+ 
+@@ -113,6 +117,11 @@
+     export GS_LIB
+ fi
+ 
++# if we're in Apple's X11 and the native window manager is available, use that
++if test -z "$KDEWM" && test -x /usr/X11R6/bin/quartz-wm; then
++    KDEWM="/usr/X11R6/bin/quartz-wm"
++fi
++
+ # Link "tmp" resource to directory in /tmp
+ # Creates a directory /tmp/kde-$USER and links $KDEHOME/tmp-$HOSTNAME to it.
+ lnusertemp tmp >/dev/null
+@@ -131,7 +140,11 @@
+     # start only dcopserver, don't start whole kdeinit (takes too long)
+     echo 'startkde: Running kpersonalizer...'  1>&2
+     dcopserver
+-    kwin &
++    if test -n "$KDEWM"; then
++        $KDEWM &
++    else
++        kwin &
++    fi
+     kpersonalizer --before-session
+     # handle kpersonalizer restarts (language change)
+     while test $? -eq 1; do
+@@ -142,7 +155,6 @@
+     sleep 1
+ fi
+ 
+-# the splashscreen and progress indicator
+ ksplash
+ 
+ # We set LD_BIND_NOW to increase the efficiency of kdeinit.
+@@ -153,6 +165,10 @@
+   echo 'startkde: Could not start kdeinit. Check your installation.'  1>&2
+   xmessage -geometry 500x100 "Could not start kdeinit. Check your installation."
+ fi
++
++# fix up KDE themes
++echo 'startkde: updating theme cache'
++kwrapper kinstalltheme
+ 
+ # finally, give the session control to the session manager
+ # if the KDEWM environment variable has been set, then it will be used as KDE's
