new version

diff --git a/10.4/unstable/main/finkinfo/editors/tea.patch b/10.4/unstable/main/finkinfo/editors/tea.patch
--- a/10.4/unstable/main/finkinfo/editors/tea.patch
+++ b/10.4/unstable/main/finkinfo/editors/tea.patch
@@ -1,7 +1,37 @@
-diff -ruN tea-14.3.0/src/rox_strings.c tea-14.3.0-patched/src/rox_strings.c
---- tea-14.3.0/src/rox_strings.c	2006-10-04 04:52:08.000000000 -0700
-+++ tea-14.3.0-patched/src/rox_strings.c	2007-08-05 20:10:19.000000000 -0700
-@@ -32,6 +32,7 @@
+diff -Nurd -x'*~' tea-17.5.4.orig/configure tea-17.5.4/configure
+--- tea-17.5.4.orig/configure	2008-01-12 08:20:40.000000000 -0500
++++ tea-17.5.4/configure	2008-02-27 01:16:59.000000000 -0500
+@@ -5798,6 +5798,7 @@
+ 		echo "yes"
+ 	else
+ 		echo "no"
++		exit 1
+ 	fi
+ 
+ else
+@@ -6246,7 +6247,7 @@
+ 	echo -n "checking for gtk+-unix-print-2.0... "
+ 	if pkg-config --exists gtk+-unix-print-2.0  ; then
+ 		LIBS="$LIBS `pkg-config --libs gtk+-unix-print-2.0 `"
+-		CFLAGS="$CFLAGS `pkg-config --cflags gtk+-unix-print-2.0 `"
++		CPPFLAGS="$CPPFLAGS `pkg-config --cflags gtk+-unix-print-2.0 `"
+ 		echo "yes"
+ 
+ cat >>confdefs.h <<\_ACEOF
+@@ -6287,7 +6288,8 @@
+ 	echo "yes"
+ 
+ else
+-	echo -n "GtkSourceView2 not found, now we search GtkSourceView1"
++	echo -n "Fink package enforces GtkSourceView2 usage, not falling back to  GtkSourceView1"
++	exit 1
+ 
+ 	if pkg-config --exists gtksourceview-1.0 ; then
+ 		LIBS="$LIBS `pkg-config --libs gtksourceview-1.0`"
+diff -Nurd -x'*~' tea-17.5.4.orig/src/rox_strings.c tea-17.5.4/src/rox_strings.c
+--- tea-17.5.4.orig/src/rox_strings.c	2008-01-09 19:19:17.000000000 -0500
++++ tea-17.5.4/src/rox_strings.c	2008-02-27 00:50:01.000000000 -0500
+@@ -34,6 +34,7 @@
  
  #include <ctype.h>
  #include <sys/stat.h>
