Patch from svn to allow building on 10.4

diff --git a/10.4/unstable/main/finkinfo/editors/texmacs.patch b/10.4/unstable/main/finkinfo/editors/texmacs.patch
--- a/10.4/unstable/main/finkinfo/editors/texmacs.patch
+++ b/10.4/unstable/main/finkinfo/editors/texmacs.patch
@@ -1,80 +1,127 @@
-diff -ur TeXmacs-1.0.6.9-src/src/makefile.in TeXmacs-1.0.6.9-src.corr/src/makefile.in
---- TeXmacs-1.0.6.9-src/src/makefile.in	2007-02-11 16:39:53.000000000 +0100
-+++ TeXmacs-1.0.6.9-src.corr/src/makefile.in	2007-04-09 09:59:55.000000000 +0200
-@@ -120,7 +120,7 @@
- deps_incl = $(call incl_flags,System System/Boot System/Classes System/Files System/Link System/Misc Classes/Abstract Classes/Atomic Classes/Compound Classes/Mathematics Data/Drd Data/String Data/Tree Data/Convert Resource Plugins Window Style/Memorizer Typeset Edit Texmacs Guile)
+--- trunk/src/configure	2009/04/16 22:06:09	2593
++++ trunk/src/configure	2009/05/01 20:06:57	2643
+@@ -696,6 +696,7 @@
+ host_vendor
+ host_os
+ CONFIG_EXPERIMENTAL
++CONFIG_MACOS
+ QMAKE
+ MOC
+ UIC
+@@ -722,7 +723,6 @@
+ CONFIG_CXXDIALECT
+ CONFIG_OS
+ CONFIG_OS_SUFFIX
+-CONFIG_MACOS
+ CONFIG_CXXWARNING
+ CONFIG_CXXTEMPLATE
+ CONFIG_CXXOPTIMIZE
+@@ -1347,6 +1347,7 @@
+   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+   --disable-fastalloc     omit fast allocator for small objects
+   --enable-experimental   support new style rewriting code
++  --enable-macosx-extensions   support new style rewriting code
+   --enable-qt             replace X11 by Qt interface
+   --enable-cocoa          replace X11 by Cocoa interface
+   --enable-debug=ARG      install a debugging enable executable -ggdb
+@@ -8247,7 +8248,6 @@
+   *apple*darwin*)
+     echo "$ac_t""final adjustments for a MacOS host" 1>&6
+     CONFIG_OS="MACOS"
+-    CONFIG_MACOS="MacOS"
+     CONFIG_CXXFLAGS="-I${prefix}/include"
+     CONFIG_BSHARED=""
+     CONFIG_BFLAGS="-framework Cocoa"
+@@ -8430,6 +8430,41 @@
  
- deps_flags = $(deps_incl)\
-- $(CPPFLAGS) $(CXXIMLIB2) $(CXXFREETYPE) $(CXXICONV) $(CXXGUILE) \
-+ $(CPPFLAGS) $(CXXFREETYPE) $(CXXIMLIB2) $(CXXICONV) $(CXXGUILE) \
-  -I$(tmsrc)/include $(CXXXWINDOW)
- # we should use -I- to separate local includes from system includes, but
- # headers of guile 1.6.0 use includes in quotes with names relative to the
-@@ -174,11 +174,13 @@
- %.o: %.cpp # Disable implicit compilation rule
  
- cxx_flags    = $(strip $(CXX) $(1) -c $< -o $@)
--cxx_incl     = $(call cxx_flags,$(1) $(CXXIMLIB2) $(CXXFREETYPE) $(CXXICONV) \
-+cxx_incl     = $(call cxx_flags,$(1) $(CXXFREETYPE) $(CXXIMLIB2) $(CXXICONV) \
-   $(CXXGUILE) $(CPPFLAGS) $(CXXFLAGS)) 
-+cxxx_incl    = $(call cxx_flags,$(1) $(CXXFREETYPE) $(CXXIMLIB2) $(CXXICONV) \
-+  $(CXXGUILE) $(CPPFLAGS) $(CXXFLAGS) $(CXXXWINDOW))
+ #--------------------------------------------------------------------
++# MacOS X extensions (spellchecker, image loading)
++#--------------------------------------------------------------------
++
++# Check whether --enable-macosx-extensions was given.
++if test "${enable_macosx_extensions+set}" = set; then
++  enableval=$enable_macosx_extensions;
++else
++  enable_macosx_extensions="no"
++fi
++
++case "$enable_macosx_extensions" in
++    yes)
++	{ echo "$as_me:$LINENO: result: enabling Mac OSX extensions" >&5
++echo "${ECHO_T}enabling Mac OSX extensions" >&6; }
++
++cat >>confdefs.h <<\_ACEOF
++#define MACOSX_EXTENSIONS 1
++_ACEOF
++
++        CONFIG_MACOS="MacOS"
++        ;;
++    no)
++	{ echo "$as_me:$LINENO: result: disabling Mac OSX extensions" >&5
++echo "${ECHO_T}disabling Mac OSX extensions" >&6; }
++        CONFIG_MACOS=""
++	;;
++    *)
++	{ { echo "$as_me:$LINENO: error: bad option --enable-macosx-extensions=$enable_macosx_extensions" >&5
++echo "$as_me: error: bad option --enable-macosx-extensions=$enable_macosx_extensions" >&2;}
++   { (exit 1); exit 1; }; }
++	;;
++esac
++
++
++#--------------------------------------------------------------------
+ # Gui selection
+ #--------------------------------------------------------------------
  
- $(system_obj): Objects/%.o: %.cpp
--	$(call cxx_incl,$(system_incl) -I$(tmsrc)/include)
-+	$(call cxxx_incl,$(system_incl) -I$(tmsrc)/include)
- $(classes_obj): Objects/%.o: %.cpp
- 	$(call cxx_incl,$(classes_incl))
- $(data_obj): Objects/%.o: %.cpp
-@@ -190,7 +192,7 @@
- $(resource_obj): Objects/%.o: %.cpp
- 	$(call cxx_incl,$(resource_incl))
- $(plugins_obj): Objects/%.o: %.cpp
--	$(call cxx_incl,$(plugins_incl) $(CXXXWINDOW))
-+	$(call cxxx_incl,$(plugins_incl))
- $(texmacs_obj): Objects/%.o: %.cpp
- 	$(call cxx_incl,$(texmacs_incl))
- $(typeset_obj): Objects/%.o: %.cpp
-@@ -200,7 +202,7 @@
- $(window_obj): Objects/%.o: %.cpp
- 	$(call cxx_incl,$(window_incl))
- $(x_window_obj): Objects/%.o: %.cpp
--	$(call cxx_incl,$(window_incl) $(CXXXWINDOW))
-+	$(call cxxx_incl,$(window_incl))
+@@ -9334,7 +9369,6 @@
  
- ###############################################################################
- # Make editor
-@@ -257,8 +259,8 @@
- TEXMACS_objects := $(strip $(call uses,system classes data resource plugins\
-  window style typeset edit glue texmacs))
  
--link_options:=-L$(tmsrc)/lib -lm $(LDPATH) $(LDXWINDOW) \
--  $(LDGUILE) $(LDIMLIB2) $(LDFREETYPE) $(LDICONV) $(LDDL)
-+link_options:=-L$(tmsrc)/lib -lm $(LDPATH) $(LDFREETYPE) $(LDXWINDOW) \
-+  $(LDGUILE) $(LDIMLIB2) $(LDICONV) $(LDDL)
  
- $(tmsrc)/bin/texmacs.bin: Objects/texmacs-$(link).bin
- 	$(CP) $^ $@
---- TeXmacs-1.0.6-src/plugins/shell/src/tm_shell.cpp	2005-12-02 19:08:07.000000000 +0100
-+++ TeXmacs-1.0.6-src.corr/plugins/shell/src/tm_shell.cpp	2005-12-23 19:04:18.000000000 +0100
-@@ -19,6 +19,7 @@
- #include <unistd.h>
- #include <sys/time.h>
- #include <sys/wait.h>
-+#include <sys/socket.h>
- using namespace std;
+-
+ #--------------------------------------------------------------------
+ # Default paths for installation
+ #--------------------------------------------------------------------
+@@ -10167,6 +10201,7 @@
+ host_vendor!$host_vendor$ac_delim
+ host_os!$host_os$ac_delim
+ CONFIG_EXPERIMENTAL!$CONFIG_EXPERIMENTAL$ac_delim
++CONFIG_MACOS!$CONFIG_MACOS$ac_delim
+ QMAKE!$QMAKE$ac_delim
+ MOC!$MOC$ac_delim
+ UIC!$UIC$ac_delim
+@@ -10179,7 +10214,6 @@
+ QT_CXXFLAGS!$QT_CXXFLAGS$ac_delim
+ QT_INCPATH!$QT_INCPATH$ac_delim
+ QT_CPPFLAGS!$QT_CPPFLAGS$ac_delim
+-QT_LFLAGS!$QT_LFLAGS$ac_delim
+ _ACEOF
  
- typedef char* charp;
-@@ -158,8 +159,10 @@
-   setenv ("PS1", "tmshell$ ", true);
-   cout << DATA_BEGIN << "verbatim:";
-   cout << "Shell session inside TeXmacs";
--  pipe (tochild);
--  pipe (fromchild);
-+//  pipe (tochild);
-+//  pipe (fromchild);
-+  socketpair (AF_UNIX, SOCK_STREAM, PF_UNSPEC, tochild);
-+  socketpair (AF_UNIX, SOCK_STREAM, PF_UNSPEC, fromchild);
-   pid= fork ();
-   if (pid==0) { // the child
-     dup2 (tochild [IN], STDIN);
+   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
+@@ -10221,6 +10255,7 @@
+ ac_delim='%!_!# '
+ for ac_last_try in false false false false false :; do
+   cat >conf$$subs.sed <<_ACEOF
++QT_LFLAGS!$QT_LFLAGS$ac_delim
+ QT_LDFLAGS!$QT_LDFLAGS$ac_delim
+ QT_LIBS!$QT_LIBS$ac_delim
+ X11_CFLAGS!$X11_CFLAGS$ac_delim
+@@ -10234,7 +10269,6 @@
+ CONFIG_CXXDIALECT!$CONFIG_CXXDIALECT$ac_delim
+ CONFIG_OS!$CONFIG_OS$ac_delim
+ CONFIG_OS_SUFFIX!$CONFIG_OS_SUFFIX$ac_delim
+-CONFIG_MACOS!$CONFIG_MACOS$ac_delim
+ CONFIG_CXXWARNING!$CONFIG_CXXWARNING$ac_delim
+ CONFIG_CXXTEMPLATE!$CONFIG_CXXTEMPLATE$ac_delim
+ CONFIG_CXXOPTIMIZE!$CONFIG_CXXOPTIMIZE$ac_delim
+--- trunk/src/src/Edit/Replace/edit_spell.cpp	2009/04/17 07:30:31	2595
++++ trunk/src/src/Edit/Replace/edit_spell.cpp	2009/05/01 20:06:57	2643
+@@ -13,7 +13,7 @@
+ #include "Replace/edit_replace.hpp"
+ #include "Interface/edit_interface.hpp"
+ 
+-#ifdef OS_MACOS
++#ifdef MACOSX_EXTENSIONS
+ #include "MacOS/mac_spellservice.h"
+ #define ispell_start mac_spell_start
+ #define ispell_check mac_spell_check
