new upstream dbus and dbus-glib

diff --git a/10.4/unstable/main/finkinfo/libs/dbus1.3-shlibs.patch b/10.4/unstable/main/finkinfo/libs/dbus1.3-shlibs.patch
--- a/10.4/unstable/main/finkinfo/libs/dbus1.3-shlibs.patch
+++ b/10.4/unstable/main/finkinfo/libs/dbus1.3-shlibs.patch
@@ -1,6 +1,6 @@
-diff -Nurd dbus-1.2.16/README.launchd dbus-1.2.16-new/README.launchd
---- dbus-1.2.16/README.launchd	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.2.16-new/README.launchd	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/README.launchd dbus-1.2.24-new/README.launchd
+--- dbus-1.2.24/README.launchd	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.2.24-new/README.launchd	2010-10-02 12:27:47.000000000 -0400
 @@ -0,0 +1,61 @@
 +Launchd[1,2] replaces init, inetd and cron on Mac OS X since 10.4 "Tiger".
 +dbus uses this service to provide a common session bus address for each user
@@ -63,9 +63,9 @@ diff -Nurd dbus-1.2.16/README.launchd dbus-1.2.16-new/README.launchd
 +
 +On the client side, the envvar DBUS_SESSION_BUS_ADDRESS can be normally used
 +but if it's not set, launchd is queried for the session bus socket.
-diff -Nurd dbus-1.2.16/bus/Makefile.am dbus-1.2.16-new/bus/Makefile.am
---- dbus-1.2.16/bus/Makefile.am	2009-07-13 12:23:26.000000000 -0400
-+++ dbus-1.2.16-new/bus/Makefile.am	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/bus/Makefile.am dbus-1.2.24-new/bus/Makefile.am
+--- dbus-1.2.24/bus/Makefile.am	2010-03-23 15:01:27.000000000 -0400
++++ dbus-1.2.24-new/bus/Makefile.am	2010-10-02 12:27:47.000000000 -0400
 @@ -9,12 +9,18 @@
  
  CONFIG_IN_FILES=				\
@@ -101,9 +101,9 @@ diff -Nurd dbus-1.2.16/bus/Makefile.am dbus-1.2.16-new/bus/Makefile.am
  	fi
  
  #### Init scripts fun
-diff -Nurd dbus-1.2.16/bus/org.freedesktop.dbus-session.plist.in dbus-1.2.16-new/bus/org.freedesktop.dbus-session.plist.in
---- dbus-1.2.16/bus/org.freedesktop.dbus-session.plist.in	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.2.16-new/bus/org.freedesktop.dbus-session.plist.in	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/bus/org.freedesktop.dbus-session.plist.in dbus-1.2.24-new/bus/org.freedesktop.dbus-session.plist.in
+--- dbus-1.2.24/bus/org.freedesktop.dbus-session.plist.in	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.2.24-new/bus/org.freedesktop.dbus-session.plist.in	2010-10-02 12:27:47.000000000 -0400
 @@ -0,0 +1,31 @@
 +<?xml version="1.0" encoding="UTF-8"?>
 +<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
@@ -136,9 +136,9 @@ diff -Nurd dbus-1.2.16/bus/org.freedesktop.dbus-session.plist.in dbus-1.2.16-new
 +	</dict>
 +</dict>
 +</plist>
-diff -Nurd dbus-1.2.16/bus/session.conf.in dbus-1.2.16-new/bus/session.conf.in
---- dbus-1.2.16/bus/session.conf.in	2009-07-14 15:38:33.000000000 -0400
-+++ dbus-1.2.16-new/bus/session.conf.in	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/bus/session.conf.in dbus-1.2.24-new/bus/session.conf.in
+--- dbus-1.2.24/bus/session.conf.in	2010-03-23 15:01:27.000000000 -0400
++++ dbus-1.2.24-new/bus/session.conf.in	2010-10-02 12:27:47.000000000 -0400
 @@ -12,7 +12,7 @@
         the behavior of child processes. -->
    <keep_umask/>
@@ -148,10 +148,10 @@ diff -Nurd dbus-1.2.16/bus/session.conf.in dbus-1.2.16-new/bus/session.conf.in
  
    <standard_session_servicedirs />
  
-diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
---- dbus-1.2.16/configure.in	2009-07-14 15:42:51.000000000 -0400
-+++ dbus-1.2.16-new/configure.in	2009-09-05 08:56:49.000000000 -0400
-@@ -78,6 +78,7 @@
+diff -Nurd dbus-1.2.24/configure.in dbus-1.2.24-new/configure.in
+--- dbus-1.2.24/configure.in	2010-03-23 15:10:49.000000000 -0400
++++ dbus-1.2.24-new/configure.in	2010-10-02 12:27:47.000000000 -0400
+@@ -80,6 +80,7 @@
  AC_ARG_ENABLE(kqueue, AS_HELP_STRING([--enable-kqueue],[build with kqueue support]),enable_kqueue=$enableval,enable_kqueue=auto)
  AC_ARG_ENABLE(console-owner-file, AS_HELP_STRING([--enable-console-owner-file],[enable console owner file]),enable_console_owner_file=$enableval,enable_console_owner_file=auto)
  AC_ARG_ENABLE(userdb-cache, AS_HELP_STRING([--enable-userdb-cache],[build with userdb-cache support]),enable_userdb_cache=$enableval,enable_userdb_cache=yes)
@@ -159,7 +159,7 @@ diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
  
  AC_ARG_WITH(xml, AS_HELP_STRING([--with-xml=[libxml/expat]],[XML library to use]))
  AC_ARG_WITH(init-scripts, AS_HELP_STRING([--with-init-scripts=[redhat]],[Style of init scripts to install]))
-@@ -87,6 +88,7 @@
+@@ -89,6 +90,7 @@
  AC_ARG_WITH(system-socket, AS_HELP_STRING([--with-system-socket=[filename]],[UNIX domain socket for systemwide daemon]))
  AC_ARG_WITH(console-auth-dir, AS_HELP_STRING([--with-console-auth-dir=[dirname]],[directory to check for console ownerhip]))
  AC_ARG_WITH(console-owner-file, AS_HELP_STRING([--with-console-owner-file=[filename]],[file whose owner determines current console owner]))
@@ -167,7 +167,7 @@ diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
  AC_ARG_WITH(dbus_user, AS_HELP_STRING([--with-dbus-user=<user>],[User for running the DBUS daemon (messagebus)]))
  AC_ARG_WITH(dbus_daemondir, AS_HELP_STRING([--with-dbus-daemondir=[dirname]],[Directory for installing the DBUS daemon]))
  
-@@ -820,6 +822,38 @@
+@@ -868,6 +870,38 @@
  
  AM_CONDITIONAL(DBUS_BUS_ENABLE_KQUEUE, test x$have_kqueue = xyes) 
  
@@ -206,7 +206,7 @@ diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
  dnl console owner file
  if test x$enable_console_owner_file = xno ; then
      have_console_owner_file=no;
-@@ -1279,6 +1313,14 @@
+@@ -1313,6 +1347,14 @@
  AC_SUBST(DBUS_SYSTEM_BUS_DEFAULT_ADDRESS)
  AC_DEFINE_UNQUOTED(DBUS_SYSTEM_BUS_DEFAULT_ADDRESS, "$DBUS_SYSTEM_BUS_DEFAULT_ADDRESS",[The default D-Bus address of the system bus])
  
@@ -221,7 +221,7 @@ diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
  #### Set up the pid file
  if ! test -z "$with_system_pid_file"; then
     DBUS_SYSTEM_PID_FILE=$with_system_pid_file
-@@ -1403,7 +1445,6 @@
+@@ -1437,7 +1479,6 @@
     DBUS_SESSION_SOCKET_DIR=$DEFAULT_SOCKET_DIR
  fi
  AC_DEFINE_UNQUOTED(DBUS_SESSION_SOCKET_DIR, "$DBUS_SESSION_SOCKET_DIR", [Where per-session bus puts its sockets])
@@ -229,7 +229,7 @@ diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
  
  AC_DEFINE_UNQUOTED(DBUS_UNIX, "1", [Defined on UNIX and Linux systems and not on Windows])
  
-@@ -1425,6 +1466,7 @@
+@@ -1459,6 +1500,7 @@
  bus/system.conf
  bus/session.conf
  bus/messagebus
@@ -237,7 +237,7 @@ diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
  bus/rc.messagebus
  bus/dbus-daemon.1
  Makefile
-@@ -1492,6 +1534,7 @@
+@@ -1527,6 +1569,7 @@
          Building Doxygen docs:    ${enable_doxygen_docs}
          Building XML docs:        ${enable_xml_docs}
          Building cache support:   ${enable_userdb_cache}
@@ -245,7 +245,7 @@ diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
          Gettext libs (empty OK):  ${INTLLIBS}
          Using XML parser:         ${with_xml}
          Init scripts style:       ${with_init_scripts}
-@@ -1505,8 +1548,11 @@
+@@ -1540,8 +1583,11 @@
          Console owner file path:  ${DBUS_CONSOLE_OWNER_FILE}
  	System bus user:          ${DBUS_USER}
  	Session bus services dir: ${EXPANDED_DATADIR}/dbus-1/services
@@ -259,9 +259,9 @@ diff -Nurd dbus-1.2.16/configure.in dbus-1.2.16-new/configure.in
  
  if test x$enable_tests = xyes; then
          echo "NOTE: building with unit tests increases the size of the installed library and renders it insecure."
-diff -Nurd dbus-1.2.16/dbus/Makefile.am dbus-1.2.16-new/dbus/Makefile.am
---- dbus-1.2.16/dbus/Makefile.am	2009-07-13 12:23:26.000000000 -0400
-+++ dbus-1.2.16-new/dbus/Makefile.am	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus/Makefile.am dbus-1.2.24-new/dbus/Makefile.am
+--- dbus-1.2.24/dbus/Makefile.am	2010-03-23 15:01:27.000000000 -0400
++++ dbus-1.2.24-new/dbus/Makefile.am	2010-10-02 12:27:47.000000000 -0400
 @@ -70,6 +70,8 @@
  	dbus-server.c				\
  	dbus-server-debug-pipe.c		\
@@ -271,9 +271,9 @@ diff -Nurd dbus-1.2.16/dbus/Makefile.am dbus-1.2.16-new/dbus/Makefile.am
  	dbus-server-protected.h			\
  	dbus-server-socket.c			\
  	dbus-server-socket.h			\
-diff -Nurd dbus-1.2.16/dbus/dbus-server-launchd.c dbus-1.2.16-new/dbus/dbus-server-launchd.c
---- dbus-1.2.16/dbus/dbus-server-launchd.c	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.2.16-new/dbus/dbus-server-launchd.c	2009-09-05 10:57:51.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus/dbus-server-launchd.c dbus-1.2.24-new/dbus/dbus-server-launchd.c
+--- dbus-1.2.24/dbus/dbus-server-launchd.c	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.2.24-new/dbus/dbus-server-launchd.c	2010-10-02 12:27:47.000000000 -0400
 @@ -0,0 +1,186 @@
 +/* dbus-server-launchd.c Server methods for interacting with launchd.
 + * Copyright (C) 2007, Tanner Lovelace <lovelace@wayfarer.org>
@@ -461,9 +461,9 @@ diff -Nurd dbus-1.2.16/dbus/dbus-server-launchd.c dbus-1.2.16-new/dbus/dbus-serv
 +  }
 +
 +/** @} */
-diff -Nurd dbus-1.2.16/dbus/dbus-server-launchd.h dbus-1.2.16-new/dbus/dbus-server-launchd.h
---- dbus-1.2.16/dbus/dbus-server-launchd.h	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.2.16-new/dbus/dbus-server-launchd.h	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus/dbus-server-launchd.h dbus-1.2.24-new/dbus/dbus-server-launchd.h
+--- dbus-1.2.24/dbus/dbus-server-launchd.h	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.2.24-new/dbus/dbus-server-launchd.h	2010-10-02 12:27:47.000000000 -0400
 @@ -0,0 +1,35 @@
 +/* dbus-server-launchd.h Server methods for interacting with launchd.
 +* Copyright (C) 2008, Benjamin Reed <rangerrick@befunk.com>
@@ -500,9 +500,9 @@ diff -Nurd dbus-1.2.16/dbus/dbus-server-launchd.h dbus-1.2.16-new/dbus/dbus-serv
 +
 +DBUS_END_DECLS
 +#endif /* DBUS_SERVER_LAUNCHD_H */
-diff -Nurd dbus-1.2.16/dbus/dbus-server-unix.c dbus-1.2.16-new/dbus/dbus-server-unix.c
---- dbus-1.2.16/dbus/dbus-server-unix.c	2009-07-14 15:39:47.000000000 -0400
-+++ dbus-1.2.16-new/dbus/dbus-server-unix.c	2009-09-05 10:57:51.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus/dbus-server-unix.c dbus-1.2.24-new/dbus/dbus-server-unix.c
+--- dbus-1.2.24/dbus/dbus-server-unix.c	2010-03-23 15:01:27.000000000 -0400
++++ dbus-1.2.24-new/dbus/dbus-server-unix.c	2010-10-02 12:27:47.000000000 -0400
 @@ -21,9 +21,11 @@
   *
   */
@@ -543,9 +543,9 @@ diff -Nurd dbus-1.2.16/dbus/dbus-server-unix.c dbus-1.2.16-new/dbus/dbus-server-
    else
      {
        /* If we don't handle the method, we return NULL with the
-diff -Nurd dbus-1.2.16/dbus/dbus-spawn.c dbus-1.2.16-new/dbus/dbus-spawn.c
---- dbus-1.2.16/dbus/dbus-spawn.c	2009-07-14 15:39:47.000000000 -0400
-+++ dbus-1.2.16-new/dbus/dbus-spawn.c	2009-09-05 10:57:51.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus/dbus-spawn.c dbus-1.2.24-new/dbus/dbus-spawn.c
+--- dbus-1.2.24/dbus/dbus-spawn.c	2010-03-23 15:01:27.000000000 -0400
++++ dbus-1.2.24-new/dbus/dbus-spawn.c	2010-10-02 12:27:47.000000000 -0400
 @@ -36,6 +36,11 @@
  #include <errno.h>
  #endif
@@ -730,9 +730,9 @@ diff -Nurd dbus-1.2.16/dbus/dbus-spawn.c dbus-1.2.16-new/dbus/dbus-spawn.c
    execve (argv[0], argv, envp);
    
    /* Exec failed */
-diff -Nurd dbus-1.2.16/dbus/dbus-sysdeps-unix.c dbus-1.2.16-new/dbus/dbus-sysdeps-unix.c
---- dbus-1.2.16/dbus/dbus-sysdeps-unix.c	2009-07-14 15:42:38.000000000 -0400
-+++ dbus-1.2.16-new/dbus/dbus-sysdeps-unix.c	2009-09-05 11:03:28.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus/dbus-sysdeps-unix.c dbus-1.2.24-new/dbus/dbus-sysdeps-unix.c
+--- dbus-1.2.24/dbus/dbus-sysdeps-unix.c	2010-03-23 15:01:27.000000000 -0400
++++ dbus-1.2.24-new/dbus/dbus-sysdeps-unix.c	2010-10-02 12:27:47.000000000 -0400
 @@ -1643,7 +1643,7 @@
            {
              if (errno == 0)
@@ -742,7 +742,7 @@ diff -Nurd dbus-1.2.16/dbus/dbus-sysdeps-unix.c dbus-1.2.16-new/dbus/dbus-sysdep
                              username_c, buf_count, buf_count);
                } 
              else
-@@ -3168,6 +3168,104 @@
+@@ -3179,6 +3179,104 @@
  #define DBUS_UNIX_STANDARD_SYSTEM_SERVICEDIR "/dbus-1/system-services"
  
  /**
@@ -847,7 +847,7 @@ diff -Nurd dbus-1.2.16/dbus/dbus-sysdeps-unix.c dbus-1.2.16-new/dbus/dbus-sysdep
   * Determines the address of the session bus by querying a
   * platform-specific method.  
   *
-@@ -3191,12 +3289,17 @@
+@@ -3202,12 +3300,17 @@
                                DBusString  *address,
                                DBusError   *error)
  {
@@ -865,9 +865,9 @@ diff -Nurd dbus-1.2.16/dbus/dbus-sysdeps-unix.c dbus-1.2.16-new/dbus/dbus-sysdep
  }
  
  /**
-diff -Nurd dbus-1.2.16/dbus/dbus-sysdeps-unix.h dbus-1.2.16-new/dbus/dbus-sysdeps-unix.h
---- dbus-1.2.16/dbus/dbus-sysdeps-unix.h	2009-07-14 15:39:47.000000000 -0400
-+++ dbus-1.2.16-new/dbus/dbus-sysdeps-unix.h	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus/dbus-sysdeps-unix.h dbus-1.2.24-new/dbus/dbus-sysdeps-unix.h
+--- dbus-1.2.24/dbus/dbus-sysdeps-unix.h	2010-03-23 15:01:27.000000000 -0400
++++ dbus-1.2.24-new/dbus/dbus-sysdeps-unix.h	2010-10-02 12:27:47.000000000 -0400
 @@ -77,6 +77,10 @@
  dbus_bool_t _dbus_send_credentials (int              server_fd,
                                      DBusError       *error);
@@ -879,9 +879,9 @@ diff -Nurd dbus-1.2.16/dbus/dbus-sysdeps-unix.h dbus-1.2.16-new/dbus/dbus-sysdep
  /** Information about a UNIX user */
  typedef struct DBusUserInfo  DBusUserInfo;
  /** Information about a UNIX group */
-diff -Nurd dbus-1.2.16/dbus/dbus-transport-unix.c dbus-1.2.16-new/dbus/dbus-transport-unix.c
---- dbus-1.2.16/dbus/dbus-transport-unix.c	2009-07-14 15:39:47.000000000 -0400
-+++ dbus-1.2.16-new/dbus/dbus-transport-unix.c	2009-09-05 10:57:51.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus/dbus-transport-unix.c dbus-1.2.24-new/dbus/dbus-transport-unix.c
+--- dbus-1.2.24/dbus/dbus-transport-unix.c	2010-03-23 15:01:27.000000000 -0400
++++ dbus-1.2.24-new/dbus/dbus-transport-unix.c	2010-10-02 12:27:47.000000000 -0400
 @@ -171,6 +171,57 @@
            return DBUS_TRANSPORT_OPEN_OK;
          }      
@@ -940,9 +940,9 @@ diff -Nurd dbus-1.2.16/dbus/dbus-transport-unix.c dbus-1.2.16-new/dbus/dbus-tran
    else
      {
        _DBUS_ASSERT_ERROR_IS_CLEAR (error);
-diff -Nurd dbus-1.2.16/dbus-xinitrc.sh dbus-1.2.16-new/dbus-xinitrc.sh
---- dbus-1.2.16/dbus-xinitrc.sh	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.2.16-new/dbus-xinitrc.sh	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/dbus-xinitrc.sh dbus-1.2.24-new/dbus-xinitrc.sh
+--- dbus-1.2.24/dbus-xinitrc.sh	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.2.24-new/dbus-xinitrc.sh	2010-10-02 12:27:47.000000000 -0400
 @@ -0,0 +1,8 @@
 +#!/bin/sh
 +
@@ -952,9 +952,9 @@ diff -Nurd dbus-1.2.16/dbus-xinitrc.sh dbus-1.2.16-new/dbus-xinitrc.sh
 +		TMPDIR=/tmp launchctl setenv DISPLAY "$DISPLAY"
 +	fi
 +fi
-diff -Nurd dbus-1.2.16/start-session-bus.sh dbus-1.2.16-new/start-session-bus.sh
---- dbus-1.2.16/start-session-bus.sh	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.2.16-new/start-session-bus.sh	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/start-session-bus.sh dbus-1.2.24-new/start-session-bus.sh
+--- dbus-1.2.24/start-session-bus.sh	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.2.24-new/start-session-bus.sh	2010-10-02 12:27:47.000000000 -0400
 @@ -0,0 +1,7 @@
 +#!/bin/sh -e
 +
@@ -963,9 +963,9 @@ diff -Nurd dbus-1.2.16/start-session-bus.sh dbus-1.2.16-new/start-session-bus.sh
 +fi
 +
 +exit 0
-diff -Nurd dbus-1.2.16/start-system-bus.sh dbus-1.2.16-new/start-system-bus.sh
---- dbus-1.2.16/start-system-bus.sh	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.2.16-new/start-system-bus.sh	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/start-system-bus.sh dbus-1.2.24-new/start-system-bus.sh
+--- dbus-1.2.24/start-system-bus.sh	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.2.24-new/start-system-bus.sh	2010-10-02 12:27:47.000000000 -0400
 @@ -0,0 +1,17 @@
 +#!/bin/sh
 +
@@ -984,19 +984,19 @@ diff -Nurd dbus-1.2.16/start-system-bus.sh dbus-1.2.16-new/start-system-bus.sh
 +fi
 +
 +exit 0
-diff -Nurd dbus-1.2.16/test/name-test/Makefile.am dbus-1.2.16-new/test/name-test/Makefile.am
---- dbus-1.2.16/test/name-test/Makefile.am	2009-07-14 15:38:42.000000000 -0400
-+++ dbus-1.2.16-new/test/name-test/Makefile.am	2009-09-05 08:56:49.000000000 -0400
+diff -Nurd dbus-1.2.24/test/name-test/Makefile.am dbus-1.2.24-new/test/name-test/Makefile.am
+--- dbus-1.2.24/test/name-test/Makefile.am	2010-03-23 15:01:17.000000000 -0400
++++ dbus-1.2.24-new/test/name-test/Makefile.am	2010-10-02 12:28:15.000000000 -0400
 @@ -16,7 +16,7 @@
  
  ## we use noinst_PROGRAMS not check_PROGRAMS for TESTS so that we
  ## build even when not doing "make check"
--noinst_PROGRAMS=test-names test-pending-call-dispatch test-pending-call-timeout test-threads-init test-ids test-shutdown test-privserver test-privserver-client
-+noinst_PROGRAMS=test-names test-pending-call-dispatch test-pending-call-timeout test-threads-init test-ids test-shutdown test-privserver test-privserver-client test-autolaunch
+-noinst_PROGRAMS=test-pending-call-dispatch test-pending-call-timeout test-threads-init test-ids test-shutdown test-privserver test-privserver-client
++noinst_PROGRAMS=test-pending-call-dispatch test-pending-call-timeout test-threads-init test-ids test-shutdown test-privserver test-privserver-client test-autolaunch
  
- test_names_SOURCES=				\
- 	test-names.c
-@@ -69,4 +69,11 @@
+ test_pending_call_dispatch_SOURCES =		\
+ 	test-pending-call-dispatch.c
+@@ -63,4 +63,11 @@
  test_privserver_client_LDADD=$(top_builddir)/dbus/libdbus-convenience.la ../libdbus-testutils.la $(DBUS_TEST_LIBS)
  test_privserver_client_LDFLAGS=@R_DYNAMIC_LDFLAG@
  
@@ -1008,19 +1008,22 @@ diff -Nurd dbus-1.2.16/test/name-test/Makefile.am dbus-1.2.16-new/test/name-test
 +test_autolaunch_LDFLAGS=@R_DYNAMIC_LDFLAG@
 +
  endif
-diff -Nurd dbus-1.2.16/test/name-test/run-test.sh dbus-1.2.16-new/test/name-test/run-test.sh
---- dbus-1.2.16/test/name-test/run-test.sh	2009-07-14 15:38:42.000000000 -0400
-+++ dbus-1.2.16-new/test/name-test/run-test.sh	2009-09-05 08:56:49.000000000 -0400
-@@ -50,3 +50,6 @@
+diff -Nurd dbus-1.2.24/test/name-test/run-test.sh dbus-1.2.24-new/test/name-test/run-test.sh
+--- dbus-1.2.24/test/name-test/run-test.sh	2010-03-23 15:01:17.000000000 -0400
++++ dbus-1.2.24-new/test/name-test/run-test.sh	2010-10-02 12:27:47.000000000 -0400
+@@ -50,6 +50,9 @@
  
- echo "running test-shutdown"
- ${DBUS_TOP_BUILDDIR}/libtool --mode=execute $DEBUG $DBUS_TOP_BUILDDIR/test/name-test/test-shutdown || die "test-shutdown failed"
+ echo "running test activation forking"
+ if ! python $DBUS_TOP_SRCDIR/test/name-test/test-activation-forking.py; then
 +
 +echo "running test-autolaunch"
 +${DBUS_TOP_BUILDDIR}/libtool --mode=execute $DEBUG $DBUS_TOP_BUILDDIR/test/name-test/test-autolaunch || die "test-autolaunch failed"
-diff -Nurd dbus-1.2.16/test/name-test/test-autolaunch.c dbus-1.2.16-new/test/name-test/test-autolaunch.c
---- dbus-1.2.16/test/name-test/test-autolaunch.c	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.2.16-new/test/name-test/test-autolaunch.c	2009-09-05 08:56:49.000000000 -0400
+   echo "Failed test-activation-forking"
+   exit 1
+ fi
+diff -Nurd dbus-1.2.24/test/name-test/test-autolaunch.c dbus-1.2.24-new/test/name-test/test-autolaunch.c
+--- dbus-1.2.24/test/name-test/test-autolaunch.c	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.2.24-new/test/name-test/test-autolaunch.c	2010-10-02 12:27:47.000000000 -0400
 @@ -0,0 +1,31 @@
 +#include <stdio.h>
 +#include <stdlib.h>
