merge from HEAD

diff --git a/10.4/unstable/main/finkinfo/languages/guile18-net-http.patch b/10.4/unstable/main/finkinfo/languages/guile18-net-http.patch
--- a/10.4/unstable/main/finkinfo/languages/guile18-net-http.patch
+++ b/10.4/unstable/main/finkinfo/languages/guile18-net-http.patch
@@ -7,8 +7,8 @@ diff -ruN net-http-new/configure net-http/configure
  
 -    # Extract the first word of "guile", so it can be a program name with args.
 -set dummy guile; ac_word=$2
-+    # Extract the first word of "guile-1.6", so it can be a program name with args.
-+set dummy guile-1.6; ac_word=$2
++    # Extract the first word of "guile-1.8", so it can be a program name with args.
++set dummy guile-1.8; ac_word=$2
  echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
  echo "configure:529: checking for $ac_word" >&5
  if eval "test \"`echo '$''{'ac_cv_path_GUILE'+set}'`\" = set"; then
@@ -19,9 +19,9 @@ diff -ruN net-http-new/configure net-http/configure
 -    echo $ac_n "checking "for guile-config"""... $ac_c" 1>&6
 -echo "configure:567: checking "for guile-config"" >&5
 -    for GUILE_CONFIG in guile-config $target-guile-config $build-guile-config; do
-+    echo $ac_n "checking "for guile-1.6-config"""... $ac_c" 1>&6
-+echo "configure:567: checking "for guile-1.6-config"" >&5
-+    for GUILE_CONFIG in guile-1.6-config $target-guile-1.6-config $build-guile-1.6-config; do
++    echo $ac_n "checking "for guile-1.8-config"""... $ac_c" 1>&6
++echo "configure:567: checking "for guile-1.8-config"" >&5
++    for GUILE_CONFIG in guile-1.8-config $target-guile-1.8-config $build-guile-1.8-config; do
          echo "$ac_t"""$GUILE_CONFIG"" 1>&6
          if ! $GUILE_CONFIG --version > /dev/null 2>&1 ; then
              echo "configure: warning: "cannot execute $GUILE_CONFIG"" 1>&2
@@ -30,7 +30,7 @@ diff -ruN net-http-new/configure net-http/configure
      done
      if test "$GUILE_CONFIG" = "error"; then
 -        { echo "configure: error: "cannot find guile-config; is Guile installed?"" 1>&2; exit 1; }
-+        { echo "configure: error: "cannot find guile-1.6-config; is Guile installed?"" 1>&2; exit 1; }
++        { echo "configure: error: "cannot find guile-1.8-config; is Guile installed?"" 1>&2; exit 1; }
          exit 1
      fi
      
