Update from #1530863

diff --git a/10.4/unstable/main/finkinfo/net/trafshow.patch b/10.4/unstable/main/finkinfo/net/trafshow.patch
--- a/10.4/unstable/main/finkinfo/net/trafshow.patch
+++ b/10.4/unstable/main/finkinfo/net/trafshow.patch
@@ -1,13 +1,3 @@
---- screen.c	2004-05-19 11:28:53.000000000 +0200
-+++ screen.c	2005-12-06 18:04:17.000000000 +0100
-@@ -41,7 +41,6 @@
- int prompt_mode = 0;
- double line_factor = 1;
- 
--extern int curs_dock_x, curs_dock_y;
- 
- /*
-  * Initialize curses.
 --- domain_resolver.c	2004-06-17 10:38:58.000000000 +0200
 +++ domain_resolver.c	2005-12-06 18:20:37.000000000 +0100
 @@ -17,6 +17,7 @@
@@ -18,3 +8,33 @@
  #include <stdio.h>
  #include <stdlib.h>
  #include <string.h>
+--- c.old	2006-07-29 14:58:41.000000000 +0200
++++ configure	2006-07-29 15:11:13.000000000 +0200
+@@ -5344,26 +5344,7 @@
+ }
+ _ACEOF
+ rm -f conftest.$ac_objext conftest$ac_exeext
+-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+-  (eval $ac_link) 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } &&
+-	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; } &&
+-	 { ac_try='test -s conftest$ac_exeext'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; }; then
++if (( 0 )); then
+   ac_cv_have_curses="slang"
+ else
+   echo "$as_me: failed program was:" >&5
