new gnome2.28 suite to unstable

diff --git a/10.4/unstable/main/finkinfo/gnome/gtk+2.patch b/10.4/unstable/main/finkinfo/gnome/gtk+2.patch
--- a/10.4/unstable/main/finkinfo/gnome/gtk+2.patch
+++ b/10.4/unstable/main/finkinfo/gnome/gtk+2.patch
@@ -1,77 +1,66 @@
-diff -Nurd -x'*~' gtk+-2.16.2.orig/Makefile.in gtk+-2.16.2/Makefile.in
---- gtk+-2.16.2.orig/Makefile.in	2009-05-31 00:11:01.000000000 -0400
-+++ gtk+-2.16.2/Makefile.in	2009-06-01 17:11:51.000000000 -0400
-@@ -527,7 +527,7 @@
+diff -Nurd -x'*~' gtk+-2.18.9.orig/Makefile.in gtk+-2.18.9/Makefile.in
+--- gtk+-2.18.9.orig/Makefile.in	2010-03-17 09:54:37.000000000 -0400
++++ gtk+-2.18.9/Makefile.in	2010-03-18 21:30:52.000000000 -0400
+@@ -469,7 +469,7 @@
+ 	|| { echo "Gtk+Tests:ERROR: Failed to start Xvfb environment for X11 target tests."; exit 1; } \
  	&& DISPLAY=:$$XID && export DISPLAY
- 
  
 -SRC_SUBDIRS = gdk-pixbuf gdk gtk modules demos tests perf contrib
 +SRC_SUBDIRS = gdk-pixbuf gdk gtk modules             perf contrib
  SUBDIRS = po po-properties $(SRC_SUBDIRS) docs m4macros
  
  # require automake 1.4
-diff -Nurd -x'*~' gtk+-2.16.2.orig/configure gtk+-2.16.2/configure
---- gtk+-2.16.2.orig/configure	2009-05-31 00:11:09.000000000 -0400
-+++ gtk+-2.16.2/configure	2009-06-01 17:11:51.000000000 -0400
-@@ -30224,6 +30224,7 @@
+diff -Nurd -x'*~' gtk+-2.18.9.orig/configure gtk+-2.18.9/configure
+--- gtk+-2.18.9.orig/configure	2010-03-17 09:54:39.000000000 -0400
++++ gtk+-2.18.9/configure	2010-03-18 21:30:52.000000000 -0400
+@@ -23842,6 +23842,7 @@
      # Check for Xinerama extension (Solaris impl or Xfree impl)
      gtk_save_cppflags="$CPPFLAGS"
      CPPFLAGS="$CPPFLAGS $x_cflags"
 +    gtk_save_libs="$LIBS"
  
-     case "$host" in
-       *-*-solaris*)
-@@ -30587,7 +30587,7 @@
+     # Check for XFree
+     { $as_echo "$as_me:${as_lineno-$LINENO}: checking for Xinerama support on XFree86" >&5
+@@ -23993,7 +23994,7 @@
  
  
    # Check for the RANDR extension
 -  if $PKG_CONFIG --exists "xrandr >= 1.2.99" ; then
 +  if $PKG_CONFIG --exists "xrandr >= 99999_FORCE_NONDETECT" ; then
  
- cat >>confdefs.h <<\_ACEOF
- #define HAVE_RANDR 1
-@@ -31975,7 +31976,7 @@
+ $as_echo "#define HAVE_RANDR 1" >>confdefs.h
  
- 
- 
--if test $have_papi = yes && test "x$CUPS_CONFIG" != "xno"; then
-+if test "x$have_papi" = "xyes" && test "x$CUPS_CONFIG" != "xno"; then
-   HAVE_PAPI_CUPS_TRUE=
-   HAVE_PAPI_CUPS_FALSE='#'
- else
-diff -Nurd -x'*~' gtk+-2.16.2.orig/docs/reference/gdk-pixbuf/Makefile.in gtk+-2.16.2/docs/reference/gdk-pixbuf/Makefile.in
---- gtk+-2.16.2.orig/docs/reference/gdk-pixbuf/Makefile.in	2009-05-31 00:11:02.000000000 -0400
-+++ gtk+-2.16.2/docs/reference/gdk-pixbuf/Makefile.in	2009-06-01 17:34:33.000000000 -0400
-@@ -542,9 +542,9 @@
- 
+diff -Nurd -x'*~' gtk+-2.18.9.orig/docs/reference/gdk-pixbuf/Makefile.in gtk+-2.18.9/docs/reference/gdk-pixbuf/Makefile.in
+--- gtk+-2.18.9.orig/docs/reference/gdk-pixbuf/Makefile.in	2010-03-17 09:54:26.000000000 -0400
++++ gtk+-2.18.9/docs/reference/gdk-pixbuf/Makefile.in	2010-03-18 21:30:52.000000000 -0400
+@@ -463,8 +463,8 @@
+ @ENABLE_GTK_DOC_TRUE@@GTK_DOC_BUILD_PDF_TRUE@PDF_BUILD_STAMP = pdf-build.stamp
  
  ########################################################################
 -@ENABLE_MAN_TRUE@man_MANS = gdk-pixbuf-csource.1 gdk-pixbuf-query-loaders.1 
-+man_MANS = gdk-pixbuf-csource.1 gdk-pixbuf-query-loaders.1 
- 
 -@ENABLE_MAN_TRUE@BUILT_EXTRA_DIST = $(man_MANS)
++man_MANS = gdk-pixbuf-csource.1 gdk-pixbuf-query-loaders.1 
 +BUILT_EXTRA_DIST = $(man_MANS)
- subdir = docs/reference/gdk-pixbuf
- ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
- mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
-diff -Nurd -x'*~' gtk+-2.16.2.orig/docs/reference/gtk/Makefile.in gtk+-2.16.2/docs/reference/gtk/Makefile.in
---- gtk+-2.16.2.orig/docs/reference/gtk/Makefile.in	2009-05-31 00:11:02.000000000 -0400
-+++ gtk+-2.16.2/docs/reference/gtk/Makefile.in	2009-06-01 17:36:01.000000000 -0400
-@@ -826,9 +826,9 @@
+ all: all-am
  
+ .SUFFIXES:
+diff -Nurd -x'*~' gtk+-2.18.9.orig/docs/reference/gtk/Makefile.in gtk+-2.18.9/docs/reference/gtk/Makefile.in
+--- gtk+-2.18.9.orig/docs/reference/gtk/Makefile.in	2010-03-17 09:54:27.000000000 -0400
++++ gtk+-2.18.9/docs/reference/gtk/Makefile.in	2010-03-18 21:30:52.000000000 -0400
+@@ -753,8 +753,8 @@
+ @ENABLE_GTK_DOC_TRUE@@GTK_DOC_BUILD_PDF_TRUE@PDF_BUILD_STAMP = pdf-build.stamp
  
  ########################################################################
 -@ENABLE_MAN_TRUE@man_MANS = gtk-query-immodules-2.0.1 gtk-update-icon-cache.1 gtk-builder-convert.1
-+man_MANS = gtk-query-immodules-2.0.1 gtk-update-icon-cache.1 gtk-builder-convert.1
- 
 -@ENABLE_MAN_TRUE@BUILT_EXTRA_DIST = $(man_MANS)
++man_MANS = gtk-query-immodules-2.0.1 gtk-update-icon-cache.1 gtk-builder-convert.1
 +BUILT_EXTRA_DIST = $(man_MANS)
- subdir = docs/reference/gtk
- ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
- mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
-diff -Nurd -x'*~' gtk+-2.16.2.orig/docs/tools/shooter.c gtk+-2.16.2/docs/tools/shooter.c
---- gtk+-2.16.2.orig/docs/tools/shooter.c	2009-04-04 00:51:45.000000000 -0400
-+++ gtk+-2.16.2/docs/tools/shooter.c	2009-06-01 17:11:51.000000000 -0400
+ all: all-am
+ 
+ .SUFFIXES:
+diff -Nurd -x'*~' gtk+-2.18.9.orig/docs/tools/shooter.c gtk+-2.18.9/docs/tools/shooter.c
+--- gtk+-2.18.9.orig/docs/tools/shooter.c	2009-06-04 15:18:03.000000000 -0400
++++ gtk+-2.18.9/docs/tools/shooter.c	2010-03-18 21:30:52.000000000 -0400
 @@ -16,7 +16,11 @@
  #include <stdlib.h>
  #include <fcntl.h>
@@ -84,21 +73,21 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/docs/tools/shooter.c gtk+-2.16.2/docs/tools/s
  #include "widgets.h"
  #include "shadow.h"
  
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/Makefile.in gtk+-2.16.2/gdk/Makefile.in
---- gtk+-2.16.2.orig/gdk/Makefile.in	2009-05-31 00:11:03.000000000 -0400
-+++ gtk+-2.16.2/gdk/Makefile.in	2009-06-01 17:11:51.000000000 -0400
-@@ -584,7 +584,7 @@
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gdk/Makefile.in gtk+-2.18.9/gdk/Makefile.in
+--- gtk+-2.18.9.orig/gdk/Makefile.in	2010-03-17 09:54:29.000000000 -0400
++++ gtk+-2.18.9/gdk/Makefile.in	2010-03-18 21:30:52.000000000 -0400
+@@ -655,7 +655,7 @@
  libgdk_x11_2_0_la_LIBADD = x11/libgdk-x11.la $(GDK_DEP_LIBS) \
    $(top_builddir)/gdk-pixbuf/libgdk_pixbuf-$(GTK_API_VERSION).la
  
 -libgdk_x11_2_0_la_LDFLAGS = $(LDADD)
 +libgdk_x11_2_0_la_LDFLAGS = $(LDADD) -lXrender
- 
  libgdk_quartz_2_0_la_SOURCES = $(common_sources) gdkkeynames.c
  libgdk_quartz_2_0_la_LIBADD = quartz/libgdk-quartz.la $(GDK_DEP_LIBS) \
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/directfb/gdkim-directfb.c gtk+-2.16.2/gdk/directfb/gdkim-directfb.c
---- gtk+-2.16.2.orig/gdk/directfb/gdkim-directfb.c	2009-04-04 00:51:45.000000000 -0400
-+++ gtk+-2.16.2/gdk/directfb/gdkim-directfb.c	2009-06-01 17:11:51.000000000 -0400
+   $(top_builddir)/gdk-pixbuf/libgdk_pixbuf-$(GTK_API_VERSION).la
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gdk/directfb/gdkim-directfb.c gtk+-2.18.9/gdk/directfb/gdkim-directfb.c
+--- gtk+-2.18.9.orig/gdk/directfb/gdkim-directfb.c	2009-06-04 15:18:03.000000000 -0400
++++ gtk+-2.18.9/gdk/directfb/gdkim-directfb.c	2010-03-18 21:30:52.000000000 -0400
 @@ -33,7 +33,11 @@
  #include "config.h"
  
@@ -111,10 +100,10 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/directfb/gdkim-directfb.c gtk+-2.16.2/gdk
  
  #include "gdkdirectfb.h"
  
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/x11/gdkdrawable-x11.c gtk+-2.16.2/gdk/x11/gdkdrawable-x11.c
---- gtk+-2.16.2.orig/gdk/x11/gdkdrawable-x11.c	2009-04-04 00:51:45.000000000 -0400
-+++ gtk+-2.16.2/gdk/x11/gdkdrawable-x11.c	2009-06-01 17:11:51.000000000 -0400
-@@ -959,11 +959,19 @@
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gdk/x11/gdkdrawable-x11.c gtk+-2.18.9/gdk/x11/gdkdrawable-x11.c
+--- gtk+-2.18.9.orig/gdk/x11/gdkdrawable-x11.c	2010-01-07 15:04:55.000000000 -0500
++++ gtk+-2.18.9/gdk/x11/gdkdrawable-x11.c	2010-03-18 21:30:52.000000000 -0400
+@@ -1044,11 +1044,19 @@
     * RENDER's preferred order
     */
    pf.direct.alphaMask = 0;
@@ -139,7 +128,7 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/x11/gdkdrawable-x11.c gtk+-2.16.2/gdk/x11
    *format = XRenderFindFormat (xdisplay,
  			       (PictFormatType | PictFormatDepth |
  				PictFormatRedMask | PictFormatRed |
-@@ -974,7 +982,14 @@
+@@ -1059,7 +1067,14 @@
  			       0);
  
    pf.direct.alphaMask = 0xff;
@@ -155,7 +144,7 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/x11/gdkdrawable-x11.c gtk+-2.16.2/gdk/x11
    
    *mask = XRenderFindFormat (xdisplay,
  			     (PictFormatType | PictFormatDepth |
-@@ -991,11 +1006,19 @@
+@@ -1076,11 +1091,19 @@
  
    pf.type = PictTypeDirect;
    pf.depth = 32;
@@ -179,9 +168,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/x11/gdkdrawable-x11.c gtk+-2.16.2/gdk/x11
  
    *format = XRenderFindFormat (xdisplay,
  			       (PictFormatType | PictFormatDepth |
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/x11/gdkfont-x11.c gtk+-2.16.2/gdk/x11/gdkfont-x11.c
---- gtk+-2.16.2.orig/gdk/x11/gdkfont-x11.c	2009-04-04 00:51:45.000000000 -0400
-+++ gtk+-2.16.2/gdk/x11/gdkfont-x11.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gdk/x11/gdkfont-x11.c gtk+-2.18.9/gdk/x11/gdkfont-x11.c
+--- gtk+-2.18.9.orig/gdk/x11/gdkfont-x11.c	2009-06-04 15:18:03.000000000 -0400
++++ gtk+-2.18.9/gdk/x11/gdkfont-x11.c	2010-03-18 21:30:52.000000000 -0400
 @@ -29,7 +29,11 @@
  #include "config.h"
  #include <X11/Xlib.h>
@@ -194,9 +183,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/x11/gdkfont-x11.c gtk+-2.16.2/gdk/x11/gdk
  
  #include "gdkx.h"
  #include "gdkfont.h"
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/x11/gdkim-x11.c gtk+-2.16.2/gdk/x11/gdkim-x11.c
---- gtk+-2.16.2.orig/gdk/x11/gdkim-x11.c	2009-04-04 00:51:45.000000000 -0400
-+++ gtk+-2.16.2/gdk/x11/gdkim-x11.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gdk/x11/gdkim-x11.c gtk+-2.18.9/gdk/x11/gdkim-x11.c
+--- gtk+-2.18.9.orig/gdk/x11/gdkim-x11.c	2010-03-17 09:31:43.000000000 -0400
++++ gtk+-2.18.9/gdk/x11/gdkim-x11.c	2010-03-18 21:30:52.000000000 -0400
 @@ -26,7 +26,11 @@
  
  #include "config.h"
@@ -209,9 +198,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gdk/x11/gdkim-x11.c gtk+-2.16.2/gdk/x11/gdkim
  #include <stdlib.h>
  #include <string.h>
  
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtk-builder-convert gtk+-2.16.2/gtk/gtk-builder-convert
---- gtk+-2.16.2.orig/gtk/gtk-builder-convert	2009-05-30 23:39:52.000000000 -0400
-+++ gtk+-2.16.2/gtk/gtk-builder-convert	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gtk/gtk-builder-convert gtk+-2.18.9/gtk/gtk-builder-convert
+--- gtk+-2.18.9.orig/gtk/gtk-builder-convert	2009-10-09 00:11:26.000000000 -0400
++++ gtk+-2.18.9/gtk/gtk-builder-convert	2010-03-18 21:30:52.000000000 -0400
 @@ -527,12 +527,12 @@
          if prop.childNodes:
              data = prop.childNodes[0].data
@@ -231,9 +220,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtk-builder-convert gtk+-2.16.2/gtk/gtk-b
          else:
              prop.appendChild(self._dom.createTextNode(""))
  
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkimmulticontext.c gtk+-2.16.2/gtk/gtkimmulticontext.c
---- gtk+-2.16.2.orig/gtk/gtkimmulticontext.c	2009-05-03 12:39:15.000000000 -0400
-+++ gtk+-2.16.2/gtk/gtkimmulticontext.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gtk/gtkimmulticontext.c gtk+-2.18.9/gtk/gtkimmulticontext.c
+--- gtk+-2.18.9.orig/gtk/gtkimmulticontext.c	2010-03-17 09:31:45.000000000 -0400
++++ gtk+-2.18.9/gtk/gtkimmulticontext.c	2010-03-18 21:30:52.000000000 -0400
 @@ -20,7 +20,11 @@
  #include "config.h"
  
@@ -246,9 +235,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkimmulticontext.c gtk+-2.16.2/gtk/gtkim
  
  #include "gtkimmulticontext.h"
  #include "gtkimmodule.h"
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkmain.c gtk+-2.16.2/gtk/gtkmain.c
---- gtk+-2.16.2.orig/gtk/gtkmain.c	2009-05-03 12:39:15.000000000 -0400
-+++ gtk+-2.16.2/gtk/gtkmain.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gtk/gtkmain.c gtk+-2.18.9/gtk/gtkmain.c
+--- gtk+-2.18.9.orig/gtk/gtkmain.c	2010-03-17 09:31:45.000000000 -0400
++++ gtk+-2.18.9/gtk/gtkmain.c	2010-03-18 21:30:52.000000000 -0400
 @@ -29,7 +29,11 @@
  #include <glib.h>
  #include "gdkconfig.h"
@@ -261,9 +250,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkmain.c gtk+-2.16.2/gtk/gtkmain.c
  
  #include <stdio.h>
  #include <stdlib.h>
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkpagesetupunixdialog.c gtk+-2.16.2/gtk/gtkpagesetupunixdialog.c
---- gtk+-2.16.2.orig/gtk/gtkpagesetupunixdialog.c	2009-04-04 00:51:45.000000000 -0400
-+++ gtk+-2.16.2/gtk/gtkpagesetupunixdialog.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gtk/gtkpagesetupunixdialog.c gtk+-2.18.9/gtk/gtkpagesetupunixdialog.c
+--- gtk+-2.18.9.orig/gtk/gtkpagesetupunixdialog.c	2010-03-17 09:31:45.000000000 -0400
++++ gtk+-2.18.9/gtk/gtkpagesetupunixdialog.c	2010-03-18 21:30:52.000000000 -0400
 @@ -21,7 +21,11 @@
  
  #include "config.h"
@@ -274,11 +263,11 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkpagesetupunixdialog.c gtk+-2.16.2/gtk/
  #include <locale.h>
 +#endif
  
- #ifdef HAVE__NL_MEASUREMENT_MEASUREMENT
- #include <langinfo.h>
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkpapersize.c gtk+-2.16.2/gtk/gtkpapersize.c
---- gtk+-2.16.2.orig/gtk/gtkpapersize.c	2009-05-03 12:39:15.000000000 -0400
-+++ gtk+-2.16.2/gtk/gtkpapersize.c	2009-06-01 17:11:51.000000000 -0400
+ #include "gtkintl.h"
+ #include "gtkprivate.h"
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gtk/gtkpapersize.c gtk+-2.18.9/gtk/gtkpapersize.c
+--- gtk+-2.18.9.orig/gtk/gtkpapersize.c	2010-03-17 09:31:45.000000000 -0400
++++ gtk+-2.18.9/gtk/gtkpapersize.c	2010-03-18 21:30:52.000000000 -0400
 @@ -22,7 +22,11 @@
  #include "config.h"
  #include <string.h>
@@ -291,9 +280,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkpapersize.c gtk+-2.16.2/gtk/gtkpapersi
  #if defined(HAVE__NL_PAPER_HEIGHT) && defined(HAVE__NL_PAPER_WIDTH)
  #include <langinfo.h>
  #endif
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkrc.c gtk+-2.16.2/gtk/gtkrc.c
---- gtk+-2.16.2.orig/gtk/gtkrc.c	2009-05-03 12:39:15.000000000 -0400
-+++ gtk+-2.16.2/gtk/gtkrc.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gtk/gtkrc.c gtk+-2.18.9/gtk/gtkrc.c
+--- gtk+-2.18.9.orig/gtk/gtkrc.c	2010-03-17 09:31:46.000000000 -0400
++++ gtk+-2.18.9/gtk/gtkrc.c	2010-03-18 21:30:52.000000000 -0400
 @@ -26,7 +26,11 @@
  
  #include "config.h"
@@ -306,9 +295,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkrc.c gtk+-2.16.2/gtk/gtkrc.c
  #ifdef HAVE_UNISTD_H
  #include <unistd.h>
  #endif
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkspinbutton.c gtk+-2.16.2/gtk/gtkspinbutton.c
---- gtk+-2.16.2.orig/gtk/gtkspinbutton.c	2009-05-03 13:03:56.000000000 -0400
-+++ gtk+-2.16.2/gtk/gtkspinbutton.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gtk/gtkspinbutton.c gtk+-2.18.9/gtk/gtkspinbutton.c
+--- gtk+-2.18.9.orig/gtk/gtkspinbutton.c	2010-03-17 09:31:47.000000000 -0400
++++ gtk+-2.18.9/gtk/gtkspinbutton.c	2010-03-18 21:30:52.000000000 -0400
 @@ -32,7 +32,11 @@
  #include <stdlib.h>
  #include <math.h>
@@ -321,9 +310,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkspinbutton.c gtk+-2.16.2/gtk/gtkspinbu
  #include "gdk/gdkkeysyms.h"
  #include "gtkbindings.h"
  #include "gtkspinbutton.h"
-diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkwidget.c gtk+-2.16.2/gtk/gtkwidget.c
---- gtk+-2.16.2.orig/gtk/gtkwidget.c	2009-05-30 23:39:53.000000000 -0400
-+++ gtk+-2.16.2/gtk/gtkwidget.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/gtk/gtkwidget.c gtk+-2.18.9/gtk/gtkwidget.c
+--- gtk+-2.18.9.orig/gtk/gtkwidget.c	2010-03-17 09:31:48.000000000 -0400
++++ gtk+-2.18.9/gtk/gtkwidget.c	2010-03-18 21:30:52.000000000 -0400
 @@ -27,7 +27,11 @@
  #include "config.h"
  #include <stdarg.h>
@@ -336,9 +325,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/gtk/gtkwidget.c gtk+-2.16.2/gtk/gtkwidget.c
  #include "gtkcontainer.h"
  #include "gtkaccelmap.h"
  #include "gtkclipboard.h"
-diff -Nurd -x'*~' gtk+-2.16.2.orig/modules/input/gtkimcontextxim.c gtk+-2.16.2/modules/input/gtkimcontextxim.c
---- gtk+-2.16.2.orig/modules/input/gtkimcontextxim.c	2009-05-03 12:39:15.000000000 -0400
-+++ gtk+-2.16.2/modules/input/gtkimcontextxim.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/modules/input/gtkimcontextxim.c gtk+-2.18.9/modules/input/gtkimcontextxim.c
+--- gtk+-2.18.9.orig/modules/input/gtkimcontextxim.c	2010-03-17 09:31:49.000000000 -0400
++++ gtk+-2.18.9/modules/input/gtkimcontextxim.c	2010-03-18 21:30:52.000000000 -0400
 @@ -18,7 +18,11 @@
   */
  
@@ -352,9 +341,53 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/modules/input/gtkimcontextxim.c gtk+-2.16.2/m
  #include <string.h>
  #include <stdlib.h>
  
-diff -Nurd -x'*~' gtk+-2.16.2.orig/tests/testicontheme.c gtk+-2.16.2/tests/testicontheme.c
---- gtk+-2.16.2.orig/tests/testicontheme.c	2009-05-03 12:39:15.000000000 -0400
-+++ gtk+-2.16.2/tests/testicontheme.c	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/modules/printbackends/cups/gtkprintbackendcups.c gtk+-2.18.9/modules/printbackends/cups/gtkprintbackendcups.c
+--- gtk+-2.18.9.orig/modules/printbackends/cups/gtkprintbackendcups.c	2010-03-17 09:31:49.000000000 -0400
++++ gtk+-2.18.9/modules/printbackends/cups/gtkprintbackendcups.c	2010-03-18 21:31:04.000000000 -0400
+@@ -663,6 +663,40 @@
+     return FALSE;
+ }
+ 
++#ifndef HAVE_CUPS_API_1_2
++
++const char *
++httpGetHostname(http_t *http,
++                char   *s,
++                int    slen)
++{
++  struct hostent *host;
++
++  if (!s || slen <= 1)
++    return (NULL);
++
++  if (http)
++    {
++      if (http->hostname[0] == '/')
++        g_strlcpy (s, "localhost", slen);
++      else
++        g_strlcpy (s, http->hostname, slen);
++    }
++  else
++    {
++      if (gethostname (s, slen) < 0)
++        g_strlcpy (s, "localhost", slen);
++
++      if (!strchr (s, '.'))
++        {
++          if ((host = gethostbyname (s)) != NULL && host->h_name)
++            g_strlcpy (s, host->h_name, slen);
++        }
++    }
++  return (s);
++}
++#endif
++
+ static void
+ gtk_print_backend_cups_set_password (GtkPrintBackend  *backend,
+                                      gchar           **auth_info_required,
+diff -Nurd -x'*~' gtk+-2.18.9.orig/tests/testicontheme.c gtk+-2.18.9/tests/testicontheme.c
+--- gtk+-2.18.9.orig/tests/testicontheme.c	2009-06-04 15:18:04.000000000 -0400
++++ gtk+-2.18.9/tests/testicontheme.c	2010-03-18 21:30:52.000000000 -0400
 @@ -21,7 +21,11 @@
  #include <gtk/gtk.h>
  #include <stdlib.h>
@@ -367,9 +400,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/tests/testicontheme.c gtk+-2.16.2/tests/testi
  
  static void
  usage (void)
-diff -Nurd -x'*~' gtk+-2.16.2.orig/update-gdk-pixbuf-loaders gtk+-2.16.2/update-gdk-pixbuf-loaders
---- gtk+-2.16.2.orig/update-gdk-pixbuf-loaders	1969-12-31 19:00:00.000000000 -0500
-+++ gtk+-2.16.2/update-gdk-pixbuf-loaders	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/update-gdk-pixbuf-loaders gtk+-2.18.9/update-gdk-pixbuf-loaders
+--- gtk+-2.18.9.orig/update-gdk-pixbuf-loaders	1969-12-31 19:00:00.000000000 -0500
++++ gtk+-2.18.9/update-gdk-pixbuf-loaders	2010-03-18 21:30:52.000000000 -0400
 @@ -0,0 +1,21 @@
 +#!/bin/sh -e
 +#
@@ -392,9 +425,9 @@ diff -Nurd -x'*~' gtk+-2.16.2.orig/update-gdk-pixbuf-loaders gtk+-2.16.2/update-
 +chmod 0644 $CONFFILE
 +
 +exit 0
-diff -Nurd -x'*~' gtk+-2.16.2.orig/update-gtk-immodules gtk+-2.16.2/update-gtk-immodules
---- gtk+-2.16.2.orig/update-gtk-immodules	1969-12-31 19:00:00.000000000 -0500
-+++ gtk+-2.16.2/update-gtk-immodules	2009-06-01 17:11:51.000000000 -0400
+diff -Nurd -x'*~' gtk+-2.18.9.orig/update-gtk-immodules gtk+-2.18.9/update-gtk-immodules
+--- gtk+-2.18.9.orig/update-gtk-immodules	1969-12-31 19:00:00.000000000 -0500
++++ gtk+-2.18.9/update-gtk-immodules	2010-03-18 21:30:52.000000000 -0400
 @@ -0,0 +1,20 @@
 +#!/bin/sh -e
 +#
