cleaner removal of inappropriate configure test

diff --git a/10.4/unstable/main/finkinfo/gnome/libgnomeprint2.2.patch b/10.4/unstable/main/finkinfo/gnome/libgnomeprint2.2.patch
--- a/10.4/unstable/main/finkinfo/gnome/libgnomeprint2.2.patch
+++ b/10.4/unstable/main/finkinfo/gnome/libgnomeprint2.2.patch
@@ -1,7 +1,19 @@
 diff -Nurd -x'*~' libgnomeprint-2.18.2.orig/configure libgnomeprint-2.18.2/configure
 --- libgnomeprint-2.18.2.orig/configure	2007-09-17 09:13:10.000000000 -0400
 +++ libgnomeprint-2.18.2/configure	2007-11-03 13:36:39.000000000 -0400
-@@ -24779,8 +24779,8 @@
+@@ -23821,11 +23821,6 @@
+   ;;
+ esac
+ 
+-if test "x$LIBM" = "x"; then
+-	{ { echo "$as_me:$LINENO: error: You need -lm(mathematic library) for this version of libgnomeprint." >&5
+-echo "$as_me: error: You need -lm(mathematic library) for this version of libgnomeprint." >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
+ LDFLAGS="$LDFLAGS $LIBM"
+ 
+ FREETYPE_LIBS=
+@@ -24779,8 +24774,8 @@
     { (exit 1); exit 1; }; }
  fi
  
