Merge pangocairo back into trunk

diff --git a/10.4/unstable/main/finkinfo/gnome/libgnomeprint2.2.patch b/10.4/unstable/main/finkinfo/gnome/libgnomeprint2.2.patch
--- a/10.4/unstable/main/finkinfo/gnome/libgnomeprint2.2.patch
+++ b/10.4/unstable/main/finkinfo/gnome/libgnomeprint2.2.patch
@@ -1,24 +1,26 @@
-diff -Nurd -x'*~' libgnomeprint-2.12.1.orig/configure.in libgnomeprint-2.12.1/configure.in
---- libgnomeprint-2.12.1.orig/configure.in	2005-09-06 11:01:33.000000000 -0400
-+++ libgnomeprint-2.12.1/configure.in	2006-02-23 21:00:21.000000000 -0500
-@@ -291,7 +291,7 @@
- dnl ===============================
- dnl LIBGNOMEPRINT_LIBS & CFLAGS
- dnl ===============================
+diff -Nurd -x'*~' libgnomeprint-2.18.3.orig/configure libgnomeprint-2.18.3/configure
+--- libgnomeprint-2.18.3.orig/configure	2008-01-28 11:07:08.000000000 -0500
++++ libgnomeprint-2.18.3/configure	2008-01-30 23:37:20.000000000 -0500
+@@ -23957,11 +23957,6 @@
+   ;;
+ esac
+ 
+-if test "x$LIBM" = "x"; then
+-	{ { echo "$as_me:$LINENO: error: You need -lm(mathematic library) for this version of libgnomeprint." >&5
+-echo "$as_me: error: You need -lm(mathematic library) for this version of libgnomeprint." >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
+ LDFLAGS="$LDFLAGS $LIBM"
+ 
+ FREETYPE_LIBS=
+@@ -24915,8 +24910,8 @@
+    { (exit 1); exit 1; }; }
+ fi
+ 
 -LIBGNOMEPRINT_CFLAGS="$GP_CFLAGS $FREETYPE_CFLAGS"
+-LIBGNOMEPRINT_LIBS="$GP_LIBS $FREETYPE_LIBS $Z_LIBS"
 +LIBGNOMEPRINT_CFLAGS="$FREETYPE_CFLAGS $GP_CFLAGS"
- LIBGNOMEPRINT_LIBS="$GP_LIBS $FREETYPE_LIBS $Z_LIBS"
- AC_SUBST(LIBGNOMEPRINT_CFLAGS)
- AC_SUBST(LIBGNOMEPRINT_LIBS)
-diff -Nurd -x'*~' libgnomeprint-2.12.1.orig/libgnomeprint/gnome-fontmap.c libgnomeprint-2.12.1/libgnomeprint/gnome-fontmap.c
---- libgnomeprint-2.12.1.orig/libgnomeprint/gnome-fontmap.c	2005-03-24 15:16:49.000000000 -0500
-+++ libgnomeprint-2.12.1/libgnomeprint/gnome-fontmap.c	2006-02-23 21:22:09.000000000 -0500
-@@ -223,6 +223,8 @@
- 		font_type = GP_FONT_ENTRY_TRUETYPE;
- 	else if (g_ascii_strcasecmp (c, ".ttc") == 0)
- 		font_type = GP_FONT_ENTRY_TRUETYPE;
-+	else if (g_ascii_strcasecmp (c, ".otf") == 0)
-+		font_type = GP_FONT_ENTRY_TRUETYPE;
- 	else if (g_ascii_strcasecmp (c, ".font") == 0) /* See #102400 */
- 		font_type = GP_FONT_ENTRY_TRUETYPE;
- 	else {
++LIBGNOMEPRINT_LIBS="$FREETYPE_LIBS $GP_LIBS $Z_LIBS"
+ 
+ 
+ 
