merge from HEAD

diff --git a/10.4/unstable/main/finkinfo/text/xpdf.patch b/10.4/unstable/main/finkinfo/text/xpdf.patch
--- a/10.4/unstable/main/finkinfo/text/xpdf.patch
+++ b/10.4/unstable/main/finkinfo/text/xpdf.patch
@@ -1,3 +1,30 @@
+diff -Nurd -x'*`' xpdf-3.02.orig/configure xpdf-3.02/configure
+--- xpdf-3.02.orig/configure	2007-02-27 17:05:51.000000000 -0500
++++ xpdf-3.02/configure	2007-07-22 20:57:43.000000000 -0400
+@@ -9902,9 +9902,8 @@
+           elif test -d "$smr_cv_with_freetype2_library"; then
+             freetype2_LIBS="-L$smr_cv_with_freetype2_library -lfreetype"
+           else
+-            { { echo "$as_me:$LINENO: error: argument must be boolean, file, or directory" >&5
+-echo "$as_me: error: argument must be boolean, file, or directory" >&2;}
+-   { (exit 1); exit 1; }; }
++	    # blindly assume user knows what he's doing...
++            freetype2_LIBS="$smr_cv_with_freetype2_library"
+           fi
+           with_freetype2=yes
+           ;;
+@@ -9948,9 +9947,8 @@
+     if test -d "$smr_cv_with_freetype2_includes"; then
+       freetype2_CFLAGS="-I$smr_cv_with_freetype2_includes"
+     else
+-      { { echo "$as_me:$LINENO: error: argument must be a directory" >&5
+-echo "$as_me: error: argument must be a directory" >&2;}
+-   { (exit 1); exit 1; }; }
++      # blindly assume user knows what he's doing...
++      freetype2_CFLAGS="$smr_cv_with_freetype2_includes"
+     fi
+   else
+     freetype2_CFLAGS=
 --- xpdf/doc/sample-xpdfrc.orig	Wed Sep  7 11:31:56 2005
 +++ xpdf/doc/sample-xpdfrc	Wed Sep  7 11:35:05 2005
 @@ -29,20 +29,20 @@
