various version bumps and bugfixes

diff --git a/10.4-transitional/unstable/main/finkinfo/database/libpqxx-2.patch b/10.4-transitional/unstable/main/finkinfo/database/libpqxx-2.patch
--- a/10.4-transitional/unstable/main/finkinfo/database/libpqxx-2.patch
+++ b/10.4-transitional/unstable/main/finkinfo/database/libpqxx-2.patch
@@ -1,7 +1,7 @@
-diff -uNr libpqxx-2.5.0/configure libpqxx-2.5.0-new/configure
---- libpqxx-2.5.0/configure	2005-03-19 08:31:37.000000000 -0500
-+++ libpqxx-2.5.0-new/configure	2005-04-01 14:08:47.000000000 -0500
-@@ -20213,7 +20213,8 @@
+diff -uNr libpqxx-2.5.5/configure libpqxx-2.5.5-new/configure
+--- libpqxx-2.5.5/configure	2005-07-01 03:52:28.000000000 -0400
++++ libpqxx-2.5.5-new/configure	2005-07-07 10:15:32.000000000 -0400
+@@ -20330,7 +20330,8 @@
  { echo "$as_me:$LINENO: using PostgreSQL libraries at $with_postgres_lib" >&5
  echo "$as_me: using PostgreSQL libraries at $with_postgres_lib" >&6;}
  
@@ -11,10 +11,19 @@ diff -uNr libpqxx-2.5.0/configure libpqxx-2.5.0-new/configure
  
  POSTGRES_LIB="-L${with_postgres_lib} -R${with_postgres_lib} -lpq"
  
-diff -uNr libpqxx-2.5.0/src/Makefile.in libpqxx-2.5.0-new/src/Makefile.in
---- libpqxx-2.5.0/src/Makefile.in	2005-03-19 08:31:35.000000000 -0500
-+++ libpqxx-2.5.0-new/src/Makefile.in	2005-04-01 14:09:05.000000000 -0500
-@@ -213,9 +213,9 @@
+@@ -21604,7 +21605,7 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  strerror_r_charp=yes
++  strerror_r_charp=no
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+diff -uNr libpqxx-2.5.5/src/Makefile.in libpqxx-2.5.5-new/src/Makefile.in
+--- libpqxx-2.5.5/src/Makefile.in	2005-07-01 03:52:26.000000000 -0400
++++ libpqxx-2.5.5-new/src/Makefile.in	2005-07-07 10:11:51.000000000 -0400
+@@ -214,9 +214,9 @@
  
  
  # Uncomment to build an unversioned library (version in soname)
