New Upstream

diff --git a/10.3/unstable/main/finkinfo/utils/tcpreplay.patch b/10.3/unstable/main/finkinfo/utils/tcpreplay.patch
--- a/10.3/unstable/main/finkinfo/utils/tcpreplay.patch
+++ b/10.3/unstable/main/finkinfo/utils/tcpreplay.patch
@@ -1,22 +1,22 @@
---- tcpreplay-1.4.6/configure	2003-12-05 18:36:04.000000000 +0100
-+++ tcpreplay-ok/configure	2003-12-07 15:42:03.000000000 +0100
-@@ -5248,7 +5248,7 @@
+--- tcpreplay-2.0.0/configure	Sun Feb  1 19:26:56 2004
++++ tcpreplay-ok/configure	Mon Feb  2 14:15:09 2004
+@@ -6594,16 +6594,16 @@
    *)
       echo "$as_me:$LINENO: result: $withval" >&5
  echo "${ECHO_T}$withval" >&6
 -     if test -f $withval/include/pcap.h -a -f $withval/lib/libpcap.a; then
 +     if test -f $withval/include/pcap.h -a -f $withval/lib/libpcap.dylib; then
-         owd=`pwd`
-         if cd $withval; then
-           withval=`pwd`
-@@ -5258,8 +5258,8 @@
+ 		LPCAPINC="-I$withval/include"
  		LPCAPINCDIR="$withval/include"
  		LPCAPLIB="-L$withval/lib -lpcap"
-      else
+-     elif test -f $withval/pcap.h -a -f $withval/libpcap.a; then
++     elif test -f $withval/pcap.h -a -f $withval/libpcap.dylib; then
+ 		LPCAPINC="-I$withval/"
+ 		LPCAPINCDIR="$withval/"
+ 		LPCAPLIB="-L$withval/ -lpcap"
+ 	 else
 -        { { echo "$as_me:$LINENO: error: pcap.h or libpcap.a not found in $withval" >&5
--echo "$as_me: error: pcap.h or libpcap.a not found in $withval" >&2;}
 +        { { echo "$as_me:$LINENO: error: pcap.h or libpcap.dylib not found in $withval" >&5
-+echo "$as_me: error: pcap.h or libpcap.dylib not found in $withval" >&2;}
+ echo "$as_me: error: pcap.h or libpcap.a not found in $withval" >&2;}
     { (exit 1); exit 1; }; }
       fi
-      ;;
