latest version to stable

diff --git a/10.4/stable/main/finkinfo/editors/emacsen-common.patch b/10.4/stable/main/finkinfo/editors/emacsen-common.patch
--- a/10.4/stable/main/finkinfo/editors/emacsen-common.patch
+++ b/10.4/stable/main/finkinfo/editors/emacsen-common.patch
@@ -1,6 +1,6 @@
-diff -Naur emacsen-common-1.4.13.orig/00debian-vars.el emacsen-common-1.4.13/00debian-vars.el
---- emacsen-common-1.4.13.orig/00debian-vars.el	Tue Feb 22 17:42:00 2000
-+++ emacsen-common-1.4.13/00debian-vars.el	Wed Dec 12 20:32:19 2001
+diff -u -Naur emacsen-common-1.4.15/00debian-vars.el emacsen-common.fink/00debian-vars.el
+--- emacsen-common-1.4.15/00debian-vars.el	Tue Feb 22 17:42:00 2000
++++ emacsen-common.fink/00debian-vars.el	Tue Jun 22 13:47:49 2004
 @@ -1,6 +1,6 @@
 -;; 00debian-vars.el
 +;; 00fink-vars.el
@@ -51,39 +51,43 @@ diff -Naur emacsen-common-1.4.13.orig/00debian-vars.el emacsen-common-1.4.13/00d
  
 -;;; 00debian-vars.el ends here
 +;;; 00fink-vars.el ends here
-diff -Naur emacsen-common-1.4.13.orig/debian-startup.el emacsen-common-1.4.13/debian-startup.el
---- emacsen-common-1.4.13.orig/debian-startup.el	Tue Jul 17 12:12:40 2001
-+++ emacsen-common-1.4.13/debian-startup.el	Wed Dec 12 15:19:02 2001
+diff -u -Naur emacsen-common-1.4.15/debian-startup.el emacsen-common.fink/debian-startup.el
+--- emacsen-common-1.4.15/debian-startup.el	Mon Feb 18 12:12:15 2002
++++ emacsen-common.fink/debian-startup.el	Tue Jun 22 13:52:56 2004
 @@ -1,4 +1,4 @@
 -;;; debian-startup.el --- Debian specific emacsen startup code.
 +;;; fink-startup.el --- Fink specific emacsen startup code.
  
  ;; Copyright (C) 1998 Rob Browning
  
-@@ -29,7 +29,7 @@
- ;; This file contains startup code needed by all the various flavors
+@@ -30,7 +30,7 @@
  ;; of Emacs for a Debian system.
  
--(defun debian-unique-strings (list) 
-+(defun fink-unique-strings (list) 
  
+-(defun debian-pkg-add-load-path-item (item)
++(defun fink-pkg-add-load-path-item (item)
+   "Takes a path item (a string) and adds it to load path in the
+ correct position for an add-on package, before the emacs system
+ directories, but after the /usr/local/ directories.  After modifying
+@@ -63,7 +63,7 @@
+ 
+ ;; Rewritten to less elegant -- non recursive version because elisp
+ ;; doesn't seem to handle tail recursion :<
+-(defun debian-unique-strings (strings) 
++(defun fink-unique-strings (strings) 
    "Takes a list of strings and returns the list with *adjacent*
  duplicates removed."
-@@ -37,10 +37,10 @@
-   (if (null list)
-       '()
-     (if (string= (car list) (car (cdr list)))
--        (debian-unique-strings (cdr list))
--      (cons (car list) (debian-unique-strings (cdr list))))))
-+        (fink-unique-strings (cdr list))
-+      (cons (car list) (fink-unique-strings (cdr list))))))
+   (let ((result '()))
+@@ -73,7 +73,7 @@
+       (setq strings (cdr strings)))
+     (nreverse result)))
  
 -(defun debian-run-directories (&rest dirs)
 +(defun fink-run-directories (&rest dirs)
  
    "Load each file of the form XXfilename.el or XXfilename.elc in any
  of the dirs, where XX must be a number.  The files will be run in
-@@ -73,7 +73,7 @@
+@@ -106,7 +106,7 @@
                     files)))
           
           ;; Finally sort them, and delete duplicates
@@ -92,7 +96,7 @@ diff -Naur emacsen-common-1.4.13.orig/debian-startup.el emacsen-common-1.4.13/de
           
           (old-load-path load-path))
  
-@@ -103,9 +103,9 @@
+@@ -134,9 +134,9 @@
                          load-path))))      
          (setq load-path (append add-on-package-paths old-load-path))))))
  
@@ -104,7 +108,7 @@ diff -Naur emacsen-common-1.4.13.orig/debian-startup.el emacsen-common-1.4.13/de
    ;; have to do it like this because some of the emacsen flavors
    ;; didn't DWIM in their startup sequence.  I wasn't as clear as I
    ;; should have been in debian-policy, but they were also
-@@ -113,15 +113,15 @@
+@@ -144,15 +144,15 @@
  
    ;; It's even weirder now.  I've changed policy back to the old way,
    ;; but I'm also doing some sanity checking here and making sure that
@@ -127,9 +131,9 @@ diff -Naur emacsen-common-1.4.13.orig/debian-startup.el emacsen-common-1.4.13/de
 +    (let ((common-dir "@PREFIX@/etc/emacs/site-start.d")
 +          (flavor-dir (concat "@PREFIX@/etc/" (symbol-name flavor) "/site-start.d")))
 +      (fink-run-directories flavor-dir common-dir))))
-diff -Naur emacsen-common-1.4.13.orig/emacs-install emacsen-common-1.4.13/emacs-install
---- emacsen-common-1.4.13.orig/emacs-install	Tue Feb 22 17:42:00 2000
-+++ emacsen-common-1.4.13/emacs-install	Wed Dec 12 15:17:57 2001
+diff -u -Naur emacsen-common-1.4.15/emacs-install emacsen-common.fink/emacs-install
+--- emacsen-common-1.4.15/emacs-install	Tue Feb 22 17:42:00 2000
++++ emacsen-common.fink/emacs-install	Tue Jun 22 13:47:49 2004
 @@ -7,8 +7,8 @@
  # Let emacs-package-install/remove know what's going on.
  $ENV{'CURRENTLY_HANDLING_EMACSEN'} = "Yes";
@@ -141,9 +145,9 @@ diff -Naur emacsen-common-1.4.13.orig/emacs-install emacsen-common-1.4.13/emacs-
  my $flavor = $ARGV[0];
  my $action = 'install';
  $action = 'remove' if $0 =~ /remove$/o;
-diff -Naur emacsen-common-1.4.13.orig/emacs-package-install emacsen-common-1.4.13/emacs-package-install
---- emacsen-common-1.4.13.orig/emacs-package-install	Tue Feb 22 17:42:00 2000
-+++ emacsen-common-1.4.13/emacs-package-install	Wed Dec 12 15:17:57 2001
+diff -u -Naur emacsen-common-1.4.15/emacs-package-install emacsen-common.fink/emacs-package-install
+--- emacsen-common-1.4.15/emacs-package-install	Mon Feb 18 12:46:42 2002
++++ emacsen-common.fink/emacs-package-install	Tue Jun 22 15:02:26 2004
 @@ -7,8 +7,8 @@
  
  my $currently_handling_emacsen = $ENV{'CURRENTLY_HANDLING_EMACSEN'};
@@ -155,10 +159,62 @@ diff -Naur emacsen-common-1.4.13.orig/emacs-package-install emacsen-common-1.4.1
  my $pkg = $ARGV[0];
  my $action = 'install';
  $action = 'remove' if $0 =~ /remove$/o;
-diff -Naur emacsen-common-1.4.13.orig/emacsen-common.install emacsen-common-1.4.13/emacsen-common.install
---- emacsen-common-1.4.13.orig/emacsen-common.install	Tue Feb 22 17:42:00 2000
-+++ emacsen-common-1.4.13/emacsen-common.install	Wed Dec 12 15:17:57 2001
-@@ -14,33 +14,33 @@
+@@ -36,13 +36,13 @@
+ # Make sure if we create any files, we do it safely.
+ umask 0022 or die "emacs-package-$action: can't set umask, aborting.";
+ 
+-if (! -e '/var/lib/emacsen-common/installed-flavors')
++if (! -e '@PREFIX@/var/lib/emacsen-common/installed-flavors')
+ {
+   die <<EOS;
+ ERROR: emacsen-common being used before being configured.
+ ERROR: This is likely a bug in the ${pkg} package, which needs to
+ ERROR: add one of the appropriate dependencies.
+-ERROR: See /usr/share/doc/emacsen-common/debian-emacs-policy.gz
++ERROR: See @PREFIX@/share/doc/emacsen-common/debian-emacs-policy.gz
+ ERROR: for details.
+ EOS
+ }
+diff -u -Naur emacsen-common-1.4.15/emacsen-common.install emacsen-common.fink/emacsen-common.install
+--- emacsen-common-1.4.15/emacsen-common.install	Tue Feb 22 17:42:00 2000
++++ emacsen-common.fink/emacsen-common.install	Tue Jun 22 17:08:42 2004
+@@ -9,38 +9,69 @@
+ 
+ if [ ${FLAVOR} != emacs ]
+ then
++
++  # Try compiling a trivial testfile  {cswinehart  |  22 june 2004}
++  echo '(defun a-fake-func()  "This function does nothing"  )' > /tmp/emacsen-common-testfile.el
++  if ${FLAVOR} ${byte_compile_options} /tmp/emacsen-common-testfile.el
++  then
++      # It worked. Clean up the testfile and be done with it.
++      rm -f /tmp/emacsen-common-testfile.el{,c}
++  else 
++      # It failed. Stop trying to install and print a meaningful error message
++      printf "\n\n\n"
++      echo "  +-------------------------------------------------------------------+"      
++      echo "  |  Fink had a problem installing this version of Emacs because      |"
++      echo "  |  ${FLAVOR} couldn't be launched successfully.                       |"
++      echo "  |                                                                   |"
++      echo "  |  This typically happens when the package was compiled on a        |"
++      echo "  |  system with an older version of Mac OS X installed. At this      |"
++      echo "  |  point you should try recompiling the emacs version that caused   |"
++      echo "  |  this error with a command like:                                  |"
++      echo "  |    fink rebuild <flavor>                                          |"
++      echo "  |  where <flavor> is a package name like \`${FLAVOR}' or \`${FLAVOR}-nox' |"
++      echo "  |                                                                   |"
++      echo "  |  If this doesn't solve the problem, please notify the maintainer  |"
++      echo "  |  of the emacs package in question.                                |"
++      echo "  +-------------------------------------------------------------------+"
++      printf "\n\n\n\n"
++
++      # Clean up and return the error code
++      rm -f /tmp/emacsen-common-testfile.el{,c}
++      exit 1
++  fi
++
+   echo emacsen-common: byte-compiling for ${FLAVOR}
+ 
    # If we had .el files that needed byte compiling in the package dir,
    # this is how we'd handle it.
  
@@ -205,9 +261,9 @@ diff -Naur emacsen-common-1.4.13.orig/emacsen-common.install emacsen-common-1.4.
  fi
  
  exit 0;
-diff -Naur emacsen-common-1.4.13.orig/emacsen-common.remove emacsen-common-1.4.13/emacsen-common.remove
---- emacsen-common-1.4.13.orig/emacsen-common.remove	Tue Feb 22 17:42:00 2000
-+++ emacsen-common-1.4.13/emacsen-common.remove	Wed Dec 12 15:17:57 2001
+diff -u -Naur emacsen-common-1.4.15/emacsen-common.remove emacsen-common.fink/emacsen-common.remove
+--- emacsen-common-1.4.15/emacsen-common.remove	Tue Feb 22 17:42:00 2000
++++ emacsen-common.fink/emacsen-common.remove	Tue Jun 22 13:47:49 2004
 @@ -9,8 +9,8 @@
  if [ ${FLAVOR} != emacs ]
  then
@@ -219,9 +275,9 @@ diff -Naur emacsen-common-1.4.13.orig/emacsen-common.remove emacsen-common-1.4.1
  fi
  
  exit 0;
-diff -Naur emacsen-common-1.4.13.orig/generate-install-list emacsen-common-1.4.13/generate-install-list
---- emacsen-common-1.4.13.orig/generate-install-list	Tue Jul 17 12:12:40 2001
-+++ emacsen-common-1.4.13/generate-install-list	Wed Dec 12 15:17:57 2001
+diff -u -Naur emacsen-common-1.4.15/generate-install-list emacsen-common.fink/generate-install-list
+--- emacsen-common-1.4.15/generate-install-list	Tue Jan 29 15:51:49 2002
++++ emacsen-common.fink/generate-install-list	Tue Jun 22 13:47:49 2004
 @@ -8,8 +8,8 @@
  # it will sort them according to their dependencies.  It will also add
  # in other add-on packages that aren't mentioned, but are needed.
