* Fix build error related to libiconv.  On 2008/01/29, rangerrick added am_cv_proto_iconv="" to configure parameters  in 10.4's libiconv.info. Because of this, the argument type of the function  'libiconv' has been changed from     libiconv(void*, const char**, size_t*, char**, size_t*)  to     libiconv(void*, char**, size_t*, char**, size_t*)  in 10.4. See also the configure script of libiconv. After this change,  the second argument of libiconv cannot accept 'const char**'.
 In order to build jgroff with both of previous libiconv and current libiconv,
 I added a patch to configure which checks the declaration of libiconv.
 This is imported from libiconv's configure.

 Thank you for the bug report, Tetsuro KURITA.

diff --git a/10.3/unstable/main/finkinfo/text/jgroff.patch b/10.3/unstable/main/finkinfo/text/jgroff.patch
--- a/10.3/unstable/main/finkinfo/text/jgroff.patch
+++ b/10.3/unstable/main/finkinfo/text/jgroff.patch
@@ -60,16 +60,12 @@ diff -Naur groff-1.18.1.1-debian11/debian/copyright groff-1.18.1.1/debian/copyri
 diff -Naur groff-1.18.1.1-debian11/src/libs/libgroff/encoding.cc groff-1.18.1.1/src/libs/libgroff/encoding.cc
 --- groff-1.18.1.1-debian11/src/libs/libgroff/encoding.cc	Wed Mar 15 15:29:48 2006
 +++ groff-1.18.1.1/src/libs/libgroff/encoding.cc	Thu Mar 16 00:43:18 2006
-@@ -145,6 +145,13 @@
+@@ -145,6 +145,9 @@
    iconv_t icd, ocd;
    const char *encoding_name;
    static iconv_handler *ih_header;
-+#ifdef __DARWIN_VERS_1050
-+ #if __DARWIN_VERS_1050 
-+  typedef char **iconv_arg_type;
-+ #endif
-+#else
-+  typedef const char **iconv_arg_type;
++#ifdef ICONV_CONST
++  typedef ICONV_CONST char **iconv_arg_type;
 +#endif
  
  public:
@@ -104,3 +100,119 @@ diff -Naur groff-1.18.1.1-debian11/tmac/docj.tmac groff-1.18.1.1/tmac/docj.tmac
  ..
  .if !\n(.g .ig
  .de sO
+diff -Naur groff-1.18.1.1-debian11/configure groff-1.18.1.1/configure
+--- groff-1.18.1.1-debian11/configure	2008-04-01 02:33:24.000000000 +0900
++++ groff-1.18.1.1/configure	2008-04-01 04:20:49.000000000 +0900
+@@ -306,6 +306,7 @@
+ #endif"
+ 
+ ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS groff_top_builddir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX TTYDEVDIRS OTHERDEVDIRS LPR LP LPQ PSPRINT DVIPRINT PERLPATH YACC RANLIB ac_ct_RANLIB INSTALL_INFO INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SH_SCRIPT_SED_CMD CPP EGREP LIBM LIBOBJS BROKEN_SPOOLER_FLAGS PAGE g sys_tmac_prefix tmac_wrap pnmcut pnmcrop pnmtopng gs psselect make_html make_install_html DVIFORMAT LTLIBOBJS'
++ac_subst_vars="$ac_subst_vars ICONV_CONST"
+ ac_subst_files=''
+ 
+ # Initialize some variables set by options.
+@@ -6037,6 +6038,104 @@
+ LTLIBOBJS=$ac_ltlibobjs
+ 
+ 
++##### check for iconv
++    { echo "$as_me:$LINENO: checking for iconv declaration" >&5
++echo $ECHO_N "checking for iconv declaration... $ECHO_C" >&6; }
++    if test "${am_cv_proto_iconv+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++
++      cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++#include <stdlib.h>
++#include <iconv.h>
++extern
++#ifdef __cplusplus
++"C"
++#endif
++#if defined(__STDC__) || defined(__cplusplus)
++size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
++#else
++size_t iconv();
++#endif
++
++int
++main ()
++{
++
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext
++if { (ac_try="$ac_compile"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_compile") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
++  { (case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_try") 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest.$ac_objext'
++  { (case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_try") 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  am_cv_proto_iconv_arg1=""
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++	am_cv_proto_iconv_arg1="const"
++fi
++
++rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
++      am_cv_proto_iconv="extern size_t iconv (iconv_t cd, $am_cv_proto_iconv_arg1 char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);"
++fi
++
++    am_cv_proto_iconv=`echo "$am_cv_proto_iconv" | tr -s ' ' | sed -e 's/( /(/'`
++    { echo "$as_me:$LINENO: result: ${ac_t:-
++         }$am_cv_proto_iconv" >&5
++echo "${ECHO_T}${ac_t:-
++         }$am_cv_proto_iconv" >&6; }
++
++cat >>confdefs.h <<_ACEOF
++#define ICONV_CONST $am_cv_proto_iconv_arg1
++_ACEOF
++
++if test -z "$am_cv_proto_iconv_arg1"; then
++  ICONV_CONST=""
++else
++  ICONV_CONST="const"
++fi
++
++DEFS="$DEFS -DICONV_CONST=$ICONV_CONST"
++##### check for iconv
+ 
+ : ${CONFIG_STATUS=./config.status}
+ ac_clean_files_save=$ac_clean_files
