Patch from Matthew Sachs of Apple.

diff --git a/10.4-transitional/unstable/crypto/finkinfo/dods.patch b/10.4-transitional/unstable/crypto/finkinfo/dods.patch
--- a/10.4-transitional/unstable/crypto/finkinfo/dods.patch
+++ b/10.4-transitional/unstable/crypto/finkinfo/dods.patch
@@ -1,69 +1,45 @@
---- DODS/src/packages-3.4.2/libcurl/configure.in.orig	Wed May 26 20:12:33 2004
-+++ DODS/src/packages-3.4.2/libcurl/configure.in	Wed May 26 20:13:34 2004
-@@ -433,7 +433,7 @@
+--- ./DODS/src/dap-3.4.5/configure.bak	2005-04-04 00:44:53.000000000 -0700
++++ ./DODS/src/dap-3.4.5/configure	2005-04-04 00:45:38.000000000 -0700
+@@ -3297,7 +3297,7 @@
+ echo "${ECHO_T}Found egcs version ${GCC_VER}." >&6 ;;
+ 	2.[7-9]*)   echo "$as_me:$LINENO: result: Found gcc/g++ version ${GCC_VER}" >&5
+ echo "${ECHO_T}Found gcc/g++ version ${GCC_VER}" >&6 ;;
+-	3.[0-9]*)   echo "$as_me:$LINENO: result: Found gcc/g++ version ${GCC_VER}" >&5
++	[4-9].*)   echo "$as_me:$LINENO: result: Found gcc/g++ version ${GCC_VER}" >&5
+ echo "${ECHO_T}Found gcc/g++ version ${GCC_VER}" >&6 ;;
+         *)      { { echo "$as_me:$LINENO: error: must be at least version 2.7.x" >&5
+ echo "$as_me: error: must be at least version 2.7.x" >&2;}
+--- ./DODS/src/dap-3.4.5/Operators.h.bak	2005-04-04 00:50:33.000000000 -0700
++++ ./DODS/src/dap-3.4.5/Operators.h	2005-04-04 00:56:13.000000000 -0700
+@@ -37,6 +37,9 @@
+ #define _operators_h
  
-   case "$OPT_SSL" in
-   yes)
--    EXTRA_SSL=/usr/local/ssl ;;
-+    EXTRA_SSL=@PREFIX@/ssl ;;
-   off)
-     EXTRA_SSL= ;;
-   *)
---- DODS/src/dap-3.4.5/configure	Thu May 27 06:51:08 2004
-+++ DODS/src/dap-3.4.5/configure.orig	Thu May 27 06:50:37 2004
-@@ -6570,7 +6570,7 @@
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   ac_check_lib_save_LIBS=$LIBS
--LIBS="-lrx  $LIBS"
-+#LIBS="-lrx  $LIBS"
- cat >conftest.$ac_ext <<_ACEOF
- #line $LINENO "configure"
- /* confdefs.h.  */
-@@ -6619,9 +6619,9 @@
- echo "$as_me:$LINENO: result: $ac_cv_lib_rx_rx_version_string" >&5
- echo "${ECHO_T}$ac_cv_lib_rx_rx_version_string" >&6
- if test $ac_cv_lib_rx_rx_version_string = yes; then
--  HAVE_RX=1; LIBS="$LIBS -lrx"
-+  HAVE_RX=1; LIBS="$LIBS"
- else
--  packages="$packages librx"; HAVE_RX=1; LIBS="$LIBS -lrx"
-+  packages="$packages librx"; HAVE_RX=1; LIBS="$LIBS"
- fi
+ #include <Regex.h>		// GNU Regex class used for string =~ op.
++#include <iostream>
++
++using namespace std;
  
+ static unsigned
+ dods_max(int i1, int i2)
+--- ./DODS/src/dap-3.4.5/RValue.cc.bak	2005-04-04 01:00:51.000000000 -0700
++++ ./DODS/src/dap-3.4.5/RValue.cc	2005-04-04 01:01:13.000000000 -0700
+@@ -110,7 +110,7 @@
+ #ifdef WIN32
+ 	BaseType **argv = (new (BaseType*)) + argc + 1;
+ #else
+-	BaseType **argv = new (BaseType*)[argc + 1];
++	BaseType **argv = new BaseType*[argc + 1];
+ #endif
  
---- DODS/src/nc3-dods-3.4.5/configure	Thu May 27 06:49:56 2004
-+++ DODS/src/nc3-dods-3.4.5/configure.orig	Thu May 27 05:43:31 2004
-@@ -3924,7 +3924,7 @@
-   echo $ac_n "(cached) $ac_c" 1>&6
- else
-   ac_save_LIBS="$LIBS"
--LIBS="-lrx  $LIBS"
-+#LIBS="-lrx  $LIBS"
- cat > conftest.$ac_ext <<EOF
- #line 3920 "configure"
- #include "confdefs.h"
-@@ -3952,10 +3952,10 @@
- fi
- if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-   echo "$ac_t""yes" 1>&6
--  HAVE_RX=1; LIBS="$LIBS -lrx"
-+  HAVE_RX=1; LIBS="$LIBS"
- else
-   echo "$ac_t""no" 1>&6
--packages="$packages librx"; HAVE_RX=1; LIBS="$LIBS -lrx"
-+packages="$packages librx"; HAVE_RX=1; LIBS="$LIBS"
- fi
- 
+ 	int index = 0;
+--- ./DODS/src/nc3-dods-3.4.5/configure.bak	2005-04-04 00:43:35.000000000 -0700
++++ ./DODS/src/nc3-dods-3.4.5/configure	2005-04-04 00:44:14.000000000 -0700
+@@ -2562,7 +2562,7 @@
+     case $GCC_VER in
+         *egcs*) echo "$ac_t""Found egcs version ${GCC_VER}." 1>&6 ;;
+ 	2.[7-9]*)   echo "$ac_t""Found gcc/g++ version ${GCC_VER}" 1>&6 ;;
+-	3.[0-9]*)   echo "$ac_t""Found gcc/g++ version ${GCC_VER}" 1>&6 ;;
++	[4-9].*)   echo "$ac_t""Found gcc/g++ version ${GCC_VER}" 1>&6 ;;
+         *)      { echo "configure: error: must be at least version 2.7.x" 1>&2; exit 1; } ;;
+     esac
      
---- DODS/src/packages-3.4.2/libcurl/curl-config.in.orig	Thu May 27 10:29:13 2004
-+++ DODS/src/packages-3.4.2/libcurl/curl-config.in	Thu May 27 10:29:28 2004
-@@ -115,7 +115,7 @@
-        	;;
- 
-     --libs)
--       	echo -L@libdir@ -lcurl @LDFLAGS@ @LIBS@
-+       	echo -L@libdir@ -lcurl -lrx @LDFLAGS@ @LIBS@
-        	;;
- 
-     *)
