upgraded zope to version 2.6.3

diff --git a/10.3/unstable/main/finkinfo/web/zope-2.6.3-1.patch b/10.3/unstable/main/finkinfo/web/zope-2.6.3-1.patch
--- a/10.3/unstable/main/finkinfo/web/zope-2.6.3-1.patch
+++ b/10.3/unstable/main/finkinfo/web/zope-2.6.3-1.patch
@@ -1,12 +1,12 @@
 diff -ruN zope.orig/z2.py zope/z2.py
---- zope.orig/z2.py	Wed Apr 24 18:49:13 2002
-+++ zope/z2.py	Thu Apr 25 02:59:29 2002
+--- zope.orig/z2.py     Thu Feb 27 07:53:08 2003
++++ zope/z2.py  Sat Jan 10 20:48:04 2004
 @@ -1,3 +1,4 @@
 +#! @PREFIX@/bin/python2.1
  ##############################################################################
  #
  # Copyright (c) 2001 Zope Corporation and Contributors. All Rights Reserved.
-@@ -220,6 +221,9 @@
+@@ -243,6 +244,9 @@
      sys.path.insert(4, '%s/bin/lib/win32/lib' % swhome)
      sys.path.insert(5, '%s' % swhome)
  
@@ -14,24 +14,25 @@ diff -ruN zope.orig/z2.py zope/z2.py
 +import sys
 +sys.path.insert(0, '@PREFIX@/lib/zope/lib/python')
  
- import os, sys, getopt, string, codecs
- # workaround to allow unicode encoding conversions in DTML
-@@ -229,7 +233,9 @@
- 
+ import os, sys, getopt, codecs, string
+ import socket
+@@ -254,7 +258,9 @@
+ sys.setcheckinterval(500)
  
  program=sys.argv[0]
 -here=os.path.join(os.getcwd(), os.path.split(program)[0])
 +#here=os.path.join(os.getcwd(), os.path.split(program)[0])
 +here="@PREFIX@/lib/zope"
 +os.chdir(here)
- Zpid=''
  
  ########################################################################
-@@ -253,7 +259,9 @@
- 
+ # Configuration section
+@@ -274,7 +280,10 @@
  # User id to run ZServer as. Note that this only works under Unix, and if
- # ZServer is started by root.
--UID='nobody'
+ # ZServer is started by root. This no longer defaults to 'nobody' since
+ # that can lead to a Zope file compromise.
+-UID=None
++# UID=None
 +## For fink, this has been changed from 'nobody' to 'www'
 +## which is also the apache web user
 +UID='www'
@@ -322,13 +323,13 @@ diff -ruN zope.orig/zpasswd.py zope/zpasswd.py
  ##############################################################################
  #
  # Copyright (c) 2001 Zope Corporation and Contributors. All Rights Reserved.
-diff -ruN orig/zopectl zope/zopectl
---- orig/zopectl	Thu Jan  1 01:00:00 1970
-+++ zope/zopectl	Thu Oct 24 21:59:03 2002
-@@ -0,0 +1,265 @@
+diff -ruN zope.orig/zopectl zope/zopectl
+--- zope.orig/zopectl	Wed Dec 31 16:00:00 1969
++++ zope/zopectl	Sun Jan 11 00:15:53 2004
+@@ -0,0 +1,195 @@
 +#!/bin/sh
 +#
-+# /sw/sbin/zopectl
++# @PREFIX@/sbin/zopectl
 +#
 +# Written by Gregor Hoffleit <flight@debian.org> for the Debian Zope package.
 +# Modified for fink by Kilian Koepsell <kilian@users.sourceforge.net>
@@ -337,15 +338,14 @@ diff -ruN orig/zopectl zope/zopectl
 +#
 +#
 +# This is a comfortable replacement for Zope's start and stop scripts
-+# It let's you start, stop, restart and examine a Zope process managed
-+# by a zdaemon.
++# It let's you start, stop, restart and examine a Zope process 
 +#
 +
 +# include local settings
-+. /sw/etc/zope/zope.cnf
++. @PREFIX@/etc/zope/zope.cnf
 +
 +# include fink path of python
-+PATH=/sw/bin:$PATH                        
++PATH=@PREFIX@/bin:$PATH                        
 +export PATH
 +
 +if [ `whoami` != "root" ]
@@ -368,8 +368,6 @@ diff -ruN orig/zopectl zope/zopectl
 +    shift
 +fi
 +
-+zdaemon_pidfile=$INSTANCE_HOME/var/zProcessManager.pid
-+zdaemon_logfile=$INSTANCE_HOME/var/Z2_debug.log
 +zope_pidfile=$INSTANCE_HOME/var/Z2.pid
 +zope_logfile=$INSTANCE_HOME/var/Z2.log
 +
@@ -378,23 +376,6 @@ diff -ruN orig/zopectl zope/zopectl
 +
 +
 +export INSTANCE_HOME
-+
-+test_zdaemon() {
-+    if [ -f $zdaemon_pidfile ]; then
-+        zdaemon_pid=`cat $zdaemon_pidfile`
-+	if [ ! "x$zdaemon_pid" = "x" ] && kill -0 $zdaemon_pid 2>/dev/null; then
-+	    zdaemon=1
-+	    true
-+	else
-+	    zdaemon=-1
-+	    rm -f $zdaemon_pidfile
-+	    false
-+	fi
-+    else
-+	zdaemon=0
-+	false
-+    fi
-+}
 +
 +test_zope() {
 +    if [ -f $zope_pidfile ]; then
@@ -415,23 +396,13 @@ diff -ruN orig/zopectl zope/zopectl
 +
 +waitfor_zope() {
 +    timeout=100
-+    test_zdaemon
 +    test_zope
-+    while [ $timeout -gt 0 -a ! $zdaemon -eq 1 ]; do
-+        sleep 1
-+        echo -n '.'
-+        test_zdaemon
-+        timeout=`expr $timeout - 1`
-+    done
-+    if [ $zdaemon -eq 1 ]; then
-+	test_zope
 +	while [ $timeout -gt 0 -a ! $zope -eq 1 ]; do
 +	    sleep 1
 +	    echo -n '.'
 +	    test_zope
 +	    timeout=`expr $timeout - 1`
 +	done
-+    fi
 +    if [ $zope -eq 1 ]; then
 +        true
 +    else
@@ -439,26 +410,10 @@ diff -ruN orig/zopectl zope/zopectl
 +    fi
 +}
 +
-+start_zdaemon() {
-+    /sw/sbin/zope-z2 $ZOPEOPTS $@
++start_zope() {
++    @PREFIX@/sbin/zope-z2 $ZOPEOPTS $@
 +}
 +
-+
-+stop_zdaemon() {
-+    test_zdaemon
-+    if [ $zdaemon -eq 1 ]; then
-+        kill $zdaemon_pid 2>/dev/null && true
-+        test_zdaemon
-+        if [ $zdaemon -eq -1 ]; then
-+            rm -f $zdaemon_pidfile
-+        fi
-+    else
-+        if [ $zdaemon -eq -1 ]; then
-+            rm -f $zdaemon_pidfile
-+	    echo "Removed stale zdaemon pidfile (pid $zdaemon_pid)."
-+        fi
-+    fi
-+}
 +
 +stop_zope() {
 +    test_zope
@@ -481,29 +436,19 @@ diff -ruN orig/zopectl zope/zopectl
 +case $OPTION in
 +
 +status)
-+    test_zdaemon
 +    test_zope
-+    if [ $zdaemon -eq 1 ]; then
 +        if [ $zope -eq 1 ]; then
-+            echo "Zope running (zdaemon pid=$zdaemon_pid, z2 pid=$zope_pid)."
-+	else
-+	    echo "Zope (re)starting (zdaemon pid=$zdaemon_pid, no z2)."
-+	fi
-+    else
-+        if [ $zope -eq 1 ]; then
-+	    echo "Problem: Found z2 process, but no zdaemon (z2 pid=$zope_pid, no zdaemon). Please stop Zope and restart."
++            echo "Zope running (pid=$zope_pid)."
 +	else
 +	    echo "Zope not running."
 +	fi
-+    fi
 +    ;;
 +
 +start)
-+    test_zdaemon
 +    test_zope
 +    echo -n "Starting Zope..."
-+    if [ ! $zdaemon -eq 1 ] && [ ! $zope -eq 1 ]; then
-+        start_zdaemon $@
++    if [ ! $zope -eq 1 ]; then
++        start_zope $@
 +        if waitfor_zope; then
 +            echo " done."
 +        else
@@ -511,38 +456,20 @@ diff -ruN orig/zopectl zope/zopectl
 +            false
 +        fi
 +    else
-+        if [ $zdaemon -eq 1 ] && [ $zope -eq 1 ]; then
++        if [ $zope -eq 1 ]; then
 +	    echo " done (Zope already running)."
-+	else
-+	    if [ $zdaemon -eq 1 ]; then
-+	        echo " Zope is currently restarting."
-+	    else
-+	        echo "Only z2 running! This should not happen. Please stop and restart Zope!"
-+	    fi
-+	    false
 +	fi
 +    fi
-+
 +    ;;
 +
 +stop)
 +    echo -n "Stopping Zope..."
-+    test_zdaemon
 +    test_zope
-+    if [ $zdaemon -eq 0 ] && [ $zdaemon -eq 0 ]; then
++    if [ $zope -eq 0 ]; then
 +        echo " done (Zope was not running)."
 +	not_running=1
 +    else
 +        not_running=0
-+    fi
-+    if [ $zdaemon -eq 1 ]; then
-+        stop_zdaemon
-+	#echo -n " [zdaemon process killed (pid $zdaemon_pid)]"
-+    else
-+        if [ $zdaemon -eq -1 ]; then
-+	    rm -f $zdaemon_pidfile
-+	    echo -n " [removed stale zdaemon pidfile (pid $zdaemon_pid)]"
-+	fi
 +    fi
 +    test_zope
 +    if [ $zope -eq 1 ]; then
@@ -561,29 +488,33 @@ diff -ruN orig/zopectl zope/zopectl
 +    ;;
 +
 +restart)
-+    test_zdaemon
 +    test_zope
-+    if [ ! $zdaemon -eq 1 ] && [ ! $zope -eq 1 ]; then
++    if [ ! $zope -eq 1 ]; then
 +	 echo -n "Starting Zope..."
-+         start_zdaemon
++         start_zope
 +         waitfor_zope
 +         echo " done."
 +    else
-+        if [ $zdaemon -eq 1 ] && [ $zope -eq 1 ]; then
++        if [ $zope -eq 1 ]; then
 +	    echo -n "Restarting Zope..."
 +	    stop_zope
 +            sleep 3
-+            waitfor_zope
-+            echo " done."
-+	else
++            start_zope $@
++            if waitfor_zope; then
++                echo " done."
++            else
++                echo " failed."
++                false
++            fi
++        else
 +	    echo "Zope is currently restarting (or something's very strange)."
 +	fi
 +    fi
 +    ;;
 +
 +force-reload)
-+    /sw/sbin/zopectl stop || true
-+    /sw/sbin/zopectl start $@ || true
++    @PREFIX@/sbin/zopectl stop || true
++    @PREFIX@/sbin/zopectl start $@ || true
 +    ;;
 +
 +*)
