I missed a cp -l invocation in pop.in. Hope this version works.

diff --git a/10.4-transitional/unstable/main/finkinfo/devel/quilt.patch b/10.4-transitional/unstable/main/finkinfo/devel/quilt.patch
--- a/10.4-transitional/unstable/main/finkinfo/devel/quilt.patch
+++ b/10.4-transitional/unstable/main/finkinfo/devel/quilt.patch
@@ -1,6 +1,6 @@
 diff -r 96be197f975c Makefile.in
 --- a/Makefile.in	Thu Nov 10 07:54:14 2005
-+++ b/Makefile.in	Thu Nov 10 23:35:48 2005
++++ b/Makefile.in	Fri Nov 11 22:36:46 2005
 @@ -41,8 +41,8 @@
  ISODATE :=	$(shell date +%Y-%m-%d)
  
@@ -58,7 +58,7 @@ diff -r 96be197f975c Makefile.in
  
 diff -r 96be197f975c lib/backup-files.c
 --- a/lib/backup-files.c	Thu Nov 10 07:54:14 2005
-+++ b/lib/backup-files.c	Thu Nov 10 23:35:48 2005
++++ b/lib/backup-files.c	Fri Nov 11 22:36:46 2005
 @@ -37,7 +37,7 @@
  #include <errno.h>
  #include <string.h>
@@ -192,28 +192,8 @@ diff -r 96be197f975c lib/backup-files.c
  		if (status)
 diff -r 96be197f975c quilt/diff.in
 --- a/quilt/diff.in	Thu Nov 10 07:54:14 2005
-+++ b/quilt/diff.in	Thu Nov 10 23:35:48 2005
-@@ -330,6 +330,19 @@
- 	files=( $(sort -u $tmp_files) )
- fi
- 
-+mycpl ()
-+{
-+  target=$1
-+  shift;
-+
-+  for src in "$@"
-+  do
-+    srcdir="${src%/*}"
-+    test -n "$srcdir" && mkdir -p "$target/$srcdir"
-+    ln $src "$target/$src"
-+  done
-+}
-+
- if [ -n "$opt_relative" ]
- then
- 	patch_file=$(patch_file_name $last_patch)
-@@ -338,7 +351,7 @@
++++ b/quilt/diff.in	Fri Nov 11 22:36:46 2005
+@@ -338,7 +338,7 @@
  
  	if [ ${#files[@]} -gt 0 ] \
  	   && ! ( cd $QUILT_PC/$last_patch &&
@@ -224,7 +204,7 @@ diff -r 96be197f975c quilt/diff.in
  		die 1
 diff -r 96be197f975c quilt/mail.in
 --- a/quilt/mail.in	Thu Nov 10 07:54:14 2005
-+++ b/quilt/mail.in	Thu Nov 10 23:35:48 2005
++++ b/quilt/mail.in	Fri Nov 11 22:36:46 2005
 @@ -52,8 +52,8 @@
  
  msgid()
@@ -278,7 +258,7 @@ diff -r 96be197f975c quilt/mail.in
  	| quilt_mail_patch_filter $patch > $body
 diff -r 96be197f975c quilt/pop.in
 --- a/quilt/pop.in	Thu Nov 10 07:54:14 2005
-+++ b/quilt/pop.in	Thu Nov 10 23:35:48 2005
++++ b/quilt/pop.in	Fri Nov 11 22:36:46 2005
 @@ -52,7 +52,7 @@
  {
  	local n=0 patch
@@ -301,9 +281,18 @@ diff -r 96be197f975c quilt/pop.in
  		[ -z "$ts" ] && return 0
  		[ "$ts" -gt $apply_ts ] && return 0
  	done
+@@ -109,7 +109,7 @@
+ 	if [ -d $QUILT_PC/$patch ]
+ 	then
+ 		if ! rmdir $workdir ||  # note that this is racey...
+-		   ! cp -rl $QUILT_PC/$patch $workdir
++		   ! (for i in "$(find "$QUILT_PC/$patch" -type f)"; do mycpl $workdir $i; done)
+ 		then
+ 			printf $"Failed to copy files to temporary directory\n" >&2
+ 			rm -rf $workdir
 diff -r 96be197f975c scripts/dependency-graph.in
 --- a/scripts/dependency-graph.in	Thu Nov 10 07:54:14 2005
-+++ b/scripts/dependency-graph.in	Thu Nov 10 23:35:48 2005
++++ b/scripts/dependency-graph.in	Fri Nov 11 22:36:46 2005
 @@ -241,7 +241,7 @@
  			print STDERR "$ENV{QUILT_PC}/$patch does not exist; skipping\n";
  			next;
@@ -315,7 +304,7 @@ diff -r 96be197f975c scripts/dependency-graph.in
  	push @nodes, {number=>$n++, name=>$patch, file=>$patch,
 diff -r 96be197f975c scripts/inspect.in
 --- a/scripts/inspect.in	Thu Nov 10 07:54:14 2005
-+++ b/scripts/inspect.in	Thu Nov 10 23:35:48 2005
++++ b/scripts/inspect.in	Fri Nov 11 22:36:46 2005
 @@ -130,7 +130,7 @@
  		if ! [ -e $tmpdir/more-md5sums ]
  		then
@@ -327,8 +316,8 @@ diff -r 96be197f975c scripts/inspect.in
  			) > $tmpdir/more-md5sums
 diff -r 96be197f975c scripts/patchfns.in
 --- a/scripts/patchfns.in	Thu Nov 10 07:54:14 2005
-+++ b/scripts/patchfns.in	Thu Nov 10 23:35:48 2005
-@@ -67,6 +67,14 @@
++++ b/scripts/patchfns.in	Fri Nov 11 22:36:46 2005
+@@ -67,6 +67,27 @@
  
  # ========================================================
  
@@ -340,10 +329,23 @@ diff -r 96be197f975c scripts/patchfns.in
 +  echo $fmt
 +}
 +
++mycpl ()
++{
++  target=$1
++  shift;
++
++  for src in "$@"
++  do
++    srcdir="${src%/*}"
++    test -n "$srcdir" && mkdir -p "$target/$srcdir"
++    ln $src "$target/$src"
++  done
++}
++
  # Quote a string for use in a basic regular expression.
  quote_bre()
  {
-@@ -542,8 +550,7 @@
+@@ -542,8 +563,7 @@
  		|| old_date=$'\t'"1970-01-01 00:00:00.000000000 +0000"
  	else
  		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
@@ -353,7 +355,7 @@ diff -r 96be197f975c scripts/patchfns.in
  	fi
  	if ! [ -s "$new_file" ]
  	then
-@@ -553,8 +560,7 @@
+@@ -553,8 +573,7 @@
  		|| new_date=$'\t'"1970-01-01 00:00:00.000000000 +0000"
  	else
  		[ -n "$QUILT_NO_DIFF_TIMESTAMPS" ] \
@@ -365,7 +367,7 @@ diff -r 96be197f975c scripts/patchfns.in
  	@DIFF@ -N $QUILT_DIFF_OPTS $old_file $new_file \
 diff -r 96be197f975c reference.sed
 --- /dev/null	Thu Nov 10 07:54:14 2005
-+++ b/reference.sed	Thu Nov 10 23:35:48 2005
++++ b/reference.sed	Fri Nov 11 22:36:46 2005
 @@ -0,0 +1,3 @@
 +/^Usage:/{s/^Usage: \?//;b
 +}
