Version bumped

diff --git a/10.3/unstable/main/finkinfo/x11/openoffice.org.patch b/10.3/unstable/main/finkinfo/x11/openoffice.org.patch
--- a/10.3/unstable/main/finkinfo/x11/openoffice.org.patch
+++ b/10.3/unstable/main/finkinfo/x11/openoffice.org.patch
@@ -1,138 +1,319 @@
-IssueTracker: #i50016#
-CWS: macosx09
-Description:
-Author:
-
-Index: scp2/source/ooo/file_library_ooo.scp
+Index: instsetoo_native/util/makefile.mk
 ===================================================================
-RCS file: /cvs/installation/scp2/source/ooo/file_library_ooo.scp,v
-retrieving revision 1.103
-diff -u -r1.103 file_library_ooo.scp
---- scp2/source/ooo/file_library_ooo.scp	31 May 2005 17:08:10 -0000	1.103
-+++ scp2/source/ooo/file_library_ooo.scp	7 Jun 2005 02:30:15 -0000
-@@ -2135,7 +2135,7 @@
-     TXT_FILE_BODY;
-     #ifdef UNX
-         #ifdef MACOSX
--            Name = STRING(CONCAT2(libxmlsec1,UNXSUFFIX));
-+            Name = STRING(CONCAT2(libxmlsec1.1.2.6,UNXSUFFIX));
-         #else
-             Name = STRING(CONCAT3(libxmlsec1,UNXSUFFIX,.1.2.6));
-         #endif
-@@ -2159,7 +2159,7 @@
- File gid_File_Lib_LibXMLSec_xmlsecnss
-     TXT_FILE_BODY;
-     #ifdef MACOSX
--        Name = STRING(CONCAT2(libxmlsec1-nss,UNXSUFFIX));
-+        Name = STRING(CONCAT2(libxmlsec1-nss.1.2.6,UNXSUFFIX));
-     #else
-         Name = STRING(CONCAT3(libxmlsec1-nss,UNXSUFFIX,.1.2.6));
-     #endif
-Index: scp2/source/ooo/shortcut_ooo.scp
-===================================================================
-RCS file: /cvs/installation/scp2/source/ooo/shortcut_ooo.scp,v
-retrieving revision 1.17
-diff -u -r1.17 shortcut_ooo.scp
---- scp2/source/ooo/shortcut_ooo.scp	27 Apr 2005 08:53:55 -0000	1.17
-+++ scp2/source/ooo/shortcut_ooo.scp	7 Jun 2005 02:30:15 -0000
-@@ -67,7 +67,11 @@
- Shortcut gid_Shortcut_Lib_Xml2
-     FileID = gid_File_Lib_Xml2;
-     Dir = gid_Dir_Program;
-+#ifdef MACOSX
-+    Name = STRING(CONCAT2(libxml2.2,UNXSUFFIX));
-+#else
-     Name = STRING(CONCAT3(libxml2,UNXSUFFIX,.2));
-+#endif
-     Styles = (NETWORK,RELATIVE);
- End
+RCS file: /cvs/installation/instsetoo_native/util/makefile.mk,v
+retrieving revision 1.34
+diff -u -r1.34 makefile.mk
+--- instsetoo_native/util/makefile.mk	11 Jul 2005 15:37:26 -0000	1.34
++++ instsetoo_native/util/makefile.mk	27 Jul 2005 02:53:04 -0000
+@@ -152,6 +152,9 @@
  
-@@ -450,7 +454,11 @@
- Shortcut gid_Shortcut_Lib_LibXMLSec_xmlseccore
-     FileID = gid_File_Lib_LibXMLSec_xmlseccore;
-     Dir = gid_Dir_Program;
-+#ifdef MACOSX
-+    Name = STRING(CONCAT2(libxmlsec1.1,UNXSUFFIX));
-+#else
-     Name = STRING(CONCAT3(libxmlsec1,UNXSUFFIX,.1));
-+#endif
-     Styles = (NETWORK,RELATIVE);
- End
- #endif
-@@ -468,7 +476,11 @@
- Shortcut gid_Shortcut_Lib_LibXMLSec_xmlsecnss
-     FileID = gid_File_Lib_LibXMLSec_xmlsecnss;
-     Dir = gid_Dir_Program;
-+#ifdef MACOSX
-+    Name = STRING(CONCAT2(libxmlsec1-nss.1,UNXSUFFIX));
-+#else
-     Name = STRING(CONCAT3(libxmlsec1-nss,UNXSUFFIX,.1));
-+#endif
-     Styles = (NETWORK,RELATIVE);
- End
- #endif
-IssueTracker: #i50317#
-CWS: macosx09
-Description:
-Author:
+ openoffice_%:
+ 	+$(PERL) -w $(SOLARENV)$/bin$/make_installer.pl -f $(PRJ)$/util$/openoffice.lst -l $(@:s/openoffice_//) -p OpenOffice -packagelist $(PRJ)$/inc_openoffice$/unix$/packagelist.txt -u $(OUT) -buildid $(BUILD) -msitemplate $(MSIOFFICETEMPLATEDIR) -msilanguage $(COMMONMISC)$/win_ulffiles -addsystemintegration $(PKGFORMATSWITCH)
++.IF "$(OS)" = "MACOSX"
++       +$(SOLARENV)$/unxmacxp$/bin$/create-package $*
++.ENDIF
+ 
+ openofficewithjre_%:
+ 	+$(PERL) -w $(SOLARENV)$/bin$/make_installer.pl -f $(PRJ)$/util$/openoffice.lst -l $(@:s/openofficewithjre_//) -p OpenOffice_wJRE -packagelist $(PRJ)$/inc_openoffice$/unix$/packagelist.txt -u $(OUT) -buildid $(BUILD) -msitemplate $(MSIOFFICETEMPLATEDIR) -msilanguage $(COMMONMISC)$/win_ulffiles -addchildprojects -addsystemintegration $(PKGFORMATSWITCH)
 
-cvs diff: warning: failed to open /var/root/.cvspass for reading: No such file or directory
-Index: stlport/STLport-4.5-macxp-panther.patch
-===================================================================
-RCS file: /cvs/external/stlport/STLport-4.5-macxp-panther.patch,v
-retrieving revision 1.3
-diff -u -r1.3 STLport-4.5-macxp-panther.patch
---- stlport/STLport-4.5-macxp-panther.patch	31 May 2005 17:03:59 -0000	1.3
-+++ stlport/STLport-4.5-macxp-panther.patch	5 Jun 2005 03:10:53 -0000
-@@ -159,7 +159,7 @@
- ! #
- ! #
- ! LINK=libtool -static -o
--! DYN_LINK=g++ -dynamiclib -single_module -install_name @executable_path/libstlport_gcc.dylib -o
-+! DYN_LINK=$(CXX) -dynamiclib -single_module -install_name @executable_path/libstlport_gcc.dylib -o
- ! 
- ! OBJEXT=o
- ! DYNEXT=dylib
-#i51126#, macosx09
-
-
-Index: scp2/source/ure/ure.scp
-===================================================================
-RCS file: /cvs/installation/scp2/source/ure/ure.scp,v
-retrieving revision 1.2
-diff -u -r1.2 ure.scp
---- scp2/source/ure/ure.scp	17 Jun 2005 10:18:35 -0000	1.2
-+++ scp2/source/ure/ure.scp	21 Jun 2005 22:24:56 -0000
-@@ -601,7 +601,11 @@
- #if defined WNT
-     Name = SCP2_URE_DL_NORMAL(libxml2);
- #else
--    Name = SCP2_URE_DL_VER(xml2, 2);
-+    #ifdef MACOSX
-+       Name = STRING(CONCAT3(libxml2,.2.6.17,UNXSUFFIX));
-+    #else
-+       Name = SCP2_URE_DL_VER(xml2,2.6.17);
-+    #endif
- #endif
-     Styles = (PACKED);
- End
---- scp2/source/ooo/file_ooo.scp	2005-06-28 03:31:33.000000000 +0200
-+++ scp2/source/ooo/file_ooo.scp	2005-06-28 03:33:57.000000000 +0200
-@@ -900,8 +900,6 @@
+--- /dev/null	2005-07-27 11:39:54.000000000 +0900
++++ solenv/unxmacxp/bin/create-package	2005-07-27 11:42:12.000000000 +0900
+@@ -0,0 +1,262 @@
++#!/bin/sh
++#*************************************************************************
++#
++#   $RCSfile: patch-#i42998#,v $
++#
++#   $Revision: 1.3 $
++#
++#   last change: $Author: maho $ $Date: 2005/07/28 09:28:46 $
++#
++#   The Contents of this file are made available subject to the terms of
++#   either of the following licenses
++#
++#          - GNU Lesser General Public License Version 2.1
++#          - Sun Industry Standards Source License Version 1.1
++#
++#   Sun Microsystems Inc., October, 2000
++#
++#   GNU Lesser General Public License Version 2.1
++#   =============================================
++#   Copyright 2000 by Sun Microsystems, Inc.
++#   901 San Antonio Road, Palo Alto, CA 94303, USA
++#
++#   This library is free software; you can redistribute it and/or
++#   modify it under the terms of the GNU Lesser General Public
++#   License version 2.1, as published by the Free Software Foundation.
++#
++#   This library is distributed in the hope that it will be useful,
++#   but WITHOUT ANY WARRANTY; without even the implied warranty of
++#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
++#   Lesser General Public License for more details.
++#
++#   You should have received a copy of the GNU Lesser General Public
++#   License along with this library; if not, write to the Free Software
++#   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
++#   MA  02111-1307  USA
++#
++#
++#   Sun Industry Standards Source License Version 1.1
++#   =================================================
++#   The contents of this file are subject to the Sun Industry Standards
++#   Source License Version 1.1 (the "License"); You may not use this file
++#   except in compliance with the License. You may obtain a copy of the
++#   License at http://www.openoffice.org/license.html.
++#
++#   Software provided under this License is provided on an "AS IS" basis,
++#   WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
++#   WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
++#   MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
++#   See the License for the specific provisions governing your rights and
++#   obligations concerning the Software.
++#
++#   The Initial Developer of the Original Code is: Sun Microsystems, Inc.
++#
++#   Copyright: 2000 by Sun Microsystems, Inc.
++#
++#   All Rights Reserved.
++#
++#   Contributor(s): _______________________________________
++#
++#
++#
++#*************************************************************************
++# 
++# Notes: It may be necessary to do a little more generalization/work with variables in the future
++
++if [ "x${SRC_ROOT}x" == "xx" ]; then
++	echo "Please make sure to source the environment variable script!"
++	exit 1
++fi
++
++OS_LOW=`uname -s | tr A-Z a-z`
++CPU_LOW=`echo $CPUNAME | tr A-Z a-z`
++KERNELVER=`uname -r | sed 's/\([0-9]\.[0-9]\).*/\1/'`
++PACKDIR="${OS_LOW}-${KERNELVER}-${CPU_LOW}"
++MINOR=`grep LAST_MINOR ${SRC_ROOT}/solenv/inc/minor.mk | sed 's/LAST_MINOR=m\(.*\)/\1/'`
++SOLVERBINOSL="${SOLARVERSION}/${INPATH}/bin/osl"
++
++if [ "x${1}x" == "xx" ]; then
++	echo "No language argument present. Exiting."
++	exit 3
++fi
++
++LANG=$1
++
++DESTDIR="${SRC_ROOT}/instsetoo_native/unxmacxp.pro/OpenOffice/install/${LANG}"
++
++if [ ! -d ${DESTDIR} ]; then
++	echo "Something wrong!"
++	exit 2
++fi
++
++cd ${DESTDIR}
++
++PKGNAME="OpenOffice.org-1.9.${MINOR}_${LANG}"
++PKGDIR="${PKGNAME}.mpkg/Contents"
++
++if [ -d "${PKGDIR}" ]; then
++	if [ -x /Developer/Tools/SetFile ]; then
++	#This unlocks the package with a Finder flag so that removing is possible
++	/Developer/Tools/SetFile -a l `dirname ${PKGDIR}`
++	fi
++	rm -rf ${PKGDIR}
++fi
++
++mkdir -p ${PKGDIR}/Resources
++mv ${PACKDIR} ${PKGDIR}
++
++#why do we need this?
++#iconv -f UTF-8 -t MAC "${SOLVERBINOSL}/LICENSE_${LANG}" >${PKGDIR}/Resources/License.txt
++#iconv -f UTF-8 -t MAC "${SOLVERBINOSL}/README_${LANG}" >${PKGDIR}/Resources/Readme.txt
++
++cat >${PKGDIR}/${PACKDIR}/openofficeorg-core01.pkg/Contents/Resources/InstallationCheck <<EOF
++#!/bin/sh
++
++VERS=`sw_vers -productVersion`
++MINOR=`echo $VERS | sed 's/10.\([0-9]\).\([0-9]\)/\1/'`
++if [ "$MINOR" -lt "3" ]; then
++	exit 112
++else
++	exit 0
++fi
++EOF
++chmod 755 ${PKGDIR}/${PACKDIR}/openofficeorg-core01.pkg/Contents/Resources/InstallationCheck
++
++echo "\"16\" = \"Sorry, currently OpenOffice.org 2.0 can only be installed on MacOSX 10.3 and greater!\"" >${PKGDIR}/${PACKDIR}/openofficeorg-core01.pkg/Contents/Resources/InstallationCheck.strings
++chmod 644 ${PKGDIR}/${PACKDIR}/openofficeorg-core01.pkg/Contents/Resources/InstallationCheck.strings
++
++echo "pmkrpkg1" > ${PKGDIR}/PkgInfo
++cat >${PKGDIR}/Resources/Description.plist <<EOF
++<?xml version="1.0" encoding="UTF-8"?>
++<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
++<plist version="1.0">
++<dict>
++	<key>IFPkgDescriptionDeleteWarning</key>
++	<string></string>
++	<key>IFPkgDescriptionDescription</key>
++	<string></string>
++	<key>IFPkgDescriptionTitle</key>
++	<string>OpenOffice.org2.0</string>
++	<key>IFPkgDescriptionVersion</key>
++EOF
++echo "	<string>1.9.${MINOR}</string>" >>${PKGDIR}/Resources/Description.plist
++cat >>${PKGDIR}/Resources/Description.plist <<EOF
++</dict>
++</plist>
++EOF
++
++echo "Title OpenOffice.org2.0" >${PKGDIR}/Resources/${PKGNAME}.info 
++echo "Version 1.9.${MINOR}" >>${PKGDIR}/Resources/${PKGNAME}.info
++cat >>${PKGDIR}/Resources/${PKGNAME}.info <<EOF
++Description 
++DefaultLocation /
++DeleteWarning 
++
++### Package Flags
++
++NeedsAuthorization NO
++Required NO
++Relocatable NO
++RequiresReboot NO
++UseUserMask NO
++OverwritePermissions NO
++InstallFat NO
++RootVolumeOnly NO
++EOF
++
++cat >${PKGDIR}/Info.plist <<EOF
++<?xml version="1.0" encoding="UTF-8"?>
++<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
++<plist version="1.0">
++<dict>
++	<key>CFBundleGetInfoString</key>
++EOF
++echo "	<string>OpenOffice.org 1.9.${MINOR}</string>" >>${PKGDIR}/Info.plist
++cat >>${PKGDIR}/Info.plist <<EOF
++	<key>CFBundleIdentifier</key>
++	<string>org.openoffice.soffice</string>
++	<key>CFBundleName</key>
++	<string>OpenOffice.org</string>
++	<key>CFBundleShortVersionString</key>
++	<string>2.0</string>
++	<key>IFMajorVersion</key>
++	<integer>2</integer>
++	<key>IFMinorVersion</key>
++	<integer>0</integer>
++	<key>IFPkgFlagAllowBackRev</key>
++	<false/>
++	<key>IFPkgFlagAuthorizationAction</key>
++	<string>NoAuthorization</string>
++	<key>IFPkgFlagComponentDirectory</key>
++	<string>..</string>
++	<key>IFPkgFlagDefaultLocation</key>
++	<string>/</string>
++	<key>IFPkgFlagFollowLinks</key>
++	<false/>
++	<key>IFPkgFlagInstallFat</key>
++	<false/>
++	<key>IFPkgFlagIsRequired</key>
++	<false/>
++	<key>IFPkgFlagOverwritePermissions</key>
++	<false/>
++	<key>IFPkgFlagPackageList</key>
++	<array>
++EOF
++for pkg in `ls -d ${PKGDIR}/${PACKDIR}/*.pkg`; do
++	echo "		<dict>" >>${PKGDIR}/Info.plist
++	echo "			<key>IFPkgFlagPackageLocation</key>" >>${PKGDIR}/Info.plist
++	echo "			<string>./${pkg}</string>" >>${PKGDIR}/Info.plist
++	echo "			<key>IFPkgFlagPackageSelection</key>" >>${PKGDIR}/Info.plist
++	pkg2=`echo ${pkg} | sed 's/openofficeorg-core//'`
++	if [ "${pkg2}" != "${pkg}" ]; then
++		echo "			<string>required</string>" >>${PKGDIR}/Info.plist
++	else
++		pkg2=`echo ${pkg} | sed 's/openofficeorg-testtool//'`
++		if [ "${pkg2}" != "${pkg}" ]; then
++			echo "			<string>unselected</string>" >>${PKGDIR}/Info.plist
++		else
++			echo "			<string>selected</string>" >>${PKGDIR}/Info.plist
++		fi
++	fi
++	echo "		</dict>" >>${PKGDIR}/Info.plist
++done
++cat >>${PKGDIR}/Info.plist <<EOF
++	</array>
++	<key>IFPkgFlagRelocatable</key>
++	<true/>
++	<key>IFPkgFlagRestartAction</key>
++	<string>NoRestart</string>
++	<key>IFPkgFlagRootVolumeOnly</key>
++	<false/>
++	<key>IFPkgFlagUpdateInstalledLanguages</key>
++	<false/>
++	<key>IFPkgFlagUseUserMask</key>
++	<false/>
++	<key>IFPkgFormatVersion</key>
++	<real>0.10000000149011612</real>
++</dict>
++</plist>
++EOF
++
++if [ -x /Developer/Tools/SetFile ]; then
++	#This locks the package with a Finder flag so that no renaming is possible
++	/Developer/Tools/SetFile -a L `dirname ${PKGDIR}`
++fi
++
++### Creating dmg
++VOLUMENAME="OpenOffice.org for Mac OS X"
++OOOSIZE=`expr $(du -ks | awk '{print $1}') + 10240`
++hdiutil create -size ${OOOSIZE}k ${PKGNAME}.tmp -layout NONE
++OOODEV=$(hdid -nomount ${PKGNAME}.tmp.dmg)
++newfs_hfs -v "${VOLUMENAME}" $OOODEV
++hdiutil eject $OOODEV
++hdid ${PKGNAME}.tmp.dmg
++/bin/cp -pR ${PKGNAME}.mpkg "/Volumes/${VOLUMENAME}"
++hdiutil eject $OOODEV
++hdiutil convert -format UDZO ${PKGNAME}.tmp.dmg -o ${PKGNAME}.dmg
++rm ${PKGNAME}.tmp.dmg
++
++#This unlocks the package with a Finder flag.
++if [ -x /Developer/Tools/SetFile ]; then
++    /Developer/Tools/SetFile -a l `dirname ${PKGDIR}`
++fi
+diff -ur package/inc/ZipPackageFolder.hxx package_new/inc/ZipPackageFolder.hxx
+--- package/inc/ZipPackageFolder.hxx	2005-07-12 14:28:10.000000000 +0200
++++ package_new/inc/ZipPackageFolder.hxx	2005-07-14 17:30:52.000000000 +0200
+@@ -121,7 +121,7 @@
+ 	}
  
- #ifndef SYSTEM_MOZILLA
+ 	void setPackageFormat_Impl( sal_Bool bPackageFormat ) { m_bPackageFormat = bPackageFormat; }
+-	void setRemoveOnInsertMode_Impl( sal_Bool bRemove ) { ZipPackageEntry::mbAllowRemoveOnInsert = bRemove; }
++	void setRemoveOnInsertMode_Impl( sal_Bool bRemove ) { this->mbAllowRemoveOnInsert = bRemove; }
  
--#ifndef MACOSX
--
- File gid_File_Mozilla_Runtime
-     TXT_FILE_BODY;
-     Styles = (ARCHIVE);
-@@ -913,8 +911,6 @@
+ 	// Recursive functions
+ 	void  saveContents(rtl::OUString &rPath, std::vector < com::sun::star::uno::Sequence < com::sun::star::beans::PropertyValue > > &rManList, ZipOutputStream & rZipOut, com::sun::star::uno::Sequence < sal_Int8 > &rEncryptionKey, rtlRandomPool & rRandomPool)
+diff -ur package/source/zippackage/ZipPackageFolder.cxx package_new/source/zippackage/ZipPackageFolder.cxx
+--- package/source/zippackage/ZipPackageFolder.cxx	2005-07-12 14:31:33.000000000 +0200
++++ package_new/source/zippackage/ZipPackageFolder.cxx	2005-07-14 17:31:14.000000000 +0200
+@@ -128,7 +128,7 @@
+ {
+ 	OSL_ENSURE( m_xFactory.is(), "No factory is provided to the package folder!" );
  
- #endif
+-	ZipPackageEntry::mbAllowRemoveOnInsert = bAllowRemoveOnInsert;
++	this->mbAllowRemoveOnInsert = bAllowRemoveOnInsert;
  
--#endif
--
- File gid_File_Oo_Inet_Xcs
-     TXT_FILE_BODY;
-     Styles = (PACKED);
+ 	SetFolder ( sal_True );
+ 	aEntry.nVersion		= -1;
+diff -ur package/source/zippackage/ZipPackageStream.cxx package_new/source/zippackage/ZipPackageStream.cxx
+--- package/source/zippackage/ZipPackageStream.cxx	2005-07-12 14:31:48.000000000 +0200
++++ package_new/source/zippackage/ZipPackageStream.cxx	2005-07-14 17:32:10.000000000 +0200
+@@ -137,7 +137,7 @@
+ { 
+ 	OSL_ENSURE( m_xFactory.is(), "No factory is provided to ZipPackageStream!\n" );
+ 
+-	ZipPackageEntry::mbAllowRemoveOnInsert = bAllowRemoveOnInsert;
++	this->mbAllowRemoveOnInsert = bAllowRemoveOnInsert;
+ 
+ 	SetFolder ( sal_False );
+ 	aEntry.nVersion		= -1;
