GNOME2.26 to stable

diff --git a/10.4/stable/main/finkinfo/gnome/libxklavier12.patch b/10.4/stable/main/finkinfo/gnome/libxklavier12.patch
--- a/10.4/stable/main/finkinfo/gnome/libxklavier12.patch
+++ b/10.4/stable/main/finkinfo/gnome/libxklavier12.patch
@@ -1,19 +1,63 @@
-diff -Nurd -x'*~' libxklavier-3.8.orig/configure libxklavier-3.8/configure
---- libxklavier-3.8.orig/configure	2008-11-16 19:47:46.000000000 -0500
-+++ libxklavier-3.8/configure	2009-02-21 14:09:19.000000000 -0500
-@@ -2316,7 +2316,7 @@
+diff -Nurd -x'*~' libxklavier-3.9.orig/configure libxklavier-3.9/configure
+--- libxklavier-3.9.orig/configure	2009-03-18 17:42:16.000000000 -0400
++++ libxklavier-3.9/configure	2009-05-21 05:20:11.000000000 -0400
+@@ -2442,7 +2442,7 @@
  
  
  # Define the identity of the package.
 - PACKAGE='libxklavier'
 + PACKAGE='libxklavier12'
-  VERSION='3.8'
+  VERSION='3.9'
  
  
-diff -Nurd -x'*~' libxklavier-3.8.orig/doc/reference/Makefile.in libxklavier-3.8/doc/reference/Makefile.in
---- libxklavier-3.8.orig/doc/reference/Makefile.in	2008-11-16 19:47:45.000000000 -0500
-+++ libxklavier-3.8/doc/reference/Makefile.in	2009-02-21 14:09:19.000000000 -0500
-@@ -247,7 +247,7 @@
+@@ -14735,12 +14735,12 @@
+         pkg_cv_XINPUT_CFLAGS="$XINPUT_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xi >= 1.1.3\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "xi >= 1.1.3") 2>&5
++    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xi >= 99999.FORCE.NONDETECT\"") >&5
++  ($PKG_CONFIG --exists --print-errors "xi >= 99999.FORCE.NONDETECT") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_XINPUT_CFLAGS=`$PKG_CONFIG --cflags "xi >= 1.1.3" 2>/dev/null`
++  pkg_cv_XINPUT_CFLAGS=`$PKG_CONFIG --cflags "xi >= 99999.FORCE.NONDETECT" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -14753,12 +14753,12 @@
+         pkg_cv_XINPUT_LIBS="$XINPUT_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xi >= 1.1.3\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "xi >= 1.1.3") 2>&5
++    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xi >= 99999.FORCE.NONDETECT\"") >&5
++  ($PKG_CONFIG --exists --print-errors "xi >= 99999.FORCE.NONDETECT") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_XINPUT_LIBS=`$PKG_CONFIG --libs "xi >= 1.1.3" 2>/dev/null`
++  pkg_cv_XINPUT_LIBS=`$PKG_CONFIG --libs "xi >= 99999.FORCE.NONDETECT" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -14777,9 +14777,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        XINPUT_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xi >= 1.1.3"`
++	        XINPUT_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xi >= 99999.FORCE.NONDETECT"`
+         else
+-	        XINPUT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xi >= 1.1.3"`
++	        XINPUT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xi >= 99999.FORCE.NONDETECT"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$XINPUT_PKG_ERRORS" >&5
+diff -Nurd -x'*~' libxklavier-3.9.orig/doc/reference/Makefile.in libxklavier-3.9/doc/reference/Makefile.in
+--- libxklavier-3.9.orig/doc/reference/Makefile.in	2009-03-18 17:42:14.000000000 -0400
++++ libxklavier-3.9/doc/reference/Makefile.in	2009-05-21 04:56:45.000000000 -0400
+@@ -249,7 +249,7 @@
  # e.g. INCLUDES=-I$(top_srcdir) -I$(top_builddir) $(GTK_DEBUG_FLAGS)
  # e.g. GTKDOC_LIBS=$(top_builddir)/gtk/$(gtktargetlib)
  INCLUDES = -I$(top_srcdir) -I$(top_builddir) $(GLIB_CFLAGS)
@@ -22,29 +66,27 @@ diff -Nurd -x'*~' libxklavier-3.8.orig/doc/reference/Makefile.in libxklavier-3.8
  @GTK_DOC_USE_LIBTOOL_FALSE@GTKDOC_CC = $(CC) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
  @GTK_DOC_USE_LIBTOOL_TRUE@GTKDOC_CC = $(LIBTOOL) --mode=compile $(CC) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
  @GTK_DOC_USE_LIBTOOL_FALSE@GTKDOC_LD = $(CC) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS)
-diff -Nurd -x'*~' libxklavier-3.8.orig/libxklavier/Makefile.in libxklavier-3.8/libxklavier/Makefile.in
---- libxklavier-3.8.orig/libxklavier/Makefile.in	2008-11-16 19:47:46.000000000 -0500
-+++ libxklavier-3.8/libxklavier/Makefile.in	2009-02-21 14:13:59.000000000 -0500
-@@ -222,8 +222,8 @@
+diff -Nurd -x'*~' libxklavier-3.9.orig/libxklavier/Makefile.in libxklavier-3.9/libxklavier/Makefile.in
+--- libxklavier-3.9.orig/libxklavier/Makefile.in	2009-03-18 17:42:14.000000000 -0400
++++ libxklavier-3.9/libxklavier/Makefile.in	2009-05-21 04:58:12.000000000 -0400
+@@ -228,7 +228,7 @@
  
  # GLIB_GENMARSHAL = $(shell $PKG_CONFIG --variable=glib_genmarshal glib-2.0)
  GLIB_GENMARSHAL = `$PKG_CONFIG --variable=glib_genmarshal glib-2.0`
 -AM_CFLAGS = -Wall -DDATA_DIR=\"$(datadir)/$(PACKAGE)\" \
--  -I. -I$(includedir) $(X_CFLAGS) -I$(top_srcdir) \
 +AM_CPPFLAGS = -Wall -DDATA_DIR=\"$(datadir)/$(PACKAGE)\" \
-+  -I. -I$(top_srcdir) $(X_CFLAGS) \
+   -I. -I$(top_srcdir) $(X_CFLAGS) \
    $(XML_CFLAGS) $(GLIB_CFLAGS) $(XINPUT_CFLAGS) \
    $(LIBXKBFILE_PRESENT_CFLAG) \
-   $(ENABLE_XKB_SUPPORT_CFLAG) \
-diff -Nurd -x'*~' libxklavier-3.8.orig/tests/Makefile.in libxklavier-3.8/tests/Makefile.in
---- libxklavier-3.8.orig/tests/Makefile.in	2008-11-16 19:47:46.000000000 -0500
-+++ libxklavier-3.8/tests/Makefile.in	2009-02-21 14:09:19.000000000 -0500
-@@ -196,7 +196,7 @@
+diff -Nurd -x'*~' libxklavier-3.9.orig/tests/Makefile.in libxklavier-3.9/tests/Makefile.in
+--- libxklavier-3.9.orig/tests/Makefile.in	2009-03-18 17:42:14.000000000 -0400
++++ libxklavier-3.9/tests/Makefile.in	2009-05-21 04:59:29.000000000 -0400
+@@ -204,7 +204,7 @@
  top_srcdir = @top_srcdir@
  test_config_SOURCES = test_config.c
  test_monitor_SOURCES = test_monitor.c
--AM_CFLAGS = -Wall -Werror -I$(includedir) $(X_CFLAGS) -I$(top_srcdir) $(GLIB_CFLAGS)
+-AM_CFLAGS = -Wall -Werror -I$(top_srcdir) $(X_CFLAGS) $(GLIB_CFLAGS)
 +AM_CPPFLAGS = -Wall -Werror -I$(top_srcdir) $(X_CFLAGS) $(GLIB_CFLAGS)
- AM_LDFLAGS = $(top_builddir)/libxklavier/libxklavier.la $(X_LIBS) -lX11 $(GLIB_LIBS)
+ LDADD = $(top_builddir)/libxklavier/libxklavier.la $(X_LIBS) -lX11 $(GLIB_LIBS)
  all: all-am
  
