lots of mono updates and related stuff

diff --git a/10.3/unstable/main/finkinfo/libs/libgdiplus.patch b/10.3/unstable/main/finkinfo/libs/libgdiplus.patch
--- a/10.3/unstable/main/finkinfo/libs/libgdiplus.patch
+++ b/10.3/unstable/main/finkinfo/libs/libgdiplus.patch
@@ -1,28 +1,36 @@
-diff -uNr libgdiplus-1.1.7/cairo/configure libgdiplus-1.1.7-new/cairo/configure
---- libgdiplus-1.1.7/cairo/configure	Tue May  3 14:44:58 2005
-+++ libgdiplus-1.1.7-new/cairo/configure	Mon Jun  6 10:53:19 2005
-@@ -22369,7 +22369,7 @@
-   enableval="$enable_glitz"
-   use_glitz=$enableval
- else
--  use_glitz=yes
-+  use_glitz=no
- fi;
+diff -uNr libgdiplus-1.1.10/Makefile.in libgdiplus-1.1.10-new/Makefile.in
+--- libgdiplus-1.1.10/Makefile.in	2005-11-08 17:52:19.000000000 -0500
++++ libgdiplus-1.1.10-new/Makefile.in	2005-11-09 19:04:47.000000000 -0500
+@@ -190,7 +190,7 @@
+ target_cpu = @target_cpu@
+ target_os = @target_os@
+ target_vendor = @target_vendor@
+-SUBDIRS = cairo src tests
++SUBDIRS = src tests
+ #libpixman
+ pkgconfigdir = $(libdir)/pkgconfig
+ pkgconfig_DATA = libgdiplus.pc 
+diff -uNr libgdiplus-1.1.10/configure libgdiplus-1.1.10-new/configure
+--- libgdiplus-1.1.10/configure	2005-11-08 17:52:21.000000000 -0500
++++ libgdiplus-1.1.10-new/configure	2005-11-09 18:51:36.000000000 -0500
+@@ -19603,14 +19603,9 @@
  
- if test "x$use_glitz" = "xyes"; then
-diff -uNr libgdiplus-1.1.7/configure libgdiplus-1.1.7-new/configure
---- libgdiplus-1.1.7/configure	Tue May  3 14:44:36 2005
-+++ libgdiplus-1.1.7-new/configure	Mon Jun  6 11:08:08 2005
-@@ -19633,7 +19633,7 @@
- _ACEOF
  
- else
--	if pkg-config --exact-version 0.3.0 cairo; then
-+	if pkg-config --atleast-version 0.3.0 cairo; then
- 		echo Cairo installation OK
- 	else
- 		{ { echo "$as_me:$LINENO: error: \"Did not find Cairo == 0.3.0\"" >&5
-@@ -20004,7 +20004,7 @@
+ 
+-subdirs="$subdirs cairo"
++CAIRO_LIBS="`pkg-config --libs cairo`"
++CAIRO_CFLAGS="`pkg-config --cflags cairo`"
+ 
+-CAIRO_LIBS='$(top_builddir)/cairo/src/libcairo.la'
+-CAIRO_CFLAGS='-I$(top_builddir)/cairo/pixman/src -I$(top_srcdir)/cairo/pixman/src -I$(top_builddir)/cairo/src -I$(top_srcdir)/cairo/src'
+-
+-cat >>confdefs.h <<\_ACEOF
+-#define USE_INCLUDED_CAIRO 1
+-_ACEOF
+ 
+ 
+ # Activate this when we support linking to an already exiting Cairo installation
+@@ -19994,7 +19989,7 @@
  #define _REENTRANT 1
  _ACEOF
  
@@ -31,7 +39,7 @@ diff -uNr libgdiplus-1.1.7/configure libgdiplus-1.1.7-new/configure
  		;;
  
  	*-*-darwin*)
-@@ -20014,7 +20014,7 @@
+@@ -20004,7 +19999,7 @@
  _ACEOF
  
  		CFLAGS="-no-cpp-precomp $CFLAGS"
@@ -40,7 +48,7 @@ diff -uNr libgdiplus-1.1.7/configure libgdiplus-1.1.7-new/configure
  		;;
  
  	*)
-@@ -20037,7 +20037,7 @@
+@@ -20027,7 +20022,7 @@
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_save_CFLAGS=$CFLAGS
@@ -49,7 +57,7 @@ diff -uNr libgdiplus-1.1.7/configure libgdiplus-1.1.7-new/configure
  
  
     ac_ext=c
-@@ -20106,7 +20106,7 @@
+@@ -20096,7 +20091,7 @@
  if test $myapp_cv_gcc_pthread = yes
  then
     myapp_threads=""
@@ -58,29 +66,37 @@ diff -uNr libgdiplus-1.1.7/configure libgdiplus-1.1.7-new/configure
  else
     echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
  echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
-@@ -21197,13 +21197,13 @@
- fi
- 
-   if test x$with_libungif != xno && test -z "$LIBUNGIF"; then
--    echo "$as_me:$LINENO: checking for DGifOpenFileName in -lungif" >&5
--echo $ECHO_N "checking for DGifOpenFileName in -lungif... $ECHO_C" >&6
-+    echo "$as_me:$LINENO: checking for DGifOpenFileName in -lgif" >&5
-+echo $ECHO_N "checking for DGifOpenFileName in -lgif... $ECHO_C" >&6
- if test "${ac_cv_lib_ungif_DGifOpenFileName+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   ac_check_lib_save_LIBS=$LIBS
--LIBS="-lungif  $LIBS"
-+LIBS="-lgif  $LIBS"
- cat >conftest.$ac_ext <<_ACEOF
- /* confdefs.h.  */
- _ACEOF
-@@ -21400,7 +21400,7 @@
+@@ -21608,16 +21603,16 @@
  
  fi
  if test $ac_cv_header_gif_lib_h = yes; then
--  UNGIF='ungif'; LIBUNGIF='-lungif'
-+  UNGIF='ungif'; LIBUNGIF='-lgif'
+-  GIF='ungif'; LIBGIF='-lungif'
++  GIF='gif'; LIBGIF='-lgif'
  else
-   { echo "$as_me:$LINENO: WARNING: *** GIF loader will not be built (ungiflibrary not found) ***" >&5
- echo "$as_me: WARNING: *** GIF loader will not be built (ungiflibrary not found) ***" >&2;}
+-  { echo "$as_me:$LINENO: WARNING: *** GIF loader will not be built (ungiflibrary not found) ***" >&5
+-echo "$as_me: WARNING: *** GIF loader will not be built (ungiflibrary not found) ***" >&2;}
++  { echo "$as_me:$LINENO: WARNING: *** GIF loader will not be built (giflibrary not found) ***" >&5
++echo "$as_me: WARNING: *** GIF loader will not be built (giflibrary not found) ***" >&2;}
+ fi
+ 
+ 
+ else
+-  { echo "$as_me:$LINENO: WARNING: *** GIF loader will not be built (ungiflibrary not found) ***" >&5
+-echo "$as_me: WARNING: *** GIF loader will not be built (ungiflibrary not found) ***" >&2;}
++  { echo "$as_me:$LINENO: WARNING: *** GIF loader will not be built (giflibrary not found) ***" >&5
++echo "$as_me: WARNING: *** GIF loader will not be built (giflibrary not found) ***" >&2;}
+ fi
+ 
+   fi
+diff -uNr libgdiplus-1.1.10/src/pngcodec.c libgdiplus-1.1.10-new/src/pngcodec.c
+--- libgdiplus-1.1.10/src/pngcodec.c	2005-10-10 04:54:45.000000000 -0400
++++ libgdiplus-1.1.10-new/src/pngcodec.c	2005-11-09 18:18:34.000000000 -0500
+@@ -451,7 +451,7 @@
+     GpBitmap *bitmap = (GpBitmap *) image;
+     gdip_stream_png_source_ptr pngsrc = NULL;
+ 
+-    int i;
++    int i, j;
+ 
+     int bit_depth;
+     int color_type;
