Fix libdevil1 building on 10.9. Now does it still build on 10.7 and 10.8?

diff --git a/10.7/stable/main/finkinfo/graphics/libdevil1.patch b/10.7/stable/main/finkinfo/graphics/libdevil1.patch
--- a/10.7/stable/main/finkinfo/graphics/libdevil1.patch
+++ b/10.7/stable/main/finkinfo/graphics/libdevil1.patch
@@ -1,63 +1,44 @@
-diff -rua devil-1.7.8.orig/docs/DevIL_manual.info devil-1.7.8/docs/DevIL_manual.info
---- devil-1.7.8.orig/docs/DevIL_manual.info	2009-03-08 16:43:50.000000000 -0400
-+++ devil-1.7.8/docs/DevIL_manual.info	2009-06-24 10:53:28.000000000 -0400
-@@ -1,7 +1,7 @@
- This is DevIL_manual.info, produced by makeinfo version 4.11 from
- DevIL_manual.texi.
+diff -ru devil-1.7.8.orig/configure devil-1.7.8/configure
+--- devil-1.7.8.orig/configure	2009-03-08 16:43:20.000000000 -0400
++++ devil-1.7.8/configure	2013-11-20 09:26:47.000000000 -0500
+@@ -16134,7 +16134,7 @@
+ 	                     { echo "$as_me:$LINENO: result: yes" >&5
+ echo "${ECHO_T}yes" >&6; }
+ 	                     CFLAGS="$TMP_CFLAGS"
+-                             GENERAL_CFLAGS="$GENERAL_CFLAGS -std=gnu99 -fgnu89-inline"
++                             GENERAL_CFLAGS="$GENERAL_CFLAGS"
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+Binary files devil-1.7.8.orig/docs/DevIL_manual.info and devil-1.7.8/docs/DevIL_manual.info differ
+diff -ru devil-1.7.8.orig/src-IL/include/il_endian.h devil-1.7.8/src-IL/include/il_endian.h
+--- devil-1.7.8.orig/src-IL/include/il_endian.h	2009-03-08 03:10:08.000000000 -0400
++++ devil-1.7.8/src-IL/include/il_endian.h	2013-11-20 09:31:36.000000000 -0500
+@@ -19,9 +19,13 @@
+ 	#ifndef __BIG_ENDIAN__
+ 	#define __BIG_ENDIAN__ 1
+ 	#endif
++#else
++	#ifndef __LITTLE_ENDIAN__
++	#define __LITTLE_ENDIAN__ 1
++	#endif
+ #endif
  
--This is `DevIL 1.7.8' manual.  Last update is from 8 March 2009.
-+This file documents `DevIL 1.7.8'.  Last update is from 8 March 2009.
- 
-    Copyright (C) 2008,2009 Denton Woods, Matěj Týč
- 
-diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
---- devil-1.7.8.orig/src-ILU/ilur/ilur.c	2009-03-08 03:10:12.000000000 -0400
-+++ devil-1.7.8/src-ILU/ilur/ilur.c	2009-06-24 10:52:35.000000000 -0400
-@@ -1,6 +1,6 @@
- #include <string.h>
- #include <stdio.h>
--#include <malloc.h>
-+#include <stdlib.h>
- 
- #include <IL/il.h>
- #include <IL/ilu.h>
---- devil-1.7.8/src-IL/src/il_icon.c.orig	2012-03-07 19:48:46.000000000 -0500
-+++ devil-1.7.8/src-IL/src/il_icon.c	2012-03-07 19:49:28.000000000 -0500
-@@ -525,7 +525,7 @@
- 
- 	// Expand low-bit-depth grayscale images to 8 bits
- 	if (ico_color_type == PNG_COLOR_TYPE_GRAY && bit_depth < 8) {
--		png_set_gray_1_2_4_to_8(ico_png_ptr);
-+		png_set_expand_gray_1_2_4_to_8(ico_png_ptr);
- 	}
- 
- 	// Expand RGB images with transparency to full alpha channels
---- devil-1.7.8/src-IL/src/il_png.c.orig	2012-03-07 19:52:01.000000000 -0500
-+++ devil-1.7.8/src-IL/src/il_png.c	2012-03-07 19:52:16.000000000 -0500
-@@ -278,7 +278,7 @@
- 
- 	// Expand low-bit-depth grayscale images to 8 bits
- 	if (png_color_type == PNG_COLOR_TYPE_GRAY && bit_depth < 8) {
--		png_set_gray_1_2_4_to_8(png_ptr);
-+		png_set_expand_gray_1_2_4_to_8(png_ptr);
- 	}
- 
- 	// Expand RGB images with transparency to full alpha channels
---- devil-1.7.8/src-IL/include/il_internal.h.orig	2012-03-08 17:31:13.000000000 -0500
-+++ devil-1.7.8/src-IL/include/il_internal.h	2012-03-08 17:32:40.000000000 -0500
-@@ -227,7 +227,9 @@
- ILboolean ilLoadBlp(ILconst_string FileName);
- ILboolean ilLoadBlpF(ILHANDLE File);
- ILboolean ilLoadBlpL(const void *Lump, ILuint Size);
-+#ifndef __cplusplus
- ILboolean ilIsValidBmp(ILconst_string CONST_RESTRICT FileName);
-+#endif
- ILboolean ilIsValidBmpF(ILHANDLE File);
- ILboolean ilIsValidBmpL(const void *Lump, ILuint Size);
- ILboolean ilLoadBmp(ILconst_string FileName);
---- devil-1.7.8/src-IL/include/il_endian.h.orig	2012-03-08 19:00:03.000000000 -0500
-+++ devil-1.7.8/src-IL/include/il_endian.h	2012-03-08 18:55:42.000000000 -0500
-@@ -56,6 +56,7 @@
+-#if (defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __BIG_ENDIAN__) \
++#if (defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__) \
+   || (defined(__BIG_ENDIAN__) && !defined(__LITTLE_ENDIAN__))
+  	#undef __LITTLE_ENDIAN__
+ 	#define Short(s) iSwapShort(s)
+@@ -39,8 +43,6 @@
+ 	#define BigDouble(d)  
+ #else
+ 	#undef __BIG_ENDIAN__
+-	#undef __LITTLE_ENDIAN__  // Not sure if it's defined by any compiler...
+-	#define __LITTLE_ENDIAN__
+ 	#define Short(s)  
+ 	#define UShort(s)  
+ 	#define Int(i)  
+@@ -56,6 +58,7 @@
  	#define BigDouble(d) iSwapDouble(d)
  #endif
  
@@ -65,7 +46,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  void   iSwapUShort(ILushort *s);
  void   iSwapShort(ILshort *s);
  void   iSwapUInt(ILuint *i);
-@@ -86,6 +87,7 @@
+@@ -86,6 +89,7 @@
  ILubyte SaveBigInt(ILint i);
  ILubyte SaveBigFloat(ILfloat f);
  ILubyte SaveBigDouble(ILdouble d);
@@ -73,7 +54,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  
  #ifdef IL_ENDIAN_C
  #undef NOINLINE
-@@ -94,7 +96,7 @@
+@@ -94,7 +98,7 @@
  #endif
  
  #ifndef NOINLINE
@@ -82,7 +63,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	#ifdef USE_WIN32_ASM
  		__asm {
  			mov ebx, s
-@@ -113,11 +115,11 @@
+@@ -113,11 +117,11 @@
  	#endif //USE_WIN32_ASM
  }
  
@@ -96,7 +77,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	#ifdef USE_WIN32_ASM
  		__asm {
  			mov ebx, i
-@@ -135,15 +137,15 @@
+@@ -135,15 +139,15 @@
  	#endif //USE_WIN32_ASM
  }
  
@@ -115,7 +96,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	#ifdef GCC_X86_ASM
  	int *t = (int*)d;
  	asm("bswap %2    \n"
-@@ -164,7 +166,7 @@
+@@ -164,7 +168,7 @@
  }
  
  
@@ -124,7 +105,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILushort s;
  	iread(&s, sizeof(ILushort), 1);
  #ifdef __BIG_ENDIAN__
-@@ -173,7 +175,7 @@
+@@ -173,7 +177,7 @@
  	return s;
  }
  
@@ -133,7 +114,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILshort s;
  	iread(&s, sizeof(ILshort), 1);
  #ifdef __BIG_ENDIAN__
-@@ -182,7 +184,7 @@
+@@ -182,7 +186,7 @@
  	return s;
  }
  
@@ -142,7 +123,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILuint i;
  	iread(&i, sizeof(ILuint), 1);
  #ifdef __BIG_ENDIAN__
-@@ -191,7 +193,7 @@
+@@ -191,7 +195,7 @@
  	return i;
  }
  
@@ -151,7 +132,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILint i;
  	iread(&i, sizeof(ILint), 1);
  #ifdef __BIG_ENDIAN__
-@@ -200,7 +202,7 @@
+@@ -200,7 +204,7 @@
  	return i;
  }
  
@@ -160,7 +141,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILfloat f;
  	iread(&f, sizeof(ILfloat), 1);
  #ifdef __BIG_ENDIAN__
-@@ -209,7 +211,7 @@
+@@ -209,7 +213,7 @@
  	return f;
  }
  
@@ -169,7 +150,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILdouble d;
  	iread(&d, sizeof(ILdouble), 1);
  #ifdef __BIG_ENDIAN__
-@@ -219,7 +221,7 @@
+@@ -219,7 +223,7 @@
  }
  
  
@@ -178,7 +159,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILushort s;
  	iread(&s, sizeof(ILushort), 1);
  #ifdef __LITTLE_ENDIAN__
-@@ -229,7 +231,7 @@
+@@ -229,7 +233,7 @@
  }
  
  
@@ -187,7 +168,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILshort s;
  	iread(&s, sizeof(ILshort), 1);
  #ifdef __LITTLE_ENDIAN__
-@@ -239,7 +241,7 @@
+@@ -239,7 +243,7 @@
  }
  
  
@@ -196,7 +177,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILuint i;
  	iread(&i, sizeof(ILuint), 1);
  #ifdef __LITTLE_ENDIAN__
-@@ -249,7 +251,7 @@
+@@ -249,7 +253,7 @@
  }
  
  
@@ -205,7 +186,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILint i;
  	iread(&i, sizeof(ILint), 1);
  #ifdef __LITTLE_ENDIAN__
-@@ -259,7 +261,7 @@
+@@ -259,7 +263,7 @@
  }
  
  
@@ -214,7 +195,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILfloat f;
  	iread(&f, sizeof(ILfloat), 1);
  #ifdef __LITTLE_ENDIAN__
-@@ -269,7 +271,7 @@
+@@ -269,7 +273,7 @@
  }
  
  
@@ -223,7 +204,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	ILdouble d;
  	iread(&d, sizeof(ILdouble), 1);
  #ifdef __LITTLE_ENDIAN__
-@@ -278,14 +280,14 @@
+@@ -278,14 +282,14 @@
  	return d;
  }
  
@@ -240,7 +221,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __BIG_ENDIAN__
  	iSwapShort(&s);
  #endif
-@@ -293,7 +295,7 @@
+@@ -293,7 +297,7 @@
  }
  
  
@@ -249,7 +230,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __BIG_ENDIAN__
  	iSwapUInt(&i);
  #endif
-@@ -301,14 +303,14 @@
+@@ -301,14 +305,14 @@
  }
  
  
@@ -266,7 +247,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __BIG_ENDIAN__
  	iSwapFloat(&f);
  #endif
-@@ -316,7 +318,7 @@
+@@ -316,7 +320,7 @@
  }
  
  
@@ -275,7 +256,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __BIG_ENDIAN__
  	iSwapDouble(&d);
  #endif
-@@ -324,7 +326,7 @@
+@@ -324,7 +328,7 @@
  }
  
  
@@ -284,7 +265,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __LITTLE_ENDIAN__
  	iSwapUShort(&s);
  #endif
-@@ -332,7 +334,7 @@
+@@ -332,7 +336,7 @@
  }
  
  
@@ -293,7 +274,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __LITTLE_ENDIAN__
  	iSwapShort(&s);
  #endif
-@@ -340,7 +342,7 @@
+@@ -340,7 +344,7 @@
  }
  
  
@@ -302,7 +283,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __LITTLE_ENDIAN__
  	iSwapUInt(&i);
  #endif
-@@ -348,7 +350,7 @@
+@@ -348,7 +352,7 @@
  }
  
  
@@ -311,7 +292,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __LITTLE_ENDIAN__
  	iSwapInt(&i);
  #endif
-@@ -356,7 +358,7 @@
+@@ -356,7 +360,7 @@
  }
  
  
@@ -320,7 +301,7 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __LITTLE_ENDIAN__
  	iSwapFloat(&f);
  #endif
-@@ -364,7 +366,7 @@
+@@ -364,7 +368,7 @@
  }
  
  
@@ -329,8 +310,22 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  #ifdef __LITTLE_ENDIAN__
  	iSwapDouble(&d);
  #endif
---- devil-1.7.8/src-IL/include/il_manip.h.orig	2012-03-08 19:03:57.000000000 -0500
-+++ devil-1.7.8/src-IL/include/il_manip.h	2012-03-08 18:55:42.000000000 -0500
+diff -ru devil-1.7.8.orig/src-IL/include/il_internal.h devil-1.7.8/src-IL/include/il_internal.h
+--- devil-1.7.8.orig/src-IL/include/il_internal.h	2009-03-08 03:10:08.000000000 -0400
++++ devil-1.7.8/src-IL/include/il_internal.h	2013-11-20 09:26:47.000000000 -0500
+@@ -227,7 +227,9 @@
+ ILboolean ilLoadBlp(ILconst_string FileName);
+ ILboolean ilLoadBlpF(ILHANDLE File);
+ ILboolean ilLoadBlpL(const void *Lump, ILuint Size);
++#ifndef __cplusplus
+ ILboolean ilIsValidBmp(ILconst_string CONST_RESTRICT FileName);
++#endif
+ ILboolean ilIsValidBmpF(ILHANDLE File);
+ ILboolean ilIsValidBmpL(const void *Lump, ILuint Size);
+ ILboolean ilLoadBmp(ILconst_string FileName);
+diff -ru devil-1.7.8.orig/src-IL/include/il_manip.h devil-1.7.8/src-IL/include/il_manip.h
+--- devil-1.7.8.orig/src-IL/include/il_manip.h	2009-03-08 03:10:08.000000000 -0400
++++ devil-1.7.8/src-IL/include/il_manip.h	2013-11-20 09:26:47.000000000 -0500
 @@ -31,7 +31,7 @@
  	#pragma warning(push)
  	#pragma warning(disable : 4756)  // Disables 'named type definition in parentheses' warning
@@ -358,8 +353,44 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  
  	int s = (y >> 15) & 0x00000001;
  	int e = (y >> 10) & 0x0000001f;
---- devil-1.7.8/src-ILU/include/ilu_internal.h.orig	2012-03-08 18:49:44.000000000 -0500
-+++ devil-1.7.8/src-ILU/include/ilu_internal.h	2012-03-08 18:51:25.000000000 -0500
+diff -ru devil-1.7.8.orig/src-IL/src/il_icon.c devil-1.7.8/src-IL/src/il_icon.c
+--- devil-1.7.8.orig/src-IL/src/il_icon.c	2009-03-08 03:10:09.000000000 -0400
++++ devil-1.7.8/src-IL/src/il_icon.c	2013-11-20 09:26:47.000000000 -0500
+@@ -525,7 +525,7 @@
+ 
+ 	// Expand low-bit-depth grayscale images to 8 bits
+ 	if (ico_color_type == PNG_COLOR_TYPE_GRAY && bit_depth < 8) {
+-		png_set_gray_1_2_4_to_8(ico_png_ptr);
++		png_set_expand_gray_1_2_4_to_8(ico_png_ptr);
+ 	}
+ 
+ 	// Expand RGB images with transparency to full alpha channels
+diff -ru devil-1.7.8.orig/src-IL/src/il_png.c devil-1.7.8/src-IL/src/il_png.c
+--- devil-1.7.8.orig/src-IL/src/il_png.c	2009-03-08 03:10:09.000000000 -0400
++++ devil-1.7.8/src-IL/src/il_png.c	2013-11-20 09:26:47.000000000 -0500
+@@ -278,7 +278,7 @@
+ 
+ 	// Expand low-bit-depth grayscale images to 8 bits
+ 	if (png_color_type == PNG_COLOR_TYPE_GRAY && bit_depth < 8) {
+-		png_set_gray_1_2_4_to_8(png_ptr);
++		png_set_expand_gray_1_2_4_to_8(png_ptr);
+ 	}
+ 
+ 	// Expand RGB images with transparency to full alpha channels
+diff -ru devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
+--- devil-1.7.8.orig/src-ILU/ilur/ilur.c	2009-03-08 03:10:12.000000000 -0400
++++ devil-1.7.8/src-ILU/ilur/ilur.c	2013-11-20 09:26:47.000000000 -0500
+@@ -1,6 +1,6 @@
+ #include <string.h>
+ #include <stdio.h>
+-#include <malloc.h>
++#include <stdlib.h>
+ 
+ #include <IL/il.h>
+ #include <IL/ilu.h>
+diff -ru devil-1.7.8.orig/src-ILU/include/ilu_internal.h devil-1.7.8/src-ILU/include/ilu_internal.h
+--- devil-1.7.8.orig/src-ILU/include/ilu_internal.h	2009-03-08 03:10:12.000000000 -0400
++++ devil-1.7.8/src-ILU/include/ilu_internal.h	2013-11-20 09:26:47.000000000 -0500
 @@ -71,22 +71,24 @@
  #define INLINE
  #endif
@@ -388,14 +419,3 @@ diff -rua devil-1.7.8.orig/src-ILU/ilur/ilur.c devil-1.7.8/src-ILU/ilur/ilur.c
  	return (ILint)(Num + 0.5); // this is truncating in away-from-0, not rounding
  }
  #endif
---- devil-1.7.8/configure.orig	2012-03-08 20:03:09.000000000 -0500
-+++ devil-1.7.8/configure	2012-03-08 20:03:43.000000000 -0500
-@@ -16134,7 +16134,7 @@
- 	                     { echo "$as_me:$LINENO: result: yes" >&5
- echo "${ECHO_T}yes" >&6; }
- 	                     CFLAGS="$TMP_CFLAGS"
--                             GENERAL_CFLAGS="$GENERAL_CFLAGS -std=gnu99 -fgnu89-inline"
-+                             GENERAL_CFLAGS="$GENERAL_CFLAGS -fgnu89-inline"
- else
-   echo "$as_me: failed program was:" >&5
- sed 's/^/| /' conftest.$ac_ext >&5
