use wrapper script to check for codesigning and -p flag in plist on darwin12 or later

diff --git a/10.7/stable/main/finkinfo/devel/gdb.patch b/10.7/stable/main/finkinfo/devel/gdb.patch
--- a/10.7/stable/main/finkinfo/devel/gdb.patch
+++ b/10.7/stable/main/finkinfo/devel/gdb.patch
@@ -236,3 +236,47 @@ index 3479140..3d2c1c2 100644
  {
 -- 
 1.9.3
+diff -uNr gdb-7.9.orig/gdb/compile/compile-loc2c.c gdb-7.9/gdb/compile/compile-loc2c.c
+--- gdb-7.9.orig/gdb/compile/compile-loc2c.c	2015-02-19 06:58:07.000000000 -0500
++++ gdb-7.9/gdb/compile/compile-loc2c.c	2015-04-13 16:18:58.000000000 -0400
+@@ -656,7 +656,7 @@
+   while (op_ptr < op_end)
+     {
+       enum dwarf_location_atom op = *op_ptr;
+-      uint64_t uoffset, reg;
++      uint64_t uoffset = 0, reg;
+       int64_t offset;
+ 
+       print_spaces (indent - 2, stream);
+diff -uNr gdb-7.9.orig/fsf-gdb-wrapper gdb-7.9/fsf-gdb-wrapper
+--- gdb-7.9.orig/fsf-gdb-wrapper	1969-12-31 19:00:00.000000000 -0500
++++ gdb-7.9/fsf-gdb-wrapper	2015-04-13 17:05:33.000000000 -0400
+@@ -0,0 +1,28 @@
++#!/bin/bash
++# Shell wrapper for FSF gdb
++
++if [ $UID != 0 ]; then
++	codesign --verify @FINKPREFIX@/lib/fsf-gdb/fsf-gdb
++	if [ $? -eq 1  ]; then
++		echo ""
++		echo "The fsf-gdb binary must be codesigned to run as non-root."
++		echo "If Keychain certificate has been created as described in"
++		echo "the DescUsage section of the gdb.info packaging file,"
++		echo "execute 'sudo codesign -s gdb-cert @FINKPREFIX@/lib/fsf-gdb/fsf-gdb'."
++		exit 1
++	fi
++	if [ "`uname -r | cut -d. -f1`" -ge "12" ]; then
++		plistfile=/System/Library/LaunchDaemons/com.apple.taskgated.plist
++		if [ !`grep "<string>-sp</string>" $plistfile` ] && [ !`grep "<string>-ps</string>" $plistfile` ] ; then
++			echo "Non-root gdb use requires /System/Library/LaunchDaemons/com.apple.taskgated.plist"
++			echo "to pass -p. Change the line..."
++			echo "     string>-s</string>"
++			echo "to...\n"
++			echo "     string>-sp</string>"
++			echo "A restart is required due to kernel caching for the change to take effect."
++			exit 1
++		fi
++	fi
++fi
++
++exec @FINKPREFIX@/lib/fsf-gdb/fsf-gdb "${@}"
