new version from submissions #4410

diff --git a/finkinfo/dbus1.3-shlibs.patch b/finkinfo/dbus1.3-shlibs.patch
--- a/finkinfo/dbus1.3-shlibs.patch
+++ b/finkinfo/dbus1.3-shlibs.patch
@@ -1,7 +1,7 @@
-diff -Nurd -x'*~' dbus-1.4.24.orig/bus/Makefile.in dbus-1.4.24/bus/Makefile.in
---- dbus-1.4.24.orig/bus/Makefile.in	2012-09-28 16:19:59.000000000 -0400
-+++ dbus-1.4.24/bus/Makefile.in	2013-06-11 04:38:08.000000000 -0400
-@@ -2404,12 +2404,13 @@
+diff -uNr dbus-1.8.2/bus/Makefile.in dbus-1.8.2.fink/bus/Makefile.in
+--- dbus-1.8.2/bus/Makefile.in	2014-04-30 15:14:40.000000000 -0400
++++ dbus-1.8.2.fink/bus/Makefile.in	2014-06-01 18:05:15.000000000 -0400
+@@ -1526,12 +1526,13 @@
  @HAVE_SYSTEMD_TRUE@	ln -fs ../dbus.service $(DESTDIR)$(systemdsystemunitdir)/multi-user.target.wants/dbus.service
  
  @DBUS_UNIX_TRUE@install-exec-hook:
@@ -16,9 +16,34 @@ diff -Nurd -x'*~' dbus-1.4.24.orig/bus/Makefile.in dbus-1.4.24/bus/Makefile.in
  @DBUS_UNIX_TRUE@	fi
  
  # Tell versions [3.59,3.63) of GNU make to not export all variables.
-diff -Nurd -x'*~' dbus-1.4.24.orig/dbus-xinitrc.sh dbus-1.4.24/dbus-xinitrc.sh
---- dbus-1.4.24.orig/dbus-xinitrc.sh	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.4.24/dbus-xinitrc.sh	2013-06-11 04:38:08.000000000 -0400
+diff -uNr dbus-1.8.2/bus/system.conf.in dbus-1.8.2.fink/bus/system.conf.in
+--- dbus-1.8.2/bus/system.conf.in	2014-01-25 07:39:25.000000000 -0500
++++ dbus-1.8.2.fink/bus/system.conf.in	2014-06-01 18:13:01.000000000 -0400
+@@ -26,9 +26,6 @@
+   <!-- This is a setuid helper that is used to launch system services -->
+   <servicehelper>@DBUS_LIBEXECDIR@/dbus-daemon-launch-helper</servicehelper>
+ 
+-  <!-- Write a pid file -->
+-  <pidfile>@DBUS_SYSTEM_PID_FILE@</pidfile>
+-
+   <!-- Enable logging to syslog -->
+   <syslog/>
+ 
+diff -uNr dbus-1.8.2/dbus/dbus-sysdeps-unix.c dbus-1.8.2.fink/dbus/dbus-sysdeps-unix.c
+--- dbus-1.8.2/dbus/dbus-sysdeps-unix.c	2014-04-28 09:59:54.000000000 -0400
++++ dbus-1.8.2.fink/dbus/dbus-sysdeps-unix.c	2014-06-01 18:12:26.000000000 -0400
+@@ -3348,7 +3348,7 @@
+       close (result_pipe[READ_END]);
+       close (errors_pipe[READ_END]);
+ 
+-      if (dup2 (fd, 0) == -1) /* setup stdin */
++      if (fd != 0 && dup2 (fd, 0) == -1) /* setup stdin */
+         _exit (1);
+       if (dup2 (result_pipe[WRITE_END], 1) == -1) /* setup stdout */
+         _exit (1);
+diff -uNr dbus-1.8.2/dbus-xinitrc.sh dbus-1.8.2.fink/dbus-xinitrc.sh
+--- dbus-1.8.2/dbus-xinitrc.sh	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.8.2.fink/dbus-xinitrc.sh	2014-06-01 18:05:15.000000000 -0400
 @@ -0,0 +1,8 @@
 +#!/bin/sh
 +
@@ -28,9 +53,9 @@ diff -Nurd -x'*~' dbus-1.4.24.orig/dbus-xinitrc.sh dbus-1.4.24/dbus-xinitrc.sh
 +		TMPDIR=/tmp launchctl setenv DISPLAY "$DISPLAY"
 +	fi
 +fi
-diff -Nurd -x'*~' dbus-1.4.24.orig/start-session-bus.sh dbus-1.4.24/start-session-bus.sh
---- dbus-1.4.24.orig/start-session-bus.sh	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.4.24/start-session-bus.sh	2013-06-11 04:38:08.000000000 -0400
+diff -uNr dbus-1.8.2/start-session-bus.sh dbus-1.8.2.fink/start-session-bus.sh
+--- dbus-1.8.2/start-session-bus.sh	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.8.2.fink/start-session-bus.sh	2014-06-01 18:05:15.000000000 -0400
 @@ -0,0 +1,7 @@
 +#!/bin/sh -e
 +
@@ -39,9 +64,9 @@ diff -Nurd -x'*~' dbus-1.4.24.orig/start-session-bus.sh dbus-1.4.24/start-sessio
 +fi
 +
 +exit 0
-diff -Nurd -x'*~' dbus-1.4.24.orig/start-system-bus.sh dbus-1.4.24/start-system-bus.sh
---- dbus-1.4.24.orig/start-system-bus.sh	1969-12-31 19:00:00.000000000 -0500
-+++ dbus-1.4.24/start-system-bus.sh	2013-06-11 04:38:08.000000000 -0400
+diff -uNr dbus-1.8.2/start-system-bus.sh dbus-1.8.2.fink/start-system-bus.sh
+--- dbus-1.8.2/start-system-bus.sh	1969-12-31 19:00:00.000000000 -0500
++++ dbus-1.8.2.fink/start-system-bus.sh	2014-06-01 18:05:15.000000000 -0400
 @@ -0,0 +1,17 @@
 +#!/bin/sh
 +
@@ -60,3 +85,16 @@ diff -Nurd -x'*~' dbus-1.4.24.orig/start-system-bus.sh dbus-1.4.24/start-system-
 +fi
 +
 +exit 0
+diff -uNr dbus-1.8.2/test/name-test/run-test.sh dbus-1.8.2.fink/test/name-test/run-test.sh
+--- dbus-1.8.2/test/name-test/run-test.sh	2014-01-25 07:39:25.000000000 -0500
++++ dbus-1.8.2.fink/test/name-test/run-test.sh	2014-06-01 18:07:23.000000000 -0400
+@@ -62,4 +62,8 @@
+ fi
+ 
+ echo "running test-autolaunch"
+-${DBUS_TOP_BUILDDIR}/libtool --mode=execute $DEBUG $DBUS_TOP_BUILDDIR/test/name-test/test-autolaunch || die "test-autolaunch failed"
++if which dbus-launch 2>/dev/null; then
++    ${DBUS_TOP_BUILDDIR}/libtool --mode=execute $DEBUG $DBUS_TOP_BUILDDIR/test/name-test/test-autolaunch || die "test-autolaunch failed"
++else
++    echo "Skipping test-autolaunch, no dbus-launch in $PATH"
++fi
