Change how install-info works, no need for splitoff now and it checks for ginstall-info so in the future it'll use it once installed.  Removed shlibs.default since fink installs that it's self.  Now the pkg builds and installs, all tests pass, but once installed I'm getting dpkg: warning: subprocess (null) was killed by signal (Segmentation fault: 11), seems to be from pre/post scripts, likely to do with the forking, looking into it.

diff --git a/finkinfo/dpkg.patch b/finkinfo/dpkg.patch
--- a/finkinfo/dpkg.patch
+++ b/finkinfo/dpkg.patch
@@ -429,8 +429,8 @@ diff -ruN dpkg-1.16.3.orig/dselect/pkgdepcon.cc dpkg-1.16.3/dselect/pkgdepcon.cc
      would = would_like_to_install(want, &possi->ed->pkg);
 diff -ruN dpkg-1.16.3.orig/fink/install-info.sh dpkg-1.16.3/fink/install-info.sh
 --- dpkg-1.16.3.orig/fink/install-info.sh	1969-12-31 17:00:00.000000000 -0700
-+++ dpkg-1.16.3/fink/install-info.sh	2012-06-23 18:48:44.000000000 -0600
-@@ -0,0 +1,35 @@
++++ dpkg-1.16.3/fink/install-info.sh	2012-06-25 12:39:56.000000000 -0600
+@@ -0,0 +1,40 @@
 +#!/bin/sh
 +#
 +# Wrapper to the GNU's install-info, to be compatible with the one that used to
@@ -444,8 +444,13 @@ diff -ruN dpkg-1.16.3.orig/fink/install-info.sh dpkg-1.16.3/fink/install-info.sh
 +if [ -z "$DPKG_RUNNING_VERSION" ] ; then
 +  # it seems we are running from outside a maintainer script, so give a
 +  # warning and call ginstall-info without anything else
-+  echo "This is not dpkg install-info anymore, but GNU install-info" >&2
-+  ginstall-info "$@"
++  if [ -f @FINKPREFIX@/bin/ginstall-info ]; then
++    echo "This is not dpkg install-info anymore, but GNU install-info" >&2
++    ginstall-info "$@"
++  else
++    echo "GNU install-info not found, fallback to system install-info" >&2
++    /usr/bin/install-info "$@"
++  fi
 +else
 +  # we are running from a maintainer script, simply ignore the call
 +  # since we have trigger support and people should rebuild their
@@ -783,108 +788,6 @@ diff -ruN dpkg-1.16.3.orig/fink/md5sum dpkg-1.16.3/fink/md5sum
 +    }
 +  }
 +}
-diff -ruN dpkg-1.16.3.orig/fink/update-info-dir dpkg-1.16.3/fink/update-info-dir
---- dpkg-1.16.3.orig/fink/update-info-dir	1969-12-31 17:00:00.000000000 -0700
-+++ dpkg-1.16.3/fink/update-info-dir	2012-06-23 20:09:09.000000000 -0600
-@@ -0,0 +1,65 @@
-+#!/bin/bash
-+# update-info-dir
-+# create a dir file from all installed info files
-+# Copyright 2009 Norbert Preining
-+# Slight modifications by Sjors Gielen for the Fink package manager, 2011
-+# GPLv2
-+
-+INFODIR=@FINKPREFIX@/share/info
-+
-+set -e
-+
-+#
-+# since user's environment is taken over into root account when sudo-ing
-+# we don't want that one's user LANGUAGE setting changes the messages in
-+# the dir file. Unset LANGUAGE and reload /etc/environment to get
-+# the system wide settings. See bug #536476
-+unset LANGUAGE
-+if [ -r @FINKPREFIX@/etc/environment ] ; then
-+  . @FINKPREFIX@/etc/environment
-+fi
-+if [ -r @FINKPREFIX@/etc/default/locale ] ; then
-+  . @FINKPREFIX@/etc/default/locale
-+fi
-+
-+if [ -n "$1" ] ; then
-+  INFODIR="$1"
-+fi
-+
-+if [ ! -d "$INFODIR" ] ; then
-+  echo "Not a directory: $INFODIR." >&2
-+  exit 1
-+fi
-+
-+if [ -r "$INFODIR/dir" ] ; then
-+  rm -f "$INFODIR/dir.old"
-+  cp $INFODIR/dir $INFODIR/dir.old
-+fi
-+
-+# we have to remove the dir file not make ginstall-info being surprised
-+rm -f "$INFODIR/dir"
-+
-+errors=0
-+find "$INFODIR" -type f | while read file ; do
-+  case $file in
-+    */dir|*/dir.gz|*/dir.old|*/dir.old.gz|*-[0-9]|*-[0-9].gz|*-[1-9][0-9]|*-[1-9][0-9].gz|*.png)
-+      # these files are ignored
-+      continue
-+      ;;
-+    *)
-+      ginstall-info "$file" "$INFODIR/dir" || {
-+        errors=$[errors+1]
-+      }
-+      ;;
-+  esac
-+done
-+
-+if [ $errors -gt 0 ] ; then
-+  exec >&2
-+  echo
-+  echo "Updating the index of info documentation produced $errors errors."
-+fi
-+
-+exit 0
-+
-+# vim:set expandtab tabstop=2: #
-diff -ruN dpkg-1.16.3.orig/fink/update-info-dir.8 dpkg-1.16.3/fink/update-info-dir.8
---- dpkg-1.16.3.orig/fink/update-info-dir.8	1969-12-31 17:00:00.000000000 -0700
-+++ dpkg-1.16.3/fink/update-info-dir.8	2012-06-23 18:56:47.000000000 -0600
-@@ -0,0 +1,29 @@
-+.TH UPDATE-INFO-DIR 8
-+.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
-+.\" other parms are allowed: see man(7), man(1)
-+.SH NAME
-+update-info-dir \- (re-)create @FINKPREFIX@/share/info/dir from all installed info files
-+.SH SYNOPSIS
-+.B update-info-dir
-+.I "[options]"
-+.br
-+.SH DESCRIPTION
-+This manual page documents briefly the
-+.BR update-info-dir
-+command.
-+This manual page was written for the Debian GNU/Linux distribution
-+because the original script was designed for Debian packaging system.
-+.PP
-+.B update-info-dir [info-directory]
-+(re-)creates the index of available documentation in info format
-+(the file @FINKPREFIX@/share/info/dir) which is usually presented by info browsers
-+on startup.
-+.SH OPTIONS
-+.TP
-+.B info-directory
-+If an argument is given update the dir file in the directory given, otherwise
-+use @FINKPREFIX@/share/info.
-+.PP
-+.SH AUTHOR
-+This manual page was written by Norbert Preining <preining@logic.at>,
-+for the Debian GNU/Linux system (but may be used by others).
 diff -ruN dpkg-1.16.3.orig/lib/dpkg/dpkg.h dpkg-1.16.3/lib/dpkg/dpkg.h
 --- dpkg-1.16.3.orig/lib/dpkg/dpkg.h	2012-04-26 20:49:02.000000000 -0600
 +++ dpkg-1.16.3/lib/dpkg/dpkg.h	2012-06-23 20:09:35.000000000 -0600
@@ -1660,7 +1563,7 @@ diff -ruN dpkg-1.16.3.orig/src/t/100_dpkg_divert.t dpkg-1.16.3/src/t/100_dpkg_di
  system("rm -f $admindir/diversions-new; mkdir $admindir/diversions-old");
 diff -ruN dpkg-1.16.3.orig/utils/install-info.c dpkg-1.16.3/utils/install-info.c
 --- dpkg-1.16.3.orig/utils/install-info.c	2012-04-26 20:49:03.000000000 -0600
-+++ dpkg-1.16.3/utils/install-info.c	2012-06-23 19:47:06.000000000 -0600
++++ dpkg-1.16.3/utils/install-info.c	2012-06-25 11:44:00.000000000 -0600
 @@ -26,8 +26,8 @@
  #include <stdlib.h>
  #include <stdio.h>
