Try to fix setpgrp semantics portably

diff --git a/10.4/unstable/crypto/finkinfo/ptlib2.6.0.patch b/10.4/unstable/crypto/finkinfo/ptlib2.6.0.patch
--- a/10.4/unstable/crypto/finkinfo/ptlib2.6.0.patch
+++ b/10.4/unstable/crypto/finkinfo/ptlib2.6.0.patch
@@ -26,8 +26,73 @@ diff -Nurd -x'*~' ptlib-2.6.0.orig/Makefile.in ptlib-2.6.0/Makefile.in
  	if test -e $(PT_LIBDIR)/device/; then \
 diff -Nurd -x'*~' ptlib-2.6.0.orig/configure ptlib-2.6.0/configure
 --- ptlib-2.6.0.orig/configure	2009-02-23 22:22:03.000000000 -0500
-+++ ptlib-2.6.0/configure	2009-03-06 03:57:53.000000000 -0500
-@@ -14812,6 +14812,7 @@
++++ ptlib-2.6.0/configure	2009-05-04 01:33:10.000000000 -0400
+@@ -7668,6 +7668,64 @@
+ 
+ 
+ 
++P_SETPGRP_SYSTEMV=0
++{ echo "$as_me:$LINENO: checking if setpgrp takes no paramaters" >&5
++echo $ECHO_N "checking if setpgrp takes no paramaters... $ECHO_C" >&6; }
++cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++#include <unistd.h>
++int
++main ()
++{
++pid_t p = setpgrp();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext
++if { (ac_try="$ac_compile"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_compile") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } && {
++	 test -z "$ac_cxx_werror_flag" ||
++	 test ! -s conftest.err
++       } && test -s conftest.$ac_objext; then
++  P_SETPGRP_NOPARM=1
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++
++  P_SETPGRP_NOPARM=0
++fi
++
++rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
++if test ${P_SETPGRP_NOPARM} = 1 ; then
++  { echo "$as_me:$LINENO: result: yes" >&5
++echo "${ECHO_T}yes" >&6; }
++cat >>confdefs.h <<_ACEOF
++#define P_SETPGRP_NOPARM 1
++_ACEOF
++else
++  { echo "$as_me:$LINENO: result: no" >&5
++echo "${ECHO_T}no" >&6; }
++fi
++
++
++
+ 
+ 
+ for ac_header in regex.h
+@@ -14812,6 +14870,7 @@
  
  test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
  
@@ -35,10 +100,81 @@ diff -Nurd -x'*~' ptlib-2.6.0.orig/configure ptlib-2.6.0/configure
  
  ac_config_files="$ac_config_files make/ptbuildopts.mak"
  
+diff -Nurd -x'*~' ptlib-2.6.0.orig/include/ptbuildopts.h.in ptlib-2.6.0/include/ptbuildopts.h.in
+--- ptlib-2.6.0.orig/include/ptbuildopts.h.in	2009-02-23 22:22:02.000000000 -0500
++++ ptlib-2.6.0/include/ptbuildopts.h.in	2009-05-04 00:40:31.000000000 -0400
+@@ -151,6 +151,7 @@
+ #undef P_HAS_RECVMSG
+ #undef P_HAS_UPAD128_T
+ #undef P_HAS_INET_NTOP
++#undef P_SETPGRP_NOPARM
+ 
+ 
+ /////////////////////////////////////////////////
 diff -Nurd -x'*~' ptlib-2.6.0.orig/include/ptlib/unix/ptlib/pmachdep.h ptlib-2.6.0/include/ptlib/unix/ptlib/pmachdep.h
 --- ptlib-2.6.0.orig/include/ptlib/unix/ptlib/pmachdep.h	2009-02-23 22:22:02.000000000 -0500
-+++ ptlib-2.6.0/include/ptlib/unix/ptlib/pmachdep.h	2009-03-06 02:56:41.000000000 -0500
-@@ -305,7 +305,9 @@
++++ ptlib-2.6.0/include/ptlib/unix/ptlib/pmachdep.h	2009-05-04 00:43:28.000000000 -0400
+@@ -50,7 +50,6 @@
+ #include <dlfcn.h>
+ 
+ #define HAS_IFREQ
+-#define PSETPGRP()  setpgrp()
+ 
+ #if __GNU_LIBRARY__ < 6
+ #define P_LINUX_LIB_OLD
+@@ -92,8 +91,6 @@
+ 
+ #define HAS_IFREQ
+ 
+-#define PSETPGRP()  setpgrp(0, 0)
+-
+ ///////////////////////////////////////////////////////////////////////////////
+ #elif defined(P_OPENBSD)
+ 
+@@ -119,8 +116,6 @@
+ 
+ #define HAS_IFREQ
+ 
+-#define PSETPGRP()  setpgrp(0, 0)
+-
+ ///////////////////////////////////////////////////////////////////////////////
+ #elif defined(P_NETBSD)
+ 
+@@ -148,8 +143,6 @@
+ 
+ #define HAS_IFREQ
+ 
+-#define PSETPGRP()  setpgrp(0, 0)
+-
+ ///////////////////////////////////////////////////////////////////////////////
+ #elif defined(P_SOLARIS)
+ 
+@@ -181,8 +174,6 @@
+ } upad128_t;
+ #endif
+ 
+-#define PSETPGRP()  setpgrp()
+-
+ #define INADDR_NONE     -1
+ #if P_SOLARIS < 7
+ typedef int socklen_t;
+@@ -212,7 +203,6 @@
+ #include <sys/sockio.h>
+ 
+ #define HAS_IFREQ
+-#define PSETPGRP()  setpgrp(0, 0)
+ #define raise(s)    kill(getpid(),s)
+ 
+ extern "C" {
+@@ -290,7 +280,6 @@
+ #include <bone/arpa/inet.h>
+ 
+ #define wait3(s, o, r) waitpid(-1, s, o)
+-#define PSETPGRP()  setpgid(0,0)
+ int seteuid(uid_t euid);
+ int setegid(gid_t gid);
+ 
+@@ -305,7 +294,9 @@
  #elif defined (P_MACOSX) || defined(P_MACOS)
   
  #if defined(P_PTHREADS)
@@ -48,6 +184,60 @@ diff -Nurd -x'*~' ptlib-2.6.0.orig/include/ptlib/unix/ptlib/pmachdep.h ptlib-2.6
  #   define P_THREAD_SAFE_CLIB
  #   include <pthread.h>
  #endif
+@@ -343,12 +334,6 @@
+  
+ #define HAS_IFREQ
+ 
+-// hf, 2008-12-25: apparently, earlier versions of 10.5.x needed a version 
+-// without parameters. however, something changed such that the 'old' version
+-// is required again. (OS X 10.5.6)
+-#define PSETPGRP()  setpgrp(0, 0)
+-
+-
+ ///////////////////////////////////////////////////////////////////////////////
+ #elif defined (P_AIX)
+ 
+@@ -374,8 +359,6 @@
+ 
+ #define HAS_IFREQ
+ 
+-#define PSETPGRP()  setpgrp()
+-
+ ///////////////////////////////////////////////////////////////////////////////
+ #elif defined (P_IRIX)
+ 
+@@ -402,8 +385,6 @@
+ 
+ typedef int socklen_t;
+ 
+-#define PSETPGRP()  setpgrp()
+-
+ ///////////////////////////////////////////////////////////////////////////////
+ #elif defined (P_VXWORKS)
+ 
+@@ -504,7 +485,6 @@
+ #include <netinet/tcp.h>
+ 
+ #define HAS_IFREQ
+-#define PSETPGRP()  setpgrp()
+ 
+ ///////////////////////////////////////////////////////////////////////////////
+ #elif defined(P_CYGWIN)
+@@ -541,6 +521,14 @@
+ 
+ typedef int SOCKET;
+ 
++#ifndef PSETPGRP
++#ifdef P_SETPGRP_NOPARM
++#define PSETPGRP()  setpgrp()
++#else
++#define PSETPGRP()  setpgrp(0, 0)
++#endif
++#endif
++
+ #ifdef P_PTHREADS
+ 
+ #include <pthread.h>
 diff -Nurd -x'*~' ptlib-2.6.0.orig/make/lib.mak ptlib-2.6.0/make/lib.mak
 --- ptlib-2.6.0.orig/make/lib.mak	2009-02-23 22:21:57.000000000 -0500
 +++ ptlib-2.6.0/make/lib.mak	2009-03-06 15:55:25.000000000 -0500
